#define ENUM_CAT_00_TEXT "Kloktijd"
#define ENUM_CAT_01_TEXT "bedieningseenheid"
#define ENUM_CAT_02_TEXT "Functie" //not sure about this translation
#define ENUM_CAT_03_TEXT "Klokprogramma 1"
#define ENUM_CAT_04_TEXT "Klokprogramma 2"
#define ENUM_CAT_05_TEXT "Klokprogramma 3"
#define ENUM_CAT_06_TEXT "Klokprogramma tapwater"
#define ENUM_CAT_08_TEXT "Vakantieprogramma GR1"
#define ENUM_CAT_09_TEXT "Vakantieprogramma GR2"
#define ENUM_CAT_0b_TEXT "Verwarmingsgroep 1"
#define ENUM_CAT_0d_TEXT "Verwarmingsgroep 2"
#define ENUM_CAT_0f_TEXT "Tapwater"
#define ENUM_CAT_12_TEXT "Voorregelaar/Systeempomp"
#define ENUM_CAT_13_TEXT "Ketel"
#define ENUM_CAT_15_TEXT "Warmtepomp"
#define ENUM_CAT_16_TEXT "Energie teller"
#define ENUM_CAT_17_TEXT "Kaskade"
#define ENUM_CAT_18_TEXT "Extra vermogen" //not sure about this translation
#define ENUM_CAT_19_TEXT "Zonnepaneel"
#define ENUM_CAT_1b_TEXT "Buffervat"
#define ENUM_CAT_1c_TEXT "Tapwater-voorraad"
#define ENUM_CAT_1d_TEXT "Tapw-Directlading"
#define ENUM_CAT_1e_TEXT "Configuratie"
#define ENUM_CAT_1f_TEXT "LPB"
#define ENUM_CAT_20_TEXT "Fout"
#define ENUM_CAT_21_TEXT "Onderhoud/Uitzonderingsbedrijf"
#define ENUM_CAT_24_TEXT "Status"
#define ENUM_CAT_26_TEXT "Diagnose opwekker"
#define ENUM_CAT_27_TEXT "Diagnose verbruiker"
#define ENUM_CAT_28_TEXT "Branderautomaat"

#define MENU_TEXT_HFK "Verwarmingsfuncties"
#define MENU_TEXT_SN1 "DS18B20 Sensor"
#define MENU_TEXT_SN2 "DHT22 Sensor"
#define MENU_TEXT_DLG "Uitvoer logbestand"
#define MENU_TEXT_SLG "Wegschrijven logbestand"
#define MENU_TEXT_CFG "Instellingen"
#define MENU_TEXT_URL "URL commando's"
#define MENU_TEXT_HWT "HowTo"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Ja"
#define MENU_TEXT_NO "Nee"
#define MENU_TEXT_ON "Aan"
#define MENU_TEXT_OFF "Uit"
#define MENU_DESC_HFK "Hiermee kunt u de functies van uw verwarmingssysteem opvragen of regelen. De individuele parameters zijn onderverdeeld in overeenkomstige categorieën, waarop u kunt klikken."
#define MENU_DESC_CFG "Hier ziet u de waarden waarmee BSB-LAN is geconfigureerd. Het wijzigen van deze parameters is mogelijk via de uitgebreide URL-opdrachten."
#define MENU_DESC_URL "Toont een overzicht van de opdrachten die u kunt verzenden via de directe invoer in de adresbalk van de browser. Deze opdrachten zijn ook nodig voor de verbinding met domotica-systemen zoals FHEM."
#define MENU_TEXT_VB1 "Logmodus geactiveerd!"
#define MENU_TEXT_VB2 "Logmodus gedeactiveerd!"
#define MENU_TEXT_VB3 "De logmodus heeft invloed op zowel de seriële console van de Arduino Mega2560 als (optioneel) het loggen van de busgegevens op de microSD-kaart, zodat de kaart wordt snel vol wordt! De HTML-uitvoer blijft ongewijzigd."
#define MENU_TEXT_SR1 "Seriële monitor geactiveerd!"
#define MENU_TEXT_SR2 "Seriële monitor gedeactiveerd!"
#define MENU_TEXT_SR3 "Alleen de seriële uitvoer wordt beïnvloed."
#define MENU_TEXT_ER1 "FOUT: Ongeldige parameter!"
#define MENU_TEXT_ER2 "FOUT: Ongeldige waarde!"
#define MENU_TEXT_ER3 "FOUT: Mislukt om in te stellen!"
#define MENU_TEXT_ER4 "Parameter is alleen lezen."
#define MENU_TEXT_ER5 "FOUT: Verkeerde type!"
#define MENU_TEXT_ER6 "FOUT: Regel niet gevonden!"
#define MENU_TEXT_ER7 "FOUT: Beschermde GPIO-pin!"
#define MENU_TEXT_BST "Branderstatistieken"
#define MENU_TEXT_BRS "Ketel- en Warmwater-looptijd ingesteld op nul"
#define MENU_TEXT_24A "24 uur gemiddelde waarden"
#define MENU_TEXT_24N "Nieuwe gemiddelde parameters"
#define MENU_TEXT_DTR "Bestand datalog.txt verwijderd en geregenereerd."
#define MENU_TEXT_DTD "Gegevens downloaden"
#define MENU_TEXT_DTF "Fout bij het maken van datalog.txt bestand!"
#define MENU_TEXT_DTO "Fout bij openen van datalog.txt bestand!"
#define MENU_TEXT_RAM "Vrij geheugen"
#define MENU_TEXT_BUS "Bus-System"
#define MENU_TEXT_BRW "Lezen/Schrijven"
#define MENU_TEXT_BRO "Alleen lezen"
#define MENU_TEXT_OWP "1-Wire Bus Pins"
#define MENU_TEXT_DHP "DHT22 Bus Pins"
#define MENU_TEXT_EXP "Geblokkeerde GPIO Pins"
#define MENU_TEXT_MAC "MAC-Adresse"
#define MENU_TEXT_LGP "Log alle komende parameters"
#define MENU_TEXT_SEC "Seconden"
#define MENU_TEXT_BZ1 "Branderlooptijd fase 1"
#define MENU_TEXT_BT1 "Brander cycli fase 1"
#define MENU_TEXT_BZ2 "Branderlooptijd fase 2"
#define MENU_TEXT_BT2 "Brander cycli fase 2"
#define MENU_TEXT_TZ1 "Warmwater runtime"
#define MENU_TEXT_TT1 "SWW-cycli"
#define MENU_TEXT_MXI "MAX!-werkelijke temperatuur"
#define MENU_TEXT_MXS "MAX!-doeltemperatuur"
#define MENU_TEXT_MXV "MAX!-klepopening"
#define MENU_TEXT_MXN "Geen MAX!-Gegevens ontvangen."
#define MENU_TEXT_BDT "BOD-gegevenstelegrammen (onafhankelijk van het interval)"
#define MENU_TEXT_BUT "Log alleen onbekende Bus-Telegrammen"
#define MENU_TEXT_MMD "Monitor Modus"
#define MENU_TEXT_VBL "Log level"
#define MENU_TEXT_AVT "Berekening van 24-uursgemiddelden voor de volgende parameters:"
#define MENU_TEXT_LBO "Alleen broadcast Bus-Telegrammen loggen"
#define MENU_TEXT_LGI "Nieuw registratie-interval"
#define MENU_TEXT_LGN "Nieuwe loggingparameters"
#define MENU_TEXT_QSC "Scannen naar apparaten"
#define MENU_TEXT_QFD "Apparaatadres gevonden"
#define MENU_TEXT_QFA "Apparaatquery mislukt"
#define MENU_TEXT_QRT "Test apparaat adres"
#define MENU_TEXT_QST "Start test"
#define MENU_TEXT_QTE "De test is voltooid"

#define STR0_TEXT "Datum/Tijd"
#define STR1_TEXT "Uren/Minuten"
#define STR2_TEXT "Dag/Maand"
#define STR3_TEXT "Jaar"
#define STR5_TEXT "Begin zomertijd dag/Maand"
#define STR6_TEXT "Einde zomertijd dag/Maand"
#define STR20_TEXT "Taal"
#define STR21_TEXT "Geef speciale bediening weer"
#define STR22_TEXT "Info"
#define STR23_TEXT "Foutmelding"
#define STR25_TEXT "Contrast van het display"
#define STR26_TEXT "Werking vergrendelen"
#define STR27_TEXT "Programmering vergrendelen"
#define STR28_TEXT "Besturingseenheid directe aanpassing"
#define STR29_TEXT "Units"
#define STR30_TEXT "Bedieningseenheid Basisinstelling opslaan"
#define STR31_TEXT "Bedieningseenheid activeert basisinstelling"
#define STR40_TEXT "Gebruik als"
#define STR42_TEXT "Toewijzing van ruimte unit 1"
// #define STR42_2_TEXT "Wirkung eines RG auf die Heizkreise" what is RG?
#define STR44_TEXT "Bediening HK 2"
#define STR46_TEXT "Bediening HK P"
#define STR48_TEXT "Effect aanwezigheidsknop"
#define STR54_TEXT "Correctieruimte sensor"
#define STR70_TEXT "Apparaatversie bedieningspaneel"
#define STR120_TEXT "Bindend"
#define STR121_TEXT "Testmodus"
#define STR130_TEXT "Ruimte unit 1-status"
#define STR131_TEXT "Ruimte unit 2-status"
#define STR132_TEXT "Ruimte unit P-status"
#define STR133_TEXT "P-status van buitensensor"
#define STR134_TEXT "Repeater P-status"
#define STR135_TEXT "Status van besturingseenheid 1"
#define STR136_TEXT "Status van besturingseenheid 2"
#define STR137_TEXT "Status van besturingseenheid P"
#define STR138_TEXT "Service Apperaat Status"
#define STR140_TEXT "Verwijder alle apparaten"
#define STR500_TEXT "Ma"
#define STR501_TEXT "Di"
#define STR502_TEXT "Wo"
#define STR503_TEXT "Do"
#define STR504_TEXT "Vr"
#define STR505_TEXT "Za"
#define STR506_TEXT "Zo"
#define STR516_TEXT "Standaardwaarden Klokpr Groep 1"
#define STR536_TEXT "Standaardwaarden Klokpr Groep 2"
#define STR556_TEXT "Standaardwaarden Klokpr 3"
#define STR576_TEXT "Standaardwaarden Klokpr 4"
#define STR648_TEXT "Bedrijfswijze vakantie Groep 1"
#define STR652_TEXT "Vakantieperiode 1 Groep 2: Eerste dag"
#define STR653_TEXT "Vakantieperiode 1 Groep 2: Laatste dag"
#define STR658_TEXT "Bedrijfswijze vakantie Groep 2"
#define STR700_TEXT "Bedrijfswijze Groep 1"
#define STR701_TEXT "Bezettingsknop (tijdelijke afwezigheid)"
#define STR710_TEXT "Ruimtemperatuur gewenste waarde Groep 1"
#define STR711_TEXT "Maximum gewenstewaarde"
#define STR712_TEXT "Ruimtetemp. gew.waarde nacht Groep 1"
#define STR714_TEXT "Ruimtetemp. gew.waarde vorst Groep 1"
#define STR720_TEXT "Stooklijn 1 steilheid"
#define STR721_TEXT "Stooklijn-parallelverschuiving"
#define STR726_TEXT "Stooklijn-adaptie Groep 1"
#define STR730_TEXT "Zomer/winter omschakeltemp. Groep 1"
#define STR732_TEXT "Dagstookgrens Groep 1"
#define STR740_TEXT "Aanvoertemp-min-begrenzing Groep 1"
#define STR741_TEXT "Aanvoertemp-max-begrenzing Groep 1"
#define STR750_TEXT "Ruimtetemperatuur invloedfactor Groep 1"
#define STR760_TEXT "Ruimtetemperatuurbegrenzing Groep 1"
#define STR770_TEXT "Ruimtetemp-verhoging Gr 1 (Snelaanw)"
#define STR780_TEXT "Snelafkoeling Groep 1"
#define STR790_TEXT "Optimalisering max. vervroeging Groep 1"
#define STR791_TEXT "Uitsch.optim. max. vervroeging Groep 1"
#define STR800_TEXT "Begin gered.ruimtemp.verhoging Gr 1"
#define STR801_TEXT "Einde gered.ruimtemp.verhoging Gr 1"
#define STR850_TEXT "Vloer-uitdrogingsbescherming"
#define STR851_TEXT "Estrik setpoint hand Groep 1"
#define STR884_TEXT "Toerental ketelpomp bij ontwerpconditie"
#define STR885_TEXT "Mod Pomp PBM min"
#define STR886_TEXT "Buitentemperatuur bij maximale warmtevraag"
#define STR887_TEXT "Gew. keteltemp bij Normbuitentemp"
#define STR888_TEXT "Grens voor temperatuurverhoging dT-regeling"
#define STR894_TEXT "Delta Aanv/Retour bij Norm-buitentemp"
#define STR1000_TEXT "Bedrijfswijze Groep 2"
#define STR1010_TEXT "Ruimtemperatuur Comfortsetpoint Groep 2"
#define STR1012_TEXT "Ruimtetemp. gew.waarde nacht Groep 2"
#define STR1014_TEXT "Ruimtetemp. gew.waarde vorst Groep 2"
#define STR1020_TEXT "Stooklijn 2 steilheid"
#define STR1021_TEXT "Stooklijn-parallelverschuiving"
#define STR1026_TEXT "Stooklijn-adaptie Groep 2"
#define STR1030_TEXT "Zomer/winter omschakeltemp. Groep 2"
#define STR1032_TEXT "Dagstookgrens Groep 2"
#define STR1040_TEXT "Aanvoertemp-min-begrenzing Groep 2"
#define STR1041_TEXT "Aanvoertemp-max-begrenzing Groep 2"
#define STR1050_TEXT "Ruimtetemperatuur invloedfactor Groep 2"
#define STR1060_TEXT "Ruimtetemperatuurbegrenzing Groep 2"
#define STR1070_TEXT "Ruimtetemp-verhoging Gr 2 (Snelaanw)"
#define STR1080_TEXT "Snelafkoeling Groep 2"
#define STR1090_TEXT "Optimalisering max. vervroeging Groep 2"
#define STR1091_TEXT "Uitsch.optim. max. vervroeging Groep 2"
#define STR1100_TEXT "Begin gered.ruimtemp.verhoging Gr 2"
#define STR1101_TEXT "Einde gered.ruimtemp.verhoging Gr 2"
#define STR1130_TEXT "Temperatuur-verhoging Verwarmingsgroep"
#define STR1134_TEXT "Servomotor-looptijd Verwarmingsgroep"
#define STR1150_TEXT "Vloer-uitdrogingsbescherming"
#define STR1151_TEXT "Estrik setpoint Hand Groep 2"
#define STR1600_TEXT "Tapwater-Bedrijfswijze"
#define STR1610_TEXT "Tapwatertemperatuur-Normaal setpoint"
#define STR1612_TEXT "Tapwatertemperatuur-Gereduceerd setpoint"
#define STR1620_TEXT "Tapwatervrijgave"
#define STR1640_TEXT "Legionellafunctie"
#define STR1641_TEXT "Periode Legionellafunctie"
#define STR1642_TEXT "Legionellafunctie dag"
#define STR1644_TEXT "Starttijd Legionellafunctie"
#define STR1645_TEXT "Legionellafunctie gew.waarde"
#define STR1646_TEXT "Duur van Legionella temperatuur"
#define STR1647_TEXT "Tapwaterpompbedrijf tijdens Legionellafunctie"
#define STR1660_TEXT "Tapwater Tapwaterpomp Vrijgave"
#define STR1661_TEXT "Tapwaterpomp taktbedrijf"
#define STR2201_TEXT "Opwekkerblokkering"
#define STR2210_TEXT "Keteltemperatuur-minimaalbegrenzing"
#define STR2212_TEXT "Keteltemperatuur-maximaalbegrenzing"
#define STR2440_TEXT "Max modulatiegraad in verwarmingsbedrijf"
#define STR2441_TEXT "Max ventilatortoeren verwarmen"
#define STR2442_TEXT "Vermogen tijdens actieve regelaarvertraging"
#define STR2443_TEXT "Vermogen bij regelaarvrijgave in DLH bedrijf"
#define STR2451_TEXT "Min branderpauzetijd"
#define STR2452_TEXT "Max. Regeldiff. binnen pauzetijd"
#define STR2453_TEXT "Regelaarvertraging na inschakeling"
#define STR2454_TEXT "Ketel-schakeldifferentie"
#define STR2455_TEXT "Min. uitschakeldifferentie ketel"
#define STR2456_TEXT "Max. uitschakeldifferentie ketel"
#define STR2471_TEXT "Pompnadraaitijd"
#define STR2472_TEXT "Pompnadraaitemperatuur Tapwater"
#define STR2521_TEXT "Inschakeltemp ketelvorstbewaking"
#define STR2522_TEXT "Uitschakeltemp ketelvorstbewaking"
#define STR3810_TEXT "Temperatuurverschil zonnepaneel IN"
#define STR3811_TEXT "Temperatuurverschil zonnepaneel UIT"
#define STR3812_TEXT "Minimale laadtemperatuur"
#define STR3831_TEXT "Min looptijd collectorpomp"
#define STR3840_TEXT "Collectorvorstbev temperatuur"
#define STR3850_TEXT "Collector oververh.bev.temperatuur"
#define STR3860_TEXT "Verdampingstemperatuur warmtedrager"
#define STR4721_TEXT "Automatische opwekkerblokk Schakeldifferentie"
#define STR4722_TEXT "Temp.verschil buffer/gr tot vrijg opwekking"
#define STR5019_TEXT "Setpointverhoging voor nalading voorraadvat"
#define STR5020_TEXT "Aanvoertemperatuurverhoging tapwater"
#define STR5050_TEXT "Maximale tapwater laadtemperatuur"
#define STR5055_TEXT "Min terugkoeltemp voor tapw-vat"
#define STR5100_TEXT "Min. Pomptoeren voor doorlading buffer"
#define STR5020_TEXT "Aanvoertemperatuurverhoging tapwater"
#define STR5400_TEXT "Setpoint voor tapwater gereed temperatuur"
#define STR5430_TEXT "Inschakeldiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5431_TEXT "Min.Uitschdiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5432_TEXT "Max.Uitschdiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5433_TEXT "Inschakeldiff. in WTB-Bedrijf (Opnemer 2)"
#define STR5434_TEXT "Min uitschakeldiff in WTB-bedrijf (Opnemer 2)"
#define STR5435_TEXT "Max.Uitschdiff. in WTB-Bedrijf (Opnemer 2)"
#define STR5450_TEXT "Grens voor beëindigen watertappen bij DLH"
#define STR5451_TEXT "Grens voor watertappen bij DLH in Comfort"
#define STR5452_TEXT "Grens voor watertappen bij DLH in VerwBedrijf"
#define STR5453_TEXT "Setpointcorrectie bij comfortregeling met 40°C"
#define STR5454_TEXT "Setpointcorrectie bij comfortregeling met 60°C"
#define STR5455_TEXT "Setpointcorrectie bij uitloopregeling met 40°C"
#define STR5456_TEXT "Setpointcorrectie bij uitloopregeling met 60°C"
#define STR5480_TEXT "DLH-Comforttijd na tappen zonder warmtevraag"
#define STR5481_TEXT "DLH-Comforttijd na tappen met warmtevraag"
#define STR5482_TEXT "Tijd tot tapw-strom.schak gesloten"
#define STR5483_TEXT "Tijd tot tapw-comfort strom.schak gesloten"
#define STR5486_TEXT "Regelvertraging bij aan/uit uitloopbedrijf"
#define STR5487_TEXT "Pompnadraai in DLH-Comfort bij brander uit"
#define STR5488_TEXT "Pompnadraai in DLH-Comfort bij brander uit"
#define STR5701_TEXT "Installatietype"
#define STR5710_TEXT "Verwarmingsgroep 1"
#define STR5715_TEXT "Verwarmingsgroep 2"
#define STR5732_TEXT "Pompuitschakeltijd bij wissel verw naar WTB"
#define STR5733_TEXT "Vertraging pompuitsch bij wissel verw->WTB"
#define STR5761_TEXT "Warmtevraag met ondersteuning door Q8"
#define STR5920_TEXT "Programmeerbare uitgang K2"
#define STR5921_TEXT "Default K2 op K1"
#define STR5922_TEXT "Funktie uitgang 1 Relais Clip-In"
#define STR5923_TEXT "Funktie uitgang 2 Relais Clip-In"
#define STR5924_TEXT "Funktie uitgang 3 Relais Clip-In"
#define STR5926_TEXT "Configuratie Uitgang 1"
#define STR5927_TEXT "Configuratie Uitgang 2"
#define STR5928_TEXT "Configuratie Uitgang 3"
#define STR5950_TEXT "Ingang H1 functiekeuze"
#define STR5957_TEXT "Modemfunctie"
#define STR5970_TEXT "Config Ruimtethermostaat 1"
#define STR5971_TEXT "Config Ruimtethermostaat 2"
#define STR5973_TEXT "Functie Ingang RelCl"
#define STR5975_TEXT "Temperatuurgrens voor externe warmtevraag"
#define STR5976_TEXT "Ingangssignaal ondergrens ext warmtevraag"
#define STR6110_TEXT "Gebouwtijdconstante"
#define STR6112_TEXT "Ruimtemodel gradient"
#define STR6120_TEXT "Installatievorstbeveiliging"
#define STR6127_TEXT "Tijd voor pomp/klepkick"
#define STR6220_TEXT "Regelaar-SW-Versie"
#define STR6225_TEXT "Regelaar-Familie"
#define STR6226_TEXT "Regelaar-Variant"
#define STR6227_TEXT "Regelaar-OV-Versie"
#define STR6230_TEXT "Regelaarconfiguratie 0"
#define STR6240_TEXT "Regelaarconfiguratie 1"
#define STR6250_TEXT "Regelaarconfiguratie 2"
#define STR6260_TEXT "Regelaarconfiguratie 3"
#define STR6270_TEXT "Regelaarconfiguratie 4"
#define STR6300_TEXT "Regelaarconfiguratie 7"
#define STR6330_TEXT "Regelaarconfiguratie 10"
#define STR6604_TEXT "LPB-voeding Functiekeuze"
#define STR6605_TEXT "LPB-voeding Status"
#define STR6625_TEXT "Tapwatertoewijzing"
#define STR6640_TEXT "Kloktijd-leverancier"
#define STR6705_TEXT "Interne diagnosecode"
#define STR6706_TEXT "Actuele waarde Storingsfase"
#define STR6741_TEXT "Tijd aanvoertemperatuuralarm Groep 2"
#define STR6823_TEXT "3e Oude waarde Albatros Foutcode"
#define STR6825_TEXT "Oude waarde 3 Storingsdiagnose"
#define STR6826_TEXT "Oude waarde 3 Storingsfase"
#define STR6830_TEXT "Oude waarde 4 Storingcode-teller"
#define STR6833_TEXT "4e Oude waarde Albatros Foutcode"
#define STR6835_TEXT "Oude waarde 4 Storingsdiagnose"
#define STR6836_TEXT "Oude waarde 4 Storingsfase"
#define STR6840_TEXT "Oude waarde 5 Storingcode-teller"
#define STR6843_TEXT "5e Oude waarde Albatros Foutcode"
#define STR6845_TEXT "Oude waarde 5 Storingsdiagnose"
#define STR6846_TEXT "Oude waarde 5 Storingsfase"
#define STR7001_TEXT "Onderhoudsmelding"
#define STR7007_TEXT "Configuratie / Reset onderhoudsmeldingen"
#define STR7010_TEXT "Onderhoudsmelding - Bevestiging"
#define STR7011_TEXT "Herhalingstijd voor onderhoudsmeldingen"
#define STR7040_TEXT "Brander onderhoudsinterval"
#define STR7041_TEXT "Bedrijfsuren sinds laatste onderhoud"
#define STR7042_TEXT "Grens voor controle sinds laatste onderhoud"
#define STR7043_TEXT "Controles sinds laatste onderhoud"
#define STR7044_TEXT "Grens voor maanden sinds laatste onderhoud"
#define STR7045_TEXT "Maanden sinds laatste onderhoud"
#define STR7050_TEXT "Ventilatortoerental voor onderhoudsmelding"
#define STR7051_TEXT "Ionisatiestroom- Onderhoudsmelding"
#define STR8000_TEXT "Status Verw.groep 1"
#define STR8001_TEXT "Status Verw.groep 2"
#define STR8003_TEXT "Status Tapwater"
#define STR8005_TEXT "Status Ketel"
#define STR8006_TEXT "Status Warmptepomp"
#define STR8007_TEXT "Status Zonne-energie"
#define STR8310_TEXT "Keteltemperatuur-meetwaarde"
#define STR8311_TEXT "Keteltemperatuur-gew.waarde"
#define STR8314_TEXT "Retourtemperatuur-meetwaarde"
#define STR8316_TEXT "Rookgastemperatuur-meetwaarde"
#define STR8324_TEXT "Actueel ventilatortoerental"
#define STR8325_TEXT "Actuele ventilatorbesturing"
#define STR8326_TEXT "Relatief vermogen"
#define STR8328_TEXT "Bedrijfsweergave FA"
#define STR2730_TEXT "Ionisatiestroom"
#define STR8336_TEXT "Regelaarbedrijfsuren"
#define STR8337_TEXT "Startteller brander"
#define STR8338_TEXT "Bedrijfsuren verwarmingsbedrijf"
#define STR8339_TEXT "Bedrijfsuren tapwaterbedrijf"
#define STR8340_TEXT "Bedrijfsuren ext. Warmtevraag"
#define STR8410_TEXT "Retourtemperatuur WP"
#define STR8411_TEXT "Gewenste waarde WP"
#define STR8510_TEXT "Collectortemperatuur 1 (B6)"
#define STR8530_TEXT "Bedrijfsuren zonopbrengst"
#define STR8700_TEXT "Lokale buitentemperatuur"
#define STR8703_TEXT "Gedempte buitentemperatuur"
#define STR8704_TEXT "Gemengde buitentemperatuur"
#define STR8740_TEXT "Ruimtetemperatuur 1 meetwaarde"
#define STR8741_TEXT "Ruimtetemp-gew. waarde actueel"
#define STR8743_TEXT "Aanvoertemperatuur meetwaarde Groep 1"
#define STR8744_TEXT "Gewenste waarde aanvoertemperatuur 1"
#define STR8750_TEXT "Pomptoerental"
#define STR8770_TEXT "Ruimtetemperatuur 2 meetwaarde"
#define STR8771_TEXT "Ruimtemp gew.waarde actueel Groep 2"
#define STR8773_TEXT "Aanvoertemperatuur meetwaarde Groep 2"
#define STR8774_TEXT "Aanvoersetpoint H2"
#define STR8830_TEXT "Tapwatertemperatuur 1"
#define STR8831_TEXT "Tapwatertemperatuur-gew.waarde aktueel"
#define STR8836_TEXT "Tapwater Laadtemperatuur"
#define STR8950_TEXT "Proces-Sig Gezamenlijke aanvoertemperatuur"
#define STR8952_TEXT "Proces-Sig Gezamenlijke retourtemperatuur"
#define STR8980_TEXT "Buffertemperatuur Boven (B4)"
#define STR9500_TEXT "Voorspoeltijd"
#define STR9502_TEXT "Modulatie lucht in voorventilatie"
#define STR9504_TEXT "Setpoint vent.toerental in voorventilatie"
#define STR9510_TEXT "Modulatie lucht in aansteeklast"
#define STR9512_TEXT "Ventilatortoerental in aansteeklast"
#define STR9520_TEXT "Modulatie lucht in deellast"
#define STR9522_TEXT "Modulatie lucht in vollast"
#define STR9524_TEXT "Ventilatortoerental in deellast"
#define STR9527_TEXT "Ventilatortoerental in vollast"
#define STR9540_TEXT "Naspoeltijd"
#define STR9560_TEXT "Ventilatormodulatie bij bufferlading"
#define STR9563_TEXT "Setpoint ventilator bij bufferlading"
#define ENUM700_01_TEXT "Automatisch"
// #define ENUM8000_03_TEXT "Wächter angesprochen"
// #define ENUM8000_04_TEXT "Handbetrieb aktiv"
#define ENUM8000_11_TEXT "Naloop actief"
// #define ENUM8000_16_TEXT "Anlagenfrostschutz aktiv"
// #define ENUM8000_17_TEXT "Frostschutz aktiv"
// #define ENUM8000_38_TEXT "Überhitzschutz aktiv"
// #define ENUM8000_65_TEXT "Raumfrostschutz aktiv"
// #define ENUM8000_66_TEXT "Estrichfunktion aktiv"
// #define ENUM8000_67_TEXT "Eingeschränkt, Kesselschutz"
// #define ENUM8000_68_TEXT "Eingeschränkt, TWW-Vorrang"
// #define ENUM8000_69_TEXT "Eingeschränkt, Puffer"
// #define ENUM8000_6a_TEXT "Heizbetrieb eingeschränkt"
// #define ENUM8000_6b_TEXT "Zwangsabnahme Puffer"
// #define ENUM8000_6c_TEXT "Zwangsabnahme TWW"
// #define ENUM8000_6d_TEXT "Zwangsabnahme Erzeuger"
// #define ENUM8000_6e_TEXT "Zwangsabnahme"
// #define ENUM8000_6f_TEXT "Einschaltopt + Schnellaufheiz"
// #define ENUM8000_70_TEXT "Einschaltoptimierung"
// #define ENUM8000_71_TEXT "Schnellaufheizung"
// #define ENUM8000_72_TEXT "Heizbetrieb Komfort"
// #define ENUM8000_73_TEXT "Ausschaltoptimierung"
// #define ENUM8000_74_TEXT "Heizbetrieb Reduziert"
// #define ENUM8000_75_TEXT "Vorlauffrostschutz aktiv"
// #define ENUM8000_76_TEXT "Sommerbetrieb"
// #define ENUM8000_77_TEXT "Tages-Eco aktiv"
// #define ENUM8000_78_TEXT "Absenkung Reduziert"
// #define ENUM8000_79_TEXT "Absenkung Frostschutz"
// #define ENUM8003_35_TEXT "Rückkühlung aktiv"
// #define ENUM8003_42_TEXT "Ladung Elektroeinsatz"
// #define ENUM8003_43_TEXT "Zwangsladung aktiv"
// #define ENUM8003_45_TEXT "Ladung aktiv"
// #define ENUM8003_46_TEXT "Geladen, Max Speichertemp"
// #define ENUM8003_47_TEXT "Geladen, Max Ladetemp"
// #define ENUM8003_4b_TEXT "Geladen"
// #define ENUM8003_4d_TEXT "Rückkühlung via Kollektor"
// #define ENUM8003_4e_TEXT "Rückkühlung via Erz / Hk's"
// #define ENUM8003_4f_TEXT "Entladeschutz aktiv"
// #define ENUM8003_50_TEXT "Ladezeitbegrenzung aktiv"
// #define ENUM8003_51_TEXT "Ladung gesperrt"
// #define ENUM8003_52_TEXT "Ladesperre aktiv"
// #define ENUM8003_53_TEXT "Zwang, Max Speichertemp"
// #define ENUM8003_54_TEXT "Zwang, Max Ladetemperatur"
// #define ENUM8003_55_TEXT "Zwang, Legionellensollwert"
// #define ENUM8003_56_TEXT "Zwang, Nennsollwert"
// #define ENUM8003_57_TEXT "Ladung Elektro, Leg’sollwert"
// #define ENUM8003_58_TEXT "Ladung Elektro, Nennsollwert"
// #define ENUM8003_59_TEXT "Ladung Elektro, Red’sollwert"
// #define ENUM8003_5a_TEXT "Ladung Elektro, Fros’sollwert"
// #define ENUM8003_5b_TEXT "Elektroeinsatz freigegeben"
// #define ENUM8003_5c_TEXT "Push, Legionellensollwert"
// #define ENUM8003_5d_TEXT "Push, Nennsollwert"
// #define ENUM8003_5e_TEXT "Push aktiv"
// #define ENUM8003_5f_TEXT "Ladung, Legionellensollwert"
// #define ENUM8003_60_TEXT "Ladung, Nennsollwert"
// #define ENUM8003_61_TEXT "Ladung, Reduziertsollwert"
// #define ENUM8003_62_TEXT "Geladen, Legio’temperatur"
// #define ENUM8003_63_TEXT "Geladen, Nenntemperatur"
// #define ENUM8003_64_TEXT "Geladen, Reduz’temperatur"
// #define ENUM8003_c7_TEXT "Zapfbetrieb"
// #define ENUM8003_c8_TEXT "Bereit"
// #define ENUM8003_c9_TEXT "Bereitschaftsladung"
// #define ENUM8004_8A_TEXT "Kühlbetrieb aus"
// #define ENUM8005_01_TEXT "STB angesprochen"
// #define ENUM8005_02_TEXT "Störung"
// #define ENUM8005_05_TEXT "Schornsteinfegerfkt, Vollast"
// #define ENUM8005_06_TEXT "Schornsteinfegerfkt, Teillast"
// #define ENUM8005_07_TEXT "Schornsteinfegerfkt aktiv"
// #define ENUM8005_08_TEXT "Gesperrt, Manuell"
// #define ENUM8005_09_TEXT "Gesperrt, Automatisch"
// #define ENUM8005_0b_TEXT "Anfahrentlastung"
// #define ENUM8005_0c_TEXT "Anfahrentlastung, Teillast"
// #define ENUM8005_0d_TEXT "Rückl’begrenzung"
// #define ENUM8005_0e_TEXT "Rückl’begrenzung, Teillast"
// #define ENUM8005_10_TEXT "Freigegeben, Teillast"
// #define ENUM8005_14_TEXT "Minimalbegrenzung"
// #define ENUM8005_15_TEXT "Minimalbegrenzung, Teillast"
// #define ENUM8005_16_TEXT "Minimalbegrenzung aktiv"
// #define ENUM8005_3b_TEXT "Ladung Pufferspeicher"
// #define ENUM8005_7b_TEXT "STB Test aktiv"
// #define ENUM8005_a6_TEXT "In Betrieb für Heizkreis"
// #define ENUM8005_a7_TEXT "In Teillastbetrieb für HK"
// #define ENUM8005_a8_TEXT "In Betrieb für Trinkwasser"
// #define ENUM8005_a9_TEXT "In Teillastbetrieb für TWW"
// #define ENUM8005_aa_TEXT "In Betrieb für HK, TWW"
// #define ENUM8005_ab_TEXT "In Teillastbetrieb für HK, TWW"
// #define ENUM8005_ac_TEXT "Gesperrt, Feststoffkessel"
// #define ENUM8005_ad_TEXT "Freigegeben für HK, TWW"
// #define ENUM8005_ae_TEXT "Freigeben für TWW"
// #define ENUM8005_af_TEXT "Freigegeben für HK"
// #define ENUM8005_b0_TEXT "Gesperrt, Außentemperatur"
// #define ENUM8005_c6_TEXT "Gesperrt, Ökobetrieb"
// #define ENUM8006_17_TEXT "Anlagefrostschutz aktiv"
// #define ENUM8006_1a_TEXT "Notbetrieb"
// #define ENUM8006_1b_TEXT "Gesperrt, extern"
// #define ENUM8006_1d_TEXT "HD bei WP-Betrieb"
// #define ENUM8006_1e_TEXT "Ström'wächter W'quelle"
// #define ENUM8006_1f_TEXT "Druckwächter W'quelle"
// #define ENUM8006_20_TEXT "Begr Heissgas Verdichter 1"
// #define ENUM8006_21_TEXT "Begr Heissgas Verdichter 2"
// #define ENUM8006_22_TEXT "Begr Ausschalttemp Max"
// #define ENUM8006_23_TEXT "Verd'stillstandzeit Min aktiv"
// #define ENUM8006_24_TEXT "Kompensat Wärmeüberschuss"
// #define ENUM8006_25_TEXT "Begrenzungszeit aktiv"
// #define ENUM8006_26_TEXT "Verd'laufzeit Min aktiv"
// #define ENUM8006_27_TEXT "Kompensation Wärmedefizit"
// #define ENUM8006_28_TEXT "Begr Spreiz Kondens Max"
// #define ENUM8006_29_TEXT "Begr Spreiz Kondens Min"
// #define ENUM8006_2a_TEXT "Begr Spreiz Verda Max"
// #define ENUM8006_2b_TEXT "Begr Spreiz Verda Min"
// #define ENUM8006_2c_TEXT "Verdichter und Elektro ein"
// #define ENUM8006_2d_TEXT "Verdichter 1 und 2 Ein"
// #define ENUM8006_2e_TEXT "Verdichter 1 Ein"
// #define ENUM8006_2f_TEXT "Verdichter 2 Ein"
// #define ENUM8006_30_TEXT "Frostschutz Wärmepumpe"
// #define ENUM8006_31_TEXT "Vorlauf aktiv"
// #define ENUM8006_32_TEXT "Freigegeben, Verd bereit"
#define ENUM8006_33_TEXT "Geen warmtevraag"
// #define ENUM8006_7d_TEXT "Abtauen aktiv"
// #define ENUM8006_7e_TEXT "Abtropfen"
// #define ENUM8006_7f_TEXT "Aktiver Kühlbetrieb"
// #define ENUM8006_80_TEXT "Passiver Kühlbetrieb"
// #define ENUM8006_81_TEXT "Abkühlen Verdampfer"
// #define ENUM8006_82_TEXT "Vorwärmen für Abtauen"
// #define ENUM8006_8b_TEXT "Begr Ausschalttemp. Min"
// #define ENUM8006_91_TEXT "Begr Aus'temp max Kühlen"
// #define ENUM8006_b4_TEXT "Drehstrom asymmetrisch"
// #define ENUM8006_b5_TEXT "Niederdruck"
// #define ENUM8006_b6_TEXT "Ventilator Überlast"
// #define ENUM8006_b7_TEXT "Verdichter 1 Überlast"
// #define ENUM8006_b8_TEXT "Verdichter 2 Überlast"
// #define ENUM8006_b9_TEXT "Quellenpumpe Überlast"
// #define ENUM8006_ba_TEXT "Ström'wächter Verbraucher"
// #define ENUM8006_bb_TEXT "Einsatzgrenze TA Min"
// #define ENUM8006_bc_TEXT "Einsatzgrenze TA Max"
// #define ENUM8006_bd_TEXT "Begr Quellentemp Min Wasser"
// #define ENUM8006_be_TEXT "Begr Quellentemp Min Sole"
// #define ENUM8006_bf_TEXT "Begr Quellentemp Max"
// #define ENUM8006_c0_TEXT "Zwangsabtauen Verdichter"
// #define ENUM8006_c1_TEXT "Zwangsabtauen Ventilator"
// #define ENUM8006_c2_TEXT "Abtauen mit Verdichter"
// #define ENUM8006_c3_TEXT "Abtauen mit Ventilator"
// #define ENUM8006_c4_TEXT "Begr Quellentemp Min Kühlen"
// #define ENUM8006_c5_TEXT "Elektro Ein"
// #define ENUM8006_cf_TEXT "Verd'laufzeit Min aktiv, Kühl"
// #define ENUM8006_d0_TEXT "Verd' 1 und 2 ein, Kühlbetr"
// #define ENUM8006_d1_TEXT "Verdichter 1 ein,Kühlbetrieb"
// #define ENUM8006_d2_TEXT "Verdichter 2 ein,Kühlbetrieb"
// #define ENUM8006_eb_TEXT "Wasserdruck zu niedrig"
// #define ENUM8006_f2_TEXT "Umschichtung aktiv"
// #define ENUM8006_f6_TEXT "Netzunterspannung"
// #define ENUM8006_fe_TEXT "Kältemittel abpumpen, Manuell"
// #define ENUM8006_01_00_TEXT "Kältemittel abpumpen"
// #define ENUM8006_01_01_TEXT "Startverzögerung Abtauen"
// #define ENUM8006_01_02_TEXT "Verdichter gesperrt"
// #define ENUM8006_01_03_TEXT "Gesperrt, Quellentemp Max"
// #define ENUM8006_01_04_TEXT "Gesperrt, Quellentemp Min"
// #define ENUM8006_01_05_TEXT "Gesperrt, Rücklauftemp Max"
// #define ENUM8006_01_06_TEXT "Gesperrt, Rücklauftemp Min"
// #define ENUM8006_01_07_TEXT "Gesperrt, Vorlauftemp Max"
// #define ENUM8006_01_08_TEXT "Gesperrt, Vorlauftemp Min"
// #define ENUM8006_01_09_TEXT "Gesperrt, Kondens'temp Max"
// #define ENUM8006_01_0a_TEXT "Gesperrt, Verdamp'temp Min"
// #define ENUM8006_01_0b_TEXT "Gesperrt, Heissgastemp Max"
// #define ENUM8006_01_0c_TEXT "Begr Verdampfungstemp Min"
// #define ENUM8006_01_0d_TEXT "Begr Kondensationstemp Max"
// #define ENUM8006_01_0e_TEXT "Begr Verdampfungstemp Max"
// #define ENUM8007_34_TEXT "Kollektorfrostschutz aktiv"
// #define ENUM8007_36_TEXT "Max Speichertemp erreicht"
// #define ENUM8007_37_TEXT "Verdampfungsschutz aktiv"
// #define ENUM8007_39_TEXT "Max Ladetemp erreicht"
// #define ENUM8007_3a_TEXT "Ladung Trinkwasser"
// #define ENUM8007_3c_TEXT "Ladung Schwimmbad"
// #define ENUM8007_3d_TEXT "Min Ladetemp nicht erreicht"
// #define ENUM8007_3e_TEXT "Temp’differenz ungenügend"
// #define ENUM8007_3f_TEXT "Einstrahlung ungenügend"
// #define ENUM8007_97_TEXT "Lad'ng TWW + Puffer + Sch'bad"
// #define ENUM8007_98_TEXT "Ladung Trinkwasser + Puffer"
// #define ENUM8007_99_TEXT "Ladung Trinkwasser + Sch'bad"
// #define ENUM8007_9a_TEXT "Ladung Puffer + Schwimmbad"
// #define ENUM8008_0d_TEXT "Rücklaufbegrenzung"
// #define ENUM8008_0e_TEXT "Rücklaufbegrenzung, Teillast"
// #define ENUM8008_8d_TEXT "Kesselfrostschutz aktiv"
// #define ENUM8008_a3_TEXT "Anfeuerungshilfe aktiv"
// #define ENUM8008_f1_TEXT "Restwärmenutzung"
// #define ENUM8009_2_D6_TEXT "Sicherheitszeit"
// #define ENUM8009_2_DA_TEXT "Vorlüften"
// #define ENUM8009_2_D7_TEXT "Inbetriebsetzung"
// #define ENUM8009_2_09_TEXT "?Außerbetriebsetzung"
// #define ENUM8009_2_D9_TEXT "Heimlauf"
// #define ENUM8009_2_DB_TEXT "Nachlüften"
// #define ENUM8009_09_TEXT "Außerbetriebsetzung"
// #define ENUM8009_E0_TEXT "Zünden"
// #define ENUM8009_E1_TEXT "Einschwingzeit"
// #define ENUM8010_33_TEXT "Keine Wärmeanforderung"
// #define ENUM8010_40_TEXT "Ladung Elektro, Notbetrieb"
// #define ENUM8010_41_TEXT "Ladung Elektro, Quell’schutz"
// #define ENUM8010_44_TEXT "Teilladung aktiv"
// #define ENUM8010_48_TEXT "Geladen, Zwanglad Solltemp"
// #define ENUM8010_49_TEXT "Geladen, Solltemperatur"
// #define ENUM8010_4a_TEXT "Teilgeladen, Solltemperatur"
// #define ENUM8010_4c_TEXT "Kalt"
// #define ENUM8010_7c_TEXT "Ladung eingeschränkt"
// #define ENUM8010_83_TEXT "Ladung Elektro, Abtauen"
// #define ENUM8010_87_TEXT "Sperrdauer nach Heizen"
// #define ENUM8010_8e_TEXT "Rückkühlung via TWW / Hk’s"
// #define ENUM8010_8f_TEXT "Geladen, Min Ladetemp"
// #define ENUM8010_93_TEXT "Warm"
// #define ENUM8010_a4_TEXT "Ladung Elektro, Zwang"
// #define ENUM8010_a5_TEXT "Ladung Elektro, Ersatz"
// #define ENUM8010_ca_TEXT "Frostschutz Kühlen aktiv"
// #define ENUM8010_cb_TEXT "Durchladung aktiv"
// #define ENUM8010_f4_TEXT "Erzeuger freigegeben"
// #define ENUM8011_9b_TEXT "Heizbetrieb Erzeuger"
// #define ENUM8011_9c_TEXT "Geheizt, Max Schw\'badtemp"
// #define ENUM8011_9d_TEXT "Geheizt, Sollwert Erzeuger"
// #define ENUM8011_9e_TEXT "Geheizt, Sollwert Solar"
// #define ENUM8011_9f_TEXT "Geheizt"
// #define ENUM8011_a0_TEXT "Heizbetrieb Solar aus"
// #define ENUM8011_a1_TEXT "Heizbetrieb Erzeuger aus"
// #define ENUM8011_a2_TEXT "Heizbetrieb aus"
// #define ENUM8100_01_TEXT "In Störung"
// #define ENUM8100_03_TEXT "Erzeugersperre aktiv"
// #define ENUM8100_05_TEXT "TWW-Trennschaltung aktiv"
// #define ENUM8100_06_TEXT "Außentemp'grenze aktiv"
// #define ENUM8100_07_TEXT "Nicht freigegeben"
// #define ENUM8313_01_TEXT "Kesselfühler B2"
// #define ENUM8313_02_TEXT "Rücklauffühler B7"
// #define ENUM8313_03_TEXT "TWW Ladefühler B36"
// #define ENUM8313_04_TEXT "TWW Zapffühler B38"
// #define ENUM8313_05_TEXT "TWW Zirkulationsfühler B39"
// #define ENUM8313_06_TEXT "Kaskadenfühler B10/ B70"
// #define ENUM8390_01_TEXT "1"
// #define ENUM8390_02_TEXT "2"
// #define ENUM8390_03_TEXT "TNN"
// #define ENUM8390_04_TEXT "STY"
// #define ENUM8390_05_TEXT "5"
// #define ENUM8390_06_TEXT "6"
// #define ENUM8390_07_TEXT "7"
// #define ENUM8390_08_TEXT "8"
// #define ENUM8390_09_TEXT "9"
// #define ENUM8390_0a_TEXT "10"
// #define ENUM8390_0b_TEXT "11"
// #define ENUM8390_0c_TEXT "12"
// #define ENUM8390_0d_TEXT "TSA"
// #define ENUM8390_0e_TEXT "14"
// #define ENUM8390_0f_TEXT "15"
// #define ENUM8390_10_TEXT "MOD"
// #define ENUM8390_11_TEXT "17"
// #define ENUM8390_12_TEXT "18"
// #define ENUM8390_13_TEXT "19"
// #define ENUM8390_14_TEXT "20"
// #define ENUM8390_15_TEXT "21"
// #define ENUM8390_16_TEXT "22"
// #define ENUM8390_17_TEXT "23"
// #define ENUM8390_18_TEXT "24"
// #define ENUM8749_00_TEXT "Kein Bedarf"
// #define ENUM15062_52_TEXT "QAA 50"
// #define ENUM15062_53_TEXT "QAA 70"