#define LANGUAGENAME_TEXT "Język polski"
#define ENUM_CAT_00_TEXT "Czas zegarowy i data"
#define ENUM_CAT_03_TEXT "Program 1. obiegu c.o."
#define ENUM_CAT_04_TEXT "Program 2. obiegu c.o."
#define ENUM_CAT_05_TEXT "Program 3 / ob.c.o. z pompą"
#define ENUM_CAT_06_TEXT "Time switch program DHW"
#define ENUM_CAT_08_TEXT "Wakacje, 1 obieg c.o."
#define ENUM_CAT_09_TEXT "Wakacje, 2 obieg c.o."
#define ENUM_CAT_0b_TEXT "Obieg c.o. 1"
#define ENUM_CAT_0d_TEXT "Obieg c.o. 2"
#define ENUM_CAT_0f_TEXT "Ciepła woda użytkowa"
#define ENUM_CAT_13_TEXT "Kocioł"
#define ENUM_CAT_19_TEXT "Obieg solarny"
#define ENUM_CAT_1b_TEXT "Zasobnik buforowy"
#define ENUM_CAT_1c_TEXT "Zasobnik c.w.u."
#define ENUM_CAT_1d_TEXT "Bezpośr. ładow. c.w.u."
#define ENUM_CAT_1e_TEXT "Konfiguracja"
#define ENUM_CAT_1f_TEXT "Magistrala LPB"
#define ENUM_CAT_20_TEXT "Błąd"
#define ENUM_CAT_21_TEXT "Konserwacja/Serwis"
#define ENUM_CAT_24_TEXT "Stan"
#define ENUM_CAT_26_TEXT "Diagnoza źródła ciepła"
#define ENUM_CAT_27_TEXT "Diagnoza odbiorców"
#define ENUM_CAT_28_TEXT "Regul. palnika"

#define MENU_TEXT_HFK "Funkcje pieca"
#define MENU_TEXT_SN1 "Czujniki DS18B20"
#define MENU_TEXT_SN2 "Czujniki DHT22"
#define MENU_TEXT_DLG "Wyświetl plik log"
#define MENU_TEXT_SLG "Wykres z pliku log"
#define MENU_TEXT_CFG "Konfiguracja"
#define MENU_TEXT_URL "Polecenia URL"
#define MENU_TEXT_HWT "Instrukcja obsługi"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Tak"
#define MENU_TEXT_NO "Nie"
#define MENU_TEXT_ON "Włączać"
#define MENU_TEXT_OFF "Wyłączać"
#define MENU_DESC_HFK "Pozwala na sprawdzenie lub ustawienie parametrów systemu grzewczego, posortowane w różnych kategoriach."
#define MENU_DESC_CFG "Wyświetla listę opcji konfiguracji. Większość z nich można zmienić, używając poleceń rozszerzonego adresu URL."
#define MENU_DESC_URL "Zaawansowane polecenia URL: Wyświetla listę rozszerzonych poleceń, do których można uzyskać dostęp bezpośrednio wprowadzając je w linii adresu przeglądarki. Polecenia te są również niezbędne do połączenia BSB-LAN z dowolnym systemem automatyki domowej, takim jak FHEM."

#define STR516_TEXT "Standard values TSP heating circuit 1"
#define STR536_TEXT "Standard values TSP heating circuit 2 "
#define STR556_TEXT "Standard values TSP3"
#define STR576_TEXT "Standard values TSP 4"
#define STR648_TEXT "Poziom roboczy podczas wakacji obieg 1"
#define STR652_TEXT "Okres wakacyjny 1 obiegu 2: dzień rozpoczęcia"
#define STR653_TEXT "Okres wakacyjny 1 obiegu 2: dzień zakończenia"
#define STR658_TEXT "Poziom roboczy podczas wakacji obieg 2"
#define STR700_TEXT "Tryb pracy obiegu grzewczego 1"
#define STR710_TEXT "Nastawa temp. komfortu obieg 1"
#define STR712_TEXT "Nastawa temp. zredukowanej obieg 1"
#define STR714_TEXT "Nastawa temp. ochrony p-mroz. obieg 1"
#define STR720_TEXT "Nachylenie krzywej grzewczej obiegu 1"
#define STR721_TEXT "Przesun. krzywej grzania"
#define STR726_TEXT "Heating curve adaptation heat circuit 1"
#define STR730_TEXT "Temperatura przełączenia lato/zima obieg 1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Flow temp min limitation heat circuit 1"
#define STR741_TEXT "Flow temp max limitation heat circuit 1"
#define STR750_TEXT "Room temp gain factor heat circuit 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Room temp setpoint boost HC1 (boost heating)"
#define STR780_TEXT "Quick setback heat circuit 1"
#define STR790_TEXT "Optymalizacja załączania maks. czas obieg 1"
#define STR791_TEXT "Optimum stop control max forward shift HC1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Osusz. jastrychu"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Punkt doboru pompy"
#define STR885_TEXT "Pompa modul. PWM min."
#define STR886_TEXT "Standard. temp. zewn."
#define STR887_TEXT "Temp. zasil. dla st. temp. zew"
#define STR888_TEXT "dT współcz. zwiększ."
#define STR894_TEXT "dT różn. dla st. temp. zewn."
#define STR1000_TEXT "Tryb pracy obiegu grzewczego 2"
#define STR1010_TEXT "Nastawa temp. komfortu obieg 2"
#define STR1012_TEXT "Nastawa temp. zredukowanej obieg 2"
#define STR1014_TEXT "Nastawa temp. ochrony p-mroz. obieg 2"
#define STR1020_TEXT "Nachylenie krzywej grzewczej obiegu 2"
#define STR1021_TEXT "Przesun. krzywej grzania"
#define STR1026_TEXT "Heating curve adaptation heat circuit 2"
#define STR1030_TEXT "Temperatura przełączenia lato/zima obieg 2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Flow temp min limitation heat circuit 2"
#define STR1041_TEXT "Flow temp max limitation heat circuit 2"
#define STR1050_TEXT "Room temp gain factor heat circuit 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Room temp setpoint boost HC2 (boost heating)"
#define STR1080_TEXT "Quick setback heat circuit 2"
#define STR1090_TEXT "Optymalizacja załączania maks. czas obieg 2"
#define STR1091_TEXT "Optimum stop control max forward shift HC2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Podw. temp. dla mieszacza"
#define STR1134_TEXT "Czas przebiegu siłownika"
#define STR1150_TEXT "Osusz. jastrychu"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "Tryb pracy CWU"
#define STR1610_TEXT "Temp. zadana"
#define STR1612_TEXT "Temp. zad. - zredukowana"
#define STR1620_TEXT "Włącz."
#define STR1640_TEXT "Dezynfekcja termiczna"
#define STR1641_TEXT "Dezynfekcja - okresowo"
#define STR1642_TEXT "Dezynfekcja - dzień tygod."
#define STR1644_TEXT "Dezynfekcja - godz."
#define STR1645_TEXT "Dezynfekcja - wart. zad."
#define STR1646_TEXT "Dezynfekcja - czas trwania"
#define STR1647_TEXT "Dezynfekcja - pompa cyrk."
#define STR1660_TEXT "Uruchamianie pompy cyrk."
#define STR1661_TEXT "Taktowanie pompy cyrk."
#define STR2201_TEXT "Blokada źródła ciepła"
#define STR2210_TEXT "Min. temp. zad."
#define STR2212_TEXT "Maks. temp. zad."
#define STR2440_TEXT "Maks. PWM went. ogrzew."
#define STR2441_TEXT "Maks. prędk. went. - ogrzew."
#define STR2442_TEXT "Opóźn. regul. went. PWM"
#define STR2443_TEXT "Wart. start. PWM dla podgrz."
#define STR2451_TEXT "Min. czas wyłącz. palnika"
#define STR2452_TEXT "Hist. wył. palnika"
#define STR2453_TEXT "Czas opóźn. regulat."
#define STR2454_TEXT "Histereza kotła"
#define STR2455_TEXT "Histereza wył. kotła min."
#define STR2456_TEXT "Histereza wył. kotła maks."
#define STR2471_TEXT "Czas wybiegu pompy"
#define STR2472_TEXT "Czas wybiegu pompy c.w.u."
#define STR2521_TEXT "Temp. włącz. ochron.p-mroz."
#define STR2522_TEXT "Temp. wył. ochron. p-mroz."
#define STR3810_TEXT "Różn. temp. zał."
#define STR3811_TEXT "Różn. temp. wył."
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Ochrona p-mroz. kolektora"
#define STR3850_TEXT "Ochrona kol. przed przegrz."
#define STR3860_TEXT "Parowanie nośnika ciepła"
#define STR4721_TEXT "Hister. autoblokady źródła"
#define STR4722_TEXT "Rożn. temp. bufor/c.o."
#define STR5019_TEXT "Ponowne ład. zasobnika"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Czas detekt. przepł. odbior."
#define STR5483_TEXT "Czas detekt. przepł. Komf."
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Schemat hydrauliczny"
#define STR5710_TEXT "Obieg c.o. 1"
#define STR5715_TEXT "Obieg c.o. 2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Pompa dosyłowa Q8"
#define STR5920_TEXT "Wyjście przekaź. K2 LMU"
#define STR5921_TEXT "Domyślnie K2 do K1"
#define STR5922_TEXT "Wyjście przekaź. 1 RelCl"
#define STR5923_TEXT "Wyjście przekaź. 2 RelCl"
#define STR5924_TEXT "Wyjście przekaź. 3 RelCl"
#define STR5926_TEXT "Wyjście przekaź. 1 SolCl"
#define STR5927_TEXT "Wyjście przekaź. 2 SolCl"
#define STR5928_TEXT "Wyjście przekaź. 3 SolCl"
#define STR5950_TEXT "Funkcja wejścia H1"
#define STR5957_TEXT "Modem"
#define STR5970_TEXT "Konfig. termost. pom. 1"
#define STR5971_TEXT "Konfig. termost. pom. 2"
#define STR5973_TEXT "Funkcja wejścia RelCl"
#define STR5975_TEXT "Max. nastawa temp. zasil."
#define STR5976_TEXT "Próg zewn. nastawy mocy"
#define STR6110_TEXT "Stała czasowa budynku"
#define STR6112_TEXT "Gradient modelu pomieszcz."
#define STR6120_TEXT "Ochrona p-mroz. instalacji"
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6220_TEXT "Wersja oprogramowania"
#define STR6225_TEXT "Grupa urządz."
#define STR6226_TEXT "Wariant urządzenia"
#define STR6227_TEXT "Wersja katalogu obiekt."
#define STR6230_TEXT "Konfig. regulatora 0"
#define STR6240_TEXT "Konfig. regulatora 1"
#define STR6250_TEXT "Konfig. regulatora 2"
#define STR6260_TEXT "Konfig. regulatora 3"
#define STR6270_TEXT "Konfig. regulatora 4"
#define STR6300_TEXT "Konfig. regulatora 7"
#define STR6330_TEXT "Konfig. regulatora 10"
#define STR6604_TEXT "Funkcja zasil. magistrali"
#define STR6605_TEXT "Stan zasilania magistrali"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Tryb zegara"
#define STR6705_TEXT "Kod diagnostyczny SW"
#define STR6706_TEXT "Faza regul. paln. poz. zablok."
#define STR6741_TEXT "Alarm - temp. zasilania 2"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "Kod diagnostyczny SW 3"
#define STR6826_TEXT "Regul. palnika faza 3"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "Kod diagnostyczny SW 4"
#define STR6836_TEXT "Regul. palnika faza 4"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "Kod diagnostyczny SW 5"
#define STR6846_TEXT "Regul. palnika faza 5"
#define STR7001_TEXT "Komunikat"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Potwierdzenie wiadomości"
#define STR7011_TEXT "Czas powtórz. wiadomości"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Prędk. went. prąd jonizacji"
#define STR7051_TEXT "Wiadomość - prąd joniz."
#define STR8000_TEXT "Stan 1. obiegu c.o."
#define STR8001_TEXT "Stan 2. obiegu c.o."
#define STR8003_TEXT "Stan c.w.u."
#define STR8005_TEXT "Stan kotła"
#define STR8007_TEXT "Stan kolektora"
#define STR8310_TEXT "Temperatura w kotle"
#define STR8311_TEXT "Wartość zadana kotła"
#define STR8314_TEXT "Temp. powrotu do kotła"
#define STR8316_TEXT "Temp. spalin"
#define STR8324_TEXT "Prędkość wentylatora"
#define STR8325_TEXT "Aktualne ster. wentylat."
#define STR8326_TEXT "Wydajność wzgl."
#define STR8328_TEXT "Wskaz. stanu reg. palnika"
#define STR2730_TEXT "Prąd jonizacji"
#define STR8336_TEXT "Czas pracy urządzenia"
#define STR8337_TEXT "Licznik startów palnika"
#define STR8338_TEXT "Czas pracy w trybie ogrzew"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Czas pracy stref"
#define STR8510_TEXT "Temperatura kolektora 1"
#define STR8530_TEXT "Czas pracy z wyk. kolektora"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Zred. temp. zewnętrzna"
#define STR8704_TEXT "Mieszana temp. zewnętrzna"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Temp. zasilania 1"
#define STR8744_TEXT "Temp. zadana zasilania H1"
#define STR8750_TEXT "Nastawa pompy modul."
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Wart. zad. w pomieszcz. 2"
#define STR8773_TEXT "Temp. zasilania 2"
#define STR8774_TEXT "Temp. zadana zasilania H2"
#define STR8830_TEXT "Temperatura c.w.u. 1"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "Temp. ładowania c.w.u."
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Temp. w zasob. bufor. 1"
#define STR9500_TEXT "Czas przed oczyszcz."
#define STR9502_TEXT "Ster. went. przed oczyszcz."
#define STR9504_TEXT "Wym. pręd. przed oczyszcz."
#define STR9510_TEXT "Ster. went. podczas zapłonu"
#define STR9512_TEXT "Wymag. prędkość zapłonu"
#define STR9520_TEXT "Min. wysterow. went"
#define STR9522_TEXT "Maks. wysterow. went."
#define STR9524_TEXT "Wymag. prędkość min."
#define STR9527_TEXT "Wymag. prędkość maks."
#define STR9540_TEXT "Czas po oczyszczaniu"
#define STR9560_TEXT "Ster. went.  pełne ładow."
#define STR9563_TEXT "Wym. prędk. dla pełn. ładow."
