#define LANGUAGENAME_TEXT "Svenska"
#define ENUM_CAT_00_TEXT "Klocka"
#define ENUM_CAT_03_TEXT "Tidprogram 1"
#define ENUM_CAT_04_TEXT "Tidprogram 2"
#define ENUM_CAT_05_TEXT "Tidprogram 3"
#define ENUM_CAT_06_TEXT "Tidprogram tappvarmvatten"
#define ENUM_CAT_08_TEXT "Semesterprogram VS1"
#define ENUM_CAT_09_TEXT "Semesterprogram VS2"
#define ENUM_CAT_0b_TEXT "Värmekrets 1"
#define ENUM_CAT_0d_TEXT "Värmekrets 2"
#define ENUM_CAT_0f_TEXT "Tappvarmvatten"
#define ENUM_CAT_13_TEXT "Panna"
#define ENUM_CAT_19_TEXT "Solvärme"
#define ENUM_CAT_1b_TEXT "Ackumulatortank"
#define ENUM_CAT_1c_TEXT "Tappvarmvattentank"
#define ENUM_CAT_1d_TEXT "Tappv.-direktladdning"
#define ENUM_CAT_1e_TEXT "Konfigurering"
#define ENUM_CAT_1f_TEXT "LPB system"
#define ENUM_CAT_20_TEXT "Larm"
#define ENUM_CAT_21_TEXT "Service/specialdrift"
#define ENUM_CAT_24_TEXT "Status"
#define ENUM_CAT_26_TEXT "Diagnostik producent"
#define ENUM_CAT_27_TEXT "Diagnostik konsument"
#define ENUM_CAT_28_TEXT "Brännarautomatik"
#define STR516_TEXT "Standardvärden Tidpr. värmekrets 1"
#define STR536_TEXT "Standardvärden Tidpr. värmekrets 2"
#define STR556_TEXT "Standardvärden Tidpr. VS3"
#define STR576_TEXT "Standardvärden Tidpr. 4"
#define STR648_TEXT "Semester driftläge VS1"
#define STR652_TEXT "Helgperiod 1 VS2: första dag"
#define STR653_TEXT "Helgperiod 1 VS2: sista dag"
#define STR658_TEXT "Semester driftläge VS2"
#define STR700_TEXT "Driftläge värmekrets 1"
#define STR710_TEXT "Rumstemperatur Komfortbörvärde VS1"
#define STR712_TEXT "Reducerat börvärde rumstemp värmekrets 1"
#define STR714_TEXT "Frysskyddsbörvärde rumstemp VS1"
#define STR720_TEXT "Värmekurva 1 lutning"
#define STR721_TEXT "Värmekurva parallellförskjutning"
#define STR726_TEXT "Adaptiv värmekurva värmekrets 1"
#define STR730_TEXT "Sommar/vinter omkoppling värmekrets 1"
#define STR732_TEXT "24-timmar värmegräns VS1"
#define STR740_TEXT "Framl.temp minbegränsning värmekrets 1"
#define STR741_TEXT "Framl.temp maxbegränsning värmekrets 1"
#define STR750_TEXT "Förstärkningsfaktor rumstemp värmekrets 1"
#define STR760_TEXT "Rumstemp.begränsning värmekrets 1"
#define STR770_TEXT "Börvärdeshöjning rumstemp VS1 (boost värme)"
#define STR780_TEXT "Snabbsänkning värmekrets 1"
#define STR790_TEXT "Optimerad start max framflyttning VS1"
#define STR791_TEXT "Optimerat stopp max framflyttning VS1"
#define STR800_TEXT "Start öka reducerat rumstempbörvärde VS1"
#define STR801_TEXT "Slut öka reducerat rumstempbörvärde VS1"
#define STR850_TEXT "Torkfunktion för golvgips"
#define STR851_TEXT "Golv manullt börvärde VS1"
#define STR884_TEXT "Pumphastighet vid värmeanl. dim.punkt"
#define STR885_TEXT "Modulerande pump PWM min"
#define STR886_TEXT "Utetemperatur vid max värmebehov"
#define STR887_TEXT "Börvärde panna vid dim utetemperatur"
#define STR888_TEXT "Begränsn. av temperaturhöjn. på dT regulator"
#define STR894_TEXT "Delta framl / returtemperatur vid dim. Utetemp"
#define STR1000_TEXT "Driftläge värmekrets 2"
#define STR1010_TEXT "Rumstemperatur Komfortbörvärde VS1"
#define STR1012_TEXT "Reducerat börvärde rumstemp värmekrets 2"
#define STR1014_TEXT "Frysskyddsbörvärde rumstemp VS2"
#define STR1020_TEXT "Värmekurva 2 lutning"
#define STR1021_TEXT "Värmekurva parallellförskjutning"
#define STR1026_TEXT "Adaptiv värmekurva värmekrets 2"
#define STR1030_TEXT "Sommar/vinter omkoppling värmekrets 2"
#define STR1032_TEXT "24-timmar värmegräns VS2"
#define STR1040_TEXT "Framl.temp minbegränsning värmekrets 2"
#define STR1041_TEXT "Framl.temp maxbegränsning värmekrets 2"
#define STR1050_TEXT "Förstärkningsfaktor rumstemp värmekrets 2"
#define STR1060_TEXT "Rumstemp.begränsning värmekrets 2"
#define STR1070_TEXT "Börvärdeshöjning rumstemp VS2 (boost värme)"
#define STR1080_TEXT "Snabbsänkning värmekrets 2"
#define STR1090_TEXT "Optimerad start max framflyttning VS2"
#define STR1091_TEXT "Optimerat stopp max framflyttning VS2"
#define STR1100_TEXT "Start öka reducerat rumstempbörvärde VS2"
#define STR1101_TEXT "Slut öka reducerat rumstempbörvärde VS2"
#define STR1130_TEXT "Temphöjn. blandn.ventil värmekrets"
#define STR1134_TEXT "Gångtid ställdon värmekrets"
#define STR1150_TEXT "Torkfunktion för golvgips"
#define STR1151_TEXT "Golv manullt börvärde VS2"
#define STR1600_TEXT "TVV Driftläge"
#define STR1610_TEXT "TVV temperatur nominellt börvärde"
#define STR1612_TEXT "TVV temperatur reducerat börvärde"
#define STR1620_TEXT "TVV aktivering"
#define STR1640_TEXT "Legionella funktion"
#define STR1641_TEXT "Periodicitet legionella funktion"
#define STR1642_TEXT "Legionella funktion dag"
#define STR1644_TEXT "Tid för legionella funktion"
#define STR1645_TEXT "Legionellafunktion börvärde"
#define STR1646_TEXT "Inkopplingstid för börvärde legionella funktion"
#define STR1647_TEXT "Drift cirk.pump under legionella funktion"
#define STR1660_TEXT "TVV cirkulationspump aktivering"
#define STR1661_TEXT "TVV cirkulationspump periodicitet"
#define STR2201_TEXT "Blockering värmegenerering"
#define STR2210_TEXT "Min begränsing panntemp"
#define STR2212_TEXT "Max begränsning panntemp"
#define STR2440_TEXT "Max nivå för modulering i värmedrift"
#define STR2441_TEXT "Max hastighet vid max utsignal i värmedrift"
#define STR2442_TEXT "Utsignal under fördr.tid regulator"
#define STR2443_TEXT "Modul. startvärde aktivering regulator TVV"
#define STR2451_TEXT "Min paustid brännare"
#define STR2452_TEXT "Max. regleravvikelse utan avbrott av paustid"
#define STR2453_TEXT "Fördr. regulator efter uppstart brännare"
#define STR2454_TEXT "Kopplingsdifferens panna"
#define STR2455_TEXT "Min urkoppl.differens för brännare"
#define STR2456_TEXT "Max urkoppl.differens för brännare"
#define STR2471_TEXT "Pump eftergångtid"
#define STR2472_TEXT "Eftergångtid pump temperatur TVV"
#define STR2521_TEXT "Frysskydd panna inkopplingstemperatur"
#define STR2522_TEXT "Frysskydd panna urkopplingstemperatur"
#define STR3810_TEXT "Tempdifferens för solvärme till"
#define STR3811_TEXT "Tempdifferens för solvärme från"
#define STR3812_TEXT "Mintemp laddning"
#define STR3831_TEXT "Min gångtid kollektorpump"
#define STR3840_TEXT "Frysskydd kollektortemp"
#define STR3850_TEXT "Kollektor övertempskydd"
#define STR3860_TEXT "Ångbildningstemperatur för värmebärare"
#define STR4721_TEXT "Automatisk prod. blockering koppl.differens"
#define STR4722_TEXT "Diff. Ack/VS temp till aktivering laddning"
#define STR5019_TEXT "Förhöjt börv. för skiktladdning. Tank"
#define STR5020_TEXT "TVV förhöjd framledn."
#define STR5050_TEXT "Max laddningstemp TVV"
#define STR5055_TEXT "Min återkylningstemperatur för TVV ack.tank"
#define STR5100_TEXT "Min pumphast. för full laddm. av strat.tank"
#define STR5020_TEXT "TVV förhöjd framledn."
#define STR5400_TEXT "Börvärde för beredskapstemperatur"
#define STR5430_TEXT "Inkoppl.differens i TVV-drift (givare 1)"
#define STR5431_TEXT "Min. urkoppl.diff. i TVV-drift (givare 1)"
#define STR5432_TEXT "Max. urkoppl.diff. i TVV-drift (givare 1)"
#define STR5433_TEXT "Inkoppl.diff. i TVV-driftt (givare 2)"
#define STR5434_TEXT "Min. urkoppl.differens i TVV-drift (givare2)"
#define STR5435_TEXT "Max urkoppl.diff. i TVV-drift (givare 2)"
#define STR5450_TEXT "Gränsvärde för detektering av TVV förbrukning"
#define STR5451_TEXT "Gränsvärde för det. TVV förbrukn. i komfortdrift"
#define STR5452_TEXT "Gränsvärde för detekt TVV förbrukn. i värmedrift"
#define STR5453_TEXT "Börvärdesjustering vid 40°C i komfortdrift"
#define STR5454_TEXT "Börvärdesjustering vid 60°C i komfortdrift"
#define STR5455_TEXT "Börvärdesjustering vi 40°C utgående temperatur"
#define STR5456_TEXT "Börvärdesjustering vi 60°C utgående temperatur"
#define STR5480_TEXT "Tid för inst. TVV komfort efter förbrukning"
#define STR5481_TEXT "Tid för inst. TVV komfort efter förbrukning (Vä)"
#define STR5482_TEXT "Tid TVV flödesvakt är stängd"
#define STR5483_TEXT "Tid TVV komfort flödesvakt är stängd"
#define STR5486_TEXT "Regulatorfördröjn. vid snabba TVV-belastningar"
#define STR5487_TEXT "Gångtid pump i TVV komfort efter frånslag bränn"
#define STR5488_TEXT "Gångtid pump i TVV komfort efter frånslag bränn"
#define STR5701_TEXT "Anläggningstyp"
#define STR5710_TEXT "Värmekrets 1"
#define STR5715_TEXT "Värmekrets 2"
#define STR5732_TEXT "Frånsl.tid vid växl. från värme till TVV-drift"
#define STR5733_TEXT "Frånsl.fördr vid växl. från värme till TVV-drift"
#define STR5761_TEXT "Värmebehov med assistans av pump Q8"
#define STR5920_TEXT "Funktion programmerbar utgång K2 LMU"
#define STR5921_TEXT "Default K2 på K1"
#define STR5922_TEXT "Funktion utgång 1 extra funktionsmodul"
#define STR5923_TEXT "Funktion utgång 2 extra funktionsmodul"
#define STR5924_TEXT "Funktion utgång 3 extra funktionsmodul"
#define STR5926_TEXT "Konfiguration utgång 1"
#define STR5927_TEXT "Konfiguration utgång 2"
#define STR5928_TEXT "Konfiguration utgång 3"
#define STR5950_TEXT "Val av funktion för ingång H1"
#define STR5957_TEXT "Modem funktion"
#define STR5970_TEXT "Konfigurera rumstermostat 1"
#define STR5971_TEXT "Konfigurera rumstermostat 2"
#define STR5973_TEXT "Funktion ingång RelCl"
#define STR5975_TEXT "Max temperatur för externt värmebehov"
#define STR5976_TEXT "Låg gräns ingångsignal för ext. Värmebehov"
#define STR6110_TEXT "Byggnadens tidskonstant"
#define STR6112_TEXT "Lutning rumsmodell"
#define STR6120_TEXT "Frysskydd för anläggnigen"
#define STR6127_TEXT "Tid för motionering av pump / fördelningsventil"
#define STR6220_TEXT "ApparatSW version"
#define STR6225_TEXT "Apparat familj"
#define STR6226_TEXT "Apparat variant"
#define STR6227_TEXT "Apparat OV version"
#define STR6230_TEXT "Regulatorinställning 0"
#define STR6240_TEXT "Regulatorinställning 1"
#define STR6250_TEXT "Regulatorinställning 2"
#define STR6260_TEXT "Regulatorinställning 3"
#define STR6270_TEXT "Regulatorinställning 4"
#define STR6300_TEXT "Regulatorinställning 7"
#define STR6330_TEXT "Regulatorkonfiguration 10"
#define STR6604_TEXT "LPB matning funktionsval"
#define STR6605_TEXT "LPB matning status"
#define STR6625_TEXT "TVV fördelning"
#define STR6640_TEXT "Källa för klocktid"
#define STR6705_TEXT "Internt värde på diagnostik kod"
#define STR6706_TEXT "Aktuellt värde på blockeringsfas"
#define STR6741_TEXT "Tid larm framledningstemperatur VS2"
#define STR6823_TEXT "3dje senaste värde på albatros diagnostik kod"
#define STR6825_TEXT "3dje senaste värde för intern diagnostik kod"
#define STR6826_TEXT "3dje senaste värde för blockeringsfas"
#define STR6830_TEXT "4e senaste värde blockering kodräknare"
#define STR6833_TEXT "4e senaste värde på albatros diagnostik kod"
#define STR6835_TEXT "4e senaste värde för intern diagnostik kod"
#define STR6836_TEXT "4e senaste värde för blockeringsfas"
#define STR6840_TEXT "5e senaste värde blockering kodräknare"
#define STR6843_TEXT "5e senaste värde på albatros diagnostik kod"
#define STR6845_TEXT "5e senaste värde för intern diagnostik kod"
#define STR6846_TEXT "5e senaste värde för blockeringsfas"
#define STR7001_TEXT "Underhållsmeddelande"
#define STR7007_TEXT "Konfiguration / Återställn. av servicemeddelande"
#define STR7010_TEXT "Bekräftelse på  servicemeddelande"
#define STR7011_TEXT "Repetitionstid för servicemeddelanden"
#define STR7040_TEXT "Underhållsintervall brännare"
#define STR7041_TEXT "Drifttid sedan senaste service"
#define STR7042_TEXT "Begräns. brännarstarter sedan senaste service"
#define STR7043_TEXT "Brännarstarter sedan senaste service"
#define STR7044_TEXT "Begräns antal månader sedan senaste service"
#define STR7045_TEXT "Månader sedan senaste service"
#define STR7050_TEXT "Gräns fläkhastighet för servicemeddelande"
#define STR7051_TEXT "Ionisation aktuellt servicemeddelande"
#define STR8000_TEXT "Status värmekrets 1"
#define STR8001_TEXT "Status värmekrets 2"
#define STR8003_TEXT "Status TVV"
#define STR8005_TEXT "Status panna"
#define STR8007_TEXT "Status Solvärme"
#define STR8310_TEXT "Panntemp ärvärde"
#define STR8311_TEXT "Börvärde panntemp."
#define STR8314_TEXT "Returtemp aktuellt värde"
#define STR8316_TEXT "Rökgastemp aktuellt värde"
#define STR8324_TEXT "Aktuell fläkthastighet"
#define STR8325_TEXT "Aktuell fläktstyrning"
#define STR8326_TEXT "Relativ utsignal"
#define STR8328_TEXT "Driftindikering brännare"
#define STR2730_TEXT "Uppmätt värde på joniseringsström"
#define STR8336_TEXT "Drifttid apparat"
#define STR8337_TEXT "Starträknare brännare"
#define STR8338_TEXT "Drifttid brännare"
#define STR8339_TEXT "Drifttid TVV-värme"
#define STR8340_TEXT "Drifttid zon"
#define STR8510_TEXT "Aktuellt värde kollektortemp 1 (B6)"
#define STR8530_TEXT "Solfångare drifttid tillskott"
#define STR8700_TEXT "Lokal utetemp.givare"
#define STR8703_TEXT "Dämpad utetemp"
#define STR8704_TEXT "Lagrad utetemp"
#define STR8740_TEXT "Rumstemp 1 aktuellt värde"
#define STR8741_TEXT "Aktuellt börvärde rumstemp"
#define STR8743_TEXT "Framl.temp aktuellt värde värmekrets 1"
#define STR8744_TEXT "Framledn.temperatur börvärde H1"
#define STR8750_TEXT "Pumphastighet"
#define STR8770_TEXT "Rumstemp 2 aktuellt värde"
#define STR8771_TEXT "Aktuellt börvärde rumstemp VS2"
#define STR8773_TEXT "Framl.temp aktuellt värde värmekrets 2"
#define STR8774_TEXT "Framledn.temperatur börvärde H2"
#define STR8830_TEXT "TVV temperatur aktuellt värde topp (B3)"
#define STR8831_TEXT "TVV temp aktuellt börvärde"
#define STR8836_TEXT "TVV laddningstemperatur"
#define STR8950_TEXT "Process signal segment framl."
#define STR8952_TEXT "Process signal segment retur"
#define STR8980_TEXT "Aktuellt värde ackumulerad temp toppen (B4)"
#define STR9500_TEXT "Tid förventilation"
#define STR9502_TEXT "Modulerande luft vid förventilation"
#define STR9504_TEXT "Erforderlig fläkthastighet vid förvädring"
#define STR9510_TEXT "Modulerande luft vid tändning"
#define STR9512_TEXT "Erforderlig hastighet vid tändning"
#define STR9520_TEXT "Modulerande luft vid låg flamma"
#define STR9522_TEXT "Modulerande luft vid hög flamma"
#define STR9524_TEXT "Erforderlig hastighet vid låg flamma"
#define STR9527_TEXT "Erforderlig hastighet vid hög flamma"
#define STR9540_TEXT "Tid efterventilation"
#define STR9560_TEXT "Fläktmodulering för full skiktladdning av tank"
#define STR9563_TEXT "Fläkthast. för full skiktladdning av tank"
