#define ENUM_CAT_00_TEXT "Ημερομηνία/ώρα"
#define ENUM_CAT_01_TEXT "Μονάδα δωματίου"
#define ENUM_CAT_02_TEXT "Ασύρματο"
#define ENUM_CAT_03_TEXT "Ώρα αλλαγής προγράμματος 1"
#define ENUM_CAT_04_TEXT "Ώρα αλλαγής προγράμματος 2"
#define ENUM_CAT_05_TEXT "Ώρα αλλαγής προγράμματος 3"
#define ENUM_CAT_06_TEXT "Ώρα αλλαγής προγράμματος 4/ΖΝΧ"
#define ENUM_CAT_07_TEXT "Ώρα αλλαγής προγράμματος 5"
#define ENUM_CAT_08_TEXT "Προγράμματα διακοπών HC1"
#define ENUM_CAT_09_TEXT "Προγράμματα διακοπών HC2"
#define ENUM_CAT_0a_TEXT "Προγράμματα διακοπών HC3"
#define ENUM_CAT_0b_TEXT "Κύκλωμα θέρμανσης 1"
#define ENUM_CAT_0c_TEXT "Κύκλωμα ψύξης 1"
#define ENUM_CAT_0d_TEXT "Κύκλωμα θέρμανσης 2"
#define ENUM_CAT_0e_TEXT "Κύκλωμα ψύξης 2"
#define ENUM_CAT_0f_TEXT "ΖΝΧ"
#define ENUM_CAT_10_TEXT "Αντλία Hx"
#define ENUM_CAT_11_TEXT "Πισίνα"
#define ENUM_CAT_12_TEXT "Primary controller/system pump"
#define ENUM_CAT_13_TEXT "Λέβητας"
#define ENUM_CAT_14_TEXT "Sitherm Pro"
#define ENUM_CAT_15_TEXT "Αντλία θερμότητας"
#define ENUM_CAT_16_TEXT "Μετρητής ενεργείας"
#define ENUM_CAT_17_TEXT "Διαδοχή"
#define ENUM_CAT_18_TEXT "Πρόσθετη πηγή θερμότητας"
#define ENUM_CAT_19_TEXT "Ηλιακό"
#define ENUM_CAT_19_TEXT "Λέβητας στερεού καυσίμου"
#define ENUM_CAT_1b_TEXT "Δοχείο αδράνειας"
#define ENUM_CAT_1c_TEXT "Δεξαμενή ΖΝΧ"
#define ENUM_CAT_1d_TEXT "Απευθείας φόρτιση ΖΝΧ"
#define ENUM_CAT_1e_TEXT "Διαμόρφωση"
#define ENUM_CAT_1f_TEXT "LPB"
#define ENUM_CAT_20_TEXT "Σφάλμα"
#define ENUM_CAT_21_TEXT "Συντήρηση/Ειδική λειτουργία"
#define ENUM_CAT_22_TEXT "Διαμόρφωση πρόσθετων αρθρωμάτων"
#define ENUM_CAT_23_TEXT "Δοκιμές εισόδου/εξόδου"
#define ENUM_CAT_24_TEXT "Κατάσταση"
#define ENUM_CAT_25_TEXT "Διάγνωση διαδοχής"
#define ENUM_CAT_26_TEXT "Διάγνωση προμηθευτή"
#define ENUM_CAT_27_TEXT "Διάγνωση καταναλωτή"
#define ENUM_CAT_28_TEXT "Έλεγχος καυστήρα"
#define ENUM_CAT_29_TEXT "Ορισμένη από το χρήστη"
#define ENUM_CAT_2a_TEXT "Αρτηρία PPS"
#define ENUM_CAT_2b_TEXT "Άγνωστη κατηγορία"
