#define ENUM_CAT_00_TEXT "Óra állás"
#define ENUM_CAT_03_TEXT "1.fűtési kör időprogram"
#define ENUM_CAT_04_TEXT "2.fűtési kör időprogram"
#define ENUM_CAT_05_TEXT "Időprogram 3/HCP"
#define ENUM_CAT_06_TEXT "Time switch program DHW"
#define ENUM_CAT_08_TEXT "Szabadság fűtési kör 1"
#define ENUM_CAT_09_TEXT "Szabadság fűtési kör 2"
#define ENUM_CAT_0b_TEXT "Fűtési kör 1"
#define ENUM_CAT_0d_TEXT "Fűtési kör 2"
#define ENUM_CAT_0f_TEXT "Használati melegvíz"
#define ENUM_CAT_13_TEXT "Kazán"
#define ENUM_CAT_19_TEXT "Napkollektor"
#define ENUM_CAT_1b_TEXT "Puffertároló"
#define ENUM_CAT_1c_TEXT "HMV tároló"
#define ENUM_CAT_1d_TEXT "Közvetlen HMV töltés"
#define ENUM_CAT_1e_TEXT "Konfiguráció"
#define ENUM_CAT_1f_TEXT "LPB rendszer"
#define ENUM_CAT_20_TEXT "Hiba"
#define ENUM_CAT_21_TEXT "Wartung"
#define ENUM_CAT_24_TEXT "Állapot"
#define ENUM_CAT_26_TEXT "Hőterm. hibakeresés"
#define ENUM_CAT_27_TEXT "Fogyasztó hibakeresés"
#define ENUM_CAT_28_TEXT "Kazán szabályozás"
#define STR516_TEXT "Kapcs.óra program standard értékek 1. fűtési kör"
#define STR536_TEXT "Kapcs.óra program standard értékek 2. fűtési kör"
#define STR556_TEXT "3. kapcsolóóra program standard értékek"
#define STR576_TEXT "4. kapcsolóóra program"
#define STR648_TEXT "Szünidei üzemi szint FK1"
#define STR652_TEXT "FK2 1. szünidei periódus: első nap"
#define STR653_TEXT "FK2 1. szünidei periódus: utolsó nap"
#define STR658_TEXT "Szünidei üzemi szint FK2"
#define STR700_TEXT "FK1 üzemmód fajta"
#define STR710_TEXT "Helyiséghőmérséklet komfort alapjel 1.fűtési kör"
#define STR712_TEXT "Csökkentett helyiség hőm. aapjel FK1"
#define STR714_TEXT "Helyiség hőm. fagyvédelmi alapjel FK1"
#define STR720_TEXT "1. Fűtési jelleggörbe meredekség"
#define STR721_TEXT "Fűtési jelleggörbe párhuzamos eltolás"
#define STR726_TEXT "Fűtési jelleggörbe adaptáció 1. fűtési kör"
#define STR730_TEXT "Nyári/téli átkapcsolási hőmérséklet 1.fűtési kör"
#define STR732_TEXT "FK1 napi fűtési határ"
#define STR740_TEXT "Előremenő hőm. minimum korlátozás FK1"
#define STR741_TEXT "Előremenő hőm. maximum korlátozás FK1"
#define STR750_TEXT "Helyiség hőm. ráhatási tényező 1 .fűtési kör"
#define STR760_TEXT "1. fűtési kör helyiség hőmérséklet korlátozás"
#define STR770_TEXT "FK1 helyiség alapjel megemelés (gyors felfűtés)"
#define STR780_TEXT "FK1 gyors fűtéscsökkentés"
#define STR790_TEXT "FK1 bekapcs.optimalizálás max. előrehozatali idő"
#define STR791_TEXT "FK1 kikapcs.optimalizálás max. előrehozatali idő"
#define STR800_TEXT "Hely.-hőm.-csökkentett alapjel megem.kezd. FK1"
#define STR801_TEXT "Hely.-hőm.-csökkentett alapjel megem.vége FK1"
#define STR850_TEXT "Padlóburkolat kiszáradási funkció"
#define STR851_TEXT "Padlóburkolat megkötési alapjel, kézi, FK1"
#define STR884_TEXT "Kazánsziv. ford.szám-fokozat névl. munkapont"
#define STR885_TEXT "Modulációs szivattyú imp.szél.mod.minimum"
#define STR886_TEXT "Külső hőmérséklet max. hőigény esetén"
#define STR887_TEXT "Kazánhőmérséklet normál külső hőmérsékletnél"
#define STR888_TEXT "Hőm.megemelési határ dT-szabályozáshoz"
#define STR894_TEXT "Előre.-/visszat. különbség normál külső hőm.-en"
#define STR1000_TEXT "FK2  üzemmód fajta"
#define STR1010_TEXT "Helyiséghőmérséklet komfort alapjel FK2"
#define STR1012_TEXT "Csökkentett helyiség hőm. alapjel FK2"
#define STR1014_TEXT "Helyiség hőm. fagyvédelmi alapjel FK2"
#define STR1020_TEXT "2. Fűtési jelleggörbe meredekség"
#define STR1021_TEXT "Fűtési jelleggörbe párhuzamos eltolás"
#define STR1026_TEXT "Fűtési jelleggörbe adaptáció 2. fűtési kör"
#define STR1030_TEXT "Nyári/téli átkapcsolási hőmérséklet 2.fűtési kör"
#define STR1032_TEXT "FK2 napi fűtési határ"
#define STR1040_TEXT "Előremenő hőm. minimum korlátozás FK2"
#define STR1041_TEXT "Előremenő hőm. maximum korlátozás FK2"
#define STR1050_TEXT "Helyiség hőm. ráhatási tényező 2. fűtési kör"
#define STR1060_TEXT "2. fűtési kör helyiség hőmérséklet korlátozás"
#define STR1070_TEXT "FK2 helyiség alapjel megemelés (gyors felfűtés)"
#define STR1080_TEXT "FK2 gyors fűtéscsökkentés"
#define STR1090_TEXT "FK2 bekapcs.optimalizálás max. előrehozatali idő"
#define STR1091_TEXT "FK2 kikapcs.optimalizálás max. előrehozatali idő"
#define STR1100_TEXT "Hely.-hőm.-csökkentett alapjel megem.kezd. FK2"
#define STR1101_TEXT "Hely.-hőm.-csökkentett alapjel megem.vége FK2"
#define STR1130_TEXT "Keverőszelepes FK hőmérséklet túlemelés"
#define STR1134_TEXT "Fűtésköri állítómű futási idő"
#define STR1150_TEXT "Padlóburkolat kiszáradási funkció"
#define STR1151_TEXT "Padlóburkolat megkötési alapjel, kézi, FK2"
#define STR1600_TEXT "Használati melegvíz üzemmód"
#define STR1610_TEXT "HMV hőmérséklet névleges alapjel"
#define STR1612_TEXT "HMV hőmérséklet csökkentett alapjel"
#define STR1620_TEXT "HMV engedélyezés"
#define STR1640_TEXT "Legionella funkció"
#define STR1641_TEXT "Legionella funkció ismétlődése"
#define STR1642_TEXT "Legionella funkció napja"
#define STR1644_TEXT "Legionella funkció időpontja"
#define STR1645_TEXT "Lagionella funkció hőmérséklet alapjel"
#define STR1646_TEXT "Tartózkodási idő a legionella hőmérs alapjelen"
#define STR1647_TEXT "Cirkulációs szivattyú üzem legionella funk.alatt"
#define STR1660_TEXT "HMV cirkulációs szivattyú engedélyezés"
#define STR1661_TEXT "HMV cirkilációs szivattyú impulzus üzemmód"
#define STR2201_TEXT "Hőtermelés kizárva"
#define STR2210_TEXT "Kazánhőmérséklet minimum korlátozás"
#define STR2212_TEXT "Kazánhőmérséklet maximum korlátozás"
#define STR2440_TEXT "Maximális modulációs fok fűtés üzemmódban"
#define STR2441_TEXT "Max. ventillátor fordulatszám fűtés üzemmódban"
#define STR2442_TEXT "Teljesítmény aktív szabályozás késleltetéskor"
#define STR2443_TEXT "Teljesítmény start Dlh üzemmódban"
#define STR2451_TEXT "Égő minimális szünetidő"
#define STR2452_TEXT "Max.szab.eltérés min.szünet letörés nélkül"
#define STR2453_TEXT "Szabályozás késleltetése üzembe helyezés után"
#define STR2454_TEXT "Kazán hiszterézis"
#define STR2455_TEXT "Kazán minimális kikapcsolási hiszterézis"
#define STR2456_TEXT "Kazán maximális kikapcsolási hiszterézis"
#define STR2471_TEXT "Szivattyú utánjáratási idő"
#define STR2472_TEXT "HMV szivattyú utánjáratási hőmérséklet"
#define STR2521_TEXT "Kazán fagyvédelem bekapcsolási hőmérséklet"
#define STR2522_TEXT "Kazán fagyvédelem kikapcsolási hőmérséklet"
#define STR3810_TEXT "Napkollektor bekapcsolási hőmérséklet különbség"
#define STR3811_TEXT "Napkollektor kikapcsolási hőmérséklet különbség"
#define STR3812_TEXT "Minimális töltési hőmérséklet"
#define STR3831_TEXT "Kollektor szivattyú minimális futási idő"
#define STR3840_TEXT "Kollektor fagyvédelmi hőmérséklet"
#define STR3850_TEXT "Kollektor túlmelegedés védelmi hőmérséklet"
#define STR3860_TEXT "Hőhordozó forrásponti hőmérséklet"
#define STR4721_TEXT "Automatikus hőtermelő letiltás hiszterézis"
#define STR4722_TEXT "Puffer/FK dT a hőtermelő engedélyezéséig"
#define STR5019_TEXT "Alapjelmegemelés réteghőmérs.utántöltéshez"
#define STR5020_TEXT "Előremenő hőmérséklet megemelés HMV-hez"
#define STR5050_TEXT "HMV tároló maximális töltési hőmérséklet"
#define STR5055_TEXT "Minimális visszatérő hőmérséklet HMV-tárolóhoz"
#define STR5100_TEXT "Min.sziv.ford.sz. réteghőmérs. áttöltéshez"
#define STR5020_TEXT "Előremenő hőmérséklet megemelés HMV-hez"
#define STR5400_TEXT "HMV készenléti hőmérséklet alapjel"
#define STR5430_TEXT "Bekap. különbség HMV üzemmódban (1.érzékelő)"
#define STR5431_TEXT "Min.kikapcs.különbs. HMV üzemm.-ban (1.érzékelő)"
#define STR5432_TEXT "Max.kikapcs.különbs. HMV üzemm.-ban (1.érzékelő)"
#define STR5433_TEXT "Bekap. különbség HMV üzemmódban (2.érzékelő)"
#define STR5434_TEXT "Min.kikapcs.különbség HMV-üzemben (2.érzékelő)"
#define STR5435_TEXT "Min.kikapcs.különbs. HMV üzemm.-ban (2.érzékelő)"
#define STR5450_TEXT "Küszöb a HMV-megcsapolás végéhez Dlh-nál"
#define STR5451_TEXT "Küszöb a HMV-megcs. Vég. Dlh-nál komfortban"
#define STR5452_TEXT "Küszöb a HMV-megcs. Vég. Dlh-nál fűtésnél"
#define STR5453_TEXT "Alapjel korrekció komfort szabályozásnál 40°C"
#define STR5454_TEXT "Alapjel korrekció komfort szabályozásnál 60°C"
#define STR5455_TEXT "Alapjel korrekció kifolyás szabályozásnál 40°C"
#define STR5456_TEXT "Alapjel korrekció kifolyás szabályozásnál 60°C"
#define STR5480_TEXT "Dlh-Komf.idő megcsap.után aktív fűt.höig.nélkül"
#define STR5481_TEXT "Dlh-Komf.idő megcsap.után aktív fűt.höig.mellett"
#define STR5482_TEXT "HSZ hőm.korl./áraml.kapcs. zárási idő"
#define STR5483_TEXT "HSZ komfort hőm.korl./áraml.kapcs. zárási idő"
#define STR5486_TEXT "Szabályozás késleltetés DLH pulzációs kifutásnál"
#define STR5487_TEXT "Szivattyú utánjár. Dlh-komfort-ban égő KI-nél"
#define STR5488_TEXT "Szivattyú utánjár. Dlh-komfort-ban égő KI-nél"
#define STR5701_TEXT "Hidraulikai séma"
#define STR5710_TEXT "1. fűtési kör"
#define STR5715_TEXT "2. fűtési kör"
#define STR5732_TEXT "Sziv.lekapcsolási idő fűtésről HMV-re váltáskor"
#define STR5733_TEXT "Sziv.lekapcs.késleltetés FK-ról HMV-re vált.-kor"
#define STR5761_TEXT "Hőigény a Q8 támogatásával"
#define STR5920_TEXT "Programozható kimenet K2"
#define STR5921_TEXT "Alapbeállítás K2, K1-re"
#define STR5922_TEXT "Funkció kimenet 1.relé Clip-In"
#define STR5923_TEXT "Funkció kimenet  2.relé Clip-In"
#define STR5924_TEXT "Funkció kimenet  3.relé Clip-In"
#define STR5926_TEXT "1. kimenet konfigurációja"
#define STR5927_TEXT "2. kimenet konfigurációja"
#define STR5928_TEXT "3. kimenet konfigurációja"
#define STR5950_TEXT "H1 bemenet funkció választás"
#define STR5957_TEXT "Modemfunkció"
#define STR5970_TEXT "1. helyiség termosztát konfigurálása"
#define STR5971_TEXT "2. helyiség termosztát konfigurálása"
#define STR5973_TEXT "Funkcionális bemenet RelCl"
#define STR5975_TEXT "Hőmérséklet határ külső alapjeladóhoz"
#define STR5976_TEXT "bemenőjel alsó határ külső hőigényhez"
#define STR6110_TEXT "Épület időállandó"
#define STR6112_TEXT "Helyiség modell meredekség"
#define STR6120_TEXT "Rendszer fagyvédelem"
#define STR6127_TEXT "Időtartam szivattyú / váltószelep megjáratáshoz"
#define STR6220_TEXT "Készülék-SW-verzió"
#define STR6225_TEXT "Készülék-család"
#define STR6226_TEXT "Készülék-változat"
#define STR6227_TEXT "Készülék-OV-verzió"
#define STR6230_TEXT "Szabályozó konfiguráció 0"
#define STR6240_TEXT "Szabályozó konfiguráció 1"
#define STR6250_TEXT "Szabályozó konfiguráció 2"
#define STR6260_TEXT "Szabályozó konfiguráció 3"
#define STR6270_TEXT "Szabályozó konfiguráció 4"
#define STR6300_TEXT "Szabályozó konfiguráció 7"
#define STR6330_TEXT "Szabályozó konfiguráció 10"
#define STR6604_TEXT "LPB-táplálás funkció választás"
#define STR6605_TEXT "LPB-táplálás státusz"
#define STR6625_TEXT "Használati melegvíz hozzárendelés"
#define STR6640_TEXT "Óra-készülékcím"
#define STR6705_TEXT "Belső diagnosztikai  kód"
#define STR6706_TEXT "zavar fázis aktuális értéke"
#define STR6741_TEXT "Előremenő hőmérséklet riasztási idő FK2"
#define STR6823_TEXT "Albatros hibakód 3. korábbi érték"
#define STR6825_TEXT "3-as zavar diagnosztika korábbi értéke"
#define STR6826_TEXT "3-as hibafázis korábbi értéke"
#define STR6830_TEXT "4-es hibakód számláló korábbi értéke"
#define STR6833_TEXT "Albatros hibakód 4. korábbi érték"
#define STR6835_TEXT "4-es zavar diagnosztika korábbi értéke"
#define STR6836_TEXT "4-es hibafázis korábbi értéke"
#define STR6840_TEXT "5-ös hibakód számláló korábbi értéke"
#define STR6843_TEXT "Albatros hibakód 5. korábbi érték"
#define STR6845_TEXT "5-ös zavar diagnosztika korábbi értéke"
#define STR6846_TEXT "5-ös hibafázis korábbi értéke"
#define STR7001_TEXT "Karbantartás jelzés"
#define STR7007_TEXT "karbantartás jelzés konfigurálás / reset"
#define STR7010_TEXT "Karbantartás jelzés nyugtázás"
#define STR7011_TEXT "Ismétlési idő karbantartás jelzéshez"
#define STR7040_TEXT "Égő karbantartási intervallum"
#define STR7041_TEXT "Üzemóraszám a legutóbbi karbantartás óta"
#define STR7042_TEXT "Határ üz.hel.-hez a legutóbbi karbantartás óta"
#define STR7043_TEXT "Üzembehelyezések száma a legutóbbi karbant. óta"
#define STR7044_TEXT "Határ hónaphoz a legutóbbi karbantartás óta"
#define STR7045_TEXT "Legutóbbi karbantartás óta eltelt hónapok száma"
#define STR7050_TEXT "Ventillátor ford.számhatár karbantartásjelzéshez"
#define STR7051_TEXT "Ionizáció áram karbantartás jelzés"
#define STR8000_TEXT "1. fűtési kör álalpota"
#define STR8001_TEXT "2. fűtési kör állapota"
#define STR8003_TEXT "HMV állapota"
#define STR8005_TEXT "Kazán állapota"
#define STR8007_TEXT "Napkollektor állapota"
#define STR8310_TEXT "Aktuális kazánhőmérséklet érték"
#define STR8311_TEXT "Kazánhőmérséklet alapjel"
#define STR8314_TEXT "Visszatérő hőmérséklet aktuális érték"
#define STR8316_TEXT "Füstgáz hőmérséklet mért érték"
#define STR8324_TEXT "Aktuális ventilátor fordulatszám"
#define STR8325_TEXT "Aktuális ventilátor kivezérlés"
#define STR8326_TEXT "Relatív teljesítmény"
#define STR8328_TEXT "Égővezérlő üzemmód kijelzés"
#define STR2730_TEXT "Ionizációs áram mért érték"
#define STR8336_TEXT "Készülék üzemóraszám"
#define STR8337_TEXT "Égő startszámláló"
#define STR8338_TEXT "Fűtés üzemmód üzemóraszám"
#define STR8339_TEXT "HMV üzemmód üzemóraszám"
#define STR8340_TEXT "Külső hőigény üzemóraszám"
#define STR8510_TEXT "Napkollektor 1-es hőm. aktuális érték (B6)"
#define STR8530_TEXT "Napkollektorhozadék üzemóraszám"
#define STR8700_TEXT "Helyi külső hőmérséklet érzékelő"
#define STR8703_TEXT "Csillapított külső hőmérséklet"
#define STR8704_TEXT "Korrigált külső hőmérséklet"
#define STR8740_TEXT "Helyiség hőmérséklet 1 mért érték"
#define STR8741_TEXT "Aktuális helyiség hőmérséklet alapjel"
#define STR8743_TEXT "Aktuális előremenő hőmérséklet érték FK1"
#define STR8744_TEXT "Előremenő alapjel H1"
#define STR8750_TEXT "Szivattyú fordulatszám"
#define STR8770_TEXT "Helyiség hőmérséklet 2 mért érték"
#define STR8771_TEXT "FK2 helyiség hőmérséklet aktuális alapjel"
#define STR8773_TEXT "Aktuális előremenő hőmérséklet érték FK2"
#define STR8774_TEXT "Előremenő alapjel H2"
#define STR8830_TEXT "HMV hőmérséklet aktuális érték felü (B3)"
#define STR8831_TEXT "Aktuális használati melegvíz hőmérséklet alapjel"
#define STR8836_TEXT "HMV töltési hőmérséklet"
#define STR8950_TEXT "Technológiai jel osztó előremenő"
#define STR8952_TEXT "Technológiai jel gyűjtő visszatérő"
#define STR8980_TEXT "Puffertároló hőm. aktuális érték felül (B4)"
#define STR9500_TEXT "Előszellóztetési idő"
#define STR9502_TEXT "Levegő moduláció előszellőztetéskor"
#define STR9504_TEXT "Ventilátor előszellőztetési fordulatszám alapjel"
#define STR9510_TEXT "Modulációs levegő gyújtási teljesítménynél"
#define STR9512_TEXT "Ventillátor névl.fordulatszám gyújtási terh.-nél"
#define STR9520_TEXT "Modulációs levegő részterhelésnél"
#define STR9522_TEXT "Modulációs levegő teljes terhelésnél"
#define STR9524_TEXT "Ventillátor névl.fordulatszám részterhelésnél"
#define STR9527_TEXT "Ventillátor névl.fordulatszám teljes terhelésnél"
#define STR9540_TEXT "Utószellőztetési idő"
#define STR9560_TEXT "Ventill.mod. biztonsági tároló feltöltéskor"
#define STR9563_TEXT "Ventill.alapjel biztonsági tároló feltöltéskor"
#define STR6225_TEXT "Készülék-család"
#define STR6226_TEXT "Készülék-változat"
#define STR6227_TEXT "Készülék-OV-verzió"
#define STR6705_TEXT "Belső diagnosztikai  kód"
#define STR7001_TEXT "Karbantartás jelzés"
#define STR8310_TEXT "Aktuális kazánhőmérséklet érték"
#define STR8830_TEXT "HMV hőmérséklet aktuális érték felü (B3)"
#define STR8510_TEXT "Napkollektor 1-es hőm. aktuális érték (B6)"
#define STR8328_TEXT "Égővezérlő üzemmód kijelzés"
#define STR8700_TEXT "Helyi külső hőmérséklet érzékelő"
#define STR8980_TEXT "Puffertároló hőm. aktuális érték felül (B4)"
#define STR8740_TEXT "Helyiség hőmérséklet 1 mért érték"
#define STR8741_TEXT "Aktuális helyiség hőmérséklet alapjel"
#define STR8743_TEXT "Aktuális előremenő hőmérséklet érték FK1"
#define STR8770_TEXT "Helyiség hőmérséklet 2 mért érték"
#define STR8771_TEXT "FK2 helyiség hőmérséklet aktuális alapjel"
#define STR8773_TEXT "Aktuális előremenő hőmérséklet érték FK2"
#define STR8950_TEXT "Technológiai jel osztó előremenő"
#define STR8952_TEXT "Technológiai jel gyűjtő visszatérő"
