#define ENUM_CAT_00_TEXT "Время дня и дата"
#define ENUM_CAT_03_TEXT "Врем прогр конт отоп 1"
#define ENUM_CAT_04_TEXT "Врем прогр конт отоп 2"
#define ENUM_CAT_05_TEXT "Врем прогр 3/КО с насосо"
#define ENUM_CAT_06_TEXT "Time switch program DHW"
#define ENUM_CAT_08_TEXT "Конт отопл1 на вых дни"
#define ENUM_CAT_09_TEXT "Конт отопл 2 на вых дни"
#define ENUM_CAT_0b_TEXT "Контур отопления 1"
#define ENUM_CAT_0d_TEXT "Контур отопления 2"
#define ENUM_CAT_0f_TEXT "Горячее водоснабжение"
#define ENUM_CAT_13_TEXT "Котел"
#define ENUM_CAT_19_TEXT "Солнечный"
#define ENUM_CAT_1b_TEXT "Буф  накопит бак"
#define ENUM_CAT_1c_TEXT "Накопит бак ГВС"
#define ENUM_CAT_1d_TEXT "Прямая загрузка ГВС"
#define ENUM_CAT_1e_TEXT "Конфигурация"
#define ENUM_CAT_1f_TEXT "Система LPB"
#define ENUM_CAT_20_TEXT "Отказ"
#define ENUM_CAT_21_TEXT "Сервисные/особые работы"
#define ENUM_CAT_24_TEXT "Состояние"
#define ENUM_CAT_26_TEXT "Диагн теплогенератора"
#define ENUM_CAT_27_TEXT "Диагн потребителей"
#define ENUM_CAT_28_TEXT "Автомат горения"
#define STR516_TEXT "Standard values TSP heating circuit 1"
#define STR536_TEXT "Standard values TSP heating circuit 2 "
#define STR556_TEXT "Standard values TSP3"
#define STR576_TEXT "Standard values TSP 4"
#define STR648_TEXT "Уровень работы в праздники КО1"
#define STR652_TEXT "Период праздники 1 КО2: первый день"
#define STR653_TEXT "Период праздники 1 КО2: последний день"
#define STR658_TEXT "Уровень работы в праздники КО2"
#define STR700_TEXT "Режим работы КО 1"
#define STR710_TEXT "Комфортн.уставка темпер.помещения КО1"
#define STR712_TEXT "Пониж.уставка темпер.помещения КО1"
#define STR714_TEXT "Уставка темпер.защиты замороз.помещ. КО1"
#define STR720_TEXT "График отопления 1, наклон"
#define STR721_TEXT "Смещ-е кривой отопления"
#define STR726_TEXT "Heating curve adaptation heat circuit 1"
#define STR730_TEXT "Темпер.переключ.лето/зима КО 1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Flow temp min limitation heat circuit 1"
#define STR741_TEXT "Flow temp max limitation heat circuit 1"
#define STR750_TEXT "Room temp gain factor heat circuit 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Room temp setpoint boost HC1 (boost heating)"
#define STR780_TEXT "Quick setback heat circuit 1"
#define STR790_TEXT "Управл.оптимал.старт Макс.сдвиг вперед КО1"
#define STR791_TEXT "Optimum stop control max forward shift HC1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Функция сушки пола"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Расч точка скорости"
#define STR885_TEXT "Мод насос ШИМ мин"
#define STR886_TEXT "Стандартн наружная темп"
#define STR887_TEXT "Уст темп подачи станд НТ"
#define STR888_TEXT "dT коэф повышения"
#define STR894_TEXT "Диф dt при станд НТ"
#define STR1000_TEXT "Режим работы КО 2"
#define STR1010_TEXT "Комфортн.уставка темпер.помещения КО2"
#define STR1012_TEXT "Пониж.уставка темпер.помещения КО2"
#define STR1014_TEXT "Уставка темпер.защиты замороз.помещ. КО2"
#define STR1020_TEXT "График отопления 2, наклон"
#define STR1021_TEXT "Смещ-е кривой отопления"
#define STR1026_TEXT "Heating curve adaptation heat circuit 2"
#define STR1030_TEXT "Темпер.переключ.лето/зима КО 2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Flow temp min limitation heat circuit 2"
#define STR1041_TEXT "Flow temp max limitation heat circuit 2"
#define STR1050_TEXT "Room temp gain factor heat circuit 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Room temp setpoint boost HC2 (boost heating)"
#define STR1080_TEXT "Quick setback heat circuit 2"
#define STR1090_TEXT "Управл.оптимал.старт Макс.сдвиг вперед КО2"
#define STR1091_TEXT "Optimum stop control max forward shift HC2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Форс. режим смеш. клапана"
#define STR1134_TEXT "Время работы привода"
#define STR1150_TEXT "Функция сушки пола"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "Режим работы ГВС"
#define STR1610_TEXT "Номинальная уставка"
#define STR1612_TEXT "Пониженная уставка"
#define STR1620_TEXT "Разрешение на запуск"
#define STR1640_TEXT "Функция Легионелла"
#define STR1641_TEXT "Период функц Легионелла"
#define STR1642_TEXT "Д нед  функц Легион-ла"
#define STR1644_TEXT "Время функц Легионелла"
#define STR1645_TEXT "Уст функц Легионелла"
#define STR1646_TEXT "Длит функц Легионелла"
#define STR1647_TEXT "Функ Лег-а  цирк насоса"
#define STR1660_TEXT "Разр вкл цирк насоса"
#define STR1661_TEXT "Чередование цирк насоса"
#define STR2201_TEXT "Блок. источн. тепла"
#define STR2210_TEXT "Мин уставка"
#define STR2212_TEXT "Уставка макс."
#define STR2440_TEXT "ШИМ вент отоп макс"
#define STR2441_TEXT "Скор вент-а отопл макс"
#define STR2442_TEXT "Зад контр вент ШИМ"
#define STR2443_TEXT "Знач старта вент ШИМ"
#define STR2451_TEXT "Мин время выкл горелки"
#define STR2452_TEXT "Переп откл горелки"
#define STR2453_TEXT "Длит задержки контр-ра"
#define STR2454_TEXT "Темп диап перекл котла"
#define STR2455_TEXT "ДП выкл котла мин"
#define STR2456_TEXT "ДП выкл котла макс"
#define STR2471_TEXT "Время выбега насоса"
#define STR2472_TEXT "Время выбега насоса ГВС"
#define STR2521_TEXT "Вкл функ защит  замораж"
#define STR2522_TEXT "Выкл функ защит замораж"
#define STR3810_TEXT "Перепад температуры вкл"
#define STR3811_TEXT "Перепад температ выкл"
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Защ от замораж коллект"
#define STR3850_TEXT "Защ колл от перегрева"
#define STR3860_TEXT "Перенос тепла испарения"
#define STR4721_TEXT "Блок.SD авт. ген. тепла"
#define STR4722_TEXT "Перепад темп буфер/КО"
#define STR5019_TEXT "Уск повт загр  нак бака"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Пост врем реле протока"
#define STR5483_TEXT "Пост врем реле  Комфорт"
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Гидравлическая схема"
#define STR5710_TEXT "Контур отопления 1"
#define STR5715_TEXT "Контур отопления 2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Насос системы Q8"
#define STR5920_TEXT "Рел выход K2 корз LMU"
#define STR5921_TEXT "По умолч. К2 в К1"
#define STR5922_TEXT "Рел выход 1 RelCl"
#define STR5923_TEXT "Рел выход 2"
#define STR5924_TEXT "Рел выход 3"
#define STR5926_TEXT "Выход реле 1 SolCl"
#define STR5927_TEXT "Выход реле 2 SolCl"
#define STR5928_TEXT "Выход реле 3 SolCl"
#define STR5950_TEXT "Вход функции Н1"
#define STR5957_TEXT "Функц модема"
#define STR5970_TEXT "Конфиг комн термост 1"
#define STR5971_TEXT "Конфиг комн термост 2"
#define STR5973_TEXT "Функц входа RelCl"
#define STR5975_TEXT "Вн уст темп подачи макс"
#define STR5976_TEXT "Вн пред зад порог вых"
#define STR6110_TEXT "Пост времени здания"
#define STR6112_TEXT "Модель темп град-та комн"
#define STR6120_TEXT "Защита от заморажи-я"
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6220_TEXT "Версия програм. обеспеч."
#define STR6225_TEXT "Семейство устройства"
#define STR6226_TEXT "Вариант устройства"
#define STR6227_TEXT "Версия директор объекта"
#define STR6230_TEXT "ConfigContrl0"
#define STR6240_TEXT "СonfigContr1"
#define STR6250_TEXT "ConfigContrl2"
#define STR6260_TEXT "ConfigContr3"
#define STR6270_TEXT "СonfigContr4"
#define STR6300_TEXT "ConfigContr7"
#define STR6330_TEXT "ConfigContr10"
#define STR6604_TEXT "Функц источн пит шины"
#define STR6605_TEXT "Сост источн пит шины"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Режим часов"
#define STR6705_TEXT "Диагн код ПО"
#define STR6706_TEXT "Пол блок регул горелки"
#define STR6741_TEXT "Синал-ция темп подачи 2"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "Диагн код ПО 3"
#define STR6826_TEXT "Управл горелкой фаза 3"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "Диагн код ПО 4"
#define STR6836_TEXT "Управл горелкой фаза 4"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "Диагн код ПО 5"
#define STR6846_TEXT "Управл горелкой фаза 5"
#define STR7001_TEXT "Сообщение"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Сообщ о подтв приема"
#define STR7011_TEXT "Сообщение времени повт"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Скор вент при иониз токе"
#define STR7051_TEXT "Сообщ тока ионизации"
#define STR8000_TEXT "Состояние отоп. конт-а 1"
#define STR8001_TEXT "Состояние отоп. конт-а 2"
#define STR8003_TEXT "Состояние ГВС"
#define STR8005_TEXT "Состояние котла"
#define STR8007_TEXT "Состояние солн элемента"
#define STR8310_TEXT "Температура котла"
#define STR8311_TEXT "Уставка темп котла"
#define STR8314_TEXT "Темпертура обратки котла"
#define STR8316_TEXT "Темп топочных газов"
#define STR8324_TEXT "Скорость вентилятора"
#define STR8325_TEXT "Регул тока вентилятора"
#define STR8326_TEXT "Относ выход"
#define STR8328_TEXT "Стат индик рег горелки"
#define STR2730_TEXT "Ток ионизации"
#define STR8336_TEXT "Время работы устройства"
#define STR8337_TEXT "Старт счетч горелки"
#define STR8338_TEXT "Время раб-ы реж отопл-я"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Время раб-ы зон"
#define STR8510_TEXT "Температура коллектора 1"
#define STR8530_TEXT "Время выраб солн. энер-и"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Наружная темп ослабл"
#define STR8704_TEXT "Наружн темп составн"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Температура подающей 1"
#define STR8744_TEXT "Уст. темп. подачи Н1"
#define STR8750_TEXT "Уставка модул насоса"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Уст комнат температуры 2"
#define STR8773_TEXT "Температура подающей 2"
#define STR8774_TEXT "Уст. темп. подачи Н2"
#define STR8830_TEXT "ГВС температура 1"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "Насос загр. ГВС"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Темп. буф. 1"
#define STR9500_TEXT "Время до продувки"
#define STR9502_TEXT "Рег вент при предпрод"
#define STR9504_TEXT "Треб скор при предпрод"
#define STR9510_TEXT "Рег вент зажиган"
#define STR9512_TEXT "Треб скорость поджига"
#define STR9520_TEXT "Мин упр работой вент"
#define STR9522_TEXT "Макс упр работой вент"
#define STR9524_TEXT "Треб скор раб мин"
#define STR9527_TEXT "Треб скор раб макс"
#define STR9540_TEXT "Время после продувки"
#define STR9560_TEXT "Регул вент при полн загр"
#define STR9563_TEXT "Треб скор полной загрузки"
