#define LANGUAGENAME_TEXT "Čeština"
#define ENUM_CAT_00_TEXT "Čas"
#define ENUM_CAT_03_TEXT "Spínací program 1"
#define ENUM_CAT_04_TEXT "Spínací program 2"
#define ENUM_CAT_05_TEXT "Spínací program 3"
#define ENUM_CAT_06_TEXT "Časový program přípravy TUV"
#define ENUM_CAT_08_TEXT "Prázdninové programy TO1"
#define ENUM_CAT_09_TEXT "Prázdninové programy TO2"
#define ENUM_CAT_0b_TEXT "Topný okruh 1"
#define ENUM_CAT_0d_TEXT "Topný okruh 2"
#define ENUM_CAT_0f_TEXT "Pitná voda"
#define ENUM_CAT_13_TEXT "Kotel"
#define ENUM_CAT_19_TEXT "Solár"
#define ENUM_CAT_1b_TEXT "Vyrovnávací zásobník"
#define ENUM_CAT_1c_TEXT "Zásobník pitné vody"
#define ENUM_CAT_1d_TEXT "Přimé nabíjení TUV"
#define ENUM_CAT_1e_TEXT "Konfigurace"
#define ENUM_CAT_1f_TEXT "Systém LPB"
#define ENUM_CAT_20_TEXT "Chyba"
#define ENUM_CAT_21_TEXT "Údržba"
#define ENUM_CAT_24_TEXT "Stav"
#define ENUM_CAT_26_TEXT "Diagnóza výrobce"
#define ENUM_CAT_27_TEXT "Diagnóza spotřebiče"
#define ENUM_CAT_28_TEXT "Hořáková automatika"
#define STR516_TEXT "Standardní hodnoty ZSP Topný okruh1"
#define STR536_TEXT "Standardní hodnoty ZSP Topný okruh2"
#define STR556_TEXT "Standardní hodnoty ZSP3"
#define STR576_TEXT "Standardní hodnoty ZSP 4"
#define STR648_TEXT "Úroveň provozu Prázdniny TO1"
#define STR652_TEXT "Prázdninová perioda 1 TO2: První den"
#define STR653_TEXT "Prázdninová perioda 1 TO2: Poslední den"
#define STR658_TEXT "Úroveň provozu Prázdniny TO2"
#define STR700_TEXT "Druh provozu topného okruhu 1"
#define STR710_TEXT "Žádaná teplota prostoru Komfort Topný okruh 1"
#define STR712_TEXT "Útlumová žádaná teplota prostoru TO 1"
#define STR714_TEXT "Protimrazová žádaná teplota prostoru TO 1"
#define STR720_TEXT "Strmost topné křivky 1"
#define STR721_TEXT "Paralelní posun topné křivky"
#define STR726_TEXT "Adaptace topné křivky topného okruhu 1"
#define STR730_TEXT "Teplota přepnutí léto/zima topného okruhu 1"
#define STR732_TEXT "Denní omezení vytápění TO1"
#define STR740_TEXT "Minimální omezení teploty náběhu topného okruhu1"
#define STR741_TEXT "Maximální omezení teploty náběhu topného okruhu1"
#define STR750_TEXT "Faktor vlivu teploty prostoru topného okruhu 1"
#define STR760_TEXT "Omezení teploty prostoru Topný okruh 1"
#define STR770_TEXT "Převýšení teploty prostoru 1 (rychlé natopení)"
#define STR780_TEXT "Rychlý útlum topného okruhu 1"
#define STR790_TEXT "Max. předstih optimalizace času zapnutí TO1"
#define STR791_TEXT "Max. předstih optimalizace času vypnutí TO1"
#define STR800_TEXT "Začátek zvyšování útlumové žád teploty prost TO1"
#define STR801_TEXT "Konec zvyšování útlum žád teploty prostoru TO1"
#define STR850_TEXT "Funkce vysoušení podlahy"
#define STR851_TEXT "Žádaná teplota vysoušení ručně TO1"
#define STR884_TEXT "Otáčky čerpadla kotle při norm. venkovní teplotě"
#define STR885_TEXT "Minimální PWM modulovaného čerpadla"
#define STR886_TEXT "Venkovní teplota při maximálním požadavku tepla"
#define STR887_TEXT "Žádaná teplota kotle při norm. venkovní teplotě"
#define STR888_TEXT "Omezení převýšení teploty při dT-regulaci"
#define STR894_TEXT "Diference náběh/zpátečka při norm. venk. teplotě"
#define STR1000_TEXT "Druh provozu topného okruhu 2"
#define STR1010_TEXT "Žádaná teplota prostoru Komfort Topný okruh 2"
#define STR1012_TEXT "Útlumová žádaná teplota prostoru TO 2"
#define STR1014_TEXT "Protimrazová žádaná teplota prostoru TO 2"
#define STR1020_TEXT "Strmost topné křivky 2"
#define STR1021_TEXT "Paralelní posun topné křivky"
#define STR1026_TEXT "Adaptace topné křivky topného okruhu 2"
#define STR1030_TEXT "Teplota přepnutí léto/zima topného okruhu 2"
#define STR1032_TEXT "Denní omezení vytápění TO2"
#define STR1040_TEXT "Minimální omezení teploty náběhu topného okruhu2"
#define STR1041_TEXT "Maximální omezení teploty náběhu topného okruhu2"
#define STR1050_TEXT "Faktor vlivu teploty prostoru topného okruhu 2"
#define STR1060_TEXT "Omezení teploty prostoru Topný okruh 2"
#define STR1070_TEXT "Převýšení teploty prostoru 2 (rychlé natopení)"
#define STR1080_TEXT "Rychlý útlum topného okruhu 2"
#define STR1090_TEXT "Max. předstih optimalizace času zapnutí TO2"
#define STR1091_TEXT "Max. předstih optimalizace času vypnutí TO2"
#define STR1100_TEXT "Začátek zvyšování útlum žád teploty prostoru TO2"
#define STR1101_TEXT "Konec zvyšování útlum žád teploty prostoru TO2"
#define STR1130_TEXT "Převýšení teploty na směšovači topného okruhu"
#define STR1134_TEXT "Doba běhu pohonu topného okruhu"
#define STR1150_TEXT "Funkce vysoušení podlahy"
#define STR1151_TEXT "Žádaná teplota vysoušení ručně TO2"
#define STR1600_TEXT "Druh přípravy TUV"
#define STR1610_TEXT "Jmenovitá žádaná teplota TUV"
#define STR1612_TEXT "Útlumová žádaná teplota TUV"
#define STR1620_TEXT "Uvolnění TUV"
#define STR1640_TEXT "Legionelní funkce"
#define STR1641_TEXT "Četnost legionelní funkce"
#define STR1642_TEXT "Legionelní funkce Den"
#define STR1644_TEXT "Čas aktivace legionelní funkce"
#define STR1645_TEXT "Žádaná hodnota teploty legionelní funkce"
#define STR1646_TEXT "Doba působení žád. teploty legionelní funkce"
#define STR1647_TEXT "Provoz cirk. čerpadla během legionelní funkce"
#define STR1660_TEXT "Uvolnění cirkulačního čerpadla TUV"
#define STR1661_TEXT "Taktovací provoz cirkulačního čerpadla TUV"
#define STR2201_TEXT "Blokace zdroje"
#define STR2210_TEXT "Minimální omezení teploty kotle"
#define STR2212_TEXT "Maximální omezení teploty kotle"
#define STR2440_TEXT "Max. stupeň modulace v režimu vytápění"
#define STR2441_TEXT "Maximální otáčky ventilátoru v režimu vytápění"
#define STR2442_TEXT "Výkon při aktivní prodlevě regulátoru"
#define STR2443_TEXT "Druh výkonu při uvolnění Dlh režimu"
#define STR2451_TEXT "Minimální doba klidu hořáku"
#define STR2452_TEXT "Max. regulační odchylka bez přeruš. min. pauzy"
#define STR2453_TEXT "Prodleva regulátoru po zapnutí hořáku"
#define STR2454_TEXT "Spínací diference kotle"
#define STR2455_TEXT "Minimální spínací diference vypnutí kotle"
#define STR2456_TEXT "Maximální spínací diference vypnutí kotle"
#define STR2471_TEXT "Doběh čerpadel"
#define STR2472_TEXT "Teplota TUV  doběhu čerpadel"
#define STR2521_TEXT "Teplota zapnutí protimrazové ochrany kotle"
#define STR2522_TEXT "Teplota vypnutí protimrazové ochrany kotle"
#define STR3810_TEXT "Spínací diference ZAP solárního okruhu"
#define STR3811_TEXT "Spínací diference VYP solárního okruhu"
#define STR3812_TEXT "Minimální teplota nabíjení"
#define STR3831_TEXT "Minimální doba chodu čerpadla kolektoru"
#define STR3840_TEXT "Teplota protimrazové ochrany kolektoru"
#define STR3850_TEXT "Teplota ochrany proti přehřátí kolektoru"
#define STR3860_TEXT "Teplota varu náplně soláru"
#define STR4721_TEXT "Spínací diference automat zablokování zdroje"
#define STR4722_TEXT "tepl diference vyrov zásob/TO do uvolnění zdroje"
#define STR5019_TEXT "Převýšení žád. teploty při celk. nabíjení zásob."
#define STR5020_TEXT "Převýšení teploty náběhu TUV"
#define STR5050_TEXT "Maximální teplota nabíjení zásobníku TUV"
#define STR5055_TEXT "Minimální tepl chlazení zpáteč pro zásobník TUV"
#define STR5100_TEXT "Min. otáčky čerpadla při celkovém nabíjení zásob"
#define STR5020_TEXT "Převýšení teploty náběhu TUV"
#define STR5400_TEXT "Žádaná pohotovostní teplota TUV"
#define STR5430_TEXT "Diference zapnutí přípravy TUV (čidlo 1)"
#define STR5431_TEXT "Min. diference zapnutí přípravy TUV (čidlo 1)"
#define STR5432_TEXT "Max. diference zapnutí přípravy TUV (čidlo 1)"
#define STR5433_TEXT "Diference zapnutí přípravy TUV (čidlo 2)"
#define STR5434_TEXT "Min. diference vypnutí TUV (čidlo 2)"
#define STR5435_TEXT "Max. diference vypnutí přípravy TUV (čidlo 2)"
#define STR5450_TEXT "Mez ukončení čerpání  při průtoké přípravě TUV"
#define STR5451_TEXT "Mez čerpání při komfortní průtokové přípravě TUV"
#define STR5452_TEXT "Mez čerpání TUV při Dlh v režimu vytápění"
#define STR5453_TEXT "Korekce žád. tepl. při komf. regulaci na 40°C"
#define STR5454_TEXT "Korekce žád. tepl. při komf. regulaci na 60°C"
#define STR5455_TEXT "Korekce žád. tepl. při průběž. regulaci na 40°C"
#define STR5456_TEXT "Korekce žád. tepl. při průběž. regulaci na 60°C"
#define STR5480_TEXT "Doba komfortní Dlh po čerpání bez vytápění"
#define STR5481_TEXT "Doba komfortní Dlh při aktivním vytápění"
#define STR5482_TEXT "Doba uzavření průtoku TUV"
#define STR5483_TEXT "Doba uzavření spnače průtoku TUV Komfort"
#define STR5486_TEXT "Zpoždění regulace při takt. provozu v DLH režimu"
#define STR5487_TEXT "Doběh čerpadla při komfortní Dlh po vyp. hořáku"
#define STR5488_TEXT "Doběh čerpadla při komfortní Dlh po vyp. hořáku"
#define STR5701_TEXT "Typ zařízení"
#define STR5710_TEXT "Topný okruh 1"
#define STR5715_TEXT "Topný okruh 2"
#define STR5732_TEXT "Čas vypnutí čerpadla při změně vytáp. na TUV"
#define STR5733_TEXT "Prodleva vypnutí čerpadla při změně ÚT->TUV"
#define STR5761_TEXT "Požadavky na teplo s podporou Q8"
#define STR5920_TEXT "Programovatelný výstup K2"
#define STR5921_TEXT "Základní K2 na K1"
#define STR5922_TEXT "Funkce výstupu 1 funkčního Clip-In"
#define STR5923_TEXT "Funkce výstupu 2 funkčního Clip-In"
#define STR5924_TEXT "Funkce výstupu 3 funkčního Clip-In"
#define STR5926_TEXT "Konfigurace výstupu 1"
#define STR5927_TEXT "Konfigurace výstupu 2"
#define STR5928_TEXT "Konfigurace výstupu 3"
#define STR5950_TEXT "Vstup H1 - volba funkce"
#define STR5957_TEXT "Funkce modemu"
#define STR5970_TEXT "Konfigurace prostorového termostatu  1"
#define STR5971_TEXT "Konfigurace prostorového termostatu  2"
#define STR5973_TEXT "Funkce vstupu RelCl"
#define STR5975_TEXT "Omezení teploty při externím požadavku"
#define STR5976_TEXT "Minimální vstupní signál pro externí požadavek"
#define STR6110_TEXT "Časová konstanta budovy"
#define STR6112_TEXT "Gradient prostorového modelu"
#define STR6120_TEXT "Protimrazová ochrama zařízení"
#define STR6127_TEXT "Doba funkce proti zatuhnutí čerpadel/ ventilů"
#define STR6220_TEXT "SW-verze přístrojů"
#define STR6225_TEXT "Skupina přístrojů"
#define STR6226_TEXT "Varianty přístrojů"
#define STR6227_TEXT "Verze OV přístroje"
#define STR6230_TEXT "Konfigurační bity 0"
#define STR6240_TEXT "Konfigurační bity 1"
#define STR6250_TEXT "Konfigurační bity 2"
#define STR6260_TEXT "Konfigurační bity 3"
#define STR6270_TEXT "Konfigurační bity 4"
#define STR6300_TEXT "Konfigurační bity 7"
#define STR6330_TEXT "Konfigurace regulátoru  10"
#define STR6604_TEXT "Napájení LPB"
#define STR6605_TEXT "Status napájení LPB"
#define STR6625_TEXT "Přiřazení programu přípravy TUV"
#define STR6640_TEXT "Dodavatel času"
#define STR6705_TEXT "Interní diagnostický kód"
#define STR6706_TEXT "Aktuální hodnota chybové fáze"
#define STR6741_TEXT "Doba alarmu teploty náběhu topného okruhu 2"
#define STR6823_TEXT "3. historická hodnota chyb. hlášení Albatros"
#define STR6825_TEXT "Historická hodnota 3 diagnózy chyby"
#define STR6826_TEXT "Historická hodnota 3 chybové fáze"
#define STR6830_TEXT "Historická hodnota 4 chyb. kódu měřiče"
#define STR6833_TEXT "4. historická hodnota chyb. hlášení Albatros"
#define STR6835_TEXT "Historická hodnota 4 diagnózy chyby"
#define STR6836_TEXT "Historická hodnota 4 chybové fáze"
#define STR6840_TEXT "Historická hodnota 5 chyb. kódu měřiče"
#define STR6843_TEXT "5. historická hodnota chyb. hlášení Albatros"
#define STR6845_TEXT "Historická hodnota 5 diagnózy chyby"
#define STR6846_TEXT "Historická hodnota 5 chybové fáze"
#define STR7001_TEXT "Servisní hlášení"
#define STR7007_TEXT "Konfigurace/ reset servisních hlášení"
#define STR7010_TEXT "Kvitování servisního hlášení"
#define STR7011_TEXT "Čas opakování servisních hlášení"
#define STR7040_TEXT "Servisní interval hořáku"
#define STR7041_TEXT "Provozní hodiny od posledního servisu"
#define STR7042_TEXT "Mez pro uvedení do provozu od posl. servisu"
#define STR7043_TEXT "Počet startů od posledního servisu"
#define STR7044_TEXT "Mez pro měsíce od posledního servisu"
#define STR7045_TEXT "Počet měsíců od posledního servisu"
#define STR7050_TEXT "Mez otáček ventilátoru pro servisní hlášení"
#define STR7051_TEXT "Hlášení udržby ionizačního proudu"
#define STR8000_TEXT "Stav topného okruhu  1"
#define STR8001_TEXT "Stav topného okruhu 2"
#define STR8003_TEXT "Stav TUV"
#define STR8005_TEXT "Stav kotle"
#define STR8007_TEXT "Stav soláru"
#define STR8310_TEXT "Teplota kotle"
#define STR8311_TEXT "Žádaná teplota kotle"
#define STR8314_TEXT "Teplota zpátečky"
#define STR8316_TEXT "Teplota spalin"
#define STR8324_TEXT "Aktuální otáčky ventilátoru"
#define STR8325_TEXT "Aktuální řízení ventilátoru"
#define STR8326_TEXT "Relativní výkon"
#define STR8328_TEXT "Zobrazení provozu  FA"
#define STR2730_TEXT "Ionizační proud"
#define STR8336_TEXT "Provozní hodiny přístroje"
#define STR8337_TEXT "Čítač startů hořáku"
#define STR8338_TEXT "Provozní hodiny vytápění"
#define STR8339_TEXT "Provozní hodiny přípravy TUV"
#define STR8340_TEXT "Provozní hodiny externího požadavku"
#define STR8510_TEXT "Teplota kolektoru 1 (B6)"
#define STR8530_TEXT "Solární výnos provozních hodin"
#define STR8700_TEXT "Lokální čidlo venkovní teploty"
#define STR8703_TEXT "Venkovní tlumená teplota"
#define STR8704_TEXT "Venkovní geometrická teplota"
#define STR8740_TEXT "Teplota prostoru 1"
#define STR8741_TEXT "Aktuální žádaná teplota prostoru"
#define STR8743_TEXT "Teplota náběhu topného okruhu 1"
#define STR8744_TEXT "Žádaná teplota náběhu H1"
#define STR8750_TEXT "Otáčky čerpadla"
#define STR8770_TEXT "Teplota prostoru 2"
#define STR8771_TEXT "Aktuální žádaná teplota prostoru TO2"
#define STR8773_TEXT "Teplota náběhu topného okruhu 2"
#define STR8774_TEXT "Žádaná teplota náběhu H2"
#define STR8830_TEXT "Skutečná teplota TUV Horní B3)"
#define STR8831_TEXT "Aktuální žádaná teplota TUV"
#define STR8836_TEXT "Nabíjecí teplota TV"
#define STR8950_TEXT "Proces-signál teploty náběhové vody"
#define STR8952_TEXT "Proces-signál teploty zpátečky"
#define STR8980_TEXT "Teplota vyrovnáv. zásobníku horní (B4)"
#define STR9500_TEXT "Doba předvětrání"
#define STR9502_TEXT "Modulace vzduchu v předvětrání"
#define STR9504_TEXT "Žádané otáčky ventilátoru v předvětrání"
#define STR9510_TEXT "Modulace vzduchu při zapalování"
#define STR9512_TEXT "Žádané otáčky ventilátoru při zapalování"
#define STR9520_TEXT "Modulace vzduchu při částečném zatížení"
#define STR9522_TEXT "Modulace vzduchu při plném zatížení"
#define STR9524_TEXT "Žádané otáčky ventilátoru při částečném zatížení"
#define STR9527_TEXT "Žádané otáčky ventilátoru při plném zatížení"
#define STR9540_TEXT "Doba provětrání"
#define STR9560_TEXT "Modulace vent. při celkovém nabíjení zásobníku"
#define STR9563_TEXT "Otáčky vent. při celkovém nabíjení zásobníku"
