#define ENUM_CAT_00_TEXT "Kloktijd"
#define ENUM_CAT_03_TEXT "Klokprogramma 1"
#define ENUM_CAT_04_TEXT "Klokprogramma 2"
#define ENUM_CAT_05_TEXT "Klokprogramma 3"
#define ENUM_CAT_06_TEXT "Klokprogramma tapwater"
#define ENUM_CAT_08_TEXT "Vakantieprogramma GR1"
#define ENUM_CAT_09_TEXT "Vakantieprogramma GR2"
#define ENUM_CAT_0b_TEXT "Verwarmingsgroep 1"
#define ENUM_CAT_0d_TEXT "Verwarmingsgroep 2"
#define ENUM_CAT_0f_TEXT "Tapwater"
#define ENUM_CAT_13_TEXT "Ketel"
#define ENUM_CAT_19_TEXT "Zonnepaneel"
#define ENUM_CAT_1b_TEXT "Buffervat"
#define ENUM_CAT_1c_TEXT "Tapwater-voorraad"
#define ENUM_CAT_1d_TEXT "Tapw-Directlading"
#define ENUM_CAT_1e_TEXT "Configuratie"
#define ENUM_CAT_1f_TEXT "LPB"
#define ENUM_CAT_20_TEXT "Fout"
#define ENUM_CAT_21_TEXT "Onderhoud/Uitzonderingsbedrijf"
#define ENUM_CAT_24_TEXT "Status"
#define ENUM_CAT_26_TEXT "Diagnose opwekker"
#define ENUM_CAT_27_TEXT "Diagnose verbruiker"
#define ENUM_CAT_28_TEXT "Branderautomaat"
#define STR516_TEXT "Standaardwaarden Klokpr Groep 1"
#define STR536_TEXT "Standaardwaarden Klokpr Groep 2"
#define STR556_TEXT "Standaardwaarden Klokpr 3"
#define STR576_TEXT "Standaardwaarden Klokpr 4"
#define STR648_TEXT "Bedrijfswijze vakantie Groep 1"
#define STR652_TEXT "Vakantieperiode 1 Groep 2: Eerste dag"
#define STR653_TEXT "Vakantieperiode 1 Groep 2: Laatste dag"
#define STR658_TEXT "Bedrijfswijze vakantie Groep 2"
#define STR700_TEXT "Bedrijfswijze Groep 1"
#define STR710_TEXT "Ruimtemperatuur Comfortsetpoint Groep 1"
#define STR712_TEXT "Ruimtetemp. gew.waarde nacht Groep 1"
#define STR714_TEXT "Ruimtetemp. gew.waarde vorst Groep 1"
#define STR720_TEXT "Stooklijn 1 steilheid"
#define STR721_TEXT "Stooklijn-parallelverschuiving"
#define STR726_TEXT "Stooklijn-adaptie Groep 1"
#define STR730_TEXT "Zomer/winter omschakeltemp. Groep 1"
#define STR732_TEXT "Dagstookgrens Groep 1"
#define STR740_TEXT "Aanvoertemp-min-begrenzing Groep 1"
#define STR741_TEXT "Aanvoertemp-max-begrenzing Groep 1"
#define STR750_TEXT "Ruimtetemperatuur invloedfactor Groep 1"
#define STR760_TEXT "Ruimtetemperatuurbegrenzing Groep 1"
#define STR770_TEXT "Ruimtetemp-verhoging Gr 1 (Snelaanw)"
#define STR780_TEXT "Snelafkoeling Groep 1"
#define STR790_TEXT "Optimalisering max. vervroeging Groep 1"
#define STR791_TEXT "Uitsch.optim. max. vervroeging Groep 1"
#define STR800_TEXT "Begin gered.ruimtemp.verhoging Gr 1"
#define STR801_TEXT "Einde gered.ruimtemp.verhoging Gr 1"
#define STR850_TEXT "Vloer-uitdrogingsbescherming"
#define STR851_TEXT "Estrik setpoint hand Groep 1"
#define STR884_TEXT "Toerental ketelpomp bij ontwerpconditie"
#define STR885_TEXT "Mod Pomp PBM min"
#define STR886_TEXT "Buitentemperatuur bij maximale warmtevraag"
#define STR887_TEXT "Gew. keteltemp bij Normbuitentemp"
#define STR888_TEXT "Grens voor temperatuurverhoging dT-regeling"
#define STR894_TEXT "Delta Aanv/Retour bij Norm-buitentemp"
#define STR1000_TEXT "Bedrijfswijze Groep 2"
#define STR1010_TEXT "Ruimtemperatuur Comfortsetpoint Groep 2"
#define STR1012_TEXT "Ruimtetemp. gew.waarde nacht Groep 2"
#define STR1014_TEXT "Ruimtetemp. gew.waarde vorst Groep 2"
#define STR1020_TEXT "Stooklijn 2 steilheid"
#define STR1021_TEXT "Stooklijn-parallelverschuiving"
#define STR1026_TEXT "Stooklijn-adaptie Groep 2"
#define STR1030_TEXT "Zomer/winter omschakeltemp. Groep 2"
#define STR1032_TEXT "Dagstookgrens Groep 2"
#define STR1040_TEXT "Aanvoertemp-min-begrenzing Groep 2"
#define STR1041_TEXT "Aanvoertemp-max-begrenzing Groep 2"
#define STR1050_TEXT "Ruimtetemperatuur invloedfactor Groep 2"
#define STR1060_TEXT "Ruimtetemperatuurbegrenzing Groep 2"
#define STR1070_TEXT "Ruimtetemp-verhoging Gr 2 (Snelaanw)"
#define STR1080_TEXT "Snelafkoeling Groep 2"
#define STR1090_TEXT "Optimalisering max. vervroeging Groep 2"
#define STR1091_TEXT "Uitsch.optim. max. vervroeging Groep 2"
#define STR1100_TEXT "Begin gered.ruimtemp.verhoging Gr 2"
#define STR1101_TEXT "Einde gered.ruimtemp.verhoging Gr 2"
#define STR1130_TEXT "Temperatuur-verhoging Verwarmingsgroep"
#define STR1134_TEXT "Servomotor-looptijd Verwarmingsgroep"
#define STR1150_TEXT "Vloer-uitdrogingsbescherming"
#define STR1151_TEXT "Estrik setpoint Hand Groep 2"
#define STR1600_TEXT "Tapwater-Bedrijfswijze"
#define STR1610_TEXT "Tapwatertemperatuur-Normaal setpoint"
#define STR1612_TEXT "Tapwatertemperatuur-Gereduceerd setpoint"
#define STR1620_TEXT "Tapwatervrijgave"
#define STR1640_TEXT "Legionellafunctie"
#define STR1641_TEXT "Periode Legionellafunctie"
#define STR1642_TEXT "Legionellafunctie dag"
#define STR1644_TEXT "Starttijd Legionellafunctie"
#define STR1645_TEXT "Legionellafunctie gew.waarde"
#define STR1646_TEXT "Duur van Legionella temperatuur"
#define STR1647_TEXT "Tapwaterpompbedrijf tijdens Legionellafunctie"
#define STR1660_TEXT "Tapwater Tapwaterpomp Vrijgave"
#define STR1661_TEXT "Tapwaterpomp taktbedrijf"
#define STR2201_TEXT "Opwekkerblokkering"
#define STR2210_TEXT "Keteltemperatuur-minimaalbegrenzing"
#define STR2212_TEXT "Keteltemperatuur-maximaalbegrenzing"
#define STR2440_TEXT "Max modulatiegraad in verwarmingsbedrijf"
#define STR2441_TEXT "Max ventilatortoeren verwarmen"
#define STR2442_TEXT "Vermogen tijdens actieve regelaarvertraging"
#define STR2443_TEXT "Vermogen bij regelaarvrijgave in DLH bedrijf"
#define STR2451_TEXT "Min branderpauzetijd"
#define STR2452_TEXT "Max. Regeldiff. binnen pauzetijd"
#define STR2453_TEXT "Regelaarvertraging na inschakeling"
#define STR2454_TEXT "Ketel-schakeldifferentie"
#define STR2455_TEXT "Min. uitschakeldifferentie ketel"
#define STR2456_TEXT "Max. uitschakeldifferentie ketel"
#define STR2471_TEXT "Pompnadraaitijd"
#define STR2472_TEXT "Pompnadraaitemperatuur Tapwater"
#define STR2521_TEXT "Inschakeltemp ketelvorstbewaking"
#define STR2522_TEXT "Uitschakeltemp ketelvorstbewaking"
#define STR3810_TEXT "Temperatuurverschil zonnepaneel IN"
#define STR3811_TEXT "Temperatuurverschil zonnepaneel UIT"
#define STR3812_TEXT "Minimale laadtemperatuur"
#define STR3831_TEXT "Min looptijd collectorpomp"
#define STR3840_TEXT "Collectorvorstbev temperatuur"
#define STR3850_TEXT "Collector oververh.bev.temperatuur"
#define STR3860_TEXT "Verdampingstemperatuur warmtedrager"
#define STR4721_TEXT "Automatische opwekkerblokk Schakeldifferentie"
#define STR4722_TEXT "Temp.verschil buffer/gr tot vrijg opwekking"
#define STR5019_TEXT "Setpointverhoging voor nalading voorraadvat"
#define STR5020_TEXT "Aanvoertemperatuurverhoging tapwater"
#define STR5050_TEXT "Maximale tapwater laadtemperatuur"
#define STR5055_TEXT "Min terugkoeltemp voor tapw-vat"
#define STR5100_TEXT "Min. Pomptoeren voor doorlading buffer"
#define STR5020_TEXT "Aanvoertemperatuurverhoging tapwater"
#define STR5400_TEXT "Setpoint voor tapwater gereed temperatuur"
#define STR5430_TEXT "Inschakeldiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5431_TEXT "Min.Uitschdiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5432_TEXT "Max.Uitschdiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5433_TEXT "Inschakeldiff. in WTB-Bedrijf (Opnemer 2)"
#define STR5434_TEXT "Min uitschakeldiff in WTB-bedrijf (Opnemer 2)"
#define STR5435_TEXT "Max.Uitschdiff. in WTB-Bedrijf (Opnemer 2)"
#define STR5450_TEXT "Grens voor beëindigen watertappen bij DLH"
#define STR5451_TEXT "Grens voor watertappen bij DLH in Comfort"
#define STR5452_TEXT "Grens voor watertappen bij DLH in VerwBedrijf"
#define STR5453_TEXT "Setpointcorrectie bij comfortregeling met 40°C"
#define STR5454_TEXT "Setpointcorrectie bij comfortregeling met 60°C"
#define STR5455_TEXT "Setpointcorrectie bij uitloopregeling met 40°C"
#define STR5456_TEXT "Setpointcorrectie bij uitloopregeling met 60°C"
#define STR5480_TEXT "DLH-Comforttijd na tappen zonder warmtevraag"
#define STR5481_TEXT "DLH-Comforttijd na tappen met warmtevraag"
#define STR5482_TEXT "Tijd tot tapw-strom.schak gesloten"
#define STR5483_TEXT "Tijd tot tapw-comfort strom.schak gesloten"
#define STR5486_TEXT "Regelvertraging bij aan/uit uitloopbedrijf"
#define STR5487_TEXT "Pompnadraai in DLH-Comfort bij brander uit"
#define STR5488_TEXT "Pompnadraai in DLH-Comfort bij brander uit"
#define STR5701_TEXT "Installatietype"
#define STR5710_TEXT "Verwarmingsgroep 1"
#define STR5715_TEXT "Verwarmingsgroep 2"
#define STR5732_TEXT "Pompuitschakeltijd bij wissel verw naar WTB"
#define STR5733_TEXT "Vertraging pompuitsch bij wissel verw->WTB"
#define STR5761_TEXT "Warmtevraag met ondersteuning door Q8"
#define STR5920_TEXT "Programmeerbare uitgang K2"
#define STR5921_TEXT "Default K2 op K1"
#define STR5922_TEXT "Funktie uitgang 1 Relais Clip-In"
#define STR5923_TEXT "Funktie uitgang 2 Relais Clip-In"
#define STR5924_TEXT "Funktie uitgang 3 Relais Clip-In"
#define STR5926_TEXT "Configuratie Uitgang 1"
#define STR5927_TEXT "Configuratie Uitgang 2"
#define STR5928_TEXT "Configuratie Uitgang 3"
#define STR5950_TEXT "Ingang H1 functiekeuze"
#define STR5957_TEXT "Modemfunctie"
#define STR5970_TEXT "Config Ruimtethermostaat 1"
#define STR5971_TEXT "Config Ruimtethermostaat 2"
#define STR5973_TEXT "Functie Ingang RelCl"
#define STR5975_TEXT "Temperatuurgrens voor externe warmtevraag"
#define STR5976_TEXT "Ingangssignaal ondergrens ext warmtevraag"
#define STR6110_TEXT "Gebouwtijdconstante"
#define STR6112_TEXT "Ruimtemodel gradient"
#define STR6120_TEXT "Installatievorstbeveiliging"
#define STR6127_TEXT "Tijd voor pomp/klepkick"
#define STR6220_TEXT "Regelaar-SW-Versie"
#define STR6225_TEXT "Regelaar-Familie"
#define STR6226_TEXT "Regelaar-Variant"
#define STR6227_TEXT "Regelaar-OV-Versie"
#define STR6230_TEXT "Regelaarconfiguratie 0"
#define STR6240_TEXT "Regelaarconfiguratie 1"
#define STR6250_TEXT "Regelaarconfiguratie 2"
#define STR6260_TEXT "Regelaarconfiguratie 3"
#define STR6270_TEXT "Regelaarconfiguratie 4"
#define STR6300_TEXT "Regelaarconfiguratie 7"
#define STR6330_TEXT "Regelaarconfiguratie 10"
#define STR6604_TEXT "LPB-voeding Functiekeuze"
#define STR6605_TEXT "LPB-voeding Status"
#define STR6625_TEXT "Tapwatertoewijzing"
#define STR6640_TEXT "Kloktijd-leverancier"
#define STR6705_TEXT "Interne diagnosecode"
#define STR6706_TEXT "Actuele waarde Storingsfase"
#define STR6741_TEXT "Tijd aanvoertemperatuuralarm Groep 2"
#define STR6823_TEXT "3e Oude waarde Albatros Foutcode"
#define STR6825_TEXT "Oude waarde 3 Storingsdiagnose"
#define STR6826_TEXT "Oude waarde 3 Storingsfase"
#define STR6830_TEXT "Oude waarde 4 Storingcode-teller"
#define STR6833_TEXT "4e Oude waarde Albatros Foutcode"
#define STR6835_TEXT "Oude waarde 4 Storingsdiagnose"
#define STR6836_TEXT "Oude waarde 4 Storingsfase"
#define STR6840_TEXT "Oude waarde 5 Storingcode-teller"
#define STR6843_TEXT "5e Oude waarde Albatros Foutcode"
#define STR6845_TEXT "Oude waarde 5 Storingsdiagnose"
#define STR6846_TEXT "Oude waarde 5 Storingsfase"
#define STR7001_TEXT "Onderhoudsmelding"
#define STR7007_TEXT "Configuratie / Reset onderhoudsmeldingen"
#define STR7010_TEXT "Onderhoudsmelding - Bevestiging"
#define STR7011_TEXT "Herhalingstijd voor onderhoudsmeldingen"
#define STR7040_TEXT "Brander onderhoudsinterval"
#define STR7041_TEXT "Bedrijfsuren sinds laatste onderhoud"
#define STR7042_TEXT "Grens voor controle sinds laatste onderhoud"
#define STR7043_TEXT "Controles sinds laatste onderhoud"
#define STR7044_TEXT "Grens voor maanden sinds laatste onderhoud"
#define STR7045_TEXT "Maanden sinds laatste onderhoud"
#define STR7050_TEXT "Ventilatortoerental voor onderhoudsmelding"
#define STR7051_TEXT "Ionisatiestroom- Onderhoudsmelding"
#define STR8000_TEXT "Status Verw.groep 1"
#define STR8001_TEXT "Status Verw.groep 2"
#define STR8003_TEXT "Status Tapwater"
#define STR8005_TEXT "Status Ketel"
#define STR8007_TEXT "Status Zonne-energie"
#define STR8310_TEXT "Keteltemperatuur-meetwaarde"
#define STR8311_TEXT "Keteltemperatuur-gew.waarde"
#define STR8314_TEXT "Retourtemperatuur-meetwaarde"
#define STR8316_TEXT "Rookgastemperatuur-meetwaarde"
#define STR8324_TEXT "Actueel ventilatortoerental"
#define STR8325_TEXT "Actuele ventilatorbesturing"
#define STR8326_TEXT "Relatief vermogen"
#define STR8328_TEXT "Bedrijfsweergave FA"
#define STR2730_TEXT "Ionisatiestroom"
#define STR8336_TEXT "Regelaarbedrijfsuren"
#define STR8337_TEXT "Startteller brander"
#define STR8338_TEXT "Bedrijfsuren verwarmingsbedrijf"
#define STR8339_TEXT "Bedrijfsuren tapwaterbedrijf"
#define STR8340_TEXT "Bedrijfsuren ext. Warmtevraag"
#define STR8510_TEXT "Collectortemperatuur 1 (B6)"
#define STR8530_TEXT "Bedrijfsuren zonopbrengst"
#define STR8700_TEXT "Buitentemperatuuropnemer locaal"
#define STR8703_TEXT "Gedempte buitentemperatuur"
#define STR8704_TEXT "Gemengde buitentemperatuur"
#define STR8740_TEXT "Ruimtetemperatuur 1 meetwaarde"
#define STR8741_TEXT "Ruimtetemp-gew. waarde actueel"
#define STR8743_TEXT "Aanvoertemperatuur meetwaarde Groep 1"
#define STR8744_TEXT "Aanvoersetpoint H1"
#define STR8750_TEXT "Pomptoerental"
#define STR8770_TEXT "Ruimtetemperatuur 2 meetwaarde"
#define STR8771_TEXT "Ruimtemp gew.waarde actueel Groep 2"
#define STR8773_TEXT "Aanvoertemperatuur meetwaarde Groep 2"
#define STR8774_TEXT "Aanvoersetpoint H2"
#define STR8830_TEXT "Tapwatertemperatuur-Boven (B3)"
#define STR8831_TEXT "Tapwatertemperatuur-gew.waarde actueel"
#define STR8836_TEXT "Tapwater Laadtemperatuur"
#define STR8950_TEXT "Proces-Sig Gezamenlijke aanvoertemperatuur"
#define STR8952_TEXT "Proces-Sig Gezamenlijke retourtemperatuur"
#define STR8980_TEXT "Buffertemperatuur Boven (B4)"
#define STR9500_TEXT "Voorspoeltijd"
#define STR9502_TEXT "Modulatie lucht in voorventilatie"
#define STR9504_TEXT "Setpoint vent.toerental in voorventilatie"
#define STR9510_TEXT "Modulatie lucht in aansteeklast"
#define STR9512_TEXT "Ventilatortoerental in aansteeklast"
#define STR9520_TEXT "Modulatie lucht in deellast"
#define STR9522_TEXT "Modulatie lucht in vollast"
#define STR9524_TEXT "Ventilatortoerental in deellast"
#define STR9527_TEXT "Ventilatortoerental in vollast"
#define STR9540_TEXT "Naspoeltijd"
#define STR9560_TEXT "Ventilatormodulatie bij bufferlading"
#define STR9563_TEXT "Setpoint ventilator bij bufferlading"
