#define ENUM_CAT_00_TEXT "Orologio"
#define ENUM_CAT_03_TEXT "Programmazione oraria 1"
#define ENUM_CAT_04_TEXT "Programmazione Oraria 2"
#define ENUM_CAT_05_TEXT "Programmazione Oraria 3"
#define ENUM_CAT_06_TEXT "Programma orario ACS"
#define ENUM_CAT_08_TEXT "Programmazione vacanze"
#define ENUM_CAT_09_TEXT "Programmazione vacanze N°2"
#define ENUM_CAT_0b_TEXT "Circuito riscaldamento 1"
#define ENUM_CAT_0d_TEXT "Circuito riscaldamento 2"
#define ENUM_CAT_0f_TEXT "Acqua calda sanitaria (ACS)"
#define ENUM_CAT_13_TEXT "Caldaia"
#define ENUM_CAT_19_TEXT "Solare"
#define ENUM_CAT_1b_TEXT "Accumulo"
#define ENUM_CAT_1c_TEXT "Accumolo ACS"
#define ENUM_CAT_1d_TEXT "ACS accumulo diretto"
#define ENUM_CAT_1e_TEXT "Configurazione"
#define ENUM_CAT_1f_TEXT "LPB"
#define ENUM_CAT_20_TEXT "Allarme"
#define ENUM_CAT_21_TEXT "Manutenzione"
#define ENUM_CAT_24_TEXT "Stato"
#define ENUM_CAT_26_TEXT "Parametri diagnostica"
#define ENUM_CAT_27_TEXT "Diagnostica utenze"
#define ENUM_CAT_28_TEXT "Controllo Bruciatore"
#define STR516_TEXT "Valori standard TSP circuito risc.1"
#define STR536_TEXT "Valori Standard TSP circuito risc. 2"
#define STR556_TEXT "Valori Standard TSP3 circuito risc.3"
#define STR576_TEXT "Valori Standard TSP 4"
#define STR648_TEXT "Reg.funz. ferie circ. risc.1"
#define STR652_TEXT "Periodo ferie 1 CR.2: 1° giorno"
#define STR653_TEXT "Periodo ferie 1 CR.2: Ultimo giorno"
#define STR658_TEXT "Reg.funz. Ferie circ.risc.2"
#define STR700_TEXT "Regime operativo CR. 1"
#define STR710_TEXT "Setpoint Comfort circ.risc.1"
#define STR712_TEXT "Setpoint T. ridotta circuito 1"
#define STR714_TEXT "Setpoint antigelo amb.te circuito 1"
#define STR720_TEXT "Curva risc 1 inclinazione"
#define STR721_TEXT "Spostamento parallelo della curva climatica"
#define STR726_TEXT "Correzione curva di riscaldamento circ 1"
#define STR730_TEXT "Estato/inverno cambio temperatura circ 1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Min limite T. di mandata circuito 1"
#define STR741_TEXT "Max limite T. di mandata circuito 1"
#define STR750_TEXT "Fattore di guadagno T. amb.te circ. 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Setpoint T. amb. accelerato CR. 1 (boost)"
#define STR780_TEXT "Riduzione rapida CR. 1"
#define STR790_TEXT "Ottimizzazione avvio max. anticipo CR.1"
#define STR791_TEXT "Ottimizzazione stop max. anticipo CR.1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Funzione pavimento malta secco su"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Velocità pompa risc prescritta"
#define STR885_TEXT "min PWM pompa modul"
#define STR886_TEXT "Temp. esterna alla max richiesta di caldo"
#define STR887_TEXT "Setpoint climat caldaia"
#define STR888_TEXT "Limite Temp. Boost regolatore dT"
#define STR894_TEXT "Differenza temp mand/ritorno TiAussenNorm"
#define STR1000_TEXT "Regime operativo CR. 2"
#define STR1010_TEXT "Setpoint Comfort circ.risc.1"
#define STR1012_TEXT "Setpoint amb.te T. rid circ 2"
#define STR1014_TEXT "Setpoint antigelo amb.te circuito 2"
#define STR1020_TEXT "Curva risc 2 inclinazione"
#define STR1021_TEXT "Spostamento parallelo della curva climatica"
#define STR1026_TEXT "Correzione curva di riscaldamento circ 2"
#define STR1030_TEXT "Estato/Inverno cambio temperatura circuito 2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Min limite T. di mandata circuito 2"
#define STR1041_TEXT "Max limite T. di mandata circuito 2"
#define STR1050_TEXT "Fattore di guadagno T. amb.te circ. 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Setpoint T. amb. accelerato CR. 2 (boost)"
#define STR1080_TEXT "Riduzione rapida CR. 2"
#define STR1090_TEXT "Ottimizzazione avvio max. anticipo CR.2"
#define STR1091_TEXT "Ottimizzazione stop max. anticipo CR.2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Incremento temp. valvola di misc. Circ. riscald"
#define STR1134_TEXT "Tempo di corsa del servocomando risc"
#define STR1150_TEXT "Funzione pavimento malta secco su"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "Regime funzionamento A.C.S."
#define STR1610_TEXT "setpoint nominale A.C.S."
#define STR1612_TEXT "setpoint ridotto A.C.S."
#define STR1620_TEXT "Attivazione A.C.S."
#define STR1640_TEXT "Funzione Legionella"
#define STR1641_TEXT "Periodicità funz. Legionella"
#define STR1642_TEXT "Giorno per funzione Legionella"
#define STR1644_TEXT "Orario funzione Legionella"
#define STR1645_TEXT "Setpoint funzione antilegionella"
#define STR1646_TEXT "Durata setpoint funzione Legionella"
#define STR1647_TEXT "Funzionamento pompa durante Legionella"
#define STR1660_TEXT "Consenso pompa ricirc."
#define STR1661_TEXT "Intermittenza pompa circ."
#define STR2201_TEXT "Blocco produz calore"
#define STR2210_TEXT "Limite min. temperatura caldaia"
#define STR2212_TEXT "Limite max. temperatura caldaia"
#define STR2440_TEXT "Max grado di modulazione in riscaldamento"
#define STR2441_TEXT "Max velocità reg. Riscaldamento"
#define STR2442_TEXT "PWM ventil. ritardo regolat."
#define STR2443_TEXT "Inizio mod valore al rilascio ACS"
#define STR2451_TEXT "Tempo min off bruciatore"
#define STR2452_TEXT "SD tempo spegnim.bruc."
#define STR2453_TEXT "Ritardo di controllo dopo avviamento bruciatore"
#define STR2454_TEXT "Differenziale interruttore caldaia"
#define STR2455_TEXT "Min diff.le Off bruciatore"
#define STR2456_TEXT "Max diff.le Off bruciatore"
#define STR2471_TEXT "Ritardo arresto della pompa"
#define STR2472_TEXT "Temp. temporizz pompa ACS"
#define STR2521_TEXT "Protez antigelo caldaia temp ON"
#define STR2522_TEXT "Temp Off per antigelo caldaia"
#define STR3810_TEXT "Temperatura differenziale solare"
#define STR3811_TEXT "T. differential off solar"
#define STR3812_TEXT "Min. temperatura di carico"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "T. protezione antigelo collettore"
#define STR3850_TEXT "Protez. antisurr. collettore"
#define STR3860_TEXT "Temperatura evaporatore"
#define STR4721_TEXT "SD blocco autom. generat."
#define STR4722_TEXT "Diff. temp. buffer/CR"
#define STR5019_TEXT "Setpoint ricarica accumulo antistratificazione"
#define STR5020_TEXT "Temperatura di mandata ACS accelerazione"
#define STR5050_TEXT "Max.T. di carico ACS"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Vel min pompa per carico accumulo"
#define STR5020_TEXT "Temperatura di mandata ACS accelerazione"
#define STR5400_TEXT "Setpoint temperatura pronto"
#define STR5430_TEXT "Diff.le On ACS sonda 1"
#define STR5431_TEXT "Min Off diff.le ACS sonda 1"
#define STR5432_TEXT "Max diff.le Off ACS sonda 1"
#define STR5433_TEXT "Diff.le On ACS sonda 2"
#define STR5434_TEXT "Min.diff.arresto ACS mode (sens2)"
#define STR5435_TEXT "Max diff.le Off ACS sonda 2"
#define STR5450_TEXT "Soglia di risposta detection of ACS consumpt."
#define STR5451_TEXT "Resp. soglia ACS consumpt. in comfort"
#define STR5452_TEXT "Resp. soglia ACS in riscaldamento"
#define STR5453_TEXT "Setpoint t 40°C in reg comfort"
#define STR5454_TEXT "Setpoint a 60°C in reg comfort"
#define STR5455_TEXT "Setpoint a 40°C di scarico"
#define STR5456_TEXT "Setpoint a 60°C di scarico"
#define STR5480_TEXT "Tempo per ACS comfort after consumption"
#define STR5481_TEXT "Tempo ACS comf. after consumpt. (heat)"
#define STR5482_TEXT "Flow switch time cons"
#define STR5483_TEXT "Flow switch time Comfort"
#define STR5486_TEXT "Regolat. ritardo all'inserz. ACS modo alternato"
#define STR5487_TEXT "Rit. Arresto pompa ACS dopo fermo bruciatore"
#define STR5488_TEXT "Rit. Arresto pompa ACS dopo fermo bruciatore"
#define STR5701_TEXT "Tipologia d'impianto"
#define STR5710_TEXT "Circuito riscaldamento 1"
#define STR5715_TEXT "Circuito riscaldamento 2"
#define STR5732_TEXT "Tempo di arresto pompa ACS in modalità risc."
#define STR5733_TEXT "Ritardo all'arresto pompa ACS"
#define STR5761_TEXT "Richiesta Calore tramite pompa Q8"
#define STR5920_TEXT "Uscita programmabile K2 LMU"
#define STR5921_TEXT "Default da K2 a K1"
#define STR5922_TEXT "Funzione uscita 1 clip-in funzione m"
#define STR5923_TEXT "Funzione uscita 2 funzione modulo"
#define STR5924_TEXT "Funzione uscita 3 clip-in modulo funzione"
#define STR5926_TEXT "Uscita relé 1 SolCI"
#define STR5927_TEXT "Uscita relé 2 SolCI"
#define STR5928_TEXT "Uscita relé 3 SolCI"
#define STR5950_TEXT "Selezione funzione ingresso H1"
#define STR5957_TEXT "Modem"
#define STR5970_TEXT "Config termost ambiente 1"
#define STR5971_TEXT "Config termost ambiente 2"
#define STR5973_TEXT "Funzione Input RelCI"
#define STR5975_TEXT "Max temperatura per richiesta esterna"
#define STR5976_TEXT "Lim inferiore segnale ingr per rich esterna"
#define STR6110_TEXT "Costante di tempo dell'edificio"
#define STR6112_TEXT "Gradiente modello ambiente"
#define STR6120_TEXT "Protezione antigelo impianto"
#define STR6127_TEXT "Tempo per antigrippaggio pompa/valvola"
#define STR6220_TEXT "Versione del software"
#define STR6225_TEXT "Famiglia d'apparecchio"
#define STR6226_TEXT "Variante d'apparecchio"
#define STR6227_TEXT "Versione OV d'apparecchio"
#define STR6230_TEXT "Controllo setting flags 0"
#define STR6240_TEXT "Controllo setting flags 1"
#define STR6250_TEXT "Controllo setting flags 2"
#define STR6260_TEXT "Controllo setting flags 3"
#define STR6270_TEXT "Controllo setting flags 4"
#define STR6300_TEXT "Controllo setting flags 7"
#define STR6330_TEXT "ConfigContr10"
#define STR6604_TEXT "Impostazione dell'alimentazione del bus dal reg."
#define STR6605_TEXT "Alimentazione del bus del regolatore"
#define STR6625_TEXT "Carico ACS"
#define STR6640_TEXT "Orologio"
#define STR6705_TEXT "Codice interno di diagnostica"
#define STR6706_TEXT "Fase"
#define STR6741_TEXT "Allarme Temp. mandata 2"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "3 valore codice diagnosi interno"
#define STR6826_TEXT "3 valore di blocco fase"
#define STR6830_TEXT "4 valore blocco contatore"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "4 valore codice diagnosi interno"
#define STR6836_TEXT "4 valore blocco fase"
#define STR6840_TEXT "5 valore di blocco contatore"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "5 valore diagnosi interno"
#define STR6846_TEXT "5 valore di blocco fase"
#define STR7001_TEXT "Mantenimento messaggio"
#define STR7007_TEXT "Configurazione / Reset messaggi di service"
#define STR7010_TEXT "Conferma messaggio Service"
#define STR7011_TEXT "Tempo di ripetizione messaggi allarme"
#define STR7040_TEXT "Intervallo manutenzione bruciatore"
#define STR7041_TEXT "Ore di funz. dall'ultimo intervento service"
#define STR7042_TEXT "Lim avvio bruciatore service"
#define STR7043_TEXT "Avvio bruciatore dopo l'ultimo service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Mesi dall'ultimo Service"
#define STR7050_TEXT "Messaggio di service per soglia Vel. Ventilatore"
#define STR7051_TEXT "Corrente di ionizzazione messaggio di servizio"
#define STR8000_TEXT "Stato circ. riscaldamento 1"
#define STR8001_TEXT "Stato circ. riscaldamento 2"
#define STR8003_TEXT "Stato ACS"
#define STR8005_TEXT "Stato caldaia"
#define STR8007_TEXT "Stato solare"
#define STR8310_TEXT "Temperatura di caldaia"
#define STR8311_TEXT "Setpoint T. di caldaia"
#define STR8314_TEXT "Temperatura di ritorno"
#define STR8316_TEXT "Val attuale T. fumi"
#define STR8324_TEXT "Num.giri ventiliatore"
#define STR8325_TEXT "Contr.ventil.attuale"
#define STR8326_TEXT "Output relativo"
#define STR8328_TEXT "Contr.indic. stato bruc."
#define STR2730_TEXT "Jonizzazione"
#define STR8336_TEXT "Ore di funzionomento dell'apparecchio"
#define STR8337_TEXT "N. avviam. bruc"
#define STR8338_TEXT "Ore funzionamento bruciatore"
#define STR8339_TEXT "Ore riscaldamento ACS"
#define STR8340_TEXT "Ore funz zona"
#define STR8510_TEXT "T. 1 collettore val. attuale (B6)"
#define STR8530_TEXT "Ore di funz. produz. solare"
#define STR8700_TEXT "Sonda locale Temperatura esterna"
#define STR8703_TEXT "Temperatura esterna attenuata"
#define STR8704_TEXT "Temperatura esterna composta"
#define STR8740_TEXT "Temperatura ambiente 1"
#define STR8741_TEXT "Setpoint temperatura ambiente"
#define STR8743_TEXT "Temperatura di mandata del circuito 1"
#define STR8744_TEXT "Setpoint mandata H1"
#define STR8750_TEXT "Velocità pompa"
#define STR8770_TEXT "Temperatura ambiente 2"
#define STR8771_TEXT "Setpoint temperatura ambiente CR. 2"
#define STR8773_TEXT "Temperatura di mandata del circuito 2"
#define STR8774_TEXT "Setpoint mandata H2"
#define STR8830_TEXT "temp. superiore A.C.S. (B3)"
#define STR8831_TEXT "Setpoint attuale temperatura ACS"
#define STR8836_TEXT "Temp carico DHW"
#define STR8950_TEXT "Segnale di processo temperatura di mandata"
#define STR8952_TEXT "Segnale di processo temperatura di ritorno"
#define STR8980_TEXT "T. serbatoio sonda superiore val attuale (B4)"
#define STR9500_TEXT "Tempo di preventilazione"
#define STR9502_TEXT "Contr ventilat. in preventil."
#define STR9504_TEXT "Velocità preventil richiesta"
#define STR9510_TEXT "Modulazione aria"
#define STR9512_TEXT "Velocità richiesta all'iniezione"
#define STR9520_TEXT "Modulazione aria fuoco basso"
#define STR9522_TEXT "Modulazione fuoco alto"
#define STR9524_TEXT "Velocità richiesta fuoco basso"
#define STR9527_TEXT "Velocità richiesta fuoco alto"
#define STR9540_TEXT "Tempo di post-ventilazione"
#define STR9560_TEXT "Modulazione velocità x carico completo accumulo"
#define STR9563_TEXT "Vel. Vent.x carico completo accumulo"
#define STR6225_TEXT "Famiglia d'apparecchio"
#define STR6226_TEXT "Variante d'apparecchio"
#define STR6227_TEXT "Versione OV d'apparecchio"
#define STR6705_TEXT "Codice interno di diagnostica"
#define STR7001_TEXT "Mantenimento messaggio"
#define STR8310_TEXT "Temperatura di caldaia"
#define STR8830_TEXT "temp. superiore A.C.S. (B3)"
#define STR8510_TEXT "T. 1 collettore val. attuale (B6)"
#define STR8328_TEXT "Contr.indic. stato bruc."
#define STR8700_TEXT "Sonda locale Temperatura esterna"
#define STR8980_TEXT "T. serbatoio sonda superiore val attuale (B4)"
#define STR8740_TEXT "Temperatura ambiente 1"
#define STR8741_TEXT "Setpoint temperatura ambiente"
#define STR8743_TEXT "Temperatura di mandata del circuito 1"
#define STR8770_TEXT "Temperatura ambiente 2"
#define STR8771_TEXT "Setpoint temperatura ambiente CR. 2"
#define STR8773_TEXT "Temperatura di mandata del circuito 2"
#define STR8950_TEXT "Segnale di processo temperatura di mandata"
#define STR8952_TEXT "Segnale di processo temperatura di ritorno"
