#define LANGUAGENAME_TEXT "Suomi"
#define ENUM_CAT_00_TEXT "Kellonaika ja päivämäärä"
#define ENUM_CAT_03_TEXT "Aikaohjelma, lämmityspiiri 1"
#define ENUM_CAT_04_TEXT "Aikaohjelma, lämmityspiiri 2"
#define ENUM_CAT_05_TEXT "Aikaohjelma 3 / LPP"
#define ENUM_CAT_06_TEXT "Time switch program DHW"
#define ENUM_CAT_08_TEXT "Loma, lämmityspiiri 1"
#define ENUM_CAT_09_TEXT "Loma, lämmityspiiri 2"
#define ENUM_CAT_0b_TEXT "Lämmityspiiri 1"
#define ENUM_CAT_0d_TEXT "Lämmityspiiri 2"
#define ENUM_CAT_0f_TEXT "Käyttövesi"
#define ENUM_CAT_13_TEXT "Kattila"
#define ENUM_CAT_19_TEXT "Aurinko"
#define ENUM_CAT_1b_TEXT "Lisävaraaja"
#define ENUM_CAT_1c_TEXT "Käyttövesivaraaja"
#define ENUM_CAT_1d_TEXT "Käyttöveden suora lataus"
#define ENUM_CAT_1e_TEXT "Konfiguraatio"
#define ENUM_CAT_1f_TEXT "LPB-järjestelmä"
#define ENUM_CAT_20_TEXT "Häiriö"
#define ENUM_CAT_21_TEXT "Huolto/erikoiskäyttö"
#define ENUM_CAT_24_TEXT "Tila"
#define ENUM_CAT_26_TEXT "Lämm.tuottajan diagnoosi"
#define ENUM_CAT_27_TEXT "Kuluttajien diagnoosi"
#define ENUM_CAT_28_TEXT "Poltinohjain"
#define STR516_TEXT "Standard values TSP heating circuit 1"
#define STR536_TEXT "Standard values TSP heating circuit 2 "
#define STR556_TEXT "Standard values TSP3"
#define STR576_TEXT "Standard values TSP 4"
#define STR648_TEXT "Loma käyttötaso lämm.piir.1"
#define STR652_TEXT "Lomajakso1 läm.piir.2:ensimm.pv"
#define STR653_TEXT "Lomajakso1 läm.piir.2:viim.pv"
#define STR658_TEXT "Loma käyttötaso lämm.piir.2"
#define STR700_TEXT "Käyttötila lämm.piir.1"
#define STR710_TEXT "Huonel.til.mukavuusaset.arv.lä.piir.1"
#define STR712_TEXT "Huo.läm.til.alen.aset.arvo.läm.piir1"
#define STR714_TEXT "Huo.läm.til.jäät.suoj.aset.arvo.l.p.1"
#define STR720_TEXT "Lämm.käyrä1, kaltevuus"
#define STR721_TEXT "Lämmityskäyrän siirto"
#define STR726_TEXT "Heating curve adaptation heat circuit 1"
#define STR730_TEXT "Talvi/kesä vaihtolämp.tila.lä.piiri1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Flow temp min limitation heat circuit 1"
#define STR741_TEXT "Flow temp max limitation heat circuit 1"
#define STR750_TEXT "Room temp gain factor heat circuit 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Room temp setpoint boost HC1 (boost heating)"
#define STR780_TEXT "Quick setback heat circuit 1"
#define STR790_TEXT "Opt.aloit.maks.aik.siirto eteenp.l.p1"
#define STR791_TEXT "Optimum stop control max forward shift HC1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Lattiankuivaustoiminto"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Kierrosluvun mitoituspiste"
#define STR885_TEXT "Mod. pumpun min. PWM"
#define STR886_TEXT "Ulkolämpötilan standardi"
#define STR887_TEXT "Menov. as.arvo, stand. UL"
#define STR888_TEXT "Lämp.ero korotuskerroin"
#define STR894_TEXT "LE erotus, standardi UL"
#define STR1000_TEXT "Käyttötila lämm.piir.2"
#define STR1010_TEXT "Huonel.til.mukavuusaset.arv.lä.piir.2"
#define STR1012_TEXT "Huo.läm.til.alen.aset.arvo.läm.piir2"
#define STR1014_TEXT "Huo.läm.til.jäät.suoj.aset.arvo.l.p.2"
#define STR1020_TEXT "Lämm.käyrä2, kaltevuus"
#define STR1021_TEXT "Lämmityskäyrän siirto"
#define STR1026_TEXT "Heating curve adaptation heat circuit 2"
#define STR1030_TEXT "Talvi/kesä vaihtolämp.tila.lä.piiri2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Flow temp min limitation heat circuit 2"
#define STR1041_TEXT "Flow temp max limitation heat circuit 2"
#define STR1050_TEXT "Room temp gain factor heat circuit 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Room temp setpoint boost HC2 (boost heating)"
#define STR1080_TEXT "Quick setback heat circuit 2"
#define STR1090_TEXT "Opt.aloit.maks.aik.siirto eteenp.l.p2"
#define STR1091_TEXT "Optimum stop control max forward shift HC2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Sekoitusventtiilin korotus"
#define STR1134_TEXT "Toimilaitteen ajoaika"
#define STR1150_TEXT "Lattiankuivaustoiminto"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "KV-käyttötila"
#define STR1610_TEXT "Nimellinen asetusarvo"
#define STR1612_TEXT "Alennettu asetusarvo"
#define STR1620_TEXT "Vapautus"
#define STR1640_TEXT "Legionellanestotoiminto"
#define STR1641_TEXT "Leg.estotoiminto jaksoittain"
#define STR1642_TEXT "Leg.estotoiminto viikoittain"
#define STR1644_TEXT "Legionellaneston ajankohta"
#define STR1645_TEXT "Legionellaneston asetusarvo"
#define STR1646_TEXT "Legionellaneston kesto"
#define STR1647_TEXT "Leg.eston kiertovesipumppu"
#define STR1660_TEXT "Kiertovesipumpun vapautus"
#define STR1661_TEXT "Kiertovesipumpun sykli"
#define STR2201_TEXT "Lämm.tuoton esto"
#define STR2210_TEXT "Minimi asetusarvo"
#define STR2212_TEXT "Maksimi asetusarvo"
#define STR2440_TEXT "Puhalt. PWM Hz maksimi"
#define STR2441_TEXT "Puhalt. kierr.luku Hz maks."
#define STR2442_TEXT "Puhalt. PWM säätimen viive"
#define STR2443_TEXT "Puh. PWM alkuarvo läpiv.lämm"
#define STR2451_TEXT "Polttimen min. off-aika"
#define STR2452_TEXT "Polttimen off-ajan kytk.ero"
#define STR2453_TEXT "Säätimen viiveen kesto"
#define STR2454_TEXT "Kattilan kytkentäero"
#define STR2455_TEXT "Kattila off kytkentäero, min."
#define STR2456_TEXT "Kattila off kytkentäero, max"
#define STR2471_TEXT "Pumpun jälkikäyntiaika"
#define STR2472_TEXT "Käyttöv.pumpun jälkik.lämp."
#define STR2521_TEXT "Jäätymissuoj. päällekytk.lämp."
#define STR2522_TEXT "Jäätymissuoj. poiskytk.lämp."
#define STR3810_TEXT "Lämpötilaero On"
#define STR3811_TEXT "Lämpötilaero Off"
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Keräimen jäätymissuojaus"
#define STR3850_TEXT "Keräimen ylilämpösuoja"
#define STR3860_TEXT "Lämm.siirtoaineen höyrystys"
#define STR4721_TEXT "Aut. lämm.tuot eston kytk.ero"
#define STR4722_TEXT "Lisävar./lämm.piirin lämp.ero"
#define STR5019_TEXT "Kerrosvar. jälkilat. korotus"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Virt.kytkimen aika, kulutus"
#define STR5483_TEXT "Virt.kytkimen aika, mukav."
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Hydrauliikkakaavio"
#define STR5710_TEXT "Lämmityspiiri 1"
#define STR5715_TEXT "Lämmityspiiri 2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Järjestelmäpumppu Q8"
#define STR5920_TEXT "Relelähtö K2 LMU-pohj."
#define STR5921_TEXT "Oletus K2 K1:een"
#define STR5922_TEXT "Relelähtö 1 RelCI"
#define STR5923_TEXT "Relelähtö 2 RelCI"
#define STR5924_TEXT "Relelähtö 3 RelCI"
#define STR5926_TEXT "Relelähtö 1 SolCI"
#define STR5927_TEXT "Relelähtö 2 SolCI"
#define STR5928_TEXT "Relelähtö 3 SolCI"
#define STR5950_TEXT "Tulon H1 toiminta"
#define STR5957_TEXT "Modeemitoiminto"
#define STR5970_TEXT "Huonetermostaatin 1 konfig."
#define STR5971_TEXT "Huonetermostaatin 2 konfig."
#define STR5973_TEXT "Tulon RelCI toiminta"
#define STR5975_TEXT "Ulk. menov. maks. as.arvo"
#define STR5976_TEXT "Ulk. esivalittu tehoraja"
#define STR6110_TEXT "Rakennuksen aikavakio"
#define STR6112_TEXT "Huonemallin gradientti"
#define STR6120_TEXT "Laitoksen jäätymissuojaus"
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6220_TEXT "Ohjelmaversio"
#define STR6225_TEXT "Laiteperhe"
#define STR6226_TEXT "Laitetyyppi"
#define STR6227_TEXT "Kohdeluetteloversio"
#define STR6230_TEXT "Säädin0Konf"
#define STR6240_TEXT "Säädin1Konf"
#define STR6250_TEXT "Säädin2Konf"
#define STR6260_TEXT "Säädin3Konf"
#define STR6270_TEXT "Säädin4Konf"
#define STR6300_TEXT "Säädin7Konf"
#define STR6330_TEXT "Säädin10Konf"
#define STR6604_TEXT "Väylän tehonsyötön toim."
#define STR6605_TEXT "Väyläsyötön tila"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Kellokäyttö"
#define STR6705_TEXT "Ohjelman diagnoosikoodi"
#define STR6706_TEXT "Poltinohj. vaihe häir.asento"
#define STR6741_TEXT "Menovesilämp. 2 hälytys"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "Ohjelman diagnoosikoodi 3"
#define STR6826_TEXT "Poltinohj. vaihe 3"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "Ohjelman diagnoosikoodi 4"
#define STR6836_TEXT "Poltinohj. vaihe 4"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "Ohjelman diagnoosikoodi 5"
#define STR6846_TEXT "Poltinohj. vaihe 5"
#define STR7001_TEXT "Viesti"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Viestin kuittaus"
#define STR7011_TEXT "Viestin toistoaika"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Ionisaatiovirran puhall.nopeus"
#define STR7051_TEXT "Ionisaatiovirran viesti"
#define STR8000_TEXT "Lämmityspiirin 1 tila"
#define STR8001_TEXT "Lämmityspiirin 2 tila"
#define STR8003_TEXT "Käyttöveden tila"
#define STR8005_TEXT "Kattilan tila"
#define STR8007_TEXT "Aurinkolämmityksen tila"
#define STR8310_TEXT "Kattilan lämpötila"
#define STR8311_TEXT "Kattilan asetusarvo"
#define STR8314_TEXT "Kattilan paluuvesilämpötila"
#define STR8316_TEXT "Savukaasun lämpötila"
#define STR8324_TEXT "Puhaltimen nopeus"
#define STR8325_TEXT "Nykyinen puhallinohjaus"
#define STR8326_TEXT "Suhteellinen teho"
#define STR8328_TEXT "Poltinohj. toiminnan näyttö"
#define STR2730_TEXT "Ionisaatiovirta"
#define STR8336_TEXT "Laitteen käyttötunnit"
#define STR8337_TEXT "Polttimen käynnistyslaskuri"
#define STR8338_TEXT "Lämmityskäytön ajotunnit"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Vyöhykkeiden ajotunnit"
#define STR8510_TEXT "Keräimen lämpötila 1"
#define STR8530_TEXT "Ajotunnit aurinkoenergialla"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Vaimennettu ulkolämpötila"
#define STR8704_TEXT "Sekoitettu ulkolämpötila"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Menoveden lämpötila 1"
#define STR8744_TEXT "Menoveden asetusarvo H1"
#define STR8750_TEXT "Modul. pumpun asetusarvo"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Huoneasetusarvo 2"
#define STR8773_TEXT "Menoveden lämpötila 2"
#define STR8774_TEXT "Menoveden asetusarvo H2"
#define STR8830_TEXT "Käyttöveden lämpötila 1"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "Käyttöveden latauslämpötila"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Lisävaraajan lämpötila 1"
#define STR9500_TEXT "Esituuletusaika"
#define STR9502_TEXT "Esituulet. puhallinohjaus"
#define STR9504_TEXT "Esituulet. k-luvun asetus"
#define STR9510_TEXT "Sytytyksen puhallinohjaus"
#define STR9512_TEXT "Sytyksen k-luvun asetus"
#define STR9520_TEXT "Käytön puhall.ohjaus min."
#define STR9522_TEXT "Käytön puhall.ohjaus maks."
#define STR9524_TEXT "Käyttönopeuden min.asetus"
#define STR9527_TEXT "Käyttönopeuden maks.asetus"
#define STR9540_TEXT "Jälkituuletusaika"
#define STR9560_TEXT "Puhallinohjaus täyslataus"
#define STR9563_TEXT "Täyslatauksen nopeusasetus"
