#define ENUM_CAT_00_TEXT "Gun ve zaman saati"
#define ENUM_CAT_03_TEXT "Zaman programi ist dev 1"
#define ENUM_CAT_04_TEXT "Zaman programi ist dev 2"
#define ENUM_CAT_05_TEXT "Zaman programi 3 / ISP"
#define ENUM_CAT_06_TEXT "Time switch program DHW"
#define ENUM_CAT_08_TEXT "Tatil isitma devresi 1"
#define ENUM_CAT_09_TEXT "Tatil isitma devresi 2"
#define ENUM_CAT_0b_TEXT "Isitma devresi-1"
#define ENUM_CAT_0d_TEXT "Isitma devresi-2"
#define ENUM_CAT_0f_TEXT "Sicak kullanma suyu"
#define ENUM_CAT_13_TEXT "Kazan"
#define ENUM_CAT_19_TEXT "Gunes enerjisi"
#define ENUM_CAT_1b_TEXT "Yedek tank"
#define ENUM_CAT_1c_TEXT "Sicak kullanma su ydk tank"
#define ENUM_CAT_1d_TEXT "Direk kullanma suyu besleme"
#define ENUM_CAT_1e_TEXT "Konfigurasyon"
#define ENUM_CAT_1f_TEXT "LPB sistemi"
#define ENUM_CAT_20_TEXT "Hata"
#define ENUM_CAT_21_TEXT "Bakim-servis"
#define ENUM_CAT_24_TEXT "Durum"
#define ENUM_CAT_26_TEXT "Isi uretimi tanimlama"
#define ENUM_CAT_27_TEXT "Tuketici tanimlama"
#define ENUM_CAT_28_TEXT "Yakici kontrol"
#define STR516_TEXT "Standard values TSP heating circuit 1"
#define STR536_TEXT "Standard values TSP heating circuit 2 "
#define STR556_TEXT "Standard values TSP3"
#define STR576_TEXT "Standard values TSP 4"
#define STR648_TEXT "Tatil işletme seviyesi Isitma Devresi 1"
#define STR652_TEXT "Tatil Modu 1 HC2: Ilk gun"
#define STR653_TEXT "Tatil Modu 1 HC2: Son Gun"
#define STR658_TEXT "Tatil işletme seviyesi Isitma Devresi 2"
#define STR700_TEXT "Isletme modu Isitma devresi1"
#define STR710_TEXT "Konfor modu set değeri Oda sıcakligi IsiDev1"
#define STR712_TEXT "Enerji Tasarrufu Oda sicakligi Isitma Devresi1"
#define STR714_TEXT "Donma Korumasi Oda sicakligi Isitma Devresi1"
#define STR720_TEXT "Isitma egrisi 1. egri"
#define STR721_TEXT "Isitma egrisi yerdegistirme"
#define STR726_TEXT "Heating curve adaptation heat circuit 1"
#define STR730_TEXT "Yaz/Kis gecisi sicakligi Isitma Devresi1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Flow temp min limitation heat circuit 1"
#define STR741_TEXT "Flow temp max limitation heat circuit 1"
#define STR750_TEXT "Room temp gain factor heat circuit 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Room temp setpoint boost HC1 (boost heating)"
#define STR780_TEXT "Quick setback heat circuit 1"
#define STR790_TEXT "Optimum baslama kontrolu max ileri oteleme IsiD1"
#define STR791_TEXT "Optimum stop control max forward shift HC1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Yerden isitma fonk"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Hiz tasarim noktasi"
#define STR885_TEXT "Modulasyon pompa PMW min"
#define STR886_TEXT "Standart dis hava sick"
#define STR887_TEXT "Akis sick set standart DH"
#define STR888_TEXT "dT artis faktoru"
#define STR894_TEXT "dT fark standart dis hv"
#define STR1000_TEXT "Isletme modu Isitma devresi2"
#define STR1010_TEXT "Konfor modu set değeri Oda sıcakligi IsiDev2"
#define STR1012_TEXT "Enerji Tasarrufu Oda sicakligi Isitma Devresi2"
#define STR1014_TEXT "Donma Korumasi Oda sicakligi  Isitma Devresi2"
#define STR1020_TEXT "Isitma egrisi 2. egri"
#define STR1021_TEXT "Isitma egrisi yerdegistirme"
#define STR1026_TEXT "Heating curve adaptation heat circuit 2"
#define STR1030_TEXT "Yaz/Kis gecisi sicakligi Isitma Devresi2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Flow temp min limitation heat circuit 2"
#define STR1041_TEXT "Flow temp max limitation heat circuit 2"
#define STR1050_TEXT "Room temp gain factor heat circuit 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Room temp setpoint boost HC2 (boost heating)"
#define STR1080_TEXT "Quick setback heat circuit 2"
#define STR1090_TEXT "Optimum baslama kontrolu max ileri oteleme IsiD2"
#define STR1091_TEXT "Optimum stop control max forward shift HC2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Karisim vanasi artis"
#define STR1134_TEXT "Vana motoru calisma zamani"
#define STR1150_TEXT "Yerden isitma fonk"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "Isletme modu Kullanim sicak suyu"
#define STR1610_TEXT "Nominal set degeri"
#define STR1612_TEXT "Dusuk mod set degeri"
#define STR1620_TEXT "Birakma"
#define STR1640_TEXT "Lejoner fonksiyonu"
#define STR1641_TEXT "Lejoner fonksiyonu periyodu"
#define STR1642_TEXT "Lejoner fonksiyonu hafta ici"
#define STR1644_TEXT "Lejoner fonksiyon zamani"
#define STR1645_TEXT "Lejoner fonksiyonu set"
#define STR1646_TEXT "Lejoner fonksiyonu suresi"
#define STR1647_TEXT "Lejoner fonk sirk pompa"
#define STR1660_TEXT "Sirkulasyon pompa serbest"
#define STR1661_TEXT "Sirkulasyon pompa devri"
#define STR2201_TEXT "Isitma uretimi kilitli"
#define STR2210_TEXT "Minimum setdegeri"
#define STR2212_TEXT "Maksimum setdegeri"
#define STR2440_TEXT "Fan PWM isitma maks"
#define STR2441_TEXT "Fan hizi isitma maks"
#define STR2442_TEXT "Fan PWM kontrolor gecikmesi"
#define STR2443_TEXT "Fan PWM cal degeri"
#define STR2451_TEXT "Yakici kapali zamani min"
#define STR2452_TEXT "Anht fark yakici kpl zaman"
#define STR2453_TEXT "Kontrolor bekleme suresi"
#define STR2454_TEXT "Boyler anahtarlama fark"
#define STR2455_TEXT "Anht fark yakici min"
#define STR2456_TEXT "Anht fark yakici maks"
#define STR2471_TEXT "Pompa ek calisma zamani"
#define STR2472_TEXT "Pmp ek calis zamani kul su"
#define STR2521_TEXT "Donma koruma acik mod sick"
#define STR2522_TEXT "Donma koruma kpl mod sick"
#define STR3810_TEXT "Sicaklik farki devrede"
#define STR3811_TEXT "Sicaklik farki kapali"
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Kollektor donma korumasi"
#define STR3850_TEXT "Kollektor yuksek sicaklik kor"
#define STR3860_TEXT "Evaparator isitma tasiyici"
#define STR4721_TEXT "Oto isi ure kilit SD"
#define STR4722_TEXT "Fark sick yedek/ID"
#define STR5019_TEXT "Tekrar bes artisi ydk tnk"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Akis anahtari sabit zamani"
#define STR5483_TEXT "Akis anahtari Konfor zamani"
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Hidrolik diyagram"
#define STR5710_TEXT "Isitma devresi-1"
#define STR5715_TEXT "Isitma devresi-2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Sistem pompa Q8"
#define STR5920_TEXT "Role cikisi K2 LMU tabanli"
#define STR5921_TEXT "Varsayilan K2'den K1'e"
#define STR5922_TEXT "Role cikisi 1 ReiCi"
#define STR5923_TEXT "Role cikisi 2 ReiCi"
#define STR5924_TEXT "Role cikisi 3 ReiCi"
#define STR5926_TEXT "Role cikisi 1 SoiCi"
#define STR5927_TEXT "Role cikisi 2 SoiCi"
#define STR5928_TEXT "Role cikisi 3 SoiCi"
#define STR5950_TEXT "Fonksiyon giris H1"
#define STR5957_TEXT "Modem fonksiyonu"
#define STR5970_TEXT "Oda termostati 1 ayarlama"
#define STR5971_TEXT "Oda termostati 2 ayarlama"
#define STR5973_TEXT "Fonksiyon giris ReICI"
#define STR5975_TEXT "Harici akis sick set maks"
#define STR5976_TEXT "Harici onsecim cikisi esik"
#define STR6110_TEXT "Sabit zamanli bina"
#define STR6112_TEXT "Egimli oda modeli"
#define STR6120_TEXT "Donma koruma merkez"
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6220_TEXT "Yazilim versiyonu"
#define STR6225_TEXT "Cihaz grubu"
#define STR6226_TEXT "Cihaz degiskenleri"
#define STR6227_TEXT "Cihazin dosya versiyonu"
#define STR6230_TEXT "Kontrol0 ayarlama"
#define STR6240_TEXT "Kontrol1 ayarlama"
#define STR6250_TEXT "Kontrol2 ayarlama"
#define STR6260_TEXT "Kontrol3 ayarlama"
#define STR6270_TEXT "Kontrol4 ayarlama"
#define STR6300_TEXT "Kontrol7 ayarlama"
#define STR6330_TEXT "Kontrol10 ayarlama"
#define STR6604_TEXT "Data hatti guc besleme fonk"
#define STR6605_TEXT "Data hatti guc besleme drm"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Saat modu"
#define STR6705_TEXT "Yazilim kontrolkodu"
#define STR6706_TEXT "Yakici kont fazi lokavt poz"
#define STR6741_TEXT "Akis sicakligi 2 alarm"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "Yazilim tanimlama kod3"
#define STR6826_TEXT "Yakici kontrol faz-3"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "Yazilim tanimlama kod4"
#define STR6836_TEXT "Yakici kontrol faz-4"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "Yazilim tanimlama kod5"
#define STR6846_TEXT "Yakici kontrol faz-5"
#define STR7001_TEXT "Mesaj"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Tespi edilmis mesaj"
#define STR7011_TEXT "Tekrarlanan zaman mesaji"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Fan hizi iyonizasyon akimi"
#define STR7051_TEXT "Mesaj iyonizasyon akimi"
#define STR8000_TEXT "Isitma devresi 1 durum"
#define STR8001_TEXT "Isitma devresi 2 durum"
#define STR8003_TEXT "Kullanim suyu durum"
#define STR8005_TEXT "Kazam durum"
#define STR8007_TEXT "Gunes enerjisi durum"
#define STR8310_TEXT "Kazan sicakligi"
#define STR8311_TEXT "Kazan set degeri"
#define STR8314_TEXT "Kazan donus sicakligi"
#define STR8316_TEXT "Baca gazi sicakligi"
#define STR8324_TEXT "Fan hizi"
#define STR8325_TEXT "Secili fan kontrolu"
#define STR8326_TEXT "Baglantili cikis"
#define STR8328_TEXT "Yakici kont durum gost"
#define STR2730_TEXT "Iyonizasyon akimi"
#define STR8336_TEXT "Cihaz calisma suresi"
#define STR8337_TEXT "Sayici basla yakici"
#define STR8338_TEXT "Isitma modu calisma suresi"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Zonlar calisma suresi"
#define STR8510_TEXT "Kollektor sicakligi 1"
#define STR8530_TEXT "Gunes enerjisi calisma suresi"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Dis hava sicakligi azaltilmis"
#define STR8704_TEXT "Dis hava sicakligi karma"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Akis sicakligi 1"
#define STR8744_TEXT "Akis sicakligi set degeri H1"
#define STR8750_TEXT "Modulasyon pompa set"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Oda setdegeri 2"
#define STR8773_TEXT "Akis sicakligi 2"
#define STR8774_TEXT "Akis sicakligi set degeri H2"
#define STR8830_TEXT "Kullanim suyu sensor 1"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "DHW sarj sick"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Yedek tank sicakligi 1"
#define STR9500_TEXT "Onsupurme zamani"
#define STR9502_TEXT "Fan kontrol on temizleme"
#define STR9504_TEXT "Gerekli hiz onsupurme"
#define STR9510_TEXT "Fan kontrol atesleme"
#define STR9512_TEXT "Gerekli hiz atesleme"
#define STR9520_TEXT "Fan kontrol calisma min"
#define STR9522_TEXT "Fan kontrol calisma maks"
#define STR9524_TEXT "Gerekli hiz calis min"
#define STR9527_TEXT "Gerekli hiz calis maks"
#define STR9540_TEXT "Temizleme zamani"
#define STR9560_TEXT "Fan kont tam besleme"
#define STR9563_TEXT "Gerekli hiz tam besleme"
#define STR6225_TEXT "Cihaz grubu"
#define STR6226_TEXT "Cihaz degiskenleri"
#define STR6227_TEXT "Cihazin dosya versiyonu"
#define STR6705_TEXT "Yazilim kontrolkodu"
#define STR7001_TEXT "Mesaj"
#define STR8310_TEXT "Kazan sicakligi"
#define STR8830_TEXT "Kullanim suyu sensor 1"
#define STR8510_TEXT "Kollektor sicakligi 1"
#define STR8328_TEXT "Yakici kont durum gost"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8980_TEXT "Yedek tank sicakligi 1"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Akis sicakligi 1"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Oda setdegeri 2"
#define STR8773_TEXT "Akis sicakligi 2"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
