#define LANGUAGENAME_TEXT "France"
#define ENUM_CAT_00_TEXT "Heure"
#define ENUM_CAT_03_TEXT "Progr. de commande horaire 1"
#define ENUM_CAT_04_TEXT "Progr. de commande horaire 2"
#define ENUM_CAT_05_TEXT "Progr. de commande horaire 3"
#define ENUM_CAT_06_TEXT "Programme horaire eau potable"
#define ENUM_CAT_07_TEXT "Progr. de commande horaire 5"
#define ENUM_CAT_08_TEXT "Programmes vacances CC1"
#define ENUM_CAT_09_TEXT "Programmes vacances CC2"
#define ENUM_CAT_0b_TEXT "Circuit de chauffe 1"
#define ENUM_CAT_0d_TEXT "Circuit de chauffe 2"
#define ENUM_CAT_0f_TEXT "Circuit de chauffe 3/P"
#define ENUM_CAT_10_TEXT "Eau potable"
#define ENUM_CAT_17_TEXT "Chaudière"
#define ENUM_CAT_1e_TEXT "Solaire"
#define ENUM_CAT_20_TEXT "Accumulateur tampon"
#define ENUM_CAT_21_TEXT "Accumulateur eau potable"
#define ENUM_CAT_22_TEXT "Charge directe Eau Potable"
#define ENUM_CAT_24_TEXT "Configuration"
#define ENUM_CAT_25_TEXT "LPB Bus"
#define ENUM_CAT_26_TEXT "Défaut"
#define ENUM_CAT_27_TEXT "Maintenance"
#define ENUM_CAT_2a_TEXT "Etat"
#define ENUM_CAT_2c_TEXT "Diagnostic générateur"
#define ENUM_CAT_2d_TEXT "Diagnostic consommateurs"
#define ENUM_CAT_2e_TEXT "Coffret de sécurité"
#define STR516_TEXT "Valeurs par défaut prog. hor. CC1"
#define STR536_TEXT "Valeurs par défaut prog. hor. CC2"
#define STR556_TEXT "Valeurs par défaut prog. hor.3"
#define STR576_TEXT "Valeurs par défaut prog. hor. 4"
#define STR648_TEXT "Niveau de fonct. pendant vacances CC1"
#define STR652_TEXT "Période de congés 1 CC2: premier jour"
#define STR653_TEXT "Période de congés 1 CC2: dernier jour"
#define STR658_TEXT "Niveau de fonct. pendant vacances CC2"
#define STR700_TEXT "Régime Circuit de chauffe  1"
#define STR710_TEXT "Consigne confort temp.ambiante CC1"
#define STR711_TEXT "Consigne confort temp.ambiante maximum CC1"
#define STR712_TEXT "Valeur de consigne réduite temp. ambiante CC1"
#define STR714_TEXT "Consigne horsgel température ambiante CC1"
#define STR720_TEXT "Pente de la courbe de chauffe 1"
#define STR721_TEXT "Translation de la courbe de chauffe"
#define STR726_TEXT "Adaptation courbe de chauffe CC1"
#define STR730_TEXT "Commutation été/hiver circuit de chauffe 1"
#define STR732_TEXT "Limite de chauffe journalière CC1"
#define STR740_TEXT "Limitation mini température de départ CC1"
#define STR741_TEXT "Limitation maxi température de départ CC1"
#define STR750_TEXT "Facteur d'influence température ambiante CC1"
#define STR760_TEXT "Limitation de température ambiante CC 1"
#define STR770_TEXT "Surélév. cons. ambiance CC1 (chauff. accéléré)"
#define STR780_TEXT "Réduction rapide CC 1"
#define STR790_TEXT "Optimis. heure d'enclenchement Avance maxi CC1"
#define STR791_TEXT "Optimis. heure de coupure, avance maxi CC1"
#define STR800_TEXT "Début relèvem. Consigne réduite TA CC1"
#define STR801_TEXT "Fin relèvement consigne réduite TA CC1"
#define STR850_TEXT "Fonction de séchage dalle"
#define STR851_TEXT "Consigne manuelle séchage chapes béton CC1"
#define STR884_TEXT "Allure pompe chaudière au point de conception"
#define STR885_TEXT "Pompe modulante TRM minimum"
#define STR886_TEXT "Temp. extérieure pour besoins calorifiques maxi"
#define STR887_TEXT "Consigne chaudière pour temp ext. Normalisée"
#define STR888_TEXT "Limite pour surélévation temp. De la régul. Dt"
#define STR894_TEXT "Delta départ/retour pour temp. Ext. Normalisée"
#define STR1000_TEXT "Régime circuit de chauffe 2"
#define STR1010_TEXT "Consigne de confort temp. ambiante CC 2"
#define STR1012_TEXT "Valeur de consigne réduite temp. ambiante CC2"
#define STR1014_TEXT "Valeur de consigne hors-gel temp. ambiante CC2"
#define STR1020_TEXT "Pente de la courbe de chauffe 2"
#define STR1021_TEXT "Translation de la courbe de chauffe"
#define STR1026_TEXT "Adaptation courbe de chauffe CC2"
#define STR1030_TEXT "Commutation été/hiver circuit de chauffe 2"
#define STR1032_TEXT "Limite de chauffe journalière CC2"
#define STR1040_TEXT "Limitation mini température de départ CC2"
#define STR1041_TEXT "Limitation maxi température de départ CC2"
#define STR1050_TEXT "Facteur d 'influence température ambiante CC2"
#define STR1060_TEXT "Limitation de température ambiante CC2"
#define STR1070_TEXT "Surélév. cons. ambiance CC2 (chauffage accéléré)"
#define STR1080_TEXT "Réduction rapide CC 2"
#define STR1090_TEXT "Optimis. heure d'enclenchem.  Avance maxi CC2"
#define STR1091_TEXT "Optimis. heure de coupure Avance maxi CC2"
#define STR1100_TEXT "Début rélèvem. Consigne réduite temp.amb. CC2"
#define STR1101_TEXT "Fin relèvement consigne réduite temp.amb. CC2"
#define STR1130_TEXT "Surélévation temp. mélangeur circuit de chauffe"
#define STR1134_TEXT "Durée de marche servomoteur circuit de chauffe"
#define STR1150_TEXT "Fonction de séchage dalle"
#define STR1151_TEXT "Consigne manuelle séchage chapes béton CC2"
#define STR1600_TEXT "Régime ECS"
#define STR1610_TEXT "Consigne nominale de température ECS"
#define STR1612_TEXT "Consigne réduite de température ECS"
#define STR1614_TEXT "Consigne réduite de température ECS maximum"
#define STR1620_TEXT "Libération ECS"
#define STR1640_TEXT "Fonction antilégionnelle"
#define STR1641_TEXT "Périodicité de la fonction anti-légionelles"
#define STR1642_TEXT "Fonction anti-légionelles Jour"
#define STR1644_TEXT "Heure de la fonction anti-légionnelles"
#define STR1645_TEXT "Consigne fonction anti-légionnelle"
#define STR1646_TEXT "Durée séjour sur consigne fonction légionelle"
#define STR1647_TEXT "Fonction. pompe circul .pendant fonction légion."
#define STR1660_TEXT "Libération de la pompe de circulation ECS"
#define STR1661_TEXT "Fonct. cyclique pompe de circulation ECS"
#define STR2201_TEXT "Blocage générateur"
#define STR2210_TEXT "Limitation mini de température de chaudière"
#define STR2212_TEXT "Limitation maxi de température de chaudière"
#define STR2440_TEXT "Degré modul. Maxi en mode chauffage"
#define STR2441_TEXT "Vitesse rotation ventil. maxi  mode chauffage"
#define STR2442_TEXT "Puissance pendant tempo. Régulateur active"
#define STR2443_TEXT "Démar. Puissance si régul. Libéré av Ch-eau inst"
#define STR2451_TEXT "Temps de pause minimal du brûleur"
#define STR2452_TEXT "Diff. De rég. Max sans interrup pause mini"
#define STR2453_TEXT "Temporisation  régulateur après mise en service"
#define STR2454_TEXT "Différentiel chaudière"
#define STR2455_TEXT "Différence coupure mini chaudière"
#define STR2456_TEXT "Diff. de coupure maxi chaudière"
#define STR2471_TEXT "Temporisation d'arrêt de la pompe"
#define STR2472_TEXT "Température retard à l'arrêt pompe ECS"
#define STR2521_TEXT "Température enclenchement antigel chaudière"
#define STR2522_TEXT "Température de coupure antigel chaudière"
#define STR3810_TEXT "Différence de température Marche solaire"
#define STR3811_TEXT "Différence de température Arrêt solaire"
#define STR3812_TEXT "Température de charge minimale"
#define STR3831_TEXT "Temps de marche min. de la pompe du collecteur"
#define STR3840_TEXT "Température anti-gel capteur solaire"
#define STR3850_TEXT "Temp. protection contre surchauffe collecteur"
#define STR3860_TEXT "Température d'évaporation caloporteur"
#define STR4721_TEXT "Différentiel blocage automatique du générateur"
#define STR4722_TEXT "Diff.  temp. Tampon/CC jusqu'à libér. Producteur"
#define STR5019_TEXT "Elévation consigne p.recharge accumulateur"
#define STR5020_TEXT "Surélévation température de départ ECS"
#define STR5050_TEXT "Température de charge maxi ballon ECS"
#define STR5055_TEXT "Temp. min. refroidissem. adiab. Ballon ECS"
#define STR5100_TEXT "Allure pompe mini pour charge cont. ballon strat"
#define STR5020_TEXT "Surélévation température de départ ECS"
#define STR5400_TEXT "Consigne pour température préparation ECS"
#define STR5430_TEXT "Différentiel enclenchement mode ECS (sonde 1)"
#define STR5431_TEXT "Différentiel coupur mini mode ECS (sonde 1)"
#define STR5432_TEXT "Différentiel coupure maxi mode ECS (sonde 1)"
#define STR5433_TEXT "Différentiel encl. En mode ECS (sonde 2)"
#define STR5434_TEXT "Différentiel  coupure mini  mode ECS (sonde 2)"
#define STR5435_TEXT "Différentiel coupure maxi mode ECS (sonde 2)"
#define STR5450_TEXT "Seuil de fin d'un tirage ECS pour ch-eau inst."
#define STR5451_TEXT "Seuil pour tirage ECS avec ch-ins en confort"
#define STR5452_TEXT "Seuil pour tirage ECS avec ch-ins en mode Ch."
#define STR5453_TEXT "Correction consigne pour régul. confort à 40°C"
#define STR5454_TEXT "Correction consigne régulation Confort à 60°C"
#define STR5455_TEXT "Correction consigne régulation sortie à 40°C"
#define STR5456_TEXT "Correction consigne régulation sortie à 60°C"
#define STR5480_TEXT "Temps Confort ch-eau après tirage sans dem. Ch."
#define STR5481_TEXT "Temps de confort Ch-eau si dem. Ch. Active"
#define STR5482_TEXT "Durée FlowSwitch ECS fermé"
#define STR5483_TEXT "Durée FlowSwitch Confort ECS fermé"
#define STR5486_TEXT "Tempo régulateur si modul."
#define STR5487_TEXT "Arrêt ret. pompe en confort CHINS si brûl. HORS"
#define STR5488_TEXT "Arrêt ret. pompe en confort CHINS si brûl. HORS"
#define STR5701_TEXT "Type d'installation"
#define STR5710_TEXT "Circuit de chauffage 1"
#define STR5715_TEXT "Circuit de chauffage 2"
#define STR5732_TEXT "Durée arrêt pompe si changeover CH vers ECS"
#define STR5733_TEXT "Tempo. Arrêt pompe si changeover CH->ECS"
#define STR5761_TEXT "Demandes de chauffage avec soutien par Q8"
#define STR5920_TEXT "Sortie programmable K2"
#define STR5921_TEXT "Défaut K2 sur K1"
#define STR5922_TEXT "Sortie fonction 1Clip-In Relais"
#define STR5923_TEXT "Sortie fonction 2 Clip-In Relais"
#define STR5924_TEXT "Sortie fonction 3 Clip-In Relais"
#define STR5926_TEXT "Configuration sortie 1"
#define STR5927_TEXT "Configuration sortie 2"
#define STR5928_TEXT "Configuration sortie 3"
#define STR5950_TEXT "Entrée H1 sélection de fonction"
#define STR5957_TEXT "Fonction modem"
#define STR5970_TEXT "Configuration thermostat d'ambiance 1"
#define STR5971_TEXT "Configuration thermostat d'ambiance 2"
#define STR5973_TEXT "Fonction Entrée RelCl"
#define STR5975_TEXT "Limite température pour consigne prescrite ext."
#define STR5976_TEXT "Limite Inf. signal entrée pour demande ext."
#define STR6110_TEXT "Constante de temps du bâtiment"
#define STR6112_TEXT "Gradient modèle d'ambiance"
#define STR6120_TEXT "Hors-gel de l'installation"
#define STR6127_TEXT "Temps pour dégommage pompes / vanne dérivation"
#define STR6220_TEXT "Version du logiciel"
#define STR6225_TEXT "Famille d'appareil"
#define STR6226_TEXT "Variante d'appareil"
#define STR6227_TEXT "Version OV d'appareil"
#define STR6230_TEXT "Configuration du régulateur 0"
#define STR6240_TEXT "Configuration du régulateur 1"
#define STR6250_TEXT "Configuration du régulateur 2"
#define STR6260_TEXT "Configuration du régulateur 3"
#define STR6270_TEXT "Configuration du régulateur 4"
#define STR6300_TEXT "Configuration du régulateur  7"
#define STR6330_TEXT "Configuration du régulateur 10"
#define STR6604_TEXT "Sélection fonction Alimentation Bus"
#define STR6605_TEXT "Etat de l'alimentation Bus"
#define STR6625_TEXT "Affectation d' ECS"
#define STR6640_TEXT "Source de l'heure"
#define STR6705_TEXT "Code de diagnostic interne"
#define STR6706_TEXT "Valeur actuelle de la phase de dérangement"
#define STR6741_TEXT "Heure alarme temp. de départ CC2"
#define STR6823_TEXT "3ème valeur d'historique du code erreur Albatros"
#define STR6825_TEXT "Valeur histo. 3 du diagnostic de dérangement"
#define STR6826_TEXT "Valeur histo. 3 de la phase de dérangement"
#define STR6830_TEXT "Valeur histo. 4 du compteur codes de dérangement"
#define STR6833_TEXT "4ème valeur d'historique du code erreur Albatros"
#define STR6835_TEXT "Valeur histo. 4 du diagnostic de dérangement"
#define STR6836_TEXT "Valeur histo. 4 de la phase de dérangement"
#define STR6840_TEXT "Valeur histo. 5 du compteur codes de dérangement"
#define STR6843_TEXT "5ème valeur d'historique du code erreur Albatros"
#define STR6845_TEXT "Valeur histo. 5 du diagnostic de dérangement"
#define STR6846_TEXT "Valeur histo. 5 de la phase de dérangement"
#define STR7001_TEXT "Signalisation de maintenance"
#define STR7007_TEXT "Configuration / RAZ des messages de maintenance"
#define STR7010_TEXT "Message de maintenance - Acquitter"
#define STR7011_TEXT "Durée de répétition pour messages maintenance"
#define STR7040_TEXT "Heures de fonc. brûleur jusqu'à la maintenance"
#define STR7041_TEXT "Heures de fonct. depuis dernière maintenance"
#define STR7042_TEXT "Limite pour m. en serv. Depuis dernière mainten."
#define STR7043_TEXT "Mises en service depuis dernière maintenance"
#define STR7044_TEXT "Limite des mois depuis la dernière maintenance"
#define STR7045_TEXT "Mois depuis dernière maintenance"
#define STR7050_TEXT "Limite vitesse rot. ventil. Pour message maint."
#define STR7051_TEXT "Signalis. maintenance courant ionisation"
#define STR8000_TEXT "Etat du circuit de chauffage 1"
#define STR8001_TEXT "Etat du circuit de chauffage 2"
#define STR8003_TEXT "Etat de l'ECS"
#define STR8005_TEXT "Etat de la chaudière"
#define STR8007_TEXT "Etat équipement solaire"
#define STR8310_TEXT "Température de chaudière"
#define STR8311_TEXT "Consigne de température de chaudière"
#define STR8314_TEXT "Température de retour"
#define STR8316_TEXT "Température actuelle gaz de fumée"
#define STR8324_TEXT "Vitesse actuelle du ventilateur"
#define STR8325_TEXT "Commande actuelle du ventilateur"
#define STR8326_TEXT "Puissance relative"
#define STR8328_TEXT "Affichage de régime coffret"
#define STR2730_TEXT "Valeur mesurée du courant d'ionisation"
#define STR8336_TEXT "Heures de fonctionnement"
#define STR8337_TEXT "Compteur de démarrages brûleur"
#define STR8338_TEXT "Heures de fonctionnement en mode chauffage"
#define STR8339_TEXT "Heures de fonctionnement en mode ECS"
#define STR8340_TEXT "Heures de fonctionnement en demande chaud ext."
#define STR8510_TEXT "Température mesurée capteur solaire 1 (B6)"
#define STR8530_TEXT "Heures de fonctionnement production solaire"
#define STR8700_TEXT "Température extérieure locale"
#define STR8703_TEXT "Température extérieure résultante"
#define STR8704_TEXT "Température extérieure mélangée"
#define STR8721_TEXT "Température ambiante"
#define STR8740_TEXT "Température ambiante 1"
#define STR8741_TEXT "Consigne actuelle de température Ambiante"
#define STR8743_TEXT "Température de départ circuit de chauffe 1"
#define STR8744_TEXT "Consigne de départ H1"
#define STR8750_TEXT "Vitesse pompe"
#define STR8770_TEXT "Température ambiante 2"
#define STR8771_TEXT "Consigne actuelle de température ambiante CC2"
#define STR8773_TEXT "Température de départ circuit de chauffe 2"
#define STR8774_TEXT "Consigne de départ H2"
#define STR8830_TEXT "Température  mesurée ECS en haut (B3)"
#define STR8831_TEXT "Consigne actuelle de température ECS"
#define STR8836_TEXT "Température de charge ECS"
#define STR8950_TEXT "Signal de processus départ segment"
#define STR8952_TEXT "Signal de processus retour segment"
#define STR8980_TEXT "Températ. accumlateur mesurée partie haute (B4)"
#define STR9500_TEXT "Temps de préventilation"
#define STR9502_TEXT "Modulation de l'air dans la préventilation"
#define STR9504_TEXT "Vitesse ventilateur dans la préventilation"
#define STR9510_TEXT "Modulation d'air en charge d'allumage"
#define STR9512_TEXT "Vitesse de rotation ventil. en charge d'allumage"
#define STR9520_TEXT "Modulation d'air en charge partielle"
#define STR9522_TEXT "Modulation d'air en pleine charge"
#define STR9524_TEXT "Consigne vitesse rotation en charge partielle"
#define STR9527_TEXT "Consigne vitesse rotation ventil. Pleine charge"
#define STR9540_TEXT "Temps de post-ventilation"
#define STR9560_TEXT "Mod. Ventil. Pour charge balllon  stratification"
#define STR9563_TEXT "Consigne ventil. Charge continue ballon  stratif"
#define STR15004_TEXT "Température départ après mélangeur"
#define STR15009_TEXT "Bouton rotatif"
#define STR15011_TEXT "Touche de présence"
#define STR15012_TEXT "Jours de vacances restants"
#define STR15019_TEXT "Période de chauffe 1 Lundi Début"
#define STR15020_TEXT "Période de chauffe 1 Lundi Fin"
#define STR15021_TEXT "Période de chauffe 2 Lundi Début"
#define STR15022_TEXT "Période de chauffe 2 Lundi Fin"
#define STR15023_TEXT "Période de chauffe 3 Lundi Début"
#define STR15024_TEXT "Période de chauffe 3 Lundi Fin"
#define STR15025_TEXT "Période de chauffe 1 Mardi Début"
#define STR15026_TEXT "Période de chauffe 1 Mardi Fin"
#define STR15027_TEXT "Période de chauffe 2 Mardi Début"
#define STR15028_TEXT "Période de chauffe 2 Mardi Fin"
#define STR15029_TEXT "Période de chauffe 3 Mardi Début"
#define STR15030_TEXT "Période de chauffe 3 Mardi Fin"
#define STR15031_TEXT "Période de chauffe 1 Mercredi Début"
#define STR15032_TEXT "Période de chauffe 1 Mercredi Fin"
#define STR15033_TEXT "Période de chauffe 2 Mercredi Début"
#define STR15034_TEXT "Période de chauffe 2 Mercredi Fin"
#define STR15035_TEXT "Période de chauffe 3 Mercredi Début"
#define STR15036_TEXT "Période de chauffe 3 Mercredi Fin"
#define STR15037_TEXT "Période de chauffe 1 Jeudi Début"
#define STR15038_TEXT "Période de chauffe 1 Jeudi Fin"
#define STR15039_TEXT "Période de chauffe 2 Jeudi Début"
#define STR15040_TEXT "Période de chauffe 2 Jeudi Fin"
#define STR15041_TEXT "Période de chauffe 3 Jeudi Début"
#define STR15042_TEXT "Période de chauffe 3 Jeudi Fin"
#define STR15043_TEXT "Période de chauffe 1 Vendredi Début"
#define STR15044_TEXT "Période de chauffe 1 Vendredi Fin"
#define STR15045_TEXT "Période de chauffe 2 Vendredi Début"
#define STR15046_TEXT "Période de chauffe 2 Vendredi Fin"
#define STR15047_TEXT "Période de chauffe 3 Vendredi Début"
#define STR15048_TEXT "Période de chauffe 3 Vendredi Fin"
#define STR15049_TEXT "Période de chauffe 1 Samedi Début"
#define STR15050_TEXT "Période de chauffe 1 Samedi Fin"
#define STR15051_TEXT "Période de chauffe 2 Samedi Début"
#define STR15052_TEXT "Période de chauffe 2 Samedi Fin"
#define STR15053_TEXT "Période de chauffe 3 Samedi Début"
#define STR15054_TEXT "Période de chauffe 3 Samedi Fin"
#define STR15055_TEXT "Période de chauffe 1 Dimanche Début"
#define STR15056_TEXT "Période de chauffe 1 Dimanche Fin"
#define STR15057_TEXT "Période de chauffe 2 Dimanche Début"
#define STR15058_TEXT "Période de chauffe 2 Dimanche Fin"
#define STR15059_TEXT "Période de chauffe 3 Dimanche Début"
#define STR15060_TEXT "Période de chauffe 3 Dimanche Fin"
#define STR15061_TEXT "Heure chaudière"
#define STR15062_TEXT "Modèle de sonde d'ambiance QAA"
#define STR15064_TEXT "Température cible"
#define STR15066_TEXT "Chauffage manuel"
#define STR15067_TEXT "Connexion interrompue"
