#define LANGUAGENAME_TEXT "France"
#define MENU_TEXT_CLOSED "Fermé"
#define MENU_TEXT_OPEN "Ouvert"
#define MENU_TEXT_HFK "Fonctions de chauffage"
#define MENU_TEXT_SNS "Capteurs"
#define MENU_TEXT_SN1 "Capteurs DS18B20"
#define MENU_TEXT_SN2 "Capteurs DHT22"
#define MENU_TEXT_CHK "Liste des paramètres spécifiques à l'appareil"
#define MENU_TEXT_DLG "Afficher le fichier journal"
#define MENU_TEXT_SLG "Fichier journal du tracé"
#define MENU_TEXT_CFG "Paramètres"
#define MENU_TEXT_URL "Commandes URL"
#define MENU_TEXT_HWT "Guide d’utilisation"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Oui"
#define MENU_TEXT_NO "Non"
#define MENU_TEXT_ON "Activé"
#define MENU_TEXT_OFF "Désactivé"
#define MENU_TEXT_NOQ "La liste des paramètres spécifiques à l'appareil n'est prise en charge que sur les systèmes basés sur BSB et LPB.<BR>Pour les appareils PPS, vous pouvez utiliser directement la catégorie correspondante.\r\n"
#define MENU_TEXT_QNC "BSB-LAN ne peut pas se connecter au système de chauffage. Veuillez vous assurer que l'adaptateur est connecté au chauffage et que le chauffage est allumé. Redémarrez ensuite BSB-LAN pour vous connecter au chauffage."
#define MENU_TEXT_QIN "Afin de créer une liste de paramètres spécifiques à l'appareil, veuillez cliquer sur 'Télécharger' ci-dessous.<BR>Si plusieurs contrôleurs sont connectés via LPB, vous <B>devez</B> connecter BSB-LAN via LPB, aussi, afin d'obtenir tous les paramètres de tous les appareils connectés !<BR>La création de ce fichier peut prendre plusieurs minutes et peut sembler caler surtout au début, <B>soyez patient !</B> \r\n <BR>Ensuite, indiquez-nous dans quelle langue vous souhaitez utiliser BSB-LAN et envoyez le fichier enregistré à bsb(ät)code-it.de.\r\nNous faisons de notre mieux pour créer une liste de paramètres spécifique à l'appareil et Renvoyez-le-nous dès que possible, mais après tout, il s'agit d'un projet de loisir, alors soyez indulgents avec nous.<BR><B>Ce processus ne doit généralement être effectué qu'une seule fois (et non à chaque mise à jour de BSB-LAN) ! </B><BR><BR>Alternativement, vous pouvez trouver le fichier BSB_LAN_custom_defs.h qui était utilisé dans les versions précédentes de BSB-LAN dans la version 2.2. Cependant, étant donné que cette liste de paramètres manque des centaines de paramètres provenant d'appareils plus récents et contient. beaucoup d'ambiguïtés et parfois aussi d'erreurs, son utilisation est <B>déconseillée</B> et ne doit se faire qu'après avoir soigneusement examiné les paramètres que vous souhaitez utiliser.<BR>"
#define MENU_TEXT_QDL "Télécharger"
#define MENU_TEXT_QSC "Recherche de périphériques..."
#define MENU_TEXT_QRT "Tester l’adresse de l’appareil"
#define MENU_TEXT_QFD "Adresse de l'appareil trouvée"
#define MENU_TEXT_QFA "La requête sur l'appareil a échoué"
#define MENU_TEXT_QRA "Exécution d'un test avec l'adresse du périphérique de destination"
#define MENU_TEXT_QST "Démarrer le test"
#define MENU_TEXT_QTE "Test terminé"
#define MENU_TEXT_QFE "Terminé"
#define MENU_TEXT_QFF "Déconnecté du broker MQTT, veuillez réessayer plus tard."
#define MENU_TEXT_TOC "Manuel"
#define MENU_TEXT_MAS "Création d'appareils via la découverte automatique MQTT..."
#define MENU_TEXT_MAR "Suppression de périphériques via la découverte automatique MQTT..."
#define MENU_TEXT_MOD "Modules installés"
#define MENU_TEXT_NVS "Vérification d'une version plus récente"
#define MENU_TEXT_NVA "Version plus récente trouvée"
#define MENU_TEXT_NVN "La version actuelle est à jour"
#define MENU_TEXT_NVW "Attention ! La nouvelle version peut contenir des modifications importantes qui nécessitent des changements de configuration. Veuillez lire attentivement le ChangeLog dans CHANGELOG.md !"
#define MENU_TEXT_SDF "Attention ! Cette installation BSB-LAN ne contient qu'un ensemble rudimentaire de paramètres. Pour utiliser l'ensemble complet des paramètres pris en charge par votre système de chauffage, veuillez générer une liste de paramètres spécifiques à l'appareil via la fonction de menu ci-dessus et flasher BSB-LAN encore une fois avec ce dossier."
#define MENU_LINK_TOC "https://docs.bsb-lan.de/fr/"
#define MENU_LINK_FAQ "https://docs.bsb-lan.de/fr/faq.html"
#define MENU_LINK_URL "https://docs.bsb-lan.de/fr/using.html"
#define MENU_DESC_HFK "Vous permet d'interroger ou de définir les paramètres de votre système de chauffage, triés en différentes catégories cliquables."
#define MENU_DESC_CFG "Affiche une liste d'options de configuration. Vous pouvez modifier la plupart d'entre elles en utilisant les commandes URL étendues."
#define MENU_DESC_URL "Affiche une liste de commandes étendues auxquelles vous pouvez accéder en les saisissant directement dans la ligne d'adresse du navigateur. Ces commandes sont également nécessaires pour relier BSB-LAN à tout système domotique tel que FHEM."
#define MENU_TEXT_VB1 "Affichage détaillé activé!"
#define MENU_TEXT_VB2 "Affichage détaillé désactivé!"
#define MENU_TEXT_VB3 "La sortie détaillée affecte à la fois la console série du mega2560 ainsi que (en option) l'enregistrement des données du bus sur la carte SD, cela peut donc remplir votre carte assez rapidement ! La sortie HTML reste inchangée."
#define MENU_TEXT_CLH "Cliquez ici"
#define MENU_TEXT_MQ1 "pour démarrer le processus de découverte automatique MQTT (cela peut prendre un certain temps)."
#define MENU_TEXT_MQ0 "pour supprimer les entrées de découverte automatique MQTT (cela peut prendre un certain temps)."

#define MENU_TEXT_ER1 "ERREUR : ligne de paramètre invalide !"
#define MENU_TEXT_ER2 "ERREUR : valeur de paramètre invalide !"
#define MENU_TEXT_ER3 "ERREUR : échec de la configuration !"
#define MENU_TEXT_ER4 "le paramètre est en lecture seule."
#define MENU_TEXT_ER5 "ERREUR : mauvais type !"
#define MENU_TEXT_ER8 "La protection globale en écriture est active dans les paramètres BSB-LAN."
#define MENU_TEXT_ER6 "ERREUR : ligne introuvable !"
#define MENU_TEXT_ER7 "ERREUR : broche GPIO protégée !"
#define MENU_TEXT_BST "Statistiques du chauffage"
#define MENU_TEXT_BRS "Temps de chauffe chaudière + ECS remis à zéro"
#define MENU_TEXT_24A "Moyennes 24h"
#define MENU_TEXT_24N "Nouveaux paramètres moyens"
#define MENU_TEXT_DTR " : le fichier a été supprimé et recréé."
#define MENU_TEXT_DLD "(chargement des données...)"
#define MENU_TEXT_DDO "Télécharger les données affichées"
#define MENU_TEXT_DTD "Télécharger toutes les données"
#define MENU_TEXT_DTF "Échec de la création du fichier datalog.txt !"
#define MENU_TEXT_DTO "Erreur à l'ouverture de datalog.txt !"
#define MENU_TEXT_RAM "Mémoire libre"
#define MENU_TEXT_BUS "Système de bus"
#define MENU_TEXT_BRW "Lecture/Ecriture"
#define MENU_TEXT_BRO "Lecture seule"
#define MENU_TEXT_OWP "Broches du bus 1-Wire"
#define MENU_TEXT_DHP "Broches du bus DHT22"
#define MENU_TEXT_EXP "Broches GPIO protégées"
#define MENU_TEXT_MAC "Adresse MAC"
#define MENU_TEXT_LIR "Les paramètres du journal seront maintenant enregistrés et le compteur d'intervalles de journal sera réinitialisé."
#define MENU_TEXT_LGP "Enregistrement des paramètres suivants chaque"
#define MENU_TEXT_SEC "secondes"
#define MENU_TEXT_BZ1 "Niveau d'exécution du graveur 1"
#define MENU_TEXT_BT1 "Cycles brûleur niveau 1"
#define MENU_TEXT_BZ2 "Niveau d'exécution du graveur 2"
#define MENU_TEXT_BT2 "Cycles brûleur niveau 2"
#define MENU_TEXT_TZ1 "Durée d'exécution ECS"
#define MENU_TEXT_TT1 "Cycles ECS"
#define MENU_TEXT_MXI "MAX! température actuelle"
#define MENU_TEXT_MXS "MAX! consigne de température"
#define MENU_TEXT_MXV "MAX! ouverture de la vanne"
#define MENU_TEXT_MXN "Aucune donnée MAX! reçue pour l'instant."
#define MENU_TEXT_BDT "Télégrammes de données BSB (indépendamment de l'intervalle)"
#define MENU_TEXT_BUT "Enregistrement des télégrammes de bus inconnus uniquement"
#define MENU_TEXT_UBT "Enregistrement des télégrammes de bus de diffusion inconnus uniquement"
#define MENU_TEXT_MMD "Mode données brutes"
#define MENU_TEXT_VBL "Affichage détaillé"
#define MENU_TEXT_AVT "Calcul des moyennes sur 24h pour les paramètres suivants"
#define MENU_TEXT_LBO "Journal des télégrammes de bus diffusés uniquement"
#define MENU_TEXT_LGI "Nouvel intervalle de journalisation"
#define MENU_TEXT_LGN "Nouveaux paramètres de journalisation"
#define MENU_TEXT_LOT "Journal des télégrammes"
#define MENU_TEXT_FSP "Espace libre dans le système de fichiers"
#define MENU_TEXT_CNV "Catégorie non disponible pour cet appareil cible."
#define MENU_TEXT_UPT "Temps de fonctionnement"
#define MENU_TEXT_VER "Version"
#define MENU_TEXT_MCU "Matériel"
#define MENU_TEXT_BYT "Octets"

#define STR_24A_TEXT "Moyenne 24h"
#define S_ERROR "Message d'erreur actuel"
#define S_MAINT "Signalisation de maintenance actuel"

#define ENUM_CAT_00_TEXT "Heure"
#define ENUM_CAT_06_TEXT "Progr. de commande horaire 1"
#define ENUM_CAT_07_TEXT "Progr. de commande horaire 2"
#define ENUM_CAT_08_TEXT "Progr. de commande horaire 3"
#define ENUM_CAT_09_TEXT "Programme horaire eau potable"
#define ENUM_CAT_0c_TEXT "Progr. de commande horaire 5"
#define ENUM_CAT_0e_TEXT "Programmes vacances CC1"
#define ENUM_CAT_0f_TEXT "Programmes vacances CC2"
#define ENUM_CAT_11_TEXT "Circuit de chauffe 1"
#define ENUM_CAT_14_TEXT "Circuit de chauffe 2"
#define ENUM_CAT_17_TEXT "Circuit de chauffe 3/P"
#define ENUM_CAT_1a_TEXT "Eau potable"
#define ENUM_CAT_22_TEXT "Chaudière"
#define ENUM_CAT_2b_TEXT "Solaire"
#define ENUM_CAT_2d_TEXT "Accumulateur tampon"
#define ENUM_CAT_2e_TEXT "Accumulateur eau potable"
#define ENUM_CAT_2f_TEXT "Charge directe Eau Potable"
#define ENUM_CAT_31_TEXT "Configuration"
#define ENUM_CAT_32_TEXT "LPB Bus"
#define ENUM_CAT_33_TEXT "Modbus"
#define ENUM_CAT_34_TEXT "Défaut"
#define ENUM_CAT_35_TEXT "Maintenance"
#define ENUM_CAT_39_TEXT "Etat"
#define ENUM_CAT_3c_TEXT "Diagnostic générateur"
#define ENUM_CAT_3d_TEXT "Diagnostic consommateurs"
#define ENUM_CAT_3f_TEXT "Coffret de sécurité"
#define STR516_TEXT "Valeurs par défaut prog. hor. CC1"
#define STR536_TEXT "Valeurs par défaut prog. hor. CC2"
#define STR556_TEXT "Valeurs par défaut prog. hor. CC3"
#define STR576_TEXT "Valeurs par défaut prog. hor. CC4"
#define STR648_TEXT "Niveau de fonct. pendant vacances CC1"
#define STR652_TEXT "Période de congés 1 CC2: premier jour"
#define STR653_TEXT "Période de congés 1 CC2: dernier jour"
#define STR658_TEXT "Niveau de fonct. pendant vacances CC2"
#define STR700_TEXT "Régime Circuit de chauffe 1"
#define STR701_TEXT "Bouton de présence (absence temporaire)"
#define STR710_TEXT "Consigne confort température ambiante CC1"
#define STR711_TEXT "Consigne confort température ambiante maximum CC1"
#define STR712_TEXT "Valeur de consigne réduite température ambiante CC1"
#define STR714_TEXT "Consigne horsgel température ambiante CC1"
#define STR720_TEXT "Pente de la courbe de chauffe 1"
#define STR721_TEXT "Translation de la courbe de chauffe"
#define STR726_TEXT "Adaptation courbe de chauffe CC1"
#define STR730_TEXT "Commutation été/hiver circuit de chauffe 1"
#define STR732_TEXT "Limite de chauffe journalière CC1"
#define STR740_TEXT "Limitation mini température de départ CC1"
#define STR741_TEXT "Limitation maxi température de départ CC1"
#define STR750_TEXT "Facteur d'influence température ambiante CC1"
#define STR760_TEXT "Limitation de température ambiante CC1"
#define STR770_TEXT "Surélév. cons. ambiance CC1 (chauff. accéléré)"
#define STR780_TEXT "Réduction rapide CC1"
#define STR790_TEXT "Optimis. heure d'enclenchement Avance maxi CC1"
#define STR791_TEXT "Optimis. heure de coupure, avance maxi CC1"
#define STR800_TEXT "Début relèvem. Consigne réduite TA CC1"
#define STR801_TEXT "Fin relèvement consigne réduite TA CC1"
#define STR850_TEXT "Fonction de séchage dalle"
#define STR851_TEXT "Consigne manuelle séchage chapes béton CC1"
#define STR884_TEXT "Allure pompe chaudière au point de conception"
#define STR885_TEXT "Pompe modulante TRM minimum"
#define STR886_TEXT "Température extérieure pour besoins calorifiques maxi"
#define STR887_TEXT "Consigne chaudière pour temp ext. Normalisée"
#define STR888_TEXT "Limite pour surélévation temp. De la régul. Dt"
#define STR894_TEXT "Delta départ/retour pour temp. Ext. Normalisée"
#define STR1000_TEXT "Régime circuit de chauffe 2"
#define STR1010_TEXT "Consigne de confort temp. ambiante CC2"
#define STR1012_TEXT "Valeur de consigne réduite temp. ambiante CC2"
#define STR1014_TEXT "Valeur de consigne hors-gel temp. ambiante CC2"
#define STR1020_TEXT "Pente de la courbe de chauffe 2"
#define STR1021_TEXT "Translation de la courbe de chauffe"
#define STR1026_TEXT "Adaptation courbe de chauffe CC2"
#define STR1030_TEXT "Commutation été/hiver circuit de chauffe 2"
#define STR1032_TEXT "Limite de chauffe journalière CC2"
#define STR1040_TEXT "Limitation mini température de départ CC2"
#define STR1041_TEXT "Limitation maxi température de départ CC2"
#define STR1050_TEXT "Facteur d'influence température ambiante CC2"
#define STR1060_TEXT "Limitation de température ambiante CC2"
#define STR1070_TEXT "Surélév. cons. ambiance CC2 (chauffage accéléré)"
#define STR1080_TEXT "Réduction rapide CC2"
#define STR1090_TEXT "Optimis. heure d'enclenchem. Avance maxi CC2"
#define STR1091_TEXT "Optimis. heure de coupure Avance maxi CC2"
#define STR1100_TEXT "Début rélèvem. Consigne réduite temp.amb. CC2"
#define STR1101_TEXT "Fin relèvement consigne réduite temp.amb. CC2"
#define STR1130_TEXT "Surélévation temp. mélangeur circuit de chauffe"
#define STR1134_TEXT "Durée de marche servomoteur circuit de chauffe"
#define STR1150_TEXT "Fonction de séchage dalle"
#define STR1151_TEXT "Consigne manuelle séchage chapes béton CC2"
#define STR1600_TEXT "Régime ECS"
#define STR1610_TEXT "Consigne nominale de température ECS"
#define STR1612_TEXT "Consigne réduite de température ECS"
#define STR1614_TEXT "Consigne réduite de température ECS maximum"
#define STR1620_TEXT "Libération ECS"
#define STR1640_TEXT "Fonction antilégionnelle"
#define STR1641_TEXT "Périodicité de la fonction anti-légionelles"
#define STR1642_TEXT "Fonction anti-légionelles Jour"
#define STR1644_TEXT "Heure de la fonction anti-légionnelles"
#define STR1645_TEXT "Consigne fonction anti-légionnelle"
#define STR1646_TEXT "Durée séjour sur consigne fonction légionelle"
#define STR1647_TEXT "Fonction. pompe circul .pendant fonction légion."
#define STR1660_TEXT "Libération de la pompe de circulation ECS"
#define STR1661_TEXT "Fonct. cyclique pompe de circulation ECS"
#define STR2201_TEXT "Blocage générateur"
#define STR2210_TEXT "Limitation mini de température de chaudière"
#define STR2212_TEXT "Limitation maxi de température de chaudière"
#define STR2440_TEXT "Degré modul. Maxi en mode chauffage"
#define STR2441_TEXT "Vitesse rotation ventil. maxi mode chauffage"
#define STR2442_TEXT "Puissance pendant tempo. Régulateur active"
#define STR2443_TEXT "Démar. Puissance si régul. Libéré av Ch-eau inst"
#define STR2451_TEXT "Temps de pause minimal du brûleur"
#define STR2452_TEXT "Diff. De rég. Max sans interrup pause mini"
#define STR2453_TEXT "Temporisation régulateur après mise en service"
#define STR2454_TEXT "Différentiel chaudière"
#define STR2455_TEXT "Différence de coupure mini chaudière"
#define STR2456_TEXT "Différence de coupure maxi chaudière"
#define STR2471_TEXT "Temporisation d'arrêt de la pompe"
#define STR2472_TEXT "Température retard à l'arrêt pompe ECS"
#define STR2521_TEXT "Température enclenchement antigel chaudière"
#define STR2522_TEXT "Température de coupure antigel chaudière"
#define STR3810_TEXT "Différence de température Marche solaire"
#define STR3811_TEXT "Différence de température Arrêt solaire"
#define STR3812_TEXT "Température de charge minimale"
#define STR3831_TEXT "Temps de marche min. de la pompe du collecteur"
#define STR3840_TEXT "Température anti-gel capteur solaire"
#define STR3850_TEXT "Température protection contre surchauffe collecteur"
#define STR3860_TEXT "Température d'évaporation caloporteur"
#define STR4721_TEXT "Différentiel blocage automatique du générateur"
#define STR4722_TEXT "Diff. temp. Tampon/CC jusqu'à libér. Producteur"
#define STR5019_TEXT "Elévation consigne p.recharge accumulateur"
#define STR5020_TEXT "Surélévation température de départ ECS"
#define STR5050_TEXT "Température de charge maxi ballon ECS"
#define STR5055_TEXT "Température min. refroidissem. adiab. Ballon ECS"
#define STR5100_TEXT "Allure pompe mini pour charge cont. ballon strat"
#define STR5020_TEXT "Surélévation température de départ ECS"
#define STR5400_TEXT "Consigne pour température préparation ECS"
#define STR5430_TEXT "Différentiel enclenchement mode ECS (sonde 1)"
#define STR5431_TEXT "Différentiel coupure mini mode ECS (sonde 1)"
#define STR5432_TEXT "Différentiel coupure maxi mode ECS (sonde 1)"
#define STR5433_TEXT "Différentiel enclenchement mode ECS (sonde 2)"
#define STR5434_TEXT "Différentiel coupure mini mode ECS (sonde 2)"
#define STR5435_TEXT "Différentiel coupure maxi mode ECS (sonde 2)"
#define STR5450_TEXT "Seuil de fin d'un tirage ECS pour ch-eau inst."
#define STR5451_TEXT "Seuil pour tirage ECS avec ch-ins en confort"
#define STR5452_TEXT "Seuil pour tirage ECS avec ch-ins en mode Ch."
#define STR5453_TEXT "Correction consigne régulation confort à 40°C"
#define STR5454_TEXT "Correction consigne régulation confort à 60°C"
#define STR5455_TEXT "Correction consigne régulation sortie à 40°C"
#define STR5456_TEXT "Correction consigne régulation sortie à 60°C"
#define STR5480_TEXT "Temps Confort ch-eau après tirage sans dem. Ch."
#define STR5481_TEXT "Temps de confort Ch-eau si dem. Ch. Active"
#define STR5482_TEXT "Durée FlowSwitch ECS fermé"
#define STR5483_TEXT "Durée FlowSwitch Confort ECS fermé"
#define STR5486_TEXT "Tempo régulateur si modul."
#define STR5487_TEXT "Arrêt ret. pompe en confort CHINS si brûl. HORS"
#define STR5488_TEXT "Arrêt ret. pompe en confort CHINS si brûl. HORS"
#define STR5701_TEXT "Type d'installation"
#define STR5710_TEXT "Circuit de chauffage 1"
#define STR5715_TEXT "Circuit de chauffage 2"
#define STR5732_TEXT "Durée arrêt pompe si changeover CH vers ECS"
#define STR5733_TEXT "Tempo. Arrêt pompe si changeover CH vers ECS"
#define STR5761_TEXT "Demandes de chauffage avec soutien par Q8"
#define STR5920_TEXT "Sortie programmable K2"
#define STR5921_TEXT "Défaut K2 sur K1"
#define STR5922_TEXT "Sortie fonction 1 Clip-In Relais"
#define STR5923_TEXT "Sortie fonction 2 Clip-In Relais"
#define STR5924_TEXT "Sortie fonction 3 Clip-In Relais"
#define STR5926_TEXT "Configuration sortie 1"
#define STR5927_TEXT "Configuration sortie 2"
#define STR5928_TEXT "Configuration sortie 3"
#define STR5950_TEXT "Entrée H1 sélection de fonction"
#define STR5957_TEXT "Fonction modem"
#define STR5970_TEXT "Configuration thermostat d'ambiance 1"
#define STR5971_TEXT "Configuration thermostat d'ambiance 2"
#define STR5973_TEXT "Fonction Entrée RelCl"
#define STR5975_TEXT "Limite température pour consigne prescrite ext."
#define STR5976_TEXT "Limite Inf. signal entrée pour demande ext."
#define STR6110_TEXT "Constante de temps du bâtiment"
#define STR6112_TEXT "Gradient modèle d'ambiance"
#define STR6120_TEXT "Hors-gel de l'installation"
#define STR6127_TEXT "Temps pour dégommage pompes / vanne dérivation"
#define STR6220_TEXT "Version du logiciel"
#define STR6225_TEXT "Famille d'appareil"
#define STR6226_TEXT "Variante d'appareil"
#define STR6227_TEXT "Version OV d'appareil"
#define STR6230_TEXT "Configuration du régulateur 0"
#define STR6240_TEXT "Configuration du régulateur 1"
#define STR6250_TEXT "Configuration du régulateur 2"
#define STR6260_TEXT "Configuration du régulateur 3"
#define STR6270_TEXT "Configuration du régulateur 4"
#define STR6300_TEXT "Configuration du régulateur 7"
#define STR6330_TEXT "Configuration du régulateur 10"
#define STR6604_TEXT "Sélection fonction Alimentation Bus"
#define STR6605_TEXT "Etat de l'alimentation Bus"
#define STR6625_TEXT "Affectation d'ECS"
#define STR6640_TEXT "Source de l'heure"
#define STR6705_TEXT "Code de diagnostic interne"
#define STR6706_TEXT "Valeur actuelle de la phase de dérangement"
#define STR6741_TEXT "Heure alarme température de départ CC2"
#define STR6823_TEXT "3ème valeur d'historique du code erreur Albatros"
#define STR6825_TEXT "Valeur histo. 3 du diagnostic de dérangement"
#define STR6826_TEXT "Valeur histo. 3 de la phase de dérangement"
#define STR6830_TEXT "Valeur histo. 4 du compteur codes de dérangement"
#define STR6833_TEXT "4ème valeur d'historique du code erreur Albatros"
#define STR6835_TEXT "Valeur histo. 4 du diagnostic de dérangement"
#define STR6836_TEXT "Valeur histo. 4 de la phase de dérangement"
#define STR6840_TEXT "Valeur histo. 5 du compteur codes de dérangement"
#define STR6843_TEXT "5ème valeur d'historique du code erreur Albatros"
#define STR6845_TEXT "Valeur histo. 5 du diagnostic de dérangement"
#define STR6846_TEXT "Valeur histo. 5 de la phase de dérangement"
#define STR7001_TEXT "Signalisation de maintenance"
#define STR7007_TEXT "Configuration / RAZ des messages de maintenance"
#define STR7010_TEXT "Message de maintenance - Acquitter"
#define STR7011_TEXT "Durée de répétition pour messages maintenance"
#define STR7040_TEXT "Heures de fonct. brûleur jusqu'à la maintenance"
#define STR7041_TEXT "Heures de fonct. depuis dernière maintenance"
#define STR7042_TEXT "Limite pour m. en serv. Depuis dernière maintenance"
#define STR7043_TEXT "Mises en service depuis dernière maintenance"
#define STR7044_TEXT "Limite des mois depuis la dernière maintenance"
#define STR7045_TEXT "Mois depuis dernière maintenance"
#define STR7050_TEXT "Limite vitesse rot. ventil. Pour message maintenance"
#define STR7051_TEXT "Signalisation maintenance courant ionisation"
#define STR8000_TEXT "Etat du circuit de chauffage 1"
#define STR8001_TEXT "Etat du circuit de chauffage 2"
#define STR8003_TEXT "Etat de l'ECS"
#define STR8005_TEXT "Etat de la chaudière"
#define STR8007_TEXT "Etat équipement solaire"
#define STR8310_TEXT "Température de chaudière"
#define STR8311_TEXT "Consigne de température de chaudière"
#define STR8314_TEXT "Température de retour"
#define STR8316_TEXT "Température actuelle gaz de fumée"
#define STR8324_TEXT "Vitesse actuelle du ventilateur"
#define STR8325_TEXT "Commande actuelle du ventilateur"
#define STR8326_TEXT "Puissance relative"
#define STR8328_TEXT "Affichage de régime coffret"
#define STR2730_TEXT "Valeur mesurée du courant d'ionisation"
#define STR8336_TEXT "Heures de fonctionnement"
#define STR8337_TEXT "Compteur de démarrages brûleur"
#define STR8338_TEXT "Heures de fonctionnement en mode chauffage"
#define STR8339_TEXT "Heures de fonctionnement en mode ECS"
#define STR8340_TEXT "Heures de fonctionnement en demande chaud ext."
#define STR8510_TEXT "Température mesurée capteur solaire 1 (B6)"
#define STR8530_TEXT "Heures de fonctionnement production solaire"
#define STR8700_TEXT "Température extérieure locale"
#define STR8703_TEXT "Température extérieure résultante"
#define STR8704_TEXT "Température extérieure mélangée"
#define STR8721_TEXT "Température ambiante"
#define STR8739_TEXT "Humidité ambiante 1"
#define STR8740_TEXT "Température ambiante 1"
#define STR8741_TEXT "Consigne actuelle de température Ambiante"
#define STR8743_TEXT "Température de départ circuit de chauffe 1"
#define STR8744_TEXT "Consigne de départ H1"
#define STR8750_TEXT "Vitesse pompe"
#define STR8770_TEXT "Température ambiante 2"
#define STR8771_TEXT "Consigne actuelle de température ambiante CC2"
#define STR8773_TEXT "Température de départ circuit de chauffe 2"
#define STR8774_TEXT "Consigne de départ H2"
#define STR8830_TEXT "Température mesurée ECS en haut (B3)"
#define STR8831_TEXT "Consigne actuelle de température ECS"
#define STR8836_TEXT "Température de charge ECS"
#define STR8950_TEXT "Signal de processus départ segment"
#define STR8952_TEXT "Signal de processus retour segment"
#define STR8980_TEXT "Température accumulateur mesurée partie haute (B4)"
#define STR9500_TEXT "Temps de préventilation"
#define STR9502_TEXT "Modulation de l'air dans la préventilation"
#define STR9504_TEXT "Vitesse ventilateur dans la préventilation"
#define STR9510_TEXT "Modulation d'air en charge d'allumage"
#define STR9512_TEXT "Vitesse de rotation ventil. en charge d'allumage"
#define STR9520_TEXT "Modulation d'air en charge partielle"
#define STR9522_TEXT "Modulation d'air en pleine charge"
#define STR9524_TEXT "Consigne vitesse rotation en charge partielle"
#define STR9527_TEXT "Consigne vitesse rotation ventil. Pleine charge"
#define STR9540_TEXT "Temps de post-ventilation"
#define STR9560_TEXT "Mod. Ventil. Pour charge balllon stratification"
#define STR9563_TEXT "Consigne ventil. Charge continue ballon stratif"
#define STR10100_TEXT "État du système"
#define STR10101_TEXT "INFO production d’ECS"
#define STR10102_TEXT "INFO chauffage 1 – en attente"
#define STR10103_TEXT "INFO chauffage 2 – en attente"
#define STR10104_TEXT "INFO chauffage 3/P – en attente"
#define STR10200_TEXT "Commande inconnue"
#define STR14081_TEXT "Durée actionneur ouverture/fermeture (convertisseur)"
#define STR14082_TEXT "Bande proportionnelle XP actionneur (convertisseur)"
#define STR14083_TEXT "Temps de réajustement TN actionneur (convertisseur)"
#define STR14084_TEXT "Surcharge consigne mélangeur/échangeur"
#define STR14085_TEXT "Limite max température départ commune"
#define STR14086_TEXT "Limite min température départ commune"
#define STR14087_TEXT "Demande de température via contact externe"
#define STR14088_TEXT "Priorité à la demande de chaleur externe"
#define STR14089_TEXT "Entrée de demande de chaleur DC 0..10 V"
#define STR15000_TEXT "Régime Circuit de chauffe 1"
#define STR15001_TEXT "Touche de présence"
#define STR15002_TEXT "Bouton rotatif"
#define STR15003_TEXT "Jours de vacances restants"
#define STR15004_TEXT "Consigne confort température ambiante CC1"
#define STR15005_TEXT "Valeur de consigne réduite température ambiante CC1"
#define STR15006_TEXT "Consigne horsgel température ambiante CC1"
#define STR15007_TEXT "Limitation maxi de température de chaudière"
#define STR15008_TEXT "Température ambiante"
#define STR15021_TEXT "Température mesurée ECS en haut (B3)"
#define STR15022_TEXT "Consigne réduite de température ECS"
#define STR15023_TEXT "Consigne nominale de température ECS"
#define STR15030_TEXT "Température extérieure locale"
#define STR15031_TEXT "Température extérieure mélangée"
#define STR15032_TEXT "Température de départ circuit de chauffe 1"
#define STR15033_TEXT "Consigne de départ H1"
#define STR15034_TEXT "Température départ après mélangeur"
#define STR15035_TEXT "Température cible"
#define STR15036_TEXT "Puissance relative"
#define STR15040_TEXT "Heure chaudière"
#define STR15043_TEXT "Chauffage manuel"
#define STR15045_TEXT "Connexion interrompue"
#define STR15046_TEXT "Modèle de sonde d'ambiance QAA"
#define STR15050_TEXT "Période de chauffe Lundi"
#define STR15056_TEXT "Période de chauffe Mardi"
#define STR15062_TEXT "Période de chauffe Mercredi"
#define STR15068_TEXT "Période de chauffe Jeudi"
#define STR15074_TEXT "Période de chauffe Vendredi"
#define STR15080_TEXT "Période de chauffe Samedi"
#define STR15086_TEXT "Période de chauffe Dimanche"
#define STR20100_TEXT "ID du capteur DHT22"
#define STR20101_TEXT "Température du capteur DHT22"
#define STR20102_TEXT "Humidité du capteur DHT22"
#define STR20103_TEXT "Humidité absolue du capteur DHT22"
#define STR20200_TEXT "ID du capteur BME280"
#define STR20201_TEXT "Température du capteur BME280"
#define STR20202_TEXT "Humidité du capteur BME280"
#define STR20203_TEXT "Pression du capteur BME280"
#define STR20204_TEXT "Altitude du capteur BME280"
#define STR20205_TEXT "Humidité absolue du capteur BME280"
#define STR20300_TEXT "ID du capteur DS18B20"
#define STR20301_TEXT "Température du capteur DS18B20"
#define STR20500_TEXT "ID du capteur MAX!"
#define STR20501_TEXT "Température actuelle du capteur MAX!"
#define STR20502_TEXT "Température cible du capteur MAX!"
#define STR20503_TEXT "Ouverture de la vanne du capteur MAX!"
#define STR20700_TEXT "Valeur personnalisée (flottant)"
#define STR20800_TEXT "Valeur personnalisée (entier long)"

#define STR99999_TEXT "Commande inconnue"
  
#define ENUM648_01_TEXT "Réduit"
#define ENUM700_00_TEXT "Hors-gel"
#define ENUM700_01_TEXT "Automatique"
#define ENUM700_03_TEXT "Confort"
#define ENUM701_00_TEXT "Retour au mode horaire"
#define ENUM701_01_TEXT "Réduit"
#define ENUM701_02_TEXT "Mode confort forcé"
#define ENUM8000_17_TEXT "Protection anti-gel"
#define ENUM8000_68_TEXT "Chauffage restreint, priorité ECS"
#define ENUM8000_72_TEXT "Chauffage mode confort"
#define ENUM8000_74_TEXT "Chauffage mode réduit"
#define ENUM8000_77_TEXT "Mode éco"
#define ENUM15000_02_TEXT MENU_TEXT_OFF

#define ENUM_CAT_40_TEXT "Personnalisé"
#define ENUM_CAT_41_TEXT "LMU64"
#define ENUM_CAT_42_TEXT "RVD/RVP"
#define ENUM_CAT_43_TEXT "Bus PPS"
#define ENUM_CAT_44_TEXT "Capteurs OneWire, DHT & MAX!"
#define ENUM_CAT_45_TEXT "Catégorie inconnue"

#define ENUM_PPS_MODE_PASSIVE_TEXT "Passif"
#define ENUM_PPS_MODE_QAA_TEXT "Comme unité ambiante"
#define ENUM_DEBUG_SERIAL_TEXT "Série"
#define ENUM_DEBUG_TELNET_TEXT "Telnet"
#define ENUM_MQTT_PLAIN_TEXT "Texte brut"
#define ENUM_MQTT_JSON_TEXT "JSON"
#define ENUM_MQTT_JSON2_TEXT "JSON enrichi"
#define ENUM_MQTT_UNITS_LOCALIZED_TEXT "Localisé"
#define ENUM_MQTT_UNITS_HOMEASSISTANT_TEXT "Home Assistant"
#define ENUM_MQTT_UNITS_NONE_TEXT "Aucune"

#define ENUM_WRITE_ENG_TEXT "Activé (standard)"
#define ENUM_WRITE_OEM_TEXT "Activé (complet)"

#define ENUM_LOGMODE_01_TEXT "Écriture sur carte SD"
#define ENUM_LOGMODE_02_TEXT "Calcul des moyennes sur 24h"
#define ENUM_LOGMODE_04_TEXT "Envoi au broker MQTT"
#define ENUM_LOGMODE_08_TEXT "Envoyer uniquement les paramètres au serveur MQTT"
#define ENUM_LOGMODE_10_TEXT "Envoyer comme messages UDP"

#define ENUM_LOG_DEST_00_TEXT "Carte SD"
#define ENUM_LOG_DEST_01_TEXT "Mémoire Flash interne"

#define ENUM_VERBOSE_00_TEXT "Désactivé"
#define ENUM_VERBOSE_01_TEXT "Activé"
#define ENUM_VERBOSE_02_TEXT "Développeur"

#define ENUM_NETWORK_TYPE_00_TEXT "LAN"
#define ENUM_NETWORK_TYPE_01_TEXT "Wi-Fi"

#define ENUM15000_00_TEXT "Automatique"
#define ENUM15000_01_TEXT "Manuel"
#define ENUM15044_00_02_TEXT "Mode auto : désactivé"
#define ENUM15044_02_02_TEXT "Mode auto : activé"
#define ENUM15044_00_08_TEXT "Pompe : activée"
#define ENUM15044_08_08_TEXT "Pompe : désactivée"
#define ENUM15044_00_10_TEXT "Contact H1 : ouvert"
#define ENUM15044_10_10_TEXT "Contact H1 : fermé"

#define ENUM_WEEKDAY_01_TEXT "Lundi"
#define ENUM_WEEKDAY_02_TEXT "Mardi"
#define ENUM_WEEKDAY_03_TEXT "Mercredi"
#define ENUM_WEEKDAY_04_TEXT "Jeudi"
#define ENUM_WEEKDAY_05_TEXT "Vendredi"
#define ENUM_WEEKDAY_06_TEXT "Samedi"
#define ENUM_WEEKDAY_07_TEXT "Dimanche"

#define EXTIF_HOME_TEXT "Accueil"
#define EXTIF_MANAGEMENT_TEXT "Gestion"
#define EXTIF_MONITOR_TEXT "Surveillance"
#define EXTIF_ABOUT_TEXT "À propos"
#define EXTIF_SAVELOAD_TEXT "Sauvegarder/Charger"
#define EXTIF_SETCLOCK_TEXT "Régler l’heure"
#define EXTIF_RESET_TEXT "Réinitialiser"
#define EXTIF_BACK_TEXT "Retour"
#define EXTIF_UPDATE_TEXT "Mettre à jour"
#define EXTIF_CANCEL_TEXT "Annuler"
#define EXTIF_SAVE_TEXT "Enregistrer"
#define EXTIF_CANTREADFILE_TEXT "Impossible de lire le fichier ! Code d’erreur : "
#define EXTIF_CATNOTEXIST_TEXT "Erreur : catégorie inexistante !"
#define EXTIF_NOTEXIST_TEXT "n’existe pas !"
#define EXTIF_FUNCNO_TEXT "Paramètre n°"
#define EXTIF_CATNO_TEXT "Catégorie n°"
#define EXTIF_CHANGEPARAM1_TEXT "Paramètre"
#define EXTIF_CHANGEPARAM2_TEXT "modifié en"
#define EXTIF_CHANGEPARAM3_TEXT ""
#define EXTIF_OK_TEXT "OK" 
#define EXTIF_FAILED_TEXT "Échec"
#define EXTIF_ERROR_TEXT "Erreur"
#define EXTIF_SETTIME_TEXT "Heure réglée sur"
#define EXTIF_JSONERROR_TEXT "Erreur : échec de l’analyse JSON."
#define EXTIF_ERROR404_TEXT "Erreur 404 : fichier non trouvé !"
#define EXTIF_ERRORREQUEST_TEXT "Erreur : requête AJAX échouée."
#define EXTIF_WARNEXIT_TEXT "Attention : quitter sans enregistrer. Êtes-vous sûr ?"
#define EXTIF_DOWNLOADCONF_TEXT "Télécharger la configuration système"
#define EXTIF_UPLOADCONF_TEXT "Téléverser la configuration sur le système"
#define EXTIF_DOWNLOADEXCL_TEXT "Créer et télécharger la liste d’exclusions"
#define EXTIF_ALLCAT_TEXT "Toutes les catégories"
#define EXTIF_STARTDATE_TEXT "Date de début"
#define EXTIF_ENDDATE_TEXT "Date de fin"

//WEBCONFIG
#define CF_USEEEPROM_TEXT "Lire la configuration depuis l’EEPROM"
#define CF_BUSTYPE_TEXT "Type de bus"
#define CF_OWN_ADDR_TEXT "Adresse locale"
#define CF_DEST_ADDR_TEXT "Adresse cible"
#define CF_PPS_WRITE_TEXT "PPS : Mode"
#define CF_QAA_TYPE_TEXT "PPS : Modèle QAA"
#define CF_LOGTELEGRAM_TEXT "Télégrammes du bus"
#define CF_LOGCURRVALUES_TEXT "Journalisation active"
#define CF_LOGCURRINTERVAL_TEXT "Intervalle de journalisation (secondes)"
#define CF_CALCULATION_TEXT "Calcul"
#define CF_PROGLIST_TEXT "Paramètres"
#define CF_DEVICES_TEXT "Appareils"
#define CF_NETWORK_TYPE_TEXT "Interface réseau"
#define CF_DHCP_TEXT "Utiliser DHCP"
#define CF_IPADDRESS_TEXT "Adresse IP statique"
#define CF_TRUSTEDIPADDRESS_TEXT "Adresse IP de confiance"
#define CF_MASK_TEXT "Masque de sous-réseau"
#define CF_GATEWAY_TEXT "Passerelle"
#define CF_DNS_TEXT "Serveur DNS"
#define CF_WWWPORT_TEXT "Port TCP"
#define CF_WIFI_SSID_TEXT "SSID Wi-Fi"
#define CF_WIFI_PASSWORD_TEXT "Mot de passe Wi-Fi"
#define CF_WEBSERVER_TEXT "Système de fichiers du serveur Web"
#define CF_PASSKEY_TEXT "Clé d’URL (passkey)"
#define CF_BASICAUTH_TEXT "Authentification HTTP"
#define CF_PINS_TEXT "Broches"
#define CF_USE_TEXT "Utiliser"
#define CF_MAX_IPADDRESS_TEXT "Adresse IP du Cube"
#define CF_WRITEMODE_TEXT "Accès en écriture (niveau)"
#define CF_MQTT_SERVER_TEXT "Serveur MQTT"
#define CF_MQTT_USERNAME_TEXT "Nom d’utilisateur"
#define CF_MQTT_PASSWORD_TEXT "Mot de passe"
#define CF_MQTT_TOPIC_TEXT "Préfixe de topic"
#define CF_MQTT_DEVICE_TEXT "ID de l’appareil"
#define CF_LOG_DEST_TEXT "Destination de stockage"
#define CF_LOGMODE_TEXT "Mode de journalisation"
#define CF_CHECKUPDATE_TEXT "Vérifier les mises à jour"
#define CF_MDNS_HOSTNAME_TEXT "Nom mDNS"
#define CF_NUM_TEXT "Capteurs"
#define CF_OTA_UPDATE_TEXT "Mise à jour OTA"
#define CF_SHOW_UNKNOWN_TEXT "Afficher les paramètres inconnus"
#define CF_RX_PIN_TEXT "Numéro de broche RX"
#define CF_TX_PIN_TEXT "Numéro de broche TX"
#define CF_CONFIG_LEVEL_TEXT "Afficher les réglages avancés"
#define CF_ENERGY_SAVE_TEXT "Mode économie d’énergie"

#define CAT_GENERAL_TEXT "Général"
#define CAT_IPV4_TEXT "Réseau"
#define CAT_MQTT_TEXT "MQTT"
#define CAT_BUS_TEXT "Bus"
#define CAT_IPWE_TEXT "IPWE"
#define CAT_DHTBUS_TEXT "DHT"
#define CAT_ONEWIREBUS_TEXT "OneWire"
#define CAT_DEBUG_TEXT "Débogage"
#define CAT_MAX_TEXT "MAX!"
#define CAT_LOGGING_TEXT "Journalisation"
#define CAT_24HAVG_TEXT "Moyennes sur 24h"
#define CAT_RGT_EMUL_TEXT "Émulation RGT"
#define CAT_BMEBUS_TEXT "Capteurs BME280"
