#define LANGUAGENAME_TEXT "Slovenščina"
#define ENUM_CAT_00_TEXT "Čas a dátum"
#define ENUM_CAT_06_TEXT "Časový program VO1"
#define ENUM_CAT_07_TEXT "Časový program VO2"
#define ENUM_CAT_08_TEXT "Časový prog. 3 / Čerp. VO"
#define ENUM_CAT_09_TEXT "Time switch program DHW"
#define ENUM_CAT_0c_TEXT "Časový program 5"
#define ENUM_CAT_0e_TEXT "Vyk. okruh 1 - prázdniny"
#define ENUM_CAT_0f_TEXT "Vyk. okruh 2 - prázdniny"
#define ENUM_CAT_11_TEXT "Vykurovací okruh 1"
#define ENUM_CAT_14_TEXT "Vykurovací okruh 2"
#define ENUM_CAT_17_TEXT "Vykurovací okruh 3"
#define ENUM_CAT_1a_TEXT "Teplá úžitková voda"
#define ENUM_CAT_22_TEXT "Kotol"
#define ENUM_CAT_2b_TEXT "Solár"
#define ENUM_CAT_2d_TEXT "Akumulačný zásobník"
#define ENUM_CAT_2e_TEXT "Zásobník TÚV"
#define ENUM_CAT_2f_TEXT "Priamy ohrev TÚV"
#define ENUM_CAT_31_TEXT "Konfigurácia"
#define ENUM_CAT_32_TEXT "LPB systém"
#define ENUM_CAT_33_TEXT "Modbus systém"
#define ENUM_CAT_34_TEXT "Chyba"
#define ENUM_CAT_35_TEXT "Údržba / servis"
#define ENUM_CAT_39_TEXT "Stav"
#define ENUM_CAT_3c_TEXT "Diagnstika zdroja"
#define ENUM_CAT_3d_TEXT "Diagnostika spotrebičov"
#define ENUM_CAT_3f_TEXT "Riadenie horáka"
#define STR516_TEXT "Standard values TSP heating circuit 1"
#define STR536_TEXT "Standard values TSP heating circuit 2 "
#define STR556_TEXT "Standard values TSP3"
#define STR576_TEXT "Standard values TSP 4"
#define STR648_TEXT "Úroveň režimu Prázdniny VO1"
#define STR652_TEXT "Prázdninová perióda 1 VO2: Prvý deň"
#define STR653_TEXT "Prázdninová perióda 1 VO2: Posledný deň"
#define STR658_TEXT "Úroveň režimu Prázdniny VO2"
#define STR700_TEXT "Druh režimu vykurovacieho okruhu 1"
#define STR710_TEXT "Žiadaná teplota priestoru Komfort VO1"
#define STR712_TEXT "Útlmová žiadaná teplota priestoru VO 1"
#define STR714_TEXT "Protimrazová žiadaná teplota priestoru VO 1"
#define STR720_TEXT "Strmosť vykurovacej krivky 1"
#define STR721_TEXT "Posunutie vyk. krivky"
#define STR726_TEXT "Heating curve adaptation heat circuit 1"
#define STR730_TEXT "Teplota prepnutia leto/zima VO 1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Flow temp min limitation heat circuit 1"
#define STR741_TEXT "Flow temp max limitation heat circuit 1"
#define STR750_TEXT "Room temp gain factor heat circuit 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Room temp setpoint boost HC1 (boost heating)"
#define STR780_TEXT "Quick setback heat circuit 1"
#define STR790_TEXT "Max. predstih optimalizácie času zapnutia VO1"
#define STR791_TEXT "Optimum stop control max forward shift HC1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Funkcia sušenia poteru"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Nominálne otáčky"
#define STR885_TEXT "Mod. čerp. - PWM min"
#define STR886_TEXT "Normálna vonk. tepl. -VT"
#define STR887_TEXT "T. prívodu pri norm. VT"
#define STR888_TEXT "dT faktor zvýšenia"
#define STR894_TEXT "dT tepl. spád pri norm. VT"
#define STR1000_TEXT "Druh režimu vykurovacieho okruhu 2"
#define STR1010_TEXT "Žiadaná teplota priestoru Komfort VO2"
#define STR1012_TEXT "Útlmová žiadaná teplota priestoru VO 2"
#define STR1014_TEXT "Protimrazová žiadaná teplota priestoru VO 2"
#define STR1020_TEXT "Strmosť vykurovacej krivky 2"
#define STR1021_TEXT "Posunutie vyk. krivky"
#define STR1026_TEXT "Heating curve adaptation heat circuit 2"
#define STR1030_TEXT "Teplota prepnutia leto/zima VO 2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Flow temp min limitation heat circuit 2"
#define STR1041_TEXT "Flow temp max limitation heat circuit 2"
#define STR1050_TEXT "Room temp gain factor heat circuit 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Room temp setpoint boost HC2 (boost heating)"
#define STR1080_TEXT "Quick setback heat circuit 2"
#define STR1090_TEXT "Max. predstih optimalizácie času zapnutia VO2"
#define STR1091_TEXT "Optimum stop control max forward shift HC2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Zmiešavač - prevýšenie"
#define STR1134_TEXT "Doba chodu pohonu"
#define STR1150_TEXT "Funkcia sušenia poteru"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "Druh prípravy TÚV"
#define STR1610_TEXT "Žiadaná komfortná teplota"
#define STR1612_TEXT "Žiadaná útlmová teplota"
#define STR1620_TEXT "Uvolnenie"
#define STR1640_TEXT "Ochrana proti Legionellám"
#define STR1641_TEXT "Ochr. proti Leg. priodicky"
#define STR1642_TEXT "Ochr. proti Leg. - pevný deň"
#define STR1644_TEXT "Čas ochr. proti Leg."
#define STR1645_TEXT "Teplota ochr. proti Leg."
#define STR1646_TEXT "Trvanie funkcie Legionela"
#define STR1647_TEXT "Ochr. proti Leg. - cirk. čerp."
#define STR1660_TEXT "Cirkulač. č. TÚV - uvolnenie"
#define STR1661_TEXT "Cyklovanie cirkulačného č."
#define STR2201_TEXT "Blokovanie zdroja tepla"
#define STR2210_TEXT "Žiad. hodn. Min"
#define STR2212_TEXT "Žiad. hodn. Max"
#define STR2440_TEXT "Ventilátor PWM vyk. Max"
#define STR2441_TEXT "Ventilátor - otáčky vyk Max"
#define STR2442_TEXT "Vent. PWM oneskorenie reg."
#define STR2443_TEXT "Ventil start PWM prietok ohr"
#define STR2451_TEXT "Minimálna doba kludu horáka"
#define STR2452_TEXT "Spín dif času Vyp horáka"
#define STR2453_TEXT "Trvanie oneskor. regulátora"
#define STR2454_TEXT "Spínacia diferencia kotla"
#define STR2455_TEXT "SD kotla off min"
#define STR2456_TEXT "SD kotla off max"
#define STR2471_TEXT "Čas dobehu čerpadla"
#define STR2472_TEXT "Čas dobehu čerpadla TÚV"
#define STR2521_TEXT "Teplota protimraz. Zap"
#define STR2522_TEXT "Teplota protimraz. Vyp"
#define STR3810_TEXT "Tep. Dif. Zap"
#define STR3811_TEXT "Tep. Dif. Vyp"
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Protimraz. ochr. kolektora"
#define STR3850_TEXT "Ochrana prehriatia kolektora"
#define STR3860_TEXT "Vyparovanie média"
#define STR4721_TEXT "Aut. blok. kotla - Spín Dif"
#define STR4722_TEXT "Tep. diferencia zásobník/VO"
#define STR5019_TEXT "Prevýšenie proti vybitiu zás"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Spínač prúdenia - čas konšt"
#define STR5483_TEXT "Spínač prúd. - čas Komfort"
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Hydraulická schéma"
#define STR5710_TEXT "Vykurovací okruh 1"
#define STR5715_TEXT "Vykurovací okruh 2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Napájacie čerpadlo Q8"
#define STR5920_TEXT "Reléový výstup LMU  K2"
#define STR5921_TEXT "Štandardne K2 na K1"
#define STR5922_TEXT "Relé 1 ReCI -  Clip-In"
#define STR5923_TEXT "Relé 2 ReCI -  Clip-In"
#define STR5924_TEXT "Relé 3 ReCI -  Clip-In"
#define STR5926_TEXT "Relé 1 SolCI - Clip-In"
#define STR5927_TEXT "Relé 2 SolCI - Clip-In"
#define STR5928_TEXT "Relé 3 SolCI - Clip-In"
#define STR5950_TEXT "Funkcia vstupu H1"
#define STR5957_TEXT "Modem"
#define STR5970_TEXT "Konfig. izbový termostat 1"
#define STR5971_TEXT "Konfig. izbový termostat 2"
#define STR5973_TEXT "Funkcia vstupu RelCI"
#define STR5975_TEXT "Ext hod. pož. T prípojn. Max"
#define STR5976_TEXT "Ext prednast. medzný výk."
#define STR6110_TEXT "Časová konštanta budovy"
#define STR6112_TEXT "Gradient modelu miestnosti"
#define STR6120_TEXT "Protimrazová ochrana zar."
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6220_TEXT "Softverová verzia"
#define STR6225_TEXT "Typ. rad zariadenia"
#define STR6226_TEXT "Verzia zariadenia"
#define STR6227_TEXT "Verzia adresára objektov"
#define STR6230_TEXT "ConfigContrl0"
#define STR6240_TEXT "ConfigContr1"
#define STR6250_TEXT "ConfigContr2"
#define STR6260_TEXT "ConfigContr3"
#define STR6270_TEXT "ConfigContr4"
#define STR6300_TEXT "ConfigContr7"
#define STR6330_TEXT "ConfigContr10"
#define STR6604_TEXT "Napájanie zbernice"
#define STR6605_TEXT "Indikácia napájania zbernice"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Režim hodín"
#define STR6705_TEXT "SW diagnostický kód"
#define STR6706_TEXT "Burn ctrl phase lockout pos"
#define STR6741_TEXT "Teplota vstupu 2 alarm"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "SW diagnostický kód 3"
#define STR6826_TEXT "Riadenie horáka fáza 3"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "SW diagnostický kód 4"
#define STR6836_TEXT "Riadenie horáka fáza 4"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "SW diagnostický kód 5"
#define STR6846_TEXT "Riadenie horáka fáza 5"
#define STR7001_TEXT "Hlásenie"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Hlásenie potvrdenia"
#define STR7011_TEXT "Čas opakovania hlásenia"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Otáčky ventilátora Ion prúd"
#define STR7051_TEXT "Hlásenie Ion prúd"
#define STR8000_TEXT "Stav vyk. okruhu 1"
#define STR8001_TEXT "Stav vyk. okruhu 2"
#define STR8003_TEXT "Stav TÚV"
#define STR8005_TEXT "Stav kotla"
#define STR8007_TEXT "Stav soláru"
#define STR8310_TEXT "Teplota kotla"
#define STR8311_TEXT "Žiadaná teplota kotla"
#define STR8314_TEXT "Teplota spiatočky kotla"
#define STR8316_TEXT "Teplota spalín"
#define STR8324_TEXT "Otáčky ventilátora"
#define STR8325_TEXT "Akt riad. ventilátora"
#define STR8326_TEXT "Relatívny výkon"
#define STR8328_TEXT "Ind. stavu riadenia horáka"
#define STR2730_TEXT "Ionizačný prúd"
#define STR8336_TEXT "Počet hodín prevádzky"
#define STR8337_TEXT "Počet štartov horáka"
#define STR8338_TEXT "Odbehnuté hodiny vyk. režim"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Odbehnuté hodiny vyk. zón"
#define STR8510_TEXT "Teplota kolektora 1"
#define STR8530_TEXT "Počet hod. solárneho zisku"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Tlmená vonkajšia teplota"
#define STR8704_TEXT "Kombinovaná vonkajšia T"
#define STR8739_TEXT "Okolitá vlhkosť 1 aktuálna hodnota"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Teplota vstupu 1"
#define STR8744_TEXT "Žiadaná teplota vstupu H1"
#define STR8750_TEXT "Žiadaná hod. mod. čerpadla"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Žiadaná priestorová T 2"
#define STR8773_TEXT "Teplota vstupu 2"
#define STR8774_TEXT "Žiadaná teplota vstupu H2"
#define STR8830_TEXT "Teplota 1 TÚV"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "Nabíjacia teplota TÚV"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Aku zásobník teplota 1"
#define STR9500_TEXT "Čas prevetrávania"
#define STR9502_TEXT "Riad. vent. pri prevetrávaní"
#define STR9504_TEXT "Žiad. otáčky prevetrávania"
#define STR9510_TEXT "Riad. vent. pri zapalovaní"
#define STR9512_TEXT "Žiadané ot. pri zapalovaní"
#define STR9520_TEXT "Riad. vent. pri min výkone"
#define STR9522_TEXT "Riad. vent. pri max výkone"
#define STR9524_TEXT "Žiadané ot. pri min výkone"
#define STR9527_TEXT "Žiadané ot. pri max výkone"
#define STR9540_TEXT "Čas prevetrávania"
#define STR9560_TEXT "Riad. vent. pri max prietoku"
#define STR9563_TEXT "Žiadané ot. pri max prietoku"
