#define LANGUAGENAME_TEXT "Portugues"
#define MENU_TEXT_NO "Não"
#define MENU_TEXT_YES "Sim"
#define MENU_TEXT_OFF "Desligado"
#define MENU_TEXT_ON "Ligado"
#define MENU_TEXT_OPEN "Aberto"
#define MENU_TEXT_CLOSE "Fechado"