#define LANGUAGENAME_TEXT "Deutsch"
#define UNIT_METER_TEXT "m"
#define UNIT_MONTHS_TEXT "Monate"
#define UNIT_DAYS_TEXT "Tage"
#define UNIT_HOUR_TEXT "h"
#define UNIT_MIN_TEXT "min"
#define UNIT_SEC_TEXT "s"
#define UNIT_MSEC_TEXT "ms"
#define UNIT_DEG_TEXT "°C"
#define UNIT_PERC_TEXT "%"
#define UNIT_RPM_TEXT "U/min"
#define UNIT_WATT_TEXT "W"
#define UNIT_KW_TEXT "kW"
#define UNIT_KWH_TEXT "kWh"
#define UNIT_KWHM3_TEXT "kWh/m³"
#define UNIT_CURR_TEXT "µA"
#define UNIT_BAR_TEXT "bar"
#define UNIT_VOLT_TEXT "V"
#define UNIT_GRADIENT_TEXT "min/K"
#define UNIT_GRADIENTKS_TEXT "K/s"
#define UNIT_INTEGRAL_TEXT "Kmin"
#define UNIT_TEMP_PER_MIN_TEXT "°C/min"
#define UNIT_CEL_MIN_TEXT "°Cmin"
#define UNIT_LITER_TEXT "l"
#define UNIT_AMP_TEXT "A"
#define UNIT_LITERPERHOUR_TEXT "l/h"
#define UNIT_LITERPERMIN_TEXT "l/min"
#define UNIT_GR_PER_CUBM_TEXT "g/m³"
#define UNIT_HPA_TEXT "hPa"
#define UNIT_PPM_TEXT "ppm"
#define UNIT_CM_TEXT "m³"
#define UNIT_HERTZ_TEXT "Hz"
#define UNIT_M3H_TEXT "m³/h"
#define UNIT_MWH_TEXT "MW/h"

#define MENU_TEXT_HFK "Heizungsfunktionen"
#define MENU_TEXT_SNS "Sensoren"
#define MENU_TEXT_SN1 "DS18B20 Sensoren"
#define MENU_TEXT_SN2 "DHT22 Sensoren"
#define MENU_TEXT_CHK "Reglerspezifische Parameterliste"
#define MENU_TEXT_DLG "Ausgabe Logdatei"
#define MENU_TEXT_SLG "Zeichne Logdatei"
#define MENU_TEXT_CFG "Einstellungen"
#define MENU_TEXT_URL "URL-Befehle"
#define MENU_TEXT_HWT "HowTo"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Ja"
#define MENU_TEXT_NO "Nein"
#define MENU_TEXT_ON "Ein"
#define MENU_TEXT_OFF "Aus"
#define MENU_TEXT_OPEN "Offen"
#define MENU_TEXT_CLOSE "Geschlossen"
#define MENU_DESC_HFK "Hiermit können Sie die Funktionen Ihres Heizungssystems abfragen bzw. steuern. Die einzelnen Parameter sind in entsprechende Kategorien aufgeteilt, die Sie anklicken können."
#define MENU_DESC_CFG "Hier sehen Sie, mit welchen Werten BSB-LAN konfiguriert ist. Eine Änderung dieser Parameter ist über die erweiterten URL-Befehle möglich."
#define MENU_DESC_URL "Zeigt Ihnen eine Übersicht der Befehle an, die Sie über die direkte Eingabe in der Adresszeile des Browsers absenden können. Diese Befehle sind auch für die Anbindung an Hausautomations-Systeme wie FHEM nötig."
#define MENU_TEXT_VB1 "Verbositätsmodus aktiviert!"
#define MENU_TEXT_VB2 "Verbositätsmodus deaktiviert!"
#define MENU_TEXT_VB3 "Der Verbositäts-Modus betrifft sowohl die serielle Konsole des Arduino Mega2560 als auch (optional) das Loggen der Bus-Daten auf die microSD-Karte, so dass die Karte u.U. sehr schnell voll wird! Die html-Ausgabe bleibt unverändert."
#define MENU_TEXT_CLH "Hier klicken"
#define MENU_TEXT_MQ1 "um den MQTT Auto Discovery Prozess zu starten (dies kann etwas dauern)."
#define MENU_TEXT_MQ0 "um die MQTT Auto Discovery Einträge zu entfernen (dies kann etwas dauern)."

#define MENU_TEXT_ER1 "FEHLER: Ungültiger Parameter!"
#define MENU_TEXT_ER2 "FEHLER: Ungültiger Wert!"
#define MENU_TEXT_ER3 "FEHLER: Setzen fehlgeschlagen!"
#define MENU_TEXT_ER4 "Parameter ist nur lesbar."
#define MENU_TEXT_ER8 "Systemweiter Schreibschutz ist in den BSB-LAN-Einstellungen aktiv."
#define MENU_TEXT_ER5 "FEHLER: Falscher Typ!"
#define MENU_TEXT_ER6 "FEHLER: Zeile nicht gefunden!"
#define MENU_TEXT_ER7 "FEHLER: Geschützter GPIO Pin!"
#define MENU_TEXT_BST "Brennerstatistik"
#define MENU_TEXT_BRS "Heizkessel- und TWW-Laufzeit auf null gesetzt"
#define MENU_TEXT_24A "24h Durchschnittswerte"
#define MENU_TEXT_24N "Neue Durchschnitts-Parameter"
#define MENU_TEXT_DTR ": Datei wurde entfernt und neu generiert."
#define MENU_TEXT_DLD "(Daten werden geladen...)"
#define MENU_TEXT_DDO "Angezeigte Daten herunterladen"
#define MENU_TEXT_DTD "Daten vollständig herunterladen"
#define MENU_TEXT_DTF "Fehler beim Erstellen der Datei datalog.txt!"
#define MENU_TEXT_DTO "Fehler beim Öffnen der Datei datalog.txt!"
#define MENU_TEXT_RAM "Freier Speicher"
#define MENU_TEXT_BUS "Bus-System"
#define MENU_TEXT_BRW "Lesen/Schreiben"
#define MENU_TEXT_BRO "Nur Lesen"
#define MENU_TEXT_OWP "1-Wire Bus Pins"
#define MENU_TEXT_DHP "DHT22 Bus Pins"
#define MENU_TEXT_EXP "Gesperrte GPIO Pins"
#define MENU_TEXT_MAC "MAC-Adresse"
#define MENU_TEXT_LIR "Log-Parameter werden nun geloggt und der Log-Intervall-Zähler wird zurückgesetzt."
#define MENU_TEXT_LGP "Loggen der folgenden Parameter alle"
#define MENU_TEXT_SEC "Sekunden"
#define MENU_TEXT_BZ1 "Brennerlaufzeit Stufe 1"
#define MENU_TEXT_BT1 "Brennertakte Stufe 1"
#define MENU_TEXT_BZ2 "Brennerlaufzeit Stufe 2"
#define MENU_TEXT_BT2 "Brennertakte Stufe 2"
#define MENU_TEXT_TZ1 "TWW-Laufzeit"
#define MENU_TEXT_TT1 "TWW-Takte"
#define MENU_TEXT_MXI "MAX!-Ist-Temperatur"
#define MENU_TEXT_MXS "MAX!-Soll-Temperatur"
#define MENU_TEXT_MXV "MAX!-Ventilöffnung"
#define MENU_TEXT_MXN "Noch keine MAX!-Daten empfangen."
#define MENU_TEXT_BDT "BSB-Datentelegramme (unabhängig vom Intervall)"
#define MENU_TEXT_LAT "Alle Bus-Telegramme loggen"
#define MENU_TEXT_BUT "Nur unbekannte Bus-Telegramme loggen"
#define MENU_TEXT_UBT "Nur unbekannte Broadcast Bus-Telegramme loggen"
#define MENU_TEXT_MMD "Rohdaten-Modus"
#define MENU_TEXT_MAS "Erzeuge Geräte über MQTT Auto Discovery..."
#define MENU_TEXT_MAR "Entferne Geräte über MQTT Auto Discovery..."
#define MENU_TEXT_VBL "Verbositätsmodus"
#define MENU_TEXT_AVT "Berechnung von 24h-Mittelwerten für die folgenden Parameter"
#define MENU_TEXT_LBO "Nur Broadcast Bus-Telegramme loggen"
#define MENU_TEXT_LGI "Neues Logging-Intervall"
#define MENU_TEXT_LGN "Neue Logging-Parameter"
#define MENU_TEXT_NOQ "Die Erstellung der reglerspezifischen Parameterliste wird nur bei BSB- und LPB-Systemen unterstützt.<BR>Für PPS-Geräte kann direkt die entsprechende Kategorie verwendet werden.\r\n"
#define MENU_TEXT_QNC "BSB-LAN kann keine Verbindung zum Heizungs-Regler aufbauen. Bitte sicherstellen, dass der Adapter mit dem Regler verbunden ist und die Heizung angeschaltet ist. Dann BSB-LAN neu starten, um die Verbindung herzustellen."
#define MENU_TEXT_QIN "Zur Erstellung der reglerspezifischen Parameterliste bitte unten auf 'Download' klicken.<BR>Wenn mehrere Regler im LPB-Verbund vorhanden sind, dann diesen Abruf <B>nur dann durchführen</B>, wenn auch BSB-LAN über LPB angeschlossen ist!<BR>Die Erstellung kann mehrere Minuten dauern und gerade am Anfang auch vermeintlich pausieren - <B>bitte warten!</B> \r\n<BR>Danach die ausgegebene Datei an bsb(ät)code-it.de schicken.\r\nWir können daraus dann die passende Datei 'BSB_LAN_custom_defs.h' erstellen und bemühen uns, diese dann zeitnah zurück zu schicken.<BR><B>Dieser Prozess muss i.d.R. nur einmal (und nicht bei jedem BSB-LAN Update) gemacht werden!</B><BR><BR>Alternativ kann die Datei 'BSB_LAN_custom_defs.h', die in den vorherigen Versionen verwendet wurde, als Teil der Release-Version 2.2 heruntergeladen werden. Den früheren allgemeinen Parameterlisten fehlen jedoch Hunderte von Parametern - insbesondere von neueren Reglern. Darüber hinaus beinhalten sie eine Vielzahl von Ungenauigkeiten und teilweise auch Fehlern, weswegen wir den Einsatz dieser früheren Parameterliste ausdrücklich <B>nicht mehr empfehlen!</B><BR>"
#define MENU_TEXT_QDL "Download"
#define MENU_TEXT_QSC "Scanne nach Geräten"
#define MENU_TEXT_QFD "Geräteadresse gefunden"
#define MENU_TEXT_QFA "Geräteabfrage fehlgeschlagen"
#define MENU_TEXT_QRT "Teste Geräteadresse"
#define MENU_TEXT_QST "Starte Test"
#define MENU_TEXT_QTE "Test beendet"
#define MENU_TEXT_QFE "Fertig"
#define MENU_TEXT_QFF "Nicht mit dem MQTT-Broker verbunden, bitte später erneut versuchen."
#define MENU_TEXT_TOC "Handbuch"
#define MENU_TEXT_UPT "Uptime"
#define MENU_TEXT_VER "Version"
#define MENU_TEXT_MCU "Hardware"
#define MENU_TEXT_BYT "Bytes"
#define MENU_TEXT_MOD "Installierte Module"
#define MENU_TEXT_NVS "Überprüfe auf neuere Version"
#define MENU_TEXT_NVA "Neuere Version gefunden"
#define MENU_TEXT_NVN "Installierte Version ist aktuell."
#define MENU_TEXT_NVW "Achtung! Neue Version kann Änderungen enthalten, die Anpassungen erforderlich machen. Bitte das ChangeLog in der Datei CHANGELOG.md lesen!"
#define MENU_TEXT_SDF "Achtung! Diese BSB-LAN Installation ist nur mit einem rudimentären Satz an Parametern ausgestattet. Um den vollen Parameterumfang nutzen zu können, muss über den entsprechenden Menüpunkt eine gerätespezifische Parameterliste erstellt und dann erneut geflasht werden."
#define MENU_LINK_TOC "https://docs.bsb-lan.de/de/"
#define MENU_LINK_FAQ "https://docs.bsb-lan.de/de/faq.html"
#define MENU_LINK_URL "https://docs.bsb-lan.de/de/using.html"
#define MENU_TEXT_LOT "Telegramme loggen"
#define MENU_TEXT_FSP "Freier Speicher im Dateisystem"
#define MENU_TEXT_CNV "Kategorie nicht für dieses Zielgerät verfügbar."

#define STR_24A_TEXT "24h Durchschnittswert"

//WEBCONFIG
#define CF_USEEEPROM_TEXT "Konfiguration aus EEPROM lesen"
#define CF_BUSTYPE_TEXT "Typ"
#define CF_OWN_ADDR_TEXT "Eigene Adresse"
#define CF_DEST_ADDR_TEXT "Zieladresse"
#define CF_PPS_WRITE_TEXT "PPS: Modus"
#define CF_QAA_TYPE_TEXT "PPS: QAA Modell"
#define CF_LOGTELEGRAM_TEXT "Bustelegramme"
#define CF_LOGCURRVALUES_TEXT "Logging aktiv"
#define CF_LOGCURRINTERVAL_TEXT "Logintervall (Sekunden)"
#define CF_CALCULATION_TEXT "Berechnung"
#define CF_PROGLIST_TEXT "Parameter"
#define CF_DEVICES_TEXT "Geräte"
#define CF_NETWORK_TYPE_TEXT "Netzwerkgerät"
#define CF_DHCP_TEXT "DHCP verwenden"
#define CF_IPADDRESS_TEXT "Statische IP-Adresse"
#define CF_TRUSTEDIPADDRESS_TEXT "Vertrauenswürdige IP-Adresse"
#define CF_MASK_TEXT "Subnetzmaske"
#define CF_GATEWAY_TEXT "Gateway"
#define CF_DNS_TEXT "DNS Server"
#define CF_WWWPORT_TEXT "TCP Port"
#define CF_WIFI_SSID_TEXT "WLAN SSID"
#define CF_WIFI_PASSWORD_TEXT "WLAN Passwort"
#define CF_WEBSERVER_TEXT "Webserver Dateisystem"
#define CF_PASSKEY_TEXT "URL Passkey"
#define CF_BASICAUTH_TEXT "HTTP-Authentifizierung"
#define CF_PINS_TEXT "Pins"
#define CF_USE_TEXT "Verwenden"
#define CF_MAX_IPADDRESS_TEXT "IP-Adresse Cube"
#define CF_WRITEMODE_TEXT "Schreibzugriff (Ebene)"
#define CF_MQTT_SERVER_TEXT "Broker Server"
#define CF_MQTT_USERNAME_TEXT "Username"
#define CF_MQTT_PASSWORD_TEXT "Passwort"
#define CF_MQTT_TOPIC_TEXT "Topic Präfix"
#define CF_MQTT_DEVICE_TEXT "Geräte ID"
#define CF_LOG_DEST_TEXT "Speicherziel"
#define CF_LOGMODE_TEXT "Log-Modus"
#define CF_CHECKUPDATE_TEXT "Auf Updates überprüfen"
#define CF_MDNS_HOSTNAME_TEXT "mDNS Hostname"
#define CF_NUM_TEXT "Sensoren"
#define CF_OTA_UPDATE_TEXT "OTA Update"
#define CF_SHOW_UNKNOWN_TEXT "Unbekannte Parameter anzeigen"
#define CF_RX_PIN_TEXT "RX Pin Nummer"
#define CF_TX_PIN_TEXT "TX Pin Nummer"
#define CF_CONFIG_LEVEL_TEXT "Erweiterte Einstellungen anzeigen"
#define CF_ENERGY_SAVE_TEXT "Energiesparmodus"

#define CAT_GENERAL_TEXT "Generell"
#define CAT_IPV4_TEXT "Netzwerk"
#define CAT_MQTT_TEXT "MQTT"
#define CAT_BUS_TEXT "Bus"
#define CAT_IPWE_TEXT "IPWE"
#define CAT_DHTBUS_TEXT "DHT"
#define CAT_ONEWIREBUS_TEXT "OneWire"
#define CAT_DEBUG_TEXT "Debugging"
#define CAT_MAX_TEXT "MAX!"
#define CAT_LOGGING_TEXT "Logging"
#define CAT_24HAVG_TEXT "24h-Durchschnittswerte"
#define CAT_RGT_EMUL_TEXT "RGT Emulation"
#define CAT_BMEBUS_TEXT "BME280 sensors"

#define STR10100_TEXT "Systemstatus"
#define STR10101_TEXT "INFO Trinkwasserbereitung"
#define STR10102_TEXT "INFO HK1 - TBD"
#define STR10103_TEXT "INFO HK2 - TBD"
#define STR10104_TEXT "INFO HK3/P - TBD"
#define STR10200_TEXT "Unknown command"

#define STR15000_TEXT "Betriebsart"
#define STR15001_TEXT "Präsenztaste"
#define STR15002_TEXT "Position Drehknopf"
#define STR15003_TEXT "Verbleibende Ferientage"
#define STR15004_TEXT "Komfortsollwert"
#define STR15005_TEXT "Reduziertsollwert"
#define STR15006_TEXT "Frostschutzsollwert"
#define STR15007_TEXT "Sollwert Maximum"
#define STR15008_TEXT "Raumtemperatur"
#define STR15020_TEXT "Trinkwasserladung"
#define STR15021_TEXT "Trinkwassertemperatur 1"
#define STR15022_TEXT "TWW Reduziertsollwert"
#define STR15023_TEXT "TWW Nennsollwert"
#define STR15030_TEXT "Außentemperatur"
#define STR15031_TEXT "Außentemperatur gemischt"
#define STR15032_TEXT "Vorlauftemperatur 1"
#define STR15033_TEXT "Vorlaufsollwert 1"
#define STR15034_TEXT "Mischervorlauftemperatur"
#define STR15035_TEXT "Zieltemperatur"
#define STR15036_TEXT "Brennermodulation"
#define STR15040_TEXT "Uhrzeit"
#define STR15041_TEXT "Wochentag"
#define STR15042_TEXT "Nächstes Schaltprogramm"
#define STR15043_TEXT "Manuelles Heizen"
#define STR15044_TEXT "Status Brenner"
#define STR15045_TEXT "Verbindung unterbrochen"
#define STR15046_TEXT "QAA Modell"
#define STR15050_TEXT "Zeitschaltprogramm Montag"
#define STR15056_TEXT "Zeitschaltprogramm Dienstag"
#define STR15062_TEXT "Zeitschaltprogramm Mittwoch"
#define STR15068_TEXT "Zeitschaltprogramm Donnerstag"
#define STR15074_TEXT "Zeitschaltprogramm Freitag"
#define STR15080_TEXT "Zeitschaltprogramm Samstag"
#define STR15086_TEXT "Zeitschaltprogramm Sonntag"
#define STR20100_TEXT "DHT22 Sensor ID"
#define STR20101_TEXT "DHT22 Sensor Temperatur"
#define STR20102_TEXT "DHT22 Sensor Luftfeuchtigkeit"
#define STR20103_TEXT "DHT22 Sensor Abs Luftfeuchtigkeit"
#define STR20200_TEXT "BME280 Sensor ID"
#define STR20201_TEXT "BME280 Sensor Temperatur"
#define STR20202_TEXT "BME280 Sensor Luftfeuchtigkeit"
#define STR20203_TEXT "BME280 Sensor Pressure"
#define STR20204_TEXT "BME280 Sensor Altitude"
#define STR20205_TEXT "BME280 Sensor Abs Luftfeuchtigkeit"
#define STR20300_TEXT "DS18B20 Sensor ID"
#define STR20301_TEXT "DS18B20 Sensor Temperatur"
#define STR20500_TEXT "MAX! Sensor ID"
#define STR20501_TEXT "MAX! Sensor Ist Temperatur"
#define STR20502_TEXT "MAX! Sensor Soll-Temperatur"
#define STR20503_TEXT "MAX! Sensor Ventilöffnung"
#define STR20700_TEXT "custom_float"
#define STR20800_TEXT "custom_long"

#define STR99999_TEXT "UNKNOWN command code"

#define ENUM_CAT_40_TEXT "Benutzerdefiniert"
#define ENUM_CAT_41_TEXT "LMU64"
#define ENUM_CAT_42_TEXT "RVD/RVP"
#define ENUM_CAT_43_TEXT "PPS-Bus"
#define ENUM_CAT_44_TEXT "One Wire, DHT & MAX! Sensors"
#define ENUM_CAT_45_TEXT "unbekannte Kategorie"

#define ENUM_PPS_MODE_PASSIVE_TEXT "Passiv"
#define ENUM_PPS_MODE_QAA_TEXT "Als Raumgerät"
#define ENUM_DEBUG_SERIAL_TEXT "Serial"
#define ENUM_DEBUG_TELNET_TEXT "Telnet"
#define ENUM_MQTT_PLAIN_TEXT "Plain text"
#define ENUM_MQTT_JSON_TEXT "JSON"
#define ENUM_MQTT_JSON2_TEXT "Rich JSON"

#define ENUM_WRITE_ENG_TEXT "Ein (Standard)"
#define ENUM_WRITE_OEM_TEXT "Ein (Komplett)"

#define ENUM_LOGMODE_01_TEXT "Auf SD-Karte schreiben"
#define ENUM_LOGMODE_02_TEXT "24-Stunden-Durchschnittswerte berechnen"
#define ENUM_LOGMODE_04_TEXT "An MQTT-Broker senden"
#define ENUM_LOGMODE_08_TEXT "Nur Log-Parameter an MQTT senden"
#define ENUM_LOGMODE_10_TEXT "Als UDP-Nachrichten senden"

#define ENUM_LOG_DEST_00_TEXT "SD-Karte"
#define ENUM_LOG_DEST_01_TEXT "Interner Flash-Speicher"
#define ENUM_VERBOSE_00_TEXT MENU_TEXT_OFF
#define ENUM_VERBOSE_01_TEXT MENU_TEXT_ON
#define ENUM_VERBOSE_02_TEXT "Entwickler"


#define ENUM_NETWORK_TYPE_00_TEXT "LAN"
#define ENUM_NETWORK_TYPE_01_TEXT "WiFi"

#define ENUM648_01_TEXT "Reduziert"
#define ENUM700_03_TEXT "Komfort"

#define STR14081_TEXT "Laufzeit Auf/Zu Antrieb Umformer"
#define STR14082_TEXT "P-Band XP Antrieb Umformer"
#define STR14083_TEXT "Nachstellzeit TN Antrieb Umformer"
#define STR14084_TEXT "Überhöhung Sollwert Mischer/Wärmetauscher"
#define STR14085_TEXT "Gemeinsame Vorlauftemperatur Maximalbegrenzung"
#define STR14086_TEXT "Gemeinsame Vorlauftemperatur Minimalbegrenzung"
#define STR14087_TEXT "Temperaturanforderung Externer Wärmebedarfskontakt"
#define STR14088_TEXT "Externer Wärmebedarf Vorrang"
#define STR14089_TEXT "Wärmebedarfseingang DC 0..10V"

#define ENUM15000_00_TEXT "Automatisch"
#define ENUM15000_01_TEXT "Manuell"
//#define ENUM15000_02_TEXT MENU_TEXT_OFF. This definition is moved to BSB_LAN/BSB_LAN_defs.h file
#define ENUM15044_00_02_TEXT "Auto-Mode: aus"
#define ENUM15044_02_02_TEXT "Auto-Mode: an"
#define ENUM15044_00_08_TEXT "Pumpe an"
#define ENUM15044_08_08_TEXT "Pumpe aus"
#define ENUM15044_00_10_TEXT "Kontakt H1: offen"
#define ENUM15044_10_10_TEXT "Kontakt H1: geschlossen"
#define ENUM15046_37_TEXT "QAA 95"
#define ENUM15046_4d_TEXT "QAW 10"
#define ENUM15046_4e_TEXT "QAW 20"
#define ENUM15046_52_TEXT "QAA 50"
#define ENUM15046_53_TEXT "QAA 70"
#define ENUM15046_58_TEXT "DC225/MCBA/REA70"
#define ENUM15046_5a_TEXT "QAA 10"
#define ENUM15046_5b_TEXT "QAA 20"
#define ENUM15046_5d_TEXT "QAA 12/13"
#define ENUM15046_66_TEXT "BMU"
#define ENUM15046_43_TEXT "RVD130"

#define ENUM_WEEKDAY_01_TEXT "Montag"
#define ENUM_WEEKDAY_02_TEXT "Dienstag"
#define ENUM_WEEKDAY_03_TEXT "Mittwoch"
#define ENUM_WEEKDAY_04_TEXT "Donnerstag"
#define ENUM_WEEKDAY_05_TEXT "Freitag"
#define ENUM_WEEKDAY_06_TEXT "Samstag"
#define ENUM_WEEKDAY_07_TEXT "Sonntag"

// These strings do not take space in Arduino memory. They are for external interfaces.
#define EXTIF_HOME_TEXT "Home"
#define EXTIF_MANAGEMENT_TEXT "Management"
#define EXTIF_MONITOR_TEXT "Monitor"
#define EXTIF_ABOUT_TEXT "Über"
#define EXTIF_SAVELOAD_TEXT "Speichern/Laden"
#define EXTIF_SETCLOCK_TEXT "Uhr einstellen"
#define EXTIF_RESET_TEXT "Reset"
#define EXTIF_BACK_TEXT "Zurück"
#define EXTIF_UPDATE_TEXT "Update"
#define EXTIF_CANCEL_TEXT "Abbrechen"
#define EXTIF_SAVE_TEXT "Speichern"
#define EXTIF_CANTREADFILE_TEXT "Datei kann nicht gelesen werden! Fehlercode "
#define EXTIF_CATNOTEXIST_TEXT "Fehler: Kategorie nicht vorhanden!"
#define EXTIF_NOTEXIST_TEXT "nicht vorhanden!"
#define EXTIF_FUNCNO_TEXT "Parameter #"
#define EXTIF_CATNO_TEXT "Kategorie #"
//Do not remove EXTIF_CHANGEPARAM1_TEXT please: EXTIF_CHANGEPARAM1_TEXT and CF_PROGLIST_TEXT are different in Russian language
#define EXTIF_CHANGEPARAM1_TEXT "Parameter"
#define EXTIF_CHANGEPARAM2_TEXT "wurde auf"
#define EXTIF_CHANGEPARAM3_TEXT "geändert"
#define EXTIF_OK_TEXT "Ok"
#define EXTIF_FAILED_TEXT "fehlgeschlagen"
#define EXTIF_ERROR_TEXT "Fehler"
#define EXTIF_SETTIME_TEXT "Zeit gesetzt auf"
#define EXTIF_JSONERROR_TEXT "Fehler: JSON-Analyse fehlgeschlagen."
#define EXTIF_ERROR404_TEXT "Fehler 404: Datei nicht gefunden!"
#define EXTIF_ERRORREQUEST_TEXT "Fehler: AJAX Anfrage ist fehlgeschlagen."
#define EXTIF_WARNEXIT_TEXT "Warnung über Verlassen ohne zu speichern. Sind Sie sicher?"
#define EXTIF_DOWNLOADCONF_TEXT "Download Systemkonfiguration"
#define EXTIF_UPLOADCONF_TEXT "Konfiguration auf System hochladen"
#define EXTIF_DOWNLOADEXCL_TEXT "Erstellen und Herunterladen von Ausschluss-Liste"
#define EXTIF_ALLCAT_TEXT "Alle Kategorien"
#define EXTIF_STARTDATE_TEXT "Startdatum"
#define EXTIF_ENDDATE_TEXT "Enddatum"

// only required for German language file
#include "localization/UNDEF_LANG_DE_LEGACY.h"
#include "localization/LANG_DE_LEGACY.h"