#define LANGUAGENAME_TEXT "Čeština"
#define MENU_TEXT_YES "Ano"
#define MENU_TEXT_NO "Ne"
#define MENU_TEXT_ON "Zap"
#define MENU_TEXT_OFF "Vyp"
#define MENU_TEXT_OPEN "Otevřít"
#define MENU_TEXT_CLOSE "Zavřít"

#define UNIT_MONTHS_TEXT "Měsíce"
#define UNIT_DAYS_TEXT "Dny"
#define UNIT_RPM_TEXT "Ot/min"
#define ENUM_CAT_00_TEXT "Čas a datum"
#define ENUM_CAT_01_TEXT "Ovládací jednotka"
#define ENUM_CAT_02_TEXT "Rádio"
#define ENUM_CAT_03_TEXT "Časový program chladícího okruhu 1"
#define ENUM_CAT_04_TEXT "Časový program chladícího okruhu 2"
#define ENUM_CAT_05_TEXT "Časový program chladícího okruhu 3"
#define ENUM_CAT_06_TEXT "Časový program topného okruhu 1"
#define ENUM_CAT_07_TEXT "Časový program topného okruhu 2"
#define ENUM_CAT_08_TEXT "Časový program topného okruhu 3"
#define ENUM_CAT_09_TEXT "Časový program 4/přípravy TUV"
#define ENUM_CAT_0a_TEXT "Časový program ventilace 1"
#define ENUM_CAT_0b_TEXT "Časový program ventilace 2"
#define ENUM_CAT_0c_TEXT "Časový program 5"
#define ENUM_CAT_0d_TEXT "Časový program ventilace 3"
#define ENUM_CAT_0e_TEXT "Prázdninové programy TO1"
#define ENUM_CAT_0f_TEXT "Prázdninové programy TO2"
#define ENUM_CAT_10_TEXT "Prázdninové programy 3"
#define ENUM_CAT_11_TEXT "Topný okruh 1"
#define ENUM_CAT_12_TEXT "Chladící okruh 1"
#define ENUM_CAT_13_TEXT "Ventilace 1"
#define ENUM_CAT_14_TEXT "Topný okruh 2"
#define ENUM_CAT_15_TEXT "Chladící okruh 2"
#define ENUM_CAT_16_TEXT "Ventilace 2"
#define ENUM_CAT_17_TEXT "Topný okruh 3"
#define ENUM_CAT_18_TEXT "Chladící okruh 3"
#define ENUM_CAT_19_TEXT "Ventilace 3"
#define ENUM_CAT_1a_TEXT "Teplá voda"
#define ENUM_CAT_1b_TEXT "Okruh spotřeby 1"
#define ENUM_CAT_1c_TEXT "Okruh spotřeby 2"
#define ENUM_CAT_1d_TEXT "Bazénový okruh"
#define ENUM_CAT_1e_TEXT "Hx čerpadlo"
#define ENUM_CAT_1f_TEXT "Bazén"
#define ENUM_CAT_20_TEXT "Předregulace/podávací čerpadlo"
#define ENUM_CAT_21_TEXT "Předregulace/podávací čerpadlo 2"
#define ENUM_CAT_22_TEXT "Kotel"
#define ENUM_CAT_23_TEXT "Sitherm Pro"
#define ENUM_CAT_24_TEXT "Tepelné čerpadlo"
#define ENUM_CAT_25_TEXT "Měřič spotřeby"
#define ENUM_CAT_26_TEXT "Hořáková řada"
#define ENUM_CAT_27_TEXT "Měřič spotřeby 2"
#define ENUM_CAT_28_TEXT "Modul monitorování sítě"
#define ENUM_CAT_29_TEXT "Kaskáda"
#define ENUM_CAT_2a_TEXT "Extra teplený zdroj"
#define ENUM_CAT_2b_TEXT "Solár"
#define ENUM_CAT_2c_TEXT "Zásobník pevného paliva"
#define ENUM_CAT_2d_TEXT "Vyrovnávací zásobník"
#define ENUM_CAT_2e_TEXT "Zásobník teplé vody"
#define ENUM_CAT_2f_TEXT "Přímé nabíjení TUV"
#define ENUM_CAT_30_TEXT "Obecné funkce"
#define ENUM_CAT_31_TEXT "Konfigurace"
#define ENUM_CAT_32_TEXT "Systém LPB"
#define ENUM_CAT_33_TEXT "Systém Modbus"
#define ENUM_CAT_34_TEXT "Chyba"
#define ENUM_CAT_35_TEXT "Údržba/servis"
#define ENUM_CAT_36_TEXT "Konfigurace rozšiřujících modulů"
#define ENUM_CAT_37_TEXT "Diagnostika modbusu"
#define ENUM_CAT_38_TEXT "Test vstupů/výstupů"
#define ENUM_CAT_39_TEXT "Stav"
#define ENUM_CAT_3a_TEXT "Diagnostika kaskády"
#define ENUM_CAT_3b_TEXT "Diagnostika generátoru"
#define ENUM_CAT_3c_TEXT "Diagnostika Zdroje tepla"
#define ENUM_CAT_3d_TEXT "Diagnostika spotřeby"
#define ENUM_CAT_3e_TEXT "Denní paměť hodnot"
#define ENUM_CAT_3f_TEXT "Hořáková automatika"
#define ENUM_CAT_40_TEXT "Uživatelsky definované"
#define ENUM_CAT_41_TEXT "LMU64"
#define ENUM_CAT_42_TEXT "RVD/RVP"
#define ENUM_CAT_43_TEXT "PPS-Bus"
#define ENUM_CAT_44_TEXT "One Wire, DHT & MAX! Sensors"
#define ENUM_CAT_45_TEXT "Neznámá kategorie"

#define MENU_TEXT_HFK "Funkce kotle"
#define MENU_TEXT_SNS "Senzory"
#define MENU_TEXT_SN1 "Senzory DS18B20"
#define MENU_TEXT_SN2 "Senzory DHT22"
#define MENU_TEXT_CHK "Vyčíst nové parametry"
#define MENU_TEXT_DLG "Zobrazit log"
#define MENU_TEXT_SLG "Zobrazit graf"
#define MENU_TEXT_CFG "Nastavení"
#define MENU_TEXT_URL "URL příkazy"
#define MENU_TEXT_HWT "JakNaTo"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_VER "Verze"
#define MENU_TEXT_DTD "Stáhnout data"
#define MENU_TEXT_NVS "Hledám novější verze"
#define MENU_TEXT_NVA "Nalezena novější verze"
#define MENU_TEXT_NVN "Nainstalovaná verze je aktuální"
#define MENU_TEXT_TOC "Návod"

#define MENU_DESC_HFK "Umožňuje načíst nebo nastavit parametry topného systému, roztřízeny do daných podmenu."
#define MENU_DESC_CFG "Zobrazí seznam nastavení webserveru. Tyto lze měnit i pomocí rozšířených URL příkazů."
#define MENU_DESC_URL "Zobrazí přehled rozšířených URL příkazů, které můžete odeslat zadáním přímo do adresního řádku prohlížeče. Tyto příkazy jsou také nezbytné pro připojení webserveru k systémům domácí automatizace, jako je FHEM."

#define STR0_TEXT "Datum/Čas"
#define STR1_TEXT "Čas"
#define STR2_TEXT "Den/měsíc"
#define STR3_TEXT "Rok"
#define STR5_TEXT "Začátek letního času"
#define STR6_TEXT "Konec letního času"
#define STR20_TEXT "Výběr jazyka"
#define STR21_TEXT "Zobrazení speciálních operací"
#define STR22_TEXT "Info"
#define STR23_TEXT "Zobrazit chyby"
#define STR25_TEXT "Kontrast displeje"
#define STR26_TEXT "Zablokování obsluhy"
#define STR27_TEXT "Zablokování programování"
#define STR28_TEXT "Přímé nastavení"
#define STR29_TEXT "Jednotka"
#define STR30_TEXT "Uložit základní nastavení"
#define STR31_TEXT "Aktivace základního nastavení"
#define STR40_TEXT "Použití jako"
#define STR42_TEXT "Přiřazení přístroje 1"
#define STR42_2_TEXT "Vliv na topné okruhy"
#define STR44_TEXT "Obsluha TO2"
#define STR46_TEXT "Obsluha TO3/Č"
#define STR48_TEXT "Prezenční tlačítko zařízení 1"
#define STR54_TEXT "Kalibrace čidla prostoru"
#define STR70_TEXT "Softwarová verze přístroje"
#define STR71_TEXT "Typ pokojové jednotky"
#define STR120_TEXT "Vazba"
#define STR121_TEXT "Testovací mód"
#define STR130_TEXT "Prost. Přístr 1"
#define STR131_TEXT "Prost. Přístr 2"
#define STR132_TEXT "Prost. Přístr 3"
#define STR133_TEXT "Venkovní čidlo"
#define STR134_TEXT "Zesilovač"
#define STR135_TEXT "Obsl. přístr 1"
#define STR136_TEXT "Obsl. přístr 2"
#define STR137_TEXT "Obsl. přístr 3"
#define STR138_TEXT "Servisní přist."
#define STR140_TEXT "Vymazání všech přístrojů"
#define STR500_TEXT "Po"
#define STR501_TEXT "Ut"
#define STR502_TEXT "St"
#define STR503_TEXT "Ct"
#define STR504_TEXT "Pa"
#define STR505_TEXT "So"
#define STR506_TEXT "Ne"
#define STR516_TEXT "Standardní hodnoty"
#define STR632_TEXT "Období 1 Start Den/Měsíc"
#define STR633_TEXT "Období 1 Konec Den/Měsíc"
#define STR634_TEXT "Období 2 Start Den/Měsíc"
#define STR635_TEXT "Období 2 Konec Den/Měsíc"
#define STR636_TEXT "Období 3 Start Den/Měsíc"
#define STR637_TEXT "Období 3 Konec Den/Měsíc"
#define STR638_TEXT "Období 4 Start Den/Měsíc"
#define STR639_TEXT "Období 4 Konec Den/Měsíc"
#define STR640_TEXT "Období 5 Start Den/Měsíc"
#define STR641_TEXT "Období 5 Konec Den/Měsíc"
#define STR642_TEXT "Období 6 Start Den/Měsíc"
#define STR643_TEXT "Období 6 Konec Den/Měsíc"
#define STR644_TEXT "Období 7 Start Den/Měsíc"
#define STR645_TEXT "Období 7 Konec Den/Měsíc"
#define STR646_TEXT "Období 8 Start Den/Měsíc"
#define STR647_TEXT "Období 8 Konec Den/Měsíc"
#define STR648_TEXT "Úroveň provozu Prázdniny"
#define STR700_TEXT "Úroveň provozu"
#define STR701_TEXT "Tlačítko přítomnosti (dočasná nepřítomnost)"
#define STR704_TEXT "Tepleji / chladněji"
#define STR705_TEXT "Dočasně tepleji"
#define STR706_TEXT "Dočasně chladněji"
#define STR707_TEXT "Dočasná nastavená hodnota místnosti"
#define STR709_TEXT "Minimální komfortní hodnota"
#define STR710_TEXT "Komfortní teplota"
#define STR711_TEXT "Maximální komfortní teplota"
#define STR712_TEXT "Útlumová teplota"
#define STR714_TEXT "Protimrazová teplota"
#define STR720_TEXT "Strmost topné křivky"
#define STR721_TEXT "Posun topné křivky"
#define STR726_TEXT "Adaptace topné křivky"
#define STR730_TEXT "Teplota přepnutí léto/zima"
#define STR732_TEXT "Denní topná mez"
#define STR733_TEXT "Prodloužení topné meze"
#define STR734_TEXT "Nastavení zpětného chodu místnosti s časovačem"
#define STR739_TEXT "Zvýšení hodnoty průtoku - maximální limit"
#define STR740_TEXT "Min. požad. teplota náběhu"
#define STR741_TEXT "Max. požad. teplota náběhu"
#define STR742_TEXT "Požad. teplota na náběhu ProstTermostat"
#define STR744_TEXT "Cílové chování při zapnutí pokojového termostatu"
#define STR746_TEXT "Zpoždění požadavku na teplo"
#define STR750_TEXT "Vliv prostoru"
#define STR760_TEXT "Omezení teploty prostoru"
#define STR761_TEXT "Limit regulátoru vytápění místnosti"
#define STR770_TEXT "Převýšení teploty prostoru (rychlé natopení)"
#define STR780_TEXT "Rychlý útlum"
#define STR781_TEXT "Faktor pro rychlý útlum"
#define STR790_TEXT "Max. předstih optimalizace zapnutí"
#define STR791_TEXT "Max. předstih optimalizace vypnutí"
#define STR794_TEXT "Gradient ohřevu"
#define STR800_TEXT "Začátek zvýšení požad. útlumové teploty"
#define STR801_TEXT "Konec zvýšení útlumové teploty."
#define STR809_TEXT "Nepřetržitý chod čerpadla"
#define STR810_TEXT "Protimrazová ochrana systému HL-Čerpadla"
#define STR812_TEXT "Předběžná protimrazová ochrana"
#define STR820_TEXT "Ochr. proti přehřátí čerpadla TO"
#define STR830_TEXT "Převýšení teploty na směšovači"
#define STR831_TEXT "Podchlazení na směšovači"
#define STR832_TEXT "Typ pohonu"
#define STR833_TEXT "Spínací diferenciál 2-bodový"
#define STR834_TEXT "Doba chodu pohonu"
#define STR835_TEXT "Směšovač P-Band Xp"
#define STR836_TEXT "Doba resetu směšovače Tn"
#define STR841_TEXT "Nastavená hodnota sledování teploty"
#define STR843_TEXT "Přídavný účinek TW vstupu"
#define STR850_TEXT "Funkce vysoušení podlahy"
#define STR851_TEXT "Požad. tepl. vysoušení ručně"
#define STR855_TEXT "Akt.požad. teplota vysoušení"
#define STR856_TEXT "Aktuální den vysoušení"
#define STR857_TEXT "Cílový den vysoušení"
#define STR861_TEXT "Odběr přebytečného tepla"
#define STR864_TEXT "Faktor blokovacího signálu"
#define STR870_TEXT "Se zásobníkem"
#define STR872_TEXT "S předregulací/podáv. čerp."
#define STR880_TEXT "Snížení otáček čerpadla"
#define STR881_TEXT "Počáteční rychlost"
#define STR882_TEXT "Min. otáčky čerpadla"
#define STR883_TEXT "Max. otáčky čerpadla"
#define STR884_TEXT "Otáčky čerpadla kotle při norm. venkovní teplotě"
#define STR885_TEXT "Minimální PWM modulovaného čerpadla"
#define STR886_TEXT "Standardní venkovní teplota"
#define STR886_2_TEXT "Maximální otáčky čerpadla OEM"
#define STR887_TEXT "Žádaná teplota kotle při norm. venkovní teplotě"
#define STR888_TEXT "dt faktor převýšení"
#define STR888_2_TEXT "Korekce topné křivky při 50% otáčkách"
#define STR889_TEXT "Časová konstanta filtru otáček"
#define STR890_TEXT "Korekce otáček na náběhu"
#define STR894_TEXT "Diference náběh/zpátečka při norm. venk. teplotě"
#define STR898_TEXT "Přepínání provozních úrovní"
#define STR1000_TEXT "Úroveň provozu"
#define STR1010_TEXT "Komfortní teplota"
#define STR1012_TEXT "Útlumová teplota"
#define STR1014_TEXT "Protimrazová teplota"
#define STR1020_TEXT "Strmost topné křivky"
#define STR1021_TEXT "Posun topné křivky"
#define STR1026_TEXT "Adaptace topné křivky"
#define STR1030_TEXT "Teplota přepnutí léto/zima"
#define STR1032_TEXT "Denní topná mez"
#define STR1040_TEXT "Min. požad. teplota náběhu"
#define STR1041_TEXT "Max. požad. teplota náběhu"
#define STR1042_TEXT "Požad. teplota na náběhu ProstTermostat"
#define STR1044_TEXT "Cílové chování při zapnutí pokojového termostatu"
#define STR1050_TEXT "Vliv prostoru"
#define STR1060_TEXT "Omezení teploty prostoru"
#define STR1070_TEXT "Převýšení teploty prostoru (rychlé natopení)"
#define STR1080_TEXT "Rychlý útlum"
#define STR1090_TEXT "Max. předstih optimalizace zapnutí"
#define STR1091_TEXT "Max. předstih optimalizace vypnutí"
#define STR1100_TEXT "Začátek zvýšení požad. útlumové teploty"
#define STR1101_TEXT "Konec zvýšení útlumové teploty"
#define STR1120_TEXT "Ochr. proti přehřátí čerpadla TO"
#define STR1130_TEXT "Převýšení teploty na směšovači"
#define STR1134_TEXT "Doba chodu pohonu"
#define STR1150_TEXT "Funkce vysoušení podlahy"
#define STR1151_TEXT "Požad. tepl. vysoušení ručně"
#define STR1600_TEXT "Druh přípravy TUV"
#define STR1602_TEXT "Status TUV"
#define STR1603_TEXT "Manuální Push TUV"
#define STR1610_TEXT "Jmenovitá žádaná teplota"
#define STR1612_TEXT "Útlumová žádaná teplota"
#define STR1614_TEXT "Teplota TUV-Max. jmenovitá teplota"
#define STR1620_TEXT "Uvolnění"
#define STR1630_TEXT "Priorita nabíjení TUV"
#define STR1640_TEXT "Legionelní funkce"
#define STR1641_TEXT "Legionelní funkce periodicky"
#define STR1642_TEXT "Legionelní funkce pevný den v týdnu"
#define STR1644_TEXT "Čas aktivace legionelní funkce"
#define STR1645_TEXT "Žádaná teplota legionelní funkce"
#define STR1646_TEXT "Doba trvání legionelní funkce"
#define STR1647_TEXT "Provoz cirk. čerpadla během legionelní funkce"
#define STR1660_TEXT "Program cirkulačního čerp."
#define STR1661_TEXT "Cyklování cirkulačního čerpadla"
#define STR1663_TEXT "Požadovaná teplota cirkulace"
#define STR1680_TEXT "Přepínání provozních režimů"
#define STR2201_TEXT "Blokace zdroje"
#define STR2210_TEXT "Minimální požadovaná teplota"
#define STR2212_TEXT "Maximální požadovaná teplota"
#define STR2214_TEXT "Požad. tepl. ručního provozu"
#define STR2241_TEXT "Minimální doba chodu hořáku"
#define STR2243_TEXT "Min. doba klidu hořáku"
#define STR2245_TEXT "Spínací diferenciál doby klidu hořáku"
#define STR2250_TEXT "Doba doběhu čerpadla"
#define STR2253_TEXT "Doběh čerpadla po ohřevu TUV"
#define STR2300_TEXT "Protimr.ochrana čerp. kotle"
#define STR2301_TEXT "Čerpadlo kotle během vypnutí kotle"
#define STR2305_TEXT "Vliv zablokování zdroje"
#define STR2315_TEXT "Teplotní diference Minimální"
#define STR2316_TEXT "Teplotní diference Maximální"
#define STR2317_TEXT "Teplotní diference Nominální"
#define STR2320_TEXT "Modulace čerpadla"
#define STR2322_TEXT "Min. otáčky čerpadla"
#define STR2322_TEXT "Max. otáčky čerpadla"
#define STR2330_TEXT "Jmenovitý výkon"
#define STR2331_TEXT "Výkon základní stupeň"
#define STR2334_TEXT "Výkon při min. otáčkách čerpadla"
#define STR2335_TEXT "Výkon při max. otáčkách čerpadla"
#define STR2440_TEXT "Max. stupeň modulace v režimu vytápění"
#define STR2441_TEXT "Maximální otáčky ventilátoru v režimu vytápění"
#define STR2441_2_TEXT "Max. otáčky ventilátoru ÚT"
#define STR2442_TEXT "Výkon při aktivní prodlevě regulátoru"
#define STR2442_2_TEXT "Max. výkon ventilátoru při plném nabíjení"
#define STR2443_TEXT "Druh výkonu při uvolnění Dlh režimu"
#define STR2443_2_TEXT "Počáteční hodnota výkonu ventilátoru Dlh režimu"
#define STR2444_2_TEXT "Max. Výkon ventilátoru při TUV"
#define STR2451_TEXT "Minimální doba klidu hořáku"
#define STR2452_TEXT "Max. regulační odchylka bez přeruš. min. pauzy"
#define STR2453_TEXT "Prodleva regulátoru po zapnutí hořáku"
#define STR2454_TEXT "Spínací diference TO"
#define STR2455_TEXT "Minimální spínací diference TO"
#define STR2456_TEXT "Maximální spínací diference TO"
#define STR2460_TEXT "Spínací diference TUV"
#define STR2461_TEXT "Minimální spínací diference TUV"
#define STR2462_TEXT "Maximální spínací diference TUV"
#define STR2470_TEXT "Zpoždění požadavku na teplo Zvláštní provoz"
#define STR2471_TEXT "Doběh čerpadel"
#define STR2472_TEXT "Teplota TUV doběhu čerpadel"
#define STR2500_TEXT "Vypnutí tlakového spínače"
#define STR2521_TEXT "Teplota zapnutí protimrazové ochrany kotle"
#define STR2522_TEXT "Teplota vypnutí protimrazové ochrany kotle"
#define STR2527_TEXT "Redukce výstupní teploty kotle"
#define STR2528_TEXT "Rozdíl v redukci teploty kotle"
#define STR2531_TEXT "Vypínací teplota mezního termostatu"
#define STR2550_TEXT "Měření plynu"
#define STR2551_TEXT "Měření plynu přepočet"
#define STR2630_TEXT "Funkce automatického odvzdušnění"
#define STR2655_TEXT "Doba zapnutí odvzdušnění"
#define STR2656_TEXT "Doba vypnutí odvzdušnění"
#define STR2657_TEXT "Počet opakování"
#define STR2730_TEXT "Ionizační proud"
#define STR3810_TEXT "Spínací diference ZAP solárního okruhu"
#define STR3811_TEXT "Spínací diference VYP solárního okruhu"
#define STR3812_TEXT "Minimální teplota nabíjení"
#define STR3831_TEXT "Minimální doba chodu čerpadla kolektoru"
#define STR3840_TEXT "Teplota protimrazové ochrany kolektoru"
#define STR3850_TEXT "Teplota ochrany proti přehřátí kolektoru"
#define STR3860_TEXT "Teplota varu náplně soláru"
#define STR4721_TEXT "Spínací diference automat zablokování zdroje"
#define STR4722_TEXT "tepl diference vyrov zásob/TO do uvolnění zdroje"
#define STR5011_TEXT "Předstih nabíjení"
#define STR5019_TEXT "Převýšení žád. teploty při celk. nabíjení zásob."
#define STR5020_TEXT "Převýšení teploty náběhu TUV"
#define STR5050_TEXT "Maximální teplota nabíjení"
#define STR5055_TEXT "Teplota zpětného chlazení"
#define STR5100_TEXT "Min. otáčky čerpadla při celkovém nabíjení zásob"
#define STR5101_TEXT "Min. otáčky čerpadla"
#define STR5102_TEXT "Max. otáčky čerpadla"
#define STR5400_TEXT "Žádaná pohotovostní teplota TUV"
#define STR5430_TEXT "Diference zapnutí přípravy TUV (čidlo 1)"
#define STR5431_TEXT "Min. diference zapnutí přípravy TUV (čidlo 1)"
#define STR5432_TEXT "Max. diference zapnutí přípravy TUV (čidlo 1)"
#define STR5433_TEXT "Diference zapnutí přípravy TUV (čidlo 2)"
#define STR5434_TEXT "Min. diference vypnutí TUV (čidlo 2)"
#define STR5435_TEXT "Max. diference vypnutí přípravy TUV (čidlo 2)"
#define STR5450_TEXT "Mez ukončení čerpání  při průtoké přípravě TUV"
#define STR5451_TEXT "Mez čerpání při komfortní průtokové přípravě TUV"
#define STR5452_TEXT "Mez čerpání TUV při Dlh v režimu vytápění"
#define STR5453_TEXT "Korekce žád. tepl. při komf. regulaci na 40°C"
#define STR5454_TEXT "Korekce žád. tepl. při komf. regulaci na 60°C"
#define STR5455_TEXT "Korekce žád. tepl. při průběž. regulaci na 40°C"
#define STR5456_TEXT "Korekce žád. tepl. při průběž. regulaci na 60°C"
#define STR5480_TEXT "Doba komfortní Dlh po čerpání bez vytápění"
#define STR5481_TEXT "Doba komfortní Dlh při aktivním vytápění"
#define STR5482_TEXT "Doba uzavření průtoku TUV"
#define STR5483_TEXT "Doba uzavření spnače průtoku TUV Komfort"
#define STR5486_TEXT "Zpoždění regulace při takt. provozu v DLH režimu"
#define STR5487_TEXT "Doběh čerpadla při komfortní Dlh po vyp. hořáku"
#define STR5488_TEXT "Doběh čerpadla při komfortní Dlh po vyp. hořáku"
#define STR5701_TEXT "Typ zařízení"
#define STR5710_TEXT "Topný okruh 1"
#define STR5715_TEXT "Topný okruh 2"
#define STR5732_TEXT "Čas vypnutí čerpadla při změně vytáp. na TUV"
#define STR5733_TEXT "Prodleva vypnutí čerpadla při změně ÚT->TUV"
#define STR5761_TEXT "Požadavky na teplo s podporou Q8"
#define STR5920_TEXT "Programovatelný výstup K2"
#define STR5921_TEXT "Základní K2 na K1"
#define STR5922_TEXT "Funkce výstupu 1 funkčního Clip-In"
#define STR5923_TEXT "Funkce výstupu 2 funkčního Clip-In"
#define STR5924_TEXT "Funkce výstupu 3 funkčního Clip-In"
#define STR5926_TEXT "Konfigurace výstupu 1"
#define STR5927_TEXT "Konfigurace výstupu 2"
#define STR5928_TEXT "Konfigurace výstupu 3"
#define STR5950_TEXT "Vstup H1 - volba funkce"
#define STR5957_TEXT "Funkce modemu"
#define STR5970_TEXT "Konfigurace prostorového termostatu  1"
#define STR5971_TEXT "Konfigurace prostorového termostatu  2"
#define STR5973_TEXT "Funkce vstupu RelCl"
#define STR5975_TEXT "Omezení teploty při externím požadavku"
#define STR5976_TEXT "Minimální vstupní signál pro externí požadavek"
#define STR6110_TEXT "Časová konstanta budovy"
#define STR6112_TEXT "Gradient prostorového modelu"
#define STR6120_TEXT "Protimrazová ochrama zařízení"
#define STR6127_TEXT "Doba funkce proti zatuhnutí čerpadel/ ventilů"
#define STR6220_TEXT "SW-verze přístrojů"
#define STR6225_TEXT "Skupina přístrojů"
#define STR6226_TEXT "Varianty přístrojů"
#define STR6227_TEXT "Verze OV přístroje"
#define STR6230_TEXT "Konfigurační bity 0"
#define STR6240_TEXT "Konfigurační bity 1"
#define STR6250_TEXT "Konfigurační bity 2"
#define STR6260_TEXT "Konfigurační bity 3"
#define STR6270_TEXT "Konfigurační bity 4"
#define STR6300_TEXT "Konfigurační bity 7"
#define STR6330_TEXT "Konfigurace regulátoru  10"
#define STR6604_TEXT "Napájení LPB"
#define STR6605_TEXT "Status napájení LPB"
#define STR6625_TEXT "Přiřazení programu přípravy TUV"
#define STR6640_TEXT "Dodavatel času"
#define STR6705_TEXT "Interní diagnostický kód"
#define STR6706_TEXT "Aktuální hodnota chybové fáze"
#define STR6741_TEXT "Doba alarmu teploty náběhu topného okruhu 2"
#define STR6823_TEXT "3. historická hodnota chyb. hlášení Albatros"
#define STR6825_TEXT "Historická hodnota 3 diagnózy chyby"
#define STR6826_TEXT "Historická hodnota 3 chybové fáze"
#define STR6830_TEXT "Historická hodnota 4 chyb. kódu měřiče"
#define STR6833_TEXT "4. historická hodnota chyb. hlášení Albatros"
#define STR6835_TEXT "Historická hodnota 4 diagnózy chyby"
#define STR6836_TEXT "Historická hodnota 4 chybové fáze"
#define STR6840_TEXT "Historická hodnota 5 chyb. kódu měřiče"
#define STR6843_TEXT "5. historická hodnota chyb. hlášení Albatros"
#define STR6845_TEXT "Historická hodnota 5 diagnózy chyby"
#define STR6846_TEXT "Historická hodnota 5 chybové fáze"
#define STR7001_TEXT "Servisní hlášení"
#define STR7007_TEXT "Konfigurace/ reset servisních hlášení"
#define STR7010_TEXT "Kvitování servisního hlášení"
#define STR7011_TEXT "Čas opakování servisních hlášení"
#define STR7040_TEXT "Servisní interval hořáku"
#define STR7041_TEXT "Provozní hodiny od posledního servisu"
#define STR7042_TEXT "Mez pro uvedení do provozu od posl. servisu"
#define STR7043_TEXT "Počet startů od posledního servisu"
#define STR7044_TEXT "Mez pro měsíce od posledního servisu"
#define STR7045_TEXT "Počet měsíců od posledního servisu"
#define STR7050_TEXT "Mez otáček ventilátoru pro servisní hlášení"
#define STR7051_TEXT "Hlášení udržby ionizačního proudu"
#define STR8000_TEXT "Stav topného okruhu 1"
#define STR8001_TEXT "Stav topného okruhu 2"
#define STR8002_TEXT "Stav okruhu P"
#define STR8003_TEXT "Stav TUV"
#define STR8005_TEXT "Stav kotle"
#define STR8007_TEXT "Stav soláru"
#define STR8009_TEXT "Stav hořáku"
#define STR8304_TEXT "Čerpadlo kotle Q1"
#define STR8308_TEXT "Otáčky čerpadla kotle"
#define STR8310_TEXT "Teplota kotle"
#define STR8311_TEXT "Požadovaná teplota kotle"
#define STR8312_TEXT "Bod sepnutí kotle"
#define STR8314_TEXT "Teplota zpátečky kotle"
#define STR8316_TEXT "Teplota spalin"
#define STR8323_TEXT "Otáčky ventilátoru"
#define STR8324_TEXT "Požad. teplota hořákového ventilátoru"
#define STR8325_TEXT "Aktuální řízení ventilátoru"
#define STR8326_TEXT "Relativní výkon"
#define STR8328_TEXT "Zobrazení provozu FA"
#define STR8329_TEXT "Ionizační proud"
#define STR8330_TEXT "Provozní hodiny 1. stupně"
#define STR8331_TEXT "Počet startů 1. stupně"
#define STR8336_TEXT "Provozní hodiny přístroje"
#define STR8337_TEXT "Počet startů hořáku"
#define STR8338_TEXT "Provozní hodiny vytápění"
#define STR8339_TEXT "Provozní hodiny přípravy TUV"
#define STR8340_TEXT "Provozní hodiny externího požadavku"
#define STR8390_TEXT "Aktuální číslo fáze"
#define STR8510_TEXT "Teplota kolektoru 1 (B6)"
#define STR8530_TEXT "Solární výnos provozních hodin"
#define STR8700_TEXT "Venkovní teplota"
#define STR8701_TEXT "Min. venkovní teplota"
#define STR8702_TEXT "Max. venkovní teplota"
#define STR8703_TEXT "Venkovní tlumená teplota"
#define STR8704_TEXT "Venkovní geometrická teplota"
#define STR8730_TEXT "Čerpadlo topného okruhu 1"
#define STR8739_TEXT "Okolní vlhkost 1"
#define STR8740_TEXT "Teplota prostoru 1"
#define STR8741_TEXT "Požadovaná teplota prostoru 1"
#define STR8743_TEXT "Teplota náběhu topného okruhu 1"
#define STR8744_TEXT "Požadovaná teplota náběhu 1"
#define STR8749_TEXT "Prostorový termostat 1"
#define STR8750_TEXT "Otáčky čerpadla"
#define STR8760_TEXT "Čerpadlo topného okruhu 2"
#define STR8761_TEXT "Směšovací ventil 2 otv."
#define STR8762_TEXT "Směšovací ventil 2 zav."
#define STR8770_TEXT "Teplota prostoru 2"
#define STR8771_TEXT "Požadovaná teplota prostoru 2"
#define STR8773_TEXT "Teplota náběhu topného okruhu 2"
#define STR8774_TEXT "Požadovaná teplota náběhu 2"
#define STR8779_TEXT "Prostorový termostat 2"
#define STR8820_TEXT "Čerpadlo TUV"
#define STR8830_TEXT "Teplota teplé vody 1"
#define STR8831_TEXT "Požadovaná teplota TUV"
#define STR8832_TEXT "Naměřená teplota TUV - dole"
#define STR8835_TEXT "Teplota cirkulace TUV"
#define STR8836_TEXT "Nabíjecí teplota TV"
#define STR8875_TEXT "Požad. teplota náběhu okruhu spotřeby 1"
#define STR8950_TEXT "Naměřená hodnota společné tepl. náběhu"
#define STR8951_TEXT "Požad. hodnota společné tepl. náběhu"
#define STR8952_TEXT "Naměřená hodnota teploty zpátečky"
#define STR8980_TEXT "Teplota vyrovnáv. zásobníku horní (B4)"
#define STR9500_TEXT "Doba předvětrání"
#define STR9502_TEXT "Modulace vzduchu v předvětrání"
#define STR9504_TEXT "Žádané otáčky ventilátoru v předvětrání"
#define STR9510_TEXT "Modulace vzduchu při zapalování"
#define STR9512_TEXT "Žádané otáčky ventilátoru při zapalování"
#define STR9520_TEXT "Modulace vzduchu při částečném zatížení"
#define STR9522_TEXT "Modulace vzduchu při plném zatížení"
#define STR9524_TEXT "Žádané otáčky ventilátoru při částečném zatížení"
#define STR9527_TEXT "Žádané otáčky ventilátoru při plném zatížení"
#define STR9529_TEXT "Požad.výkon při plné zátěži"
#define STR9540_TEXT "Doba dovětrání"
#define STR9560_TEXT "Modulace vent. při celkovém nabíjení zásobníku"
#define STR9563_TEXT "Otáčky vent. při celkovém nabíjení zásobníku"
#define STR9626_TEXT "Výkon ventilátoru-zvýšení rychlosti"
#define STR9627_TEXT "Výkon ventilátoru-rychlost Y-úseku"

#define ENUM48_00_TEXT "Žádný"
#define ENUM130_01_TEXT "V provozu"
#define ENUM648_00_TEXT "Protimrazová ochrana"
#define ENUM648_01_TEXT "Útlumový"
#define ENUM700_00_TEXT "Ochranný režim"
#define ENUM700_01_TEXT "Automatický"
#define ENUM700_03_TEXT "Komfortní"
#define ENUM702_00_TEXT "Letní provoz"
#define ENUM702_01_TEXT "Topný program 1"
#define ENUM702_02_TEXT "Úsporný program"
#define ENUM702_03_TEXT "Normalní program"
#define ENUM702_04_TEXT "Neznámý"
#define ENUM702_05_TEXT "Topný program 2"
#define ENUM702_06_TEXT "Topný program 3"
#define ENUM780_01_TEXT "Na útlumovou teplotu"
#define ENUM780_02_TEXT "Na protimrazovou teplotu"
#define ENUM832_00_TEXT "2 pozice"
#define ENUM832_01_TEXT "3 pozice"
#define ENUM843_01_TEXT "Vypnutá potřeba tepla"
#define ENUM861_01_TEXT "Provoz vytápění"
#define ENUM861_02_TEXT "Vždy"
#define ENUM880_00_TEXT "Druh provozu"
#define ENUM880_01_TEXT "Topná křivka"
#define ENUM1602_00_02_TEXT "TUV Push není aktivní"
#define ENUM1602_02_02_TEXT "TUV Push je aktivní"
#define ENUM1602_00_04_TEXT "TUV Vypnuto"
#define ENUM1602_04_04_TEXT "TUV Zapnuto"
#define ENUM1602_00_08_TEXT "TUV Nabíjení není aktivní"
#define ENUM1602_08_08_TEXT "TUV Nabíjení je aktivní"
#define ENUM1620_00_TEXT "24h/denně"
#define ENUM1620_01_TEXT "Časové programy TO"
#define ENUM1620_02_TEXT "Časový program 4/TUV"
#define ENUM1630_00_TEXT "Absolutní"
#define ENUM1630_01_TEXT "Plovoucí"
#define ENUM1630_02_TEXT "Žádné"
#define ENUM1630_03_TEXT "MK Plovoucí PK Absolutní"
#define ENUM2206_00_TEXT "V provozu"
#define ENUM2206_01_TEXT "Připraven"
#define ENUM2480_00_TEXT "Zamezení startu"
#define ENUM2480_ff_TEXT "Porucha"
#define ENUM8003_c8_TEXT "Připraven"


#define ENUM_WEEKDAY_01_TEXT "Pondělí"
#define ENUM_WEEKDAY_02_TEXT "Úterý"
#define ENUM_WEEKDAY_03_TEXT "Středa"
#define ENUM_WEEKDAY_04_TEXT "Čtvrtek"
#define ENUM_WEEKDAY_05_TEXT "Pátek"
#define ENUM_WEEKDAY_06_TEXT "Sobota"
#define ENUM_WEEKDAY_07_TEXT "Neděle"