#define LANGUAGENAME_TEXT "Français"
#define UNIT_METER_TEXT "m"
#define UNIT_MONTHS_TEXT "mois"
#define UNIT_DAYS_TEXT "jours"
#define UNIT_HOUR_TEXT "h"
#define UNIT_MIN_TEXT "min"
#define UNIT_SEC_TEXT "s"
#define UNIT_MSEC_TEXT "ms"
#define UNIT_DEG_TEXT "°C"
#define UNIT_PERC_TEXT "%"
#define UNIT_RPM_TEXT "tr/min"
#define UNIT_WATT_TEXT "W"
#define UNIT_KW_TEXT "kW"
#define UNIT_KWH_TEXT "kWh"
#define UNIT_KWHM3_TEXT "kWh/m³"
#define UNIT_CURR_TEXT "µA"
#define UNIT_BAR_TEXT "bar"
#define UNIT_VOLT_TEXT "V"
#define UNIT_GRADIENT_TEXT "min/K"
#define UNIT_GRADIENTKS_TEXT "K/s"
#define UNIT_INTEGRAL_TEXT "K·min"
#define UNIT_TEMP_PER_MIN_TEXT "°C/min"
#define UNIT_CEL_MIN_TEXT "°C·min"
#define UNIT_LITER_TEXT "l"
#define UNIT_AMP_TEXT "A"
#define UNIT_LITERPERHOUR_TEXT "l/h"
#define UNIT_LITERPERMIN_TEXT "l/min"
#define UNIT_GR_PER_CUBM_TEXT "g/m³"
#define UNIT_HPA_TEXT "hPa"
#define UNIT_PPM_TEXT "ppm"
#define UNIT_CM_TEXT "m³"
#define UNIT_HERTZ_TEXT "Hz"
#define UNIT_M3H_TEXT "m³/h"
#define UNIT_MWH_TEXT "MW/h"

#define MENU_TEXT_HFK "Fonctions chauffage"
#define MENU_TEXT_SNS "Capteurs"
#define MENU_TEXT_SN1 "Capteurs DS18B20"
#define MENU_TEXT_SN2 "Capteurs DHT22"
#define MENU_TEXT_CHK "Liste des paramètres du régulateur"
#define MENU_TEXT_DLG "Afficher le fichier journal"
#define MENU_TEXT_SLG "Enregistrer le fichier journal"
#define MENU_TEXT_CFG "Paramètres"
#define MENU_TEXT_URL "Commandes URL"
#define MENU_TEXT_HWT "Guide d’utilisation"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Oui"
#define MENU_TEXT_NO "Non"
#define MENU_TEXT_ON "Activé"
#define MENU_TEXT_OFF "Désactivé"
#define MENU_TEXT_OPEN "Ouvert"
#define MENU_TEXT_CLOSE "Fermé"
#define MENU_DESC_HFK "Permet de consulter ou de piloter les fonctions de votre système de chauffage. Les paramètres sont regroupés par catégories accessibles en cliquant dessus."
#define MENU_DESC_CFG "Affiche les paramètres actuels de configuration de BSB-LAN. Vous pouvez les modifier via des commandes URL avancées."
#define MENU_DESC_URL "Affiche la liste des commandes que vous pouvez envoyer via la barre d’adresse de votre navigateur. Ces commandes sont également utiles pour l’intégration avec des systèmes domotiques comme FHEM."
#define MENU_TEXT_VB1 "Affichage détaillé activé !"
#define MENU_TEXT_VB2 "Affichage détaillé désactivé !"
#define MENU_TEXT_VB3 "L'affichage détaillé concerne la console série de l’Arduino Mega2560 et, en option, la journalisation des données du bus sur la carte microSD, ce qui peut rapidement saturer la carte ! La sortie HTML reste inchangée."
#define MENU_TEXT_CLH "Cliquez ici"
#define MENU_TEXT_MQ1 "pour démarrer la découverte automatique MQTT (cela peut prendre un moment)."
#define MENU_TEXT_MQ0 "pour supprimer les entrées de découverte automatique MQTT (cela peut prendre un moment)."

#define MENU_TEXT_ER1 "ERREUR : paramètre invalide !"
#define MENU_TEXT_ER2 "ERREUR : valeur invalide !"
#define MENU_TEXT_ER3 "ERREUR : échec de l'enregistrement !"
#define MENU_TEXT_ER4 "Paramètre en lecture seule."
#define MENU_TEXT_ER8 "Protection en écriture activée dans les paramètres BSB-LAN."
#define MENU_TEXT_ER5 "ERREUR : type incorrect !"
#define MENU_TEXT_ER6 "ERREUR : ligne introuvable !"
#define MENU_TEXT_ER7 "ERREUR : broche GPIO protégée !"
#define MENU_TEXT_BST "Statistiques du brûleur"
#define MENU_TEXT_BRS "Temps de chauffe chaudière + ECS remis à zéro"
#define MENU_TEXT_24A "Moyennes sur 24h"
#define MENU_TEXT_24N "Nouveaux paramètres de moyenne"
#define MENU_TEXT_DTR ": Fichier supprimé et régénéré."
#define MENU_TEXT_DLD "(Chargement des données...)"
#define MENU_TEXT_DDO "Télécharger les données affichées"
#define MENU_TEXT_DTD "Télécharger toutes les données"
#define MENU_TEXT_DTF "Erreur lors de la création du fichier datalog.txt !"
#define MENU_TEXT_DTO "Erreur lors de l’ouverture du fichier datalog.txt !"
#define MENU_TEXT_RAM "Mémoire libre"
#define MENU_TEXT_BUS "Système de bus"
#define MENU_TEXT_BRW "Lecture/Écriture"
#define MENU_TEXT_BRO "Lecture seule"
#define MENU_TEXT_OWP "Broches bus 1-Wire"
#define MENU_TEXT_DHP "Broches bus DHT22"
#define MENU_TEXT_EXP "Broches GPIO verrouillées"
#define MENU_TEXT_MAC "Adresse MAC"
#define MENU_TEXT_LIR "Paramètres de log activés — le compteur d’intervalle est réinitialisé."
#define MENU_TEXT_LGP "Enregistrer les paramètres suivants toutes les"
#define MENU_TEXT_SEC "secondes"
#define MENU_TEXT_BZ1 "Durée fonctionnement brûleur niveau 1"
#define MENU_TEXT_BT1 "Cycles brûleur niveau 1"
#define MENU_TEXT_BZ2 "Durée fonctionnement brûleur niveau 2"
#define MENU_TEXT_BT2 "Cycles brûleur niveau 2"
#define MENU_TEXT_TZ1 "Durée de chauffe ECS"
#define MENU_TEXT_TT1 "Cycles ECS"
#define MENU_TEXT_MXI "Température actuelle MAX!"
#define MENU_TEXT_MXS "Température de consigne MAX!"
#define MENU_TEXT_MXV "Ouverture vanne MAX!"
#define MENU_TEXT_MXN "Aucune donnée MAX! reçue."
#define MENU_TEXT_BDT "Télégrammes BSB (hors intervalle)"
#define MENU_TEXT_LAT "Enregistrer tous les télégrammes du bus"
#define MENU_TEXT_BUT "Enregistrer uniquement les télégrammes inconnus"
#define MENU_TEXT_UBT "Enregistrer uniquement les broadcasts inconnus"
#define MENU_TEXT_MMD "Mode brut"
#define MENU_TEXT_MAS "Créer les appareils via MQTT Auto Discovery..."
#define MENU_TEXT_MAR "Supprimer les appareils via MQTT Auto Discovery..."
#define MENU_TEXT_VBL "Affichage détaillé"
#define MENU_TEXT_AVT "Calcul des moyennes 24h pour les paramètres suivants"
#define MENU_TEXT_LBO "Enregistrer uniquement les broadcasts du bus"
#define MENU_TEXT_LGI "Nouvel intervalle de journalisation"
#define MENU_TEXT_LGN "Nouveaux paramètres de journalisation"
#define MENU_TEXT_NOQ "La génération de la liste de paramètres spécifique au régulateur n’est disponible que pour les systèmes BSB et LPB.<BR>Pour les appareils PPS, utilisez directement la catégorie dédiée.\r\n"
#define MENU_TEXT_QNC "BSB-LAN ne parvient pas à se connecter au régulateur de chauffage. Vérifiez que l’adaptateur est bien branché et que la chaudière est allumée. Puis redémarrez BSB-LAN pour établir la connexion."
#define MENU_TEXT_QIN "Pour générer la liste de paramètres spécifique au régulateur, cliquez sur 'Télécharger' ci-dessous.<BR>Si plusieurs régulateurs sont présents sur le bus LPB, effectuez cette opération <B>uniquement</B> si BSB-LAN est connecté via LPB !<BR>Le processus peut prendre plusieurs minutes et sembler bloqué au début — <B>merci de patienter !</B>\r\n<BR>Ensuite, envoyez le fichier généré à bsb(ät)code-it.de.\r\nNous créerons alors le fichier 'BSB_LAN_custom_defs.h' adapté à votre configuration et vous le renverrons rapidement.<BR><B>Cette opération n’est normalement requise qu’une seule fois (et non à chaque mise à jour de BSB-LAN).</B><BR><BR>Alternativement, vous pouvez utiliser un ancien fichier 'BSB_LAN_custom_defs.h' provenant d’une version antérieure (comme la release 2.2). Attention : ces anciennes listes manquent de nombreux paramètres récents et contiennent parfois des erreurs. Nous <B>ne recommandons plus</B> leur utilisation !<BR>"
#define MENU_TEXT_QDL "Télécharger"
#define MENU_TEXT_QSC "Recherche d’appareils"
#define MENU_TEXT_QFD "Adresse de l’appareil trouvée"
#define MENU_TEXT_QFA "Échec de l’interrogation de l’appareil"
#define MENU_TEXT_QRT "Tester l’adresse de l’appareil"
#define MENU_TEXT_QST "Démarrer le test"
#define MENU_TEXT_QTE "Test terminé"
#define MENU_TEXT_QFE "Terminé"
#define MENU_TEXT_QFF "Non connecté au broker MQTT — réessayez plus tard."
#define MENU_TEXT_TOC "Manuel"
#define MENU_TEXT_UPT "Temps de fonctionnement"
#define MENU_TEXT_VER "Version"
#define MENU_TEXT_MCU "Matériel"
#define MENU_TEXT_BYT "Octets"
#define MENU_TEXT_MOD "Modules installés"
#define MENU_TEXT_NVS "Vérifier les mises à jour"
#define MENU_TEXT_NVA "Nouvelle version disponible"
#define MENU_TEXT_NVN "Version actuelle à jour"
#define MENU_TEXT_NVW "Attention ! La nouvelle version peut nécessiter des ajustements. Consultez le fichier CHANGELOG.md."
#define MENU_TEXT_SDF "Cette installation de BSB-LAN ne contient qu’un ensemble limité de paramètres. Pour activer tous les paramètres, créez une liste spécifique à l’appareil via le menu prévu, puis reflash le système."
#define MENU_LINK_TOC "https://docs.bsb-lan.de/fr/"
#define MENU_LINK_FAQ "https://docs.bsb-lan.de/fr/faq.html"
#define MENU_LINK_URL "https://docs.bsb-lan.de/fr/using.html"
#define MENU_TEXT_LOT "Journaliser les télégrammes"
#define MENU_TEXT_FSP "Espace libre dans le système de fichiers"
#define MENU_TEXT_CNV "Catégorie non disponible pour cet appareil cible."

#define STR_24A_TEXT "Moyenne sur 24h"

//WEBCONFIG
#define CF_USEEEPROM_TEXT "Lire la configuration depuis l’EEPROM"
#define CF_BUSTYPE_TEXT "Type de bus"
#define CF_OWN_ADDR_TEXT "Adresse locale"
#define CF_DEST_ADDR_TEXT "Adresse cible"
#define CF_PPS_WRITE_TEXT "PPS : Mode"
#define CF_QAA_TYPE_TEXT "PPS : Modèle QAA"
#define CF_LOGTELEGRAM_TEXT "Télégrammes du bus"
#define CF_LOGCURRVALUES_TEXT "Journalisation active"
#define CF_LOGCURRINTERVAL_TEXT "Intervalle de journalisation (secondes)"
#define CF_CALCULATION_TEXT "Calcul"
#define CF_PROGLIST_TEXT "Paramètres"
#define CF_DEVICES_TEXT "Appareils"
#define CF_NETWORK_TYPE_TEXT "Interface réseau"
#define CF_DHCP_TEXT "Utiliser DHCP"
#define CF_IPADDRESS_TEXT "Adresse IP statique"
#define CF_TRUSTEDIPADDRESS_TEXT "Adresse IP de confiance"
#define CF_MASK_TEXT "Masque de sous-réseau"
#define CF_GATEWAY_TEXT "Passerelle"
#define CF_DNS_TEXT "Serveur DNS"
#define CF_WWWPORT_TEXT "Port TCP"
#define CF_WIFI_SSID_TEXT "SSID Wi-Fi"
#define CF_WIFI_PASSWORD_TEXT "Mot de passe Wi-Fi"
#define CF_WEBSERVER_TEXT "Système de fichiers du serveur Web"
#define CF_PASSKEY_TEXT "Clé d’URL (passkey)"
#define CF_BASICAUTH_TEXT "Authentification HTTP"
#define CF_PINS_TEXT "Broches"
#define CF_USE_TEXT "Utiliser"
#define CF_MAX_IPADDRESS_TEXT "Adresse IP du Cube"
#define CF_WRITEMODE_TEXT "Accès en écriture (niveau)"
#define CF_MQTT_SERVER_TEXT "Serveur MQTT"
#define CF_MQTT_USERNAME_TEXT "Nom d’utilisateur"
#define CF_MQTT_PASSWORD_TEXT "Mot de passe"
#define CF_MQTT_TOPIC_TEXT "Préfixe de topic"
#define CF_MQTT_DEVICE_TEXT "ID de l’appareil"
#define CF_LOG_DEST_TEXT "Destination de stockage"
#define CF_LOGMODE_TEXT "Mode de journalisation"
#define CF_CHECKUPDATE_TEXT "Vérifier les mises à jour"
#define CF_MDNS_HOSTNAME_TEXT "Nom mDNS"
#define CF_NUM_TEXT "Capteurs"
#define CF_OTA_UPDATE_TEXT "Mise à jour OTA"
#define CF_SHOW_UNKNOWN_TEXT "Afficher les paramètres inconnus"
#define CF_RX_PIN_TEXT "Numéro de broche RX"
#define CF_TX_PIN_TEXT "Numéro de broche TX"
#define CF_CONFIG_LEVEL_TEXT "Afficher les réglages avancés"
#define CF_ENERGY_SAVE_TEXT "Mode économie d’énergie"

#define CAT_GENERAL_TEXT "Général"
#define CAT_IPV4_TEXT "Réseau"
#define CAT_MQTT_TEXT "MQTT"
#define CAT_BUS_TEXT "Bus"
#define CAT_IPWE_TEXT "IPWE"
#define CAT_DHTBUS_TEXT "DHT"
#define CAT_ONEWIREBUS_TEXT "OneWire"
#define CAT_DEBUG_TEXT "Débogage"
#define CAT_MAX_TEXT "MAX!"
#define CAT_LOGGING_TEXT "Journalisation"
#define CAT_24HAVG_TEXT "Moyennes sur 24h"
#define CAT_RGT_EMUL_TEXT "Émulation RGT"
#define CAT_BMEBUS_TEXT "Capteurs BME280"

#define STR10100_TEXT "État du système"
#define STR10101_TEXT "INFO production d’ECS"
#define STR10102_TEXT "INFO chauffage 1 – en attente"
#define STR10103_TEXT "INFO chauffage 2 – en attente
#define STR10104_TEXT "INFO chauffage 3/P – en attente"
#define STR10200_TEXT "Commande inconnue"

#define STR15000_TEXT "Mode de fonctionnement"
#define STR15001_TEXT "Bouton de présence"
#define STR15002_TEXT "Position du bouton rotatif"
#define STR15003_TEXT "Jours de vacances restants"
#define STR15004_TEXT "Température de confort"
#define STR15005_TEXT "Température réduite"
#define STR15006_TEXT "Température antigel"
#define STR15007_TEXT "Température maximale"
#define STR15008_TEXT "Température de la pièce"
#define STR15020_TEXT "Chauffage de l'eau chaude sanitaire"
#define STR15021_TEXT "Température de l'eau chaude sanitaire 1"
#define STR15022_TEXT "Température réduite de l'eau chaude sanitaire"
#define STR15023_TEXT "Température nominale de l'eau chaude sanitaire"
#define STR15030_TEXT "Température extérieure"
#define STR15031_TEXT "Température extérieure mélangée"
#define STR15032_TEXT "Température de départ 1"
#define STR15033_TEXT "Température de consigne 1"
#define STR15034_TEXT "Température de départ du mélangeur"
#define STR15035_TEXT "Température cible"
#define STR15036_TEXT "Modulation du brûleur"
#define STR15040_TEXT "Heure"
#define STR15041_TEXT "Jour de la semaine"
#define STR15042_TEXT "Prochain programme de commutation"
#define STR15043_TEXT "Chauffage manuel"
#define STR15044_TEXT "Statut du brûleur"
#define STR15045_TEXT "Connexion interrompue"
#define STR15046_TEXT "Modèle QAA"
#define STR15050_TEXT "Programme horaire lundi"
#define STR15056_TEXT "Programme horaire mardi"
#define STR15062_TEXT "Programme horaire mercredi"
#define STR15068_TEXT "Programme horaire jeudi"
#define STR15074_TEXT "Programme horaire vendredi"
#define STR15080_TEXT "Programme horaire samedi"
#define STR15086_TEXT "Programme horaire dimanche"
#define STR20100_TEXT "ID du capteur DHT22"
#define STR20101_TEXT "Température du capteur DHT22"
#define STR20102_TEXT "Humidité du capteur DHT22"
#define STR20103_TEXT "Humidité absolue du capteur DHT22"
#define STR20200_TEXT "ID du capteur BME280"
#define STR20201_TEXT "Température du capteur BME280"
#define STR20202_TEXT "Humidité du capteur BME280"
#define STR20203_TEXT "Pression du capteur BME280"
#define STR20204_TEXT "Altitude du capteur BME280"
#define STR20205_TEXT "Humidité absolue du capteur BME280"
#define STR20300_TEXT "ID du capteur DS18B20"
#define STR20301_TEXT "Température du capteur DS18B20"
#define STR20500_TEXT "ID du capteur MAX!"
#define STR20501_TEXT "Température actuelle du capteur MAX!"
#define STR20502_TEXT "Température cible du capteur MAX!"
#define STR20503_TEXT "Ouverture de la vanne du capteur MAX!"
#define STR20700_TEXT "Valeur personnalisée (flottant)"
#define STR20800_TEXT "Valeur personnalisée (entier long)"

#define STR99999_TEXT "Commande inconnue"

#define ENUM_CAT_40_TEXT "Personnalisé"
#define ENUM_CAT_41_TEXT "LMU64"
#define ENUM_CAT_42_TEXT "RVD/RVP"
#define ENUM_CAT_43_TEXT "Bus PPS"
#define ENUM_CAT_44_TEXT "Capteurs OneWire, DHT & MAX!"
#define ENUM_CAT_45_TEXT "Catégorie inconnue"

#define ENUM_PPS_MODE_PASSIVE_TEXT "Passif"
#define ENUM_PPS_MODE_QAA_TEXT "Comme unité ambiante"
#define ENUM_DEBUG_SERIAL_TEXT "Série"
#define ENUM_DEBUG_TELNET_TEXT "Telnet"
#define ENUM_MQTT_PLAIN_TEXT "Texte brut"
#define ENUM_MQTT_JSON_TEXT "JSON"
#define ENUM_MQTT_JSON2_TEXT "JSON enrichi"

#define ENUM_WRITE_ENG_TEXT "Activé (standard)"
#define ENUM_WRITE_OEM_TEXT "Activé (complet)"

#define ENUM_LOGMODE_01_TEXT "Écriture sur carte SD"
#define ENUM_LOGMODE_02_TEXT "Calcul des moyennes sur 24h"
#define ENUM_LOGMODE_04_TEXT "Envoi au broker MQTT"
#define ENUM_LOGMODE_08_TEXT "Envoyer uniquement les paramètres au serveur MQTT"
#define ENUM_LOGMODE_10_TEXT "Envoyer comme messages UDP"

#define ENUM_LOG_DEST_00_TEXT "Carte SD"
#define ENUM_LOG_DEST_01_TEXT "Mémoire Flash interne"

#define ENUM_VERBOSE_00_TEXT "Désactivé"
#define ENUM_VERBOSE_01_TEXT "Activé"
#define ENUM_VERBOSE_02_TEXT "Développeur"

#define ENUM_NETWORK_TYPE_00_TEXT "LAN"
#define ENUM_NETWORK_TYPE_01_TEXT "Wi-Fi"

#define ENUM648_01_TEXT "Réduit"
#define ENUM700_03_TEXT "Confort"

#define STR14081_TEXT "Durée actionneur ouverture/fermeture (convertisseur)"
#define STR14082_TEXT "Bande proportionnelle XP actionneur (convertisseur)"
#define STR14083_TEXT "Temps de réajustement TN actionneur (convertisseur)"
#define STR14084_TEXT "Surcharge consigne mélangeur/échangeur"
#define STR14085_TEXT "Limite max température départ commune"
#define STR14086_TEXT "Limite min température départ commune"
#define STR14087_TEXT "Demande de température via contact externe"
#define STR14088_TEXT "Priorité à la demande de chaleur externe"
#define STR14089_TEXT "Entrée de demande de chaleur DC 0..10 V"

#define ENUM15000_00_TEXT "Automatique"
#define ENUM15000_01_TEXT "Manuel"
//#define ENUM15000_02_TEXT MENU_TEXT_OFF. Cette définition est déplacée dans le fichier BSB_LAN/BSB_LAN_defs.h
#define ENUM15044_00_02_TEXT "Mode auto : désactivé"
#define ENUM15044_02_02_TEXT "Mode auto : activé"
#define ENUM15044_00_08_TEXT "Pompe activée"
#define ENUM15044_08_08_TEXT "Pompe désactivée"
#define ENUM15044_00_10_TEXT "Contact H1 : ouvert"
#define ENUM15044_10_10_TEXT "Contact H1 : fermé"
#define ENUM15046_37_TEXT "QAA 95"
#define ENUM15046_4d_TEXT "QAW 10"
#define ENUM15046_4e_TEXT "QAW 20"
#define ENUM15046_52_TEXT "QAA 50"
#define ENUM15046_53_TEXT "QAA 70"
#define ENUM15046_58_TEXT "DC225 / MCBA / REA70"
#define ENUM15046_5a_TEXT "QAA 10"
#define ENUM15046_5b_TEXT "QAA 20"
#define ENUM15046_5d_TEXT "QAA 12 / 13"
#define ENUM15046_66_TEXT "BMU"
#define ENUM15046_43_TEXT "RVD130"

#define ENUM_WEEKDAY_01_TEXT "Lundi"
#define ENUM_WEEKDAY_02_TEXT "Mardi"
#define ENUM_WEEKDAY_03_TEXT "Mercredi"
#define ENUM_WEEKDAY_04_TEXT "Jeudi"
#define ENUM_WEEKDAY_05_TEXT "Vendredi"
#define ENUM_WEEKDAY_06_TEXT "Samedi"
#define ENUM_WEEKDAY_07_TEXT "Dimanche"

// Ces chaînes ne consomment pas de mémoire sur Arduino. Elles sont destinées aux interfaces externes.
#define EXTIF_HOME_TEXT "Accueil"
#define EXTIF_MANAGEMENT_TEXT "Gestion"
#define EXTIF_MONITOR_TEXT "Surveillance"
#define EXTIF_ABOUT_TEXT "À propos"
#define EXTIF_SAVELOAD_TEXT "Sauvegarder/Charger"
#define EXTIF_SETCLOCK_TEXT "Régler l’heure"
#define EXTIF_RESET_TEXT "Réinitialiser"
#define EXTIF_BACK_TEXT "Retour"
#define EXTIF_UPDATE_TEXT "Mettre à jour"
#define EXTIF_CANCEL_TEXT "Annuler"
#define EXTIF_SAVE_TEXT "Enregistrer"
#define EXTIF_CANTREADFILE_TEXT "Impossible de lire le fichier ! Code d’erreur : "
#define EXTIF_CATNOTEXIST_TEXT "Erreur : catégorie inexistante !"
#define EXTIF_NOTEXIST_TEXT "n’existe pas !"
#define EXTIF_FUNCNO_TEXT "Paramètre n°"
#define EXTIF_CATNO_TEXT "Catégorie n°"
// Ne pas supprimer EXTIF_CHANGEPARAM1_TEXT : EXTIF_CHANGEPARAM1_TEXT et CF_PROGLIST_TEXT sont différents en russe
#define EXTIF_CHANGEPARAM1_TEXT "Paramètre"
#define EXTIF_CHANGEPARAM2_TEXT "modifié en"
#define EXTIF_CHANGEPARAM3_TEXT ""
#define EXTIF_OK_TEXT "OK" 
#define EXTIF_FAILED_TEXT "Échec"
#define EXTIF_ERROR_TEXT "Erreur"
#define EXTIF_SETTIME_TEXT "Heure réglée sur"
#define EXTIF_JSONERROR_TEXT "Erreur : échec de l’analyse JSON."
#define EXTIF_ERROR404_TEXT "Erreur 404 : fichier non trouvé !"
#define EXTIF_ERRORREQUEST_TEXT "Erreur : requête AJAX échouée."
#define EXTIF_WARNEXIT_TEXT "Attention : quitter sans enregistrer. Êtes-vous sûr ?"
#define EXTIF_DOWNLOADCONF_TEXT "Télécharger la configuration système"
#define EXTIF_UPLOADCONF_TEXT "Téléverser la configuration sur le système"
#define EXTIF_DOWNLOADEXCL_TEXT "Créer et télécharger la liste d’exclusions"
#define EXTIF_ALLCAT_TEXT "Toutes les catégories"
#define EXTIF_STARTDATE_TEXT "Date de début"
#define EXTIF_ENDDATE_TEXT "Date de fin"

// only required for french language file
#include "LANG_FR_LEGACY.h"
