#define LANGUAGENAME_TEXT "Język polski"
#define MENU_TEXT_YES "Tak"
#define MENU_TEXT_NO "Nie"
#define MENU_TEXT_ON "Włączony"
#define MENU_TEXT_OFF "Wyłączony"
#define MENU_TEXT_OPEN "Otwarty"
#define MENU_TEXT_CLOSED "Zwarty"

#define ENUM_CAT_00_TEXT "Godzina i data"
#define ENUM_CAT_01_TEXT "Jednostka sterująca"
#define ENUM_CAT_02_TEXT "Radio"
#define ENUM_CAT_06_TEXT "Program 1 obiegu CO"
#define ENUM_CAT_07_TEXT "Program 2 obiegu CO"
#define ENUM_CAT_08_TEXT "Program 3 obiegu CO"
#define ENUM_CAT_09_TEXT "Program 4 obiegu CO / CWU"
#define ENUM_CAT_0c_TEXT "Program 5"
#define ENUM_CAT_0e_TEXT "Wakacje 1 obiegu CO"
#define ENUM_CAT_0f_TEXT "Wakacje 2 obiegu CO"
#define ENUM_CAT_10_TEXT "Wakacje obiegu P"
#define ENUM_CAT_11_TEXT "Obieg CO 1"
#define ENUM_CAT_12_TEXT "Obieg chłodzenia 1"
#define ENUM_CAT_14_TEXT "Obieg CO 2"
#define ENUM_CAT_15_TEXT "Obieg chłodzenia 2"
#define ENUM_CAT_17_TEXT "Obieg CO 3"
#define ENUM_CAT_1a_TEXT "Ciepła woda użytkowa (CWU)"
#define ENUM_CAT_1e_TEXT "Pompa Hx"
#define ENUM_CAT_1f_TEXT "Basen"
#define ENUM_CAT_20_TEXT "Kontroler podstawowy/Pompa"
#define ENUM_CAT_21_TEXT "Kontroler podstawowy/Pompa 2"
#define ENUM_CAT_22_TEXT "Kocioł"
#define ENUM_CAT_23_TEXT "Sitherm Pro"
#define ENUM_CAT_24_TEXT "Pompa ciepła"
#define ENUM_CAT_25_TEXT "Licznik energii"
#define ENUM_CAT_29_TEXT "Instalacja kaskadowa"
#define ENUM_CAT_2a_TEXT "Dodatkowe źródła"
#define ENUM_CAT_2b_TEXT "Obieg solarny"
#define ENUM_CAT_2c_TEXT "Kocioł na paliwo stałe"
#define ENUM_CAT_2d_TEXT "Zasobnik buforowy"
#define ENUM_CAT_2e_TEXT "Zasobnik CWU"
#define ENUM_CAT_2f_TEXT "Ładowanie CWU"
#define ENUM_CAT_31_TEXT "Konfiguracja"
#define ENUM_CAT_32_TEXT "Magistrala LPB"
#define ENUM_CAT_33_TEXT "Magistrala Modbus"
#define ENUM_CAT_34_TEXT "Błąd"
#define ENUM_CAT_35_TEXT "Konserwacja/Serwis"
#define ENUM_CAT_36_TEXT "Konfiguracja modułów rozszerzenia"
#define ENUM_CAT_38_TEXT "Test wejścia/wyjścia"
#define ENUM_CAT_39_TEXT "Stan"
#define ENUM_CAT_3a_TEXT "Diagnoza kaskady"
#define ENUM_CAT_3c_TEXT "Diagnoza źródeł ciepła"
#define ENUM_CAT_3d_TEXT "Diagnoza odbiorców"
#define ENUM_CAT_3f_TEXT "Regulacja palnika"
#define ENUM_CAT_40_TEXT "Zdefiniowane przez użytkownika"
#define ENUM_CAT_43_TEXT "PPS-Bus"
#define ENUM_CAT_45_TEXT "nieznana kategoria"
#define MENU_TEXT_HFK "Funkcje pieca"
#define MENU_TEXT_SNS "Czujniki"
#define MENU_TEXT_SN1 "Czujniki DS18B20"
#define MENU_TEXT_SN2 "Czujniki DHT22"
#define MENU_TEXT_CHK "Sprawdź nowe parametry"
#define MENU_TEXT_DLG "Edytuj plik log"
#define MENU_TEXT_SLG "Wykres z pliku log"
#define MENU_TEXT_CFG "Konfiguracja"
#define MENU_TEXT_URL "Polecenia URL"
#define MENU_TEXT_HWT "Instrukcja obsługi"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_DESC_HFK "Pozwala na sprawdzenie lub ustawienie parametrów systemu grzewczego, posortowane w różnych kategoriach."
#define MENU_DESC_CFG "Wyświetla listę opcji konfiguracji. Większość z nich można zmienić, używając poleceń rozszerzonego adresu URL."
#define MENU_DESC_URL "Zaawansowane polecenia URL: Wyświetla listę rozszerzonych poleceń, do których można uzyskać dostęp bezpośrednio wprowadzając je w linii adresu przeglądarki. Polecenia te są również niezbędne do połączenia BSB-LAN z dowolnym systemem automatyki domowej, takim jak FHEM."
#define MENU_TEXT_VB1 "Tryb szczegółowy (gadatliwy) aktywny!"
#define MENU_TEXT_VB2 "Tryb szczegółowy (gadatliwy) wyłączony!"
#define MENU_TEXT_VB3 "Tryb szczegółow wpływa zarówno na konsolę szeregową Arduino Mega2560, jak i (opcjonalnie) na rejestrowanie danych magistrali na karcie microSD, dzięki czemu karta może bardzo szybko się zapełnić! Wyjście HTML pozostaje niezmienione."
#define MENU_TEXT_SR1 "Monitor szeregowy aktywny!"
#define MENU_TEXT_SR2 "Monitor szeregowy wyłączony!"
#define MENU_TEXT_SR3 "Dotyczy tylko wyjścia szeregowego."
#define MENU_TEXT_ER1 "BŁĄD: Niepoprawny parametr!"
#define MENU_TEXT_ER2 "BŁĄD: Niepoprawna wartość!"
#define MENU_TEXT_ER3 "BŁĄD: Nie można ustawić!"
#define MENU_TEXT_ER4 "Parametr tylko do odczytu."
#define MENU_TEXT_ER5 "BŁĄD: Zły typ!"
#define MENU_TEXT_ER6 "BŁĄD: Nie znaleziono linii!"
#define MENU_TEXT_ER7 "BŁĄD: Chroniony pin GPIO!"
#define MENU_TEXT_BST "Statystyki palnika"
#define MENU_TEXT_BRS "Czas pracy kotła i ciepłej wody użytkowej ustawiony na zero"
#define MENU_TEXT_24A "Średnie wartości z 24 godzin"
#define MENU_TEXT_24N "Nowe średnie parametry"
#define MENU_TEXT_DTR "Plik datalog.txt usunięty i zregenerowany"
#define MENU_TEXT_DTD "Pobierz dane"
#define MENU_TEXT_DTF "BŁĄD podczas tworzenia pliku datalog.txt!"
#define MENU_TEXT_DTO "BŁĄD podczas otwierania pliku datalog.txt!"
#define MENU_TEXT_RAM "Wolna pamięć"
#define MENU_TEXT_BUS "Magistrala systemowa"
#define MENU_TEXT_BRW "Odczyt/Zapis"
#define MENU_TEXT_BRO "Tylko do odczytu"
#define MENU_TEXT_OWP "Piny magistrali 1-Wire"
#define MENU_TEXT_DHP "Piny DHT22"
#define MENU_TEXT_EXP "Zablokowane piny GPIO"
#define MENU_TEXT_MAC "Adres MAC"
#define MENU_TEXT_LGP "Zapisz wszystkie parametry"
#define MENU_TEXT_SEC "sekund"
#define MENU_TEXT_BZ1 "Palnik - czas pracy faza 1"
#define MENU_TEXT_BT1 "Palnik - cykl pracy faza 1"
#define MENU_TEXT_BZ2 "Palnik - czas pracy faza 2"
#define MENU_TEXT_BT2 "Palnik - cykl pracy faza 2"
#define MENU_TEXT_TZ1 "CWU - czas pracy"
#define MENU_TEXT_TT1 "CWU - cykl pracy"
#define MENU_TEXT_MXI "MAX!-aktualna temperatura"
#define MENU_TEXT_MXS "MAX!-nastawa temperatury"
#define MENU_TEXT_MXV "MAX!-otwarcie zaworu"
#define MENU_TEXT_MXN "MAX!-brak danych"
#define MENU_TEXT_BDT "Dane BSB (niezależnie od interwału)"
#define MENU_TEXT_BUT "Rejestruj tylko nieznane dane z magistrali"
#define MENU_TEXT_MMD "Tryb monitorowania"
#define MENU_TEXT_VBL "Poziom szczegółowości (gadatliwości)"
#define MENU_TEXT_AVT "Obliczanie średnich dobowych dla następujących parametrów:"
#define MENU_TEXT_LBO "Rejestruj tylko dane z magistrali rozgłoszeniowej"
#define MENU_TEXT_LGI "Nowy interwał rejestrowania"
#define MENU_TEXT_LGN "Nowe parametry rejestrowania"
#define MENU_TEXT_QSC "Szukaj nowych urządzeń"
#define MENU_TEXT_QFD "Znaleziono urządzenie"
#define MENU_TEXT_QFA "Zapytanie o urządzenie nie powiodło się"
#define MENU_TEXT_QRT "Testuj adres urządzenia"
#define MENU_TEXT_QST "Rozpocznij test"
#define MENU_TEXT_QTE "Test zakończony"
#define MENU_TEXT_QFE "Gotowe"
#define STR0_TEXT "Czas i data"
#define STR1_TEXT "Godziny/minuty"
#define STR2_TEXT "Dzień/miesiąc"
#define STR3_TEXT "Rok"
#define STR5_TEXT "Początek czasu letniego dzień/miesiąc"
#define STR6_TEXT "Początek czasu zimowego dzień/miesiąc"
#define STR20_TEXT "Język"
#define STR21_TEXT "Tryb specjalny"
#define STR22_TEXT "Informacja"
#define STR23_TEXT "Wskazania błędów"
#define STR25_TEXT "Kontrast wyświetlacza"
#define STR26_TEXT "Blokada obsługi"
#define STR27_TEXT "Blokada programowania"
#define STR28_TEXT "Bezpośrednia regulacja jednostki sterującej"
#define STR29_TEXT "Jednostki"
#define STR30_TEXT "Zapisz podstawowe nastawy"
#define STR31_TEXT "Aktywuj podstawowe nastawy"
#define STR40_TEXT "Zastosowanie jako"
#define STR42_TEXT "Przypisanie regulatora pokojowego 1"
#define STR42_2_TEXT "Wpływ modułu pokojowego na obiegi grzewcze"
#define STR44_TEXT "Obsługa 2 obiegu CO"
#define STR46_TEXT "Obsługa 3 obiegu CO"
#define STR48_TEXT "Efekt przycisku obecności"
#define STR54_TEXT "Korekta czujnika pokojowego"
#define STR70_TEXT "Wersja firmware"
#define STR71_TEXT "Typ modułu pokojowego"
#define STR120_TEXT "Łączenie"
#define STR121_TEXT "Tryb testowy"
#define STR130_TEXT "Stan modułu pokojowego 1"
#define STR131_TEXT "Stan modułu pokojowego 2"
#define STR132_TEXT "Stan modułu pokojowego P"
#define STR133_TEXT "Stan czujnika zewnętrznego P"
#define STR134_TEXT "Stan repeatera P"
#define STR135_TEXT "Stan jednostki sterującej 1"
#define STR136_TEXT "Stan jednostki sterującej 2"
#define STR137_TEXT "Stan jednostki sterującej P"
#define STR138_TEXT "Stan urządzenia serwisowego"
#define STR140_TEXT "Usuń wszystkie urządzenia"
#define STR500_TEXT "Poniedziałek"
#define STR501_TEXT "Wtorek"
#define STR502_TEXT "Środa"
#define STR503_TEXT "Czwartek"
#define STR504_TEXT "Piątek"
#define STR505_TEXT "Sobota"
#define STR506_TEXT "Niedziela"
#define STR516_TEXT "Wartości domyślne programu 1 obiegu CO"
#define STR536_TEXT "Wartości domyślne programu 2 obiegu CO"
#define STR556_TEXT "Wartości domyślne programu 3 obiegu CO"
#define STR576_TEXT "Wartości domyślne programu 4 obiegu CO/CWU"
#define STR632_TEXT "Okres 1 początek dzień/miesiąc"
#define STR633_TEXT "Okres 1 koniec dzień/miesiąc"
#define STR634_TEXT "Okres 2 początek dzień/miesiąc"
#define STR635_TEXT "Okres 2 koniec dzień/miesiąc"
#define STR636_TEXT "Okres 3 początek dzień/miesiąc"
#define STR637_TEXT "Okres 3 koniec dzień/miesiąc"
#define STR638_TEXT "Okres 4 początek dzień/miesiąc"
#define STR639_TEXT "Okres 4 koniec dzień/miesiąc"
#define STR640_TEXT "Okres 5 początek dzień/miesiąc"
#define STR641_TEXT "Okres 5 koniec dzień/miesiąc"
#define STR642_TEXT "Okres 6 początek dzień/miesiąc"
#define STR643_TEXT "Okres 6 koniec dzień/miesiąc"
#define STR644_TEXT "Okres 7 początek dzień/miesiąc"
#define STR645_TEXT "Okres 7 koniec dzień/miesiąc"
#define STR646_TEXT "Okres 8 początek dzień/miesiąc"
#define STR647_TEXT "Okres 8 koniec dzień/miesiąc"
#define STR648_TEXT "Poziom roboczy podczas wakacji obieg 1"
#define STR652_TEXT "Okres wakacyjny 1 obiegu 2: dzień rozpoczęcia"
#define STR653_TEXT "Okres wakacyjny 1 obiegu 2: dzień zakończenia"
#define STR658_TEXT "Poziom roboczy podczas wakacji obieg 2"
#define STR700_TEXT "Tryb pracy obiegu grzewczego 1"
#define STR701_TEXT "Przycisk obecności"
#define STR709_TEXT "Minimalna temperatura komfortu"
#define STR710_TEXT "Nastawa temperatury komfortu"
#define STR711_TEXT "Maksymalna temperatura komfortu"
#define STR712_TEXT "Nastawa temperatury zredukowanej"
#define STR714_TEXT "Nastawa temperatury ochrony przeciwmrozowej"
#define STR720_TEXT "Nachylenie krzywej grzania"
#define STR721_TEXT "Przesunięcie krzywej grzania"
#define STR726_TEXT "Adaptacja krzywej grzania"
#define STR730_TEXT "Temperatura przełączenia (graniczna) lato/zima"
#define STR732_TEXT "Dobowa granica ogrzewania"
#define STR733_TEXT "Wydłużenie dziennego limitu ogrzewania"
#define STR734_TEXT "Obniżenie temperatury pomieszczenia z timerem"
#define STR740_TEXT "Minimalna temperatura zadana zasilania"
#define STR741_TEXT "Maksymalna temperatura zadana zasilania"
#define STR742_TEXT "Temperatura zadana zasilająca termostat"
#define STR744_TEXT "Włącz. stopn. pom."
#define STR750_TEXT "Wpływ temperatury pomieszczenia"
#define STR760_TEXT "Ograniczenie temperatury w pomieszczeniu"
#define STR761_TEXT "Granica ogrzewania regulatora pokojowego"
#define STR770_TEXT "Szybkie nagrzewanie"
#define STR780_TEXT "Szybkie obniżenie temperatury"
#define STR781_TEXT "Współczynnik szybkiego obniżania"
#define STR790_TEXT "Optymalizacja załączania ogrzewania"
#define STR791_TEXT "Optymalizacja wyłączenia ogrzewania"
#define STR800_TEXT "Zwiękrzenie temperatury zredukowanej -początek"
#define STR801_TEXT "Zwiękrzenie temperatury zredukowanej -koniec"
#define STR809_TEXT "Ciągła praca pompy"
#define STR820_TEXT "Ochrona przegrzania CO z pompą"
#define STR830_TEXT "Zawór mieszający podwyższa temperaturę"
#define STR834_TEXT "Czas przebiegu siłownika"
#define STR850_TEXT "Osuszanie jastrychu"
#define STR851_TEXT "Temperaturą zadana ręczne osuszanie jastrychu"
#define STR855_TEXT "Aktualna temperatura zadana suszenia jastrychu"
#define STR861_TEXT "Odbiór nadwyżki ciepła"
#define STR870_TEXT "Z zasobnikiem buforowym"
#define STR872_TEXT "Z regulacją wstępną/pompą dosyłania"
#define STR880_TEXT "Zmniejszenie prędkości pompy obiegu 1"
#define STR882_TEXT "Minimalna prędkość pompy"
#define STR883_TEXT "Maksymalna prędkość pompy"
#define STR884_TEXT "Punkt doboru pompy"
#define STR885_TEXT "Pompa modul. PWM min."
#define STR886_TEXT "Standard. temp. zewn."
#define STR887_TEXT "Temp. zasil. dla st. temp. zew"
#define STR888_TEXT "dT współcz. zwiększ."
#define STR888_2_TEXT "Korekta krzywej przy prędkości 50%"
#define STR890_TEXT "Korekta prędkości regulacji zasilania"
#define STR894_TEXT "dT różn. dla st. temp. zewn."
#define STR895_TEXT "dT Spreizung Maximum"
#define STR898_TEXT "Przełączenie poziomu roboczego"
#define STR900_TEXT "Przełączanie trybu pracy"
#define STR1000_TEXT "Tryb pracy obiegu grzewczego 2"
#define STR1010_TEXT "Nastawa temp. komfortu obieg 2"
#define STR1012_TEXT "Nastawa temp. zredukowanej obieg 2"
#define STR1014_TEXT "Nastawa temp. ochrony p-mroz. obieg 2"
#define STR1020_TEXT "Nachylenie krzywej grzewczej obiegu 2"
#define STR1021_TEXT "Przesun. krzywej grzania"
#define STR1030_TEXT "Temperatura przełączenia lato/zima obieg 2"
#define STR1090_TEXT "Optymalizacja załączania maks. czas obieg 2"
#define STR1130_TEXT "Podw. temp. dla mieszacza"
#define STR1134_TEXT "Czas przebiegu siłownika"
#define STR1150_TEXT "Osuszanie jastrychu"
#define STR1600_TEXT "Tryb pracy CWU"
#define STR1601_TEXT "Wybór trybu pracy Eko"
#define STR1602_TEXT "Stan CWU"
#define STR1603_TEXT "Ręczne CWU-Push"
#define STR1610_TEXT "Temperatura zadana"
#define STR1612_TEXT "Temperatura zadana - zredukowana"
#define STR1614_TEXT "Maksymalna temperatura zadana"
#define STR1620_TEXT "Zwolnienie do pracy"
#define STR1630_TEXT "Priorytet ładowania CWU"
#define STR1640_TEXT "Dezynfekcja termiczna"
#define STR1641_TEXT "Dezynfekcja - okresowo"
#define STR1642_TEXT "Dezynfekcja - dzień tygodnia"
#define STR1644_TEXT "Dezynfekcja - godzina"
#define STR1645_TEXT "Dezynfekcja - wartość zadana"
#define STR1646_TEXT "Dezynfekcja - czas trwania"
#define STR1647_TEXT "Dezynfekcja - pompa cyrkulacyjna"
#define STR1660_TEXT "Uruchamianie pompy cyrkulacyjnej"
#define STR1661_TEXT "Taktowanie pompy cyrkulacyjnej"
#define STR1663_TEXT "wartosc zadana - cyrkulacja"
#define STR1680_TEXT "Przełączanie trybu pracy"
#define STR2201_TEXT "Blokada źródła ciepła"
#define STR2210_TEXT "Minimalna temperatura zadana"
#define STR2212_TEXT "Maksymalna temperatura zadana"
#define STR2214_TEXT "Temperatura zadana - tryb ręczny"
#define STR2241_TEXT "Minimalny czas pracy palnika"
#define STR2243_TEXT "Minimalny czas wyłączenia palnika"
#define STR2245_TEXT "Histereza wyłączenia palnika"
#define STR2250_TEXT "Czas wybiegu pompy"
#define STR2253_TEXT "Czas wybieg. pompy po CWU"
#define STR2300_TEXT "Ochr. p-mroz. pompa kotła"
#define STR2301_TEXT "Pompa kotła po blok. źr.ciep"
#define STR2305_TEXT "Wpływ blokady źródła ciepła"
#define STR2315_TEXT "Minimalna różnica temp"
#define STR2316_TEXT "Maks. różnica temp"
#define STR2317_TEXT "Nominalna różnica temp"
#define STR2320_TEXT "Modulacja pompy"
#define STR2330_TEXT "Moc nominalna"
#define STR2331_TEXT "Moc stopnia podstawowego"
#define STR2334_TEXT "Moc przy minimalnej prędkości pompy"
#define STR2335_TEXT "Moc przy maksymalnej prędkości pompy"
#define STR2440_TEXT "Maks. PWM went. ogrzew."
#define STR2441_TEXT "Maks. prędk. went. - ogrzew."
#define STR2442_TEXT "Opóźn. regul. went. PWM"
#define STR2443_TEXT "Wart. start. PWM dla podgrz."
#define STR2451_TEXT "Min. czas wyłącz. palnika"
#define STR2452_TEXT "Hist. wył. palnika"
#define STR2453_TEXT "Czas opóźn. regulat."
#define STR2454_TEXT "Histereza kotła"
#define STR2455_TEXT "Histereza wył. kotła min."
#define STR2456_TEXT "Histereza wył. kotła maks."
#define STR2471_TEXT "Czas wybiegu pompy"
#define STR2472_TEXT "Czas wybiegu pompy CWU"
#define STR2478_TEXT "Parametr"
#define STR2521_TEXT "Temp. włącz. ochron.p-mroz."
#define STR2522_TEXT "Temp. wył. ochron. p-mroz."
#define STR2730_TEXT "Prąd jonizacji"
#define STR3810_TEXT "Różn. temp. zał."
#define STR3811_TEXT "Różn. temp. wył."
#define STR3840_TEXT "Ochrona p-mroz. kolektora"
#define STR3850_TEXT "Ochrona kol. przed przegrz."
#define STR3860_TEXT "Parowanie nośnika ciepła"
#define STR4721_TEXT "Hister. autoblokady źródła"
#define STR4722_TEXT "Rożn. temp. bufor/CO"
#define STR5010_TEXT "Ładowanie CWU"
#define STR5011_TEXT "Wyprzedzenie ładowania"
#define STR5019_TEXT "Ponowne ład. zasobnika"
#define STR5020_TEXT "Podwyższona temperatura zadanego zasilania"
#define STR5022_2_TEXT "Sposób ładowania"
#define STR5030_TEXT "Ograniczenie czasu ładowania"
#define STR5040_TEXT "Ochrona przed rozładowaniem"
#define STR5050_TEXT "Maksymalna temperatura ładowania"
#define STR5051_TEXT "Maksymalna temperatura CWU"
#define STR5055_TEXT "Temperatura wychłodzenia"
#define STR5057_TEXT "Wychłodzenie kolektora"
#define STR5060_TEXT "Tryb pracy grzałki elektrycznej"
#define STR5061_TEXT "Zwolnienie grzałki elektrycznej"
#define STR5062_TEXT "Regulacja grzałki elektrycznej"
#define STR5070_TEXT "Automatyczne wymuszenie(Push)"
#define STR5090_TEXT "Z zasobnikiem buforowym"
#define STR5092_TEXT "Z regulatorem/pompą dosyłową"
#define STR5093_TEXT "Integracja z układem solarnym"
#define STR5101_TEXT "Minimalna prędkość pompy"
#define STR5102_TEXT "Maksymalna prędkość pompy"
#define STR5130_TEXT "Sposób ładowania"
#define STR5482_TEXT "Czas detekt. przepł. odbior."
#define STR5483_TEXT "Czas detekt. przepł. Komf."
#define STR5701_TEXT "Schemat hydrauliczny"
#define STR5710_TEXT "Obieg CO 1"
#define STR5715_TEXT "Obieg CO 2"
#define STR5730_TEXT "Czujnik CWU B3"
#define STR5731_TEXT "Element wykonawczy CWU Q3"
#define STR5734_TEXT "Podst. poz. zaw. rozdz. cwu"
#define STR5736_TEXT "Oddzielny układ CWU"
#define STR5761_TEXT "Pompa dosyłowa Q8"
#define STR5774_TEXT "Ster. pompą kot./zaw. CWU"
#define STR5800_TEXT "Źródło ciepła"
#define STR5920_TEXT "Wyjście przekaź. K2 LMU"
#define STR5921_TEXT "Domyślnie K2 do K1"
#define STR5922_TEXT "Wyjście przekaź. 1 RelCl"
#define STR5923_TEXT "Wyjście przekaź. 2 RelCl"
#define STR5924_TEXT "Wyjście przekaź. 3 RelCl"
#define STR5926_TEXT "Wyjście przekaź. 1 SolCl"
#define STR5927_TEXT "Wyjście przekaź. 2 SolCl"
#define STR5928_TEXT "Wyjście przekaź. 3 SolCl"
#define STR5950_TEXT "Funkcja wejścia H1"
#define STR5957_TEXT "Modem"
#define STR5970_TEXT "Konfig. termost. pom. 1"
#define STR5971_TEXT "Konfig. termost. pom. 2"
#define STR5973_TEXT "Funkcja wejścia RelCl"
#define STR5975_TEXT "Max. nastawa temp. zasil."
#define STR5976_TEXT "Próg zewn. nastawy mocy"
#define STR6110_TEXT "Stała czasowa budynku"
#define STR6112_TEXT "Gradient modelu pomieszcz."
#define STR6120_TEXT "Ochrona p-mroz. instalacji"
#define STR6220_TEXT "Wersja oprogramowania"
#define STR6225_TEXT "Grupa urządz."
#define STR6226_TEXT "Wariant urządzenia"
#define STR6227_TEXT "Wersja katalogu obiekt."
#define STR6228_TEXT "Wersja Bootloader"
#define STR6229_TEXT "Wersja EEPROM"
#define STR6230_TEXT "Konfig. regulatora 0"
#define STR6230_2_TEXT "Konfiguracja - Info 1 OEM"
#define STR6231_TEXT "Konfiguracja - Info 2 OEM"
#define STR6240_TEXT "Konfig. regulatora 1"
#define STR6250_TEXT "Konfig. regulatora 2"
#define STR6260_TEXT "Konfig. regulatora 3"
#define STR6270_TEXT "Konfig. regulatora 4"
#define STR6300_TEXT "Konfig. regulatora 7"
#define STR6300_2_TEXT "Info 1 OEM"
#define STR6604_TEXT "Funkcja zasil. magistrali"
#define STR6605_TEXT "Stan zasilania magistrali"
#define STR6640_TEXT "Tryb zegara"
#define STR6705_TEXT "Kod diagnostyczny SW"
#define STR6706_TEXT "Faza regul. paln. poz. zablok."
#define STR6710_TEXT "Reset przek. sygn alarm."
#define STR6740_TEXT "Alarm - temperatura zasilania 1"
#define STR6741_TEXT "Alarm - temperatura zasilania 2"
#define STR6742_TEXT "Alarm - temperatura zasilania 3"
#define STR6743_TEXT "Alarm temperatura kotła"
#define STR6745_TEXT "Alarm ładowania CWU"
#define STR6800_2_TEXT "Historia 1"
#define STR6805_2_TEXT "Kod diagnostyczny SW 1"
#define STR6806_2_TEXT "Faza FA 1"
#define STR6810_2_TEXT "Historia 2"
#define STR6811_2_TEXT "Kod błędu 2"
#define STR6815_2_TEXT "Kod diagnostyczny SW 2"
#define STR6816_2_TEXT "Faza FA 2"
#define STR6820_2_TEXT "Historia 3"
#define STR6821_TEXT "Kod błędu 3"
#define STR6825_TEXT "Kod diagnostyczny SW 3"
#define STR6826_TEXT "Regul. palnika faza 3"
#define STR6831_TEXT "Kod błędu 4"
#define STR6835_TEXT "Kod diagnostyczny SW 4"
#define STR6836_TEXT "Regul. palnika faza 4"
#define STR6845_TEXT "Kod diagnostyczny SW 5"
#define STR6846_TEXT "Regul. palnika faza 5"
#define STR6855_TEXT "Kod diagnostyczny SW 6"
#define STR6856_TEXT "Faza FA 6"
#define STR6865_TEXT "Kod diagnostyczny SW 7"
#define STR6866_TEXT "Faza FA 7"
#define STR6875_TEXT "Kod diagnostyczny SW 8"
#define STR6876_TEXT "Faza FA 8"
#define STR6885_TEXT "Kod diagnostyczny SW 9"
#define STR6886_TEXT "Faza FA 9"
#define STR6895_TEXT "Kod diagnostyczny SW 10"
#define STR6896_TEXT "Faza FA 10"
#define STR6905_TEXT "Kod diagnostyczny SW 11"
#define STR6906_TEXT "Faza FA 11"
#define STR6915_TEXT "Kod diagnostyczny SW 12"
#define STR6916_TEXT "Faza FA 12"
#define STR6925_TEXT "Kod diagnostyczny SW 13"
#define STR6926_TEXT "Faza FA 13"
#define STR6935_TEXT "Kod diagnostyczny SW 14"
#define STR6936_TEXT "Faza FA 14"
#define STR6945_TEXT "Kod diagnostyczny SW 15"
#define STR6946_TEXT "Faza FA 15"
#define STR6955_TEXT "Kod diagnostyczny SW 16"
#define STR6956_TEXT "Faza FA 16"
#define STR6965_TEXT "Kod diagnostyczny SW 17"
#define STR6966_TEXT "Faza FA 17"
#define STR6975_TEXT "Kod diagnostyczny SW 18"
#define STR6976_TEXT "Faza FA 18"
#define STR6985_TEXT "Kod diagnostyczny SW 19"
#define STR6986_TEXT "Faza FA 19"
#define STR6995_TEXT "Kod diagnostyczny SW 20"
#define STR6996_TEXT "Faza FA 20"
#define STR6800_TEXT "Historia 1 Data/godzina"
#define STR6801_TEXT "Historia 1 Kod błędu"
#define STR6802_TEXT "Historia 2 Data/godzina"
#define STR6803_TEXT "Historia 2 Kod błędu"
#define STR6804_TEXT "Historia 3 Data/godzina"
#define STR6805_TEXT "Historia 3 Kod błędu"
#define STR6806_TEXT "Historia 4 Data/godzina"
#define STR6807_TEXT "Historia 4 Kod błędu"
#define STR6808_TEXT "Historia 5 Data/godzina"
#define STR6809_TEXT "Historia 5 Kod błędu"
#define STR6810_TEXT "Historia 6 Data/godzina"
#define STR6811_TEXT "Historia 6 Kod błędu"
#define STR6812_TEXT "Historia 7 Data/godzina"
#define STR6813_TEXT "Historia 7 Kod błędu"
#define STR6814_TEXT "Historia 8 Data/godzina"
#define STR6815_TEXT "Historia 8 Kod błędu"
#define STR6816_TEXT "Historia 9 Data/godzina"
#define STR6817_TEXT "Historia 9 Kod błędu"
#define STR6818_TEXT "Historia 10 Data/godzina"
#define STR6819_TEXT "Historia 10 Kod błędu"
#define STR6900_TEXT "Historia 11 Data/godzina"
#define STR6901_TEXT "Historia 11 Kod błędu"
#define STR6910_TEXT "Historia 12 Data/godzina"
#define STR6911_TEXT "Historia 12 Kod błędu"
#define STR6920_TEXT "Historia 13 Data/godzina"
#define STR6921_TEXT "Historia 13 Kod błędu"
#define STR6930_TEXT "Historia 14 Data/godzina"
#define STR6931_TEXT "Historia 14 Kod błędu"
#define STR6940_TEXT "Historia 15 Data/godzina"
#define STR6941_TEXT "Historia 15 Kod błędu"
#define STR6950_TEXT "Historia 16 Data/godzina"
#define STR6951_TEXT "Historia 16 Kod błędu"
#define STR6960_TEXT "Historia 17 Data/godzina"
#define STR6961_TEXT "Historia 17 Kod błędu"
#define STR6970_TEXT "Historia 18 Data/godzina"
#define STR6971_TEXT "Historia 18 Kod błędu"
#define STR6980_TEXT "Historia 19 Data/godzina"
#define STR6981_TEXT "Historia 19 Kod błędu"
#define STR6990_TEXT "Historia 20 Data/godzina"
#define STR6991_TEXT "Historia 20 Kod błędu"
#define STR6820_TEXT "Reset historii"
#define STR7001_TEXT "Komunikat"
#define STR7010_TEXT "Potwierdzenie wiadomości"
#define STR7011_TEXT "Czas powtórz. wiadomości"
#define STR7050_TEXT "Prędk. went. prąd jonizacji"
#define STR7051_TEXT "Wiadomość - prąd joniz."
#define STR8000_TEXT "Stan 1. obiegu CO"
#define STR8001_TEXT "Stan 2. obiegu CO"
#define STR8003_TEXT "Stan CWU"
#define STR8005_TEXT "Stan kotła"
#define STR8007_TEXT "Stan kolektora"
#define STR8023_TEXT "Status Sitherm Pro"
#define STR8304_TEXT "Pompa kotła Q1"
#define STR8310_TEXT "Temperatura w kotle"
#define STR8311_TEXT "Wartość zadana kotła"
#define STR8312_TEXT "Punkt przełączania dla kotła"
#define STR8313_TEXT "Czujnik regulacyjny"
#define STR8314_TEXT "Temp. powrotu do kotła"
#define STR8316_TEXT "Temp. spalin"
#define STR8323_TEXT "Prędkość wentylatora"
#define STR8324_TEXT "Nastawa wentylatora"
#define STR8325_TEXT "Aktualne ster. wentylatora"
#define STR8326_TEXT "Wydajność wzgl."
#define STR8327_TEXT "Ciśnienie wody"
#define STR8328_TEXT "Wskaz. stanu reg. palnika"
#define STR8330_TEXT "Betriebsstunden 1.Stufe"
#define STR8336_TEXT "Czas pracy urządzenia"
#define STR8337_TEXT "Licznik startów palnika"
#define STR8338_TEXT "Czas pracy w trybie ogrzew"
#define STR8340_TEXT "Czas pracy stref"
#define STR8510_TEXT "Temperatura kolektora 1"
#define STR8530_TEXT "Czas pracy z wykorzystaniem kolektora"
#define STR8700_TEXT "Temperatura zewnętrzna"
#define STR8701_TEXT "Minimalna temperatura zewnętrzna"
#define STR8702_TEXT "Maksymalna temperatura zewnętrzna"
#define STR8703_TEXT "Zredukowana temperatura zewnętrzna"
#define STR8704_TEXT "Mieszana temperatura zewnętrzna"
#define STR8730_TEXT "Pompa Q2 obiegu grzewczego 1"
#define STR8731_TEXT "Mieszczacz 1 obiegu CO otwarty"
#define STR8732_TEXT "Mieszczacz 1 obiegu CO zamykanie"
#define STR8735_TEXT "Prędkość pompy obiegu grzewczego 1"
#define STR8739_TEXT "Tłumiona temperatura zewnętrzna"
#define STR8740_TEXT "Temperatura w pomieszczeniu 1"
#define STR8741_TEXT "Wartość zadana w pomieszczeniu 1"
#define STR8743_TEXT "Temperatura zasilania 1"
#define STR8744_TEXT "Temperatura zadana zasilania 1"
#define STR8749_TEXT "Termostat w pomieszczeniu 1"
#define STR8750_TEXT "Nastawa pompy modul."
#define STR8760_TEXT "Pompa 2 obiegu CO"
#define STR8761_TEXT "Mieszczacz 2 obiegu CO otwarty"
#define STR8762_TEXT "Mieszczacz 2 obiegu CO zamykanie"
#define STR8765_TEXT "Prędkość pompy obiegu grzewczego 2"
#define STR8770_TEXT "Temperatura w pomieszczeniu 2"
#define STR8771_TEXT "Wart. zad. w pomieszcz. 2"
#define STR8773_TEXT "Temp. zasilania 2"
#define STR8774_TEXT "Temp. zadana zasilania 2"
#define STR8779_TEXT "Termostat pomieszczenia 2"
#define STR8790_TEXT "Pompa 3"
#define STR8809_TEXT "Termostat pomieszczenia 3"
#define STR8830_TEXT "Temperatura CWU"
#define STR8831_TEXT "Temperatura zadana CWU"
#define STR8832_TEXT "Temperatura CWU 2"
#define STR8835_TEXT "Temperatura cyrkulacji CWU"
#define STR8836_TEXT "Temperatura ładowania CWU"
#define STR8980_TEXT "Temp. w zasob. bufor. 1"
#define STR8950_TEXT "Temperatura wspólna zasilania"
#define STR8951_TEXT "Wartość zadana zasilania wspólnego"
#define STR8952_TEXT "Temperatura wspólna powrotu"
#define STR8981_TEXT "Wartość zadana zasobnika buforowego"
#define STR9009_TEXT "Ciśnienie wody H3"
#define STR9500_TEXT "Czas przed oczyszcz."
#define STR9502_TEXT "Ster. went. przed oczyszcz."
#define STR9504_TEXT "Wym. pręd. przed oczyszcz."
#define STR9510_TEXT "Ster. went. podczas zapłonu"
#define STR9512_TEXT "Wymag. prędkość zapłonu"
#define STR9520_TEXT "Min. wysterow. went"
#define STR9522_TEXT "Maks. wysterow. went."
#define STR9524_TEXT "Wymag. prędkość min."
#define STR9527_TEXT "Wymag. prędkość maks."
#define STR9540_TEXT "Czas po oczyszczaniu"
#define STR9560_TEXT "Ster. went.  pełne ładow."
#define STR9563_TEXT "Wym. prędk. dla pełn. ładow."
#define ENUM22_01_TEXT "Tymczasowy"
#define ENUM22_02_TEXT "Stały"
#define ENUM23_00_TEXT "Kod"
#define ENUM23_01_TEXT "Kod i tekst"
#define ENUM28_01_TEXT "Zapisz automatycznie"
#define ENUM28_02_TEXT "Zapisz z potwierdzeniem"
#define ENUM29_01_TEXT "°C,bar"
#define ENUM29_02_TEXT "°F,PSI"
#define ENUM40_00_TEXT "Regulator pokojowy 1"
#define ENUM40_01_TEXT "Regulator pokojowy 2"
#define ENUM40_02_TEXT "Regulator pokojowy P"
#define ENUM40_03_TEXT "Jednostka sterująca 1"
#define ENUM40_04_TEXT "Jednostka sterująca 2"
#define ENUM40_05_TEXT "Urządzenie serwisowe"
#define ENUM42_01_TEXT "Obieg grzewczy 1 i 2"
#define ENUM42_02_TEXT "Obieg grzewczy 1 i P"
#define ENUM42_03_TEXT "Wszystkie obiegi grzewcze"
#define ENUM44_01_TEXT "Razem z pompą obiegu 1"
#define ENUM44_02_TEXT "Niezależny"
#define ENUM47_02_TEXT "Dla wszystkich przypisanych obiegów grzewczych"
#define ENUM48_00_TEXT "Nie"
#define ENUM48_03_TEXT "Razem"
#define ENUM130_00_TEXT "Brakujący"
#define ENUM130_01_TEXT "W trakcie"
#define ENUM130_02_TEXT "Brak odbioru"
#define ENUM130_03_TEXT "Zmień baterię"
#define ENUM648_00_TEXT "Ochrona przez zamarzaniem"
#define ENUM648_01_TEXT "Zredukowany"
#define ENUM700_00_TEXT "Tryb ochrony"
#define ENUM700_01_TEXT "Automatyczny"
#define ENUM700_03_TEXT "Komfort"
#define ENUM702_00_TEXT "Tryb letni"
#define ENUM702_01_TEXT "Program ogrzewania 1"
#define ENUM702_02_TEXT "Program oszczędny"
#define ENUM702_03_TEXT "Program normalny"
#define ENUM702_04_TEXT "Nieznany"
#define ENUM702_05_TEXT "Program ogrzewania 2"
#define ENUM702_06_TEXT "Program ogrzewania 3"
#define ENUM703_00_TEXT "Obecny"
#define ENUM703_01_TEXT "Nieobecny"
#define ENUM780_01_TEXT "Do obniżonej wartości zadanej"
#define ENUM780_02_TEXT "Do wartości zadanej ochrony przed zamarzaniem"
#define ENUM832_00_TEXT "2-punktowy"
#define ENUM832_01_TEXT "3-punktowy"
#define ENUM850_05_TEXT "Ręczny"
#define ENUM861_01_TEXT "Tryb ogrzewania"
#define ENUM861_02_TEXT "Zawsze"
#define ENUM880_00_TEXT "Poziom operacyjny"
#define ENUM880_01_TEXT "Charakterystyka"
#define ENUM880_02_TEXT "Nominalny skok temperatury"
#define ENUM1600_02_TEXT "Eko"
#define ENUM1602_00_02_TEXT "CWU-Push nieaktywne"
#define ENUM1602_02_02_TEXT "CWU-Push aktywne"
#define ENUM1602_00_04_TEXT "CWU wyłączona"
#define ENUM1602_04_04_TEXT "CWU włączona"
#define ENUM1602_00_08_TEXT "Ładowanie CWU nieaktywne"
#define ENUM1602_08_08_TEXT "Ładowanie CWU aktywne"
#define ENUM1620_00_TEXT "24h/dzień"
#define ENUM1620_01_TEXT "Programy czasowe obiegów grzewczych"
#define ENUM1620_02_TEXT "Program czasowy 4/CWU"
#define ENUM1630_01_TEXT "Pływający"
#define ENUM1630_02_TEXT "Nie"
#define ENUM1640_01_TEXT "Okresowo"
#define ENUM1660_02_TEXT "Uwalnianie wody pitnej"
#define ENUM2150_00_TEXT "Z pamięci podręcznej"
#define ENUM2200_00_TEXT "Praca ciągła"
#define ENUM2205_01_TEXT "Woda pitna"
#define ENUM2206_00_TEXT "Działanie"
#define ENUM2206_01_TEXT "Tryb gotowości"
#define ENUM2291_00_TEXT "Praca z palnikiem równoległym"
#define ENUM2291_01_TEXT "Temperatura powrotu"
#define ENUM2305_00_TEXT "Tylko ogrzewanie"
#define ENUM2305_01_TEXT "Ogrzewanie i eksploatacja wody pitnej"
#define ENUM2320_01_TEXT "Zapotrzebowanie"
#define ENUM2320_02_TEXT "Wartość zadana kotła"
#define ENUM2320_04_TEXT "Wydajność palnika"
#define ENUM2450_02_TEXT "Tylko woda pitna"
#define ENUM2480_00_TEXT "Rozpocznij zapobieganie"
#define ENUM2480_ff_TEXT "Pozycja błędu"
#define ENUM2706_00_TEXT "Zablokowany"
#define ENUM2706_01_TEXT "Tryb testowy silnika krokowego"
#define ENUM2706_02_TEXT "Rozpocznij ręczny test znoszenia"
#define ENUM2706_04_TEXT "Inicjalizacja"
#define ENUM2706_05_TEXT "Zapłon"
#define ENUM2706_06_TEXT "Wykrywanie zimnego startera"
#define ENUM2706_07_TEXT "Korekta"
#define ENUM2706_08_TEXT "Stabilizacja"
#define ENUM2706_09_TEXT "Sterowanie"
#define ENUM2706_0a_TEXT "Działanie gazu niebezpiecznego"
#define ENUM2706_0b_TEXT "Kontrola optymalizacji spalania aktywna"
#define ENUM2706_0c_TEXT "Kontrola optymalizacji spalania wymagana"
#define ENUM2706_0d_TEXT "Kontrola optymalizacji spalania zaległa"
#define ENUM2706_12_TEXT "ADA 1 wymagany"
#define ENUM2721_01_TEXT "Gaz ziemny"
#define ENUM2721_02_TEXT "LPG"
#define ENUM2727_01_TEXT "Obszar 1"
#define ENUM2727_02_TEXT "Obszar 2"
#define ENUM2727_03_TEXT "Obszar 3"
#define ENUM2749_01_TEXT "Nowa elektroda"
#define ENUM2749_02_TEXT "Zużyta elektroda"
#define ENUM2880_02_TEXT "Dodatkowy obieg grzewczy"
#define ENUM2920_01_TEXT "Udostępniono"
#define ENUM3090_00_TEXT "Nie (z wejściem)"
#define ENUM3092_00_TEXT "kWh"
#define ENUM3095_01_TEXT "Z wejściem H1"
#define ENUM3095_02_TEXT "Z wejściem H2 Modul 1"
#define ENUM3095_03_TEXT "Z wejściem H2 Modul 2"
#define ENUM3095_04_TEXT "Z wejściem H2 Modul 3"
#define ENUM3095_05_TEXT "Z wejściem H21 Modul 1"
#define ENUM3095_06_TEXT "Z wejściem H21 Modul 2"
#define ENUM3095_07_TEXT "Z wejściem H21 Modul 3"
#define ENUM3095_08_TEXT "Z wejściem H22 Modul 1"
#define ENUM3095_09_TEXT "Z wejściem H22 Modul 2"
#define ENUM3095_0a_TEXT "Z wejściem H22 Modul 3"
#define ENUM3095_0b_TEXT "Z wejściem H3"
#define ENUM3095_0c_TEXT "Z wejściem H31"
#define ENUM3095_0d_TEXT "Z wejściem H32"
#define ENUM3102_02_TEXT "m3"
#define ENUM3109_01_TEXT "Ciepło oddane"
#define ENUM3109_02_TEXT "Zużyta energia"
#define ENUM3109_03_TEXT "Oba"
#define ENUM3510_00_TEXT "Późno, wcześnie"
#define ENUM3510_01_TEXT "Późno, późno"
#define ENUM3510_02_TEXT "Wcześnie, późno"
#define ENUM3541_01_TEXT "Pierwszy"
#define ENUM3541_02_TEXT "Ostatni"
#define ENUM3544_00_TEXT "Źródło 1"
#define ENUM3544_01_TEXT "Źródło 2"
#define ENUM3544_02_TEXT "Źródło 3"
#define ENUM3544_03_TEXT "Źródło 4"
#define ENUM3544_04_TEXT "Źródło 5"
#define ENUM3544_05_TEXT "Źródło 6"
#define ENUM3544_06_TEXT "Źródło 7"
#define ENUM3544_07_TEXT "Źródło 8"
#define ENUM3544_08_TEXT "Źródło 9"
#define ENUM3544_09_TEXT "Źródło 10"
#define ENUM3544_0a_TEXT "Źródło 11"
#define ENUM3544_0b_TEXT "Źródło 12"
#define ENUM3544_0c_TEXT "Źródło 13"
#define ENUM3544_0d_TEXT "Źródło 14"
#define ENUM3544_0e_TEXT "Źródło 15"
#define ENUM3544_0f_TEXT "Źródło 16"
#define ENUM3880_02_TEXT "Glikol etylenowy"
#define ENUM3880_03_TEXT "Glikol propylenowy"
#define ENUM3880_04_TEXT "Glikol etylenowy i propylenowy"
#define ENUM3887_03_TEXT "Litr"
#define ENUM4133_01_TEXT "Czujnik wody pitnej B3"
#define ENUM4133_02_TEXT "Czujnik wody pitnej B31"
#define ENUM4133_03_TEXT "Czujnik zbiornika buforowego B4"
#define ENUM4133_04_TEXT "Czujnik zbiornika buforowego B41"
#define ENUM4133_05_TEXT "Wartość zadana przepływu"
#define ENUM4133_06_TEXT "Minimum wartości zadanej"
#define ENUM4720_01_TEXT "Z B4"
#define ENUM4720_02_TEXT "Z B4 i B42/41"
#define ENUM4757_01_TEXT "Lato"
#define ENUM4795_02_TEXT "Z B41"
#define ENUM4795_03_TEXT "Z B42"
#define ENUM4796_01_TEXT "Redukcja temperatury"
#define ENUM4796_02_TEXT "Wzrost temperatury"
#define ENUM4813_02_TEXT "Z B42/B41"
#define ENUM5010_00_TEXT "Raz dziennie"
#define ENUM5010_ff_TEXT "Wiele razy dziennie"
#define ENUM5022_01_TEXT "Z B3"
#define ENUM5022_02_TEXT "Z B3/B31"
#define ENUM5022_03_TEXT "Z B3, Legio B3/31"
#define ENUM5022_2_01_TEXT "Przeładuj"
#define ENUM5022_2_02_TEXT "Załaduj"
#define ENUM5040_02_TEXT "Automatyczny"
#define ENUM5060_01_TEXT "Wymiana"
#define ENUM5062_01_TEXT "Termostat zewnętrzny"
#define ENUM5062_02_TEXT "Czujnik wody pitnej"
#define ENUM5130_01_TEXT "Uwolnienie ciepłej wody"
#define ENUM5700_01_TEXT "Ustawienie domyślne obwodu grzewczego 1: 1 z rezystorem grzejnym lub bez niego oraz z ciepłą wodą użytkową lub bez niej"
#define ENUM5700_02_TEXT "Ustawienie domyślne obiegów grzewczych 2: 2 z lub bez rezystora grzejnego i z ciepłą wodą lub bez"
#define ENUM5700_03_TEXT "Ustawienie domyślne 3: Transfer z kotła, 1 obieg grzewczy z ciepłą wodą lub bez"
#define ENUM5700_04_TEXT "Ustawienie domyślne 4: Transfer z kotła, 2 obiegi grzewcze z ciepłą wodą lub bez"
#define ENUM5700_05_TEXT "Nieużywany"
#define ENUM5711_01_TEXT "System 4-przewodowy"
#define ENUM5711_02_TEXT "System 2-przewodowy"
#define ENUM5712_01_TEXT "Ogrzewanie"
#define ENUM5712_02_TEXT "Chłodzenie"
#define ENUM5712_03_TEXT "Ogrzewanie i chłodzenie"
#define ENUM5715_01_TEXT "Chłodzenie przewodów"
#define ENUM5715_03_TEXT "Chłodzenie przewodów 2"
#define ENUM5730_00_TEXT "Czujnik"
#define ENUM5730_01_TEXT "Termostat"
#define ENUM5731_00_TEXT "Nie"
#define ENUM5731_01_TEXT "Pompa ładująca"
#define ENUM5731_02_TEXT "Zawór przełączający"
#define ENUM5734_01_TEXT "Obieg grzewczy"
#define ENUM5760_00_TEXT "Przed buforem"
#define ENUM5761_01_01_TEXT "Strefy z pompą podajnika"
#define ENUM5761_02_02_TEXT "Obieg grzewczy 1 z pompą podajnika"
#define ENUM5761_04_04_TEXT "Obieg grzewczy 2 z pompą podajnika"
#define ENUM5761_08_08_TEXT "CWU z pompą podajnika"
#define ENUM5770_00_TEXT "Brak źródła lub PPS-BMU"
#define ENUM5770_01_TEXT "1-etapowy"
#define ENUM5770_02_TEXT "2-etapowy"
#define ENUM5770_03_TEXT "Modulujący 3-punktowy siłownik przepustnicy"
#define ENUM5770_04_TEXT "Modulujący 2-punktowy siłownik przepustnicy"
#define ENUM5770_05_TEXT "Kaskada (dwa palniki 1-stopniowe)"
#define ENUM5774_00_TEXT "Wszystkie wymagania"
#define ENUM5806_01_TEXT "3-etapowy"
#define ENUM5806_02_TEXT "Wyłączenie 2-etapowy"
#define ENUM5806_03_TEXT "Dodatkowo 2-etapowy"
#define ENUM5806_04_TEXT "Modulowanie UX"
#define ENUM5890_01_TEXT "Pompa obiegowa Q4"
#define ENUM5890_02_TEXT "Grzałka CWU K6"
#define ENUM5890_03_TEXT "Pompa kolektora Q5"
#define ENUM5890_04_TEXT "Pompa Q15"
#define ENUM5890_05_TEXT "Pompa kotła Q1"
#define ENUM5890_06_TEXT "Pompa obejściowa Q12"
#define ENUM5890_07_TEXT "Wyjście alarmowe K10"
#define ENUM5890_08_TEXT "2 stopień pompy HK1 Q21"
#define ENUM5890_09_TEXT "2 stopień pompy HK2 Q22"
#define ENUM5890_0a_TEXT "2 stopień pompy HKP Q23"
#define ENUM5890_0b_TEXT "Pompa obiegu grzewczego HKP Q20"
#define ENUM5890_0c_TEXT "Pompa H2 Q18"
#define ENUM5890_0d_TEXT "Zubringerpumpe Q14"
#define ENUM5890_0e_TEXT "Zawor odcinający źródło Y4"
#define ENUM5890_0f_TEXT "Pompa kotła na paliwo stałe Q10"
#define ENUM5890_10_TEXT "Program czasowy 5 K13"
#define ENUM5890_11_TEXT "Zawór powrotny bufora Y15"
#define ENUM5890_12_TEXT "Zewnętrzny wymiennik pompy solarnej K9"
#define ENUM5890_13_TEXT "Pompa kolektora słonecznego zasobnik K8"
#define ENUM5890_14_TEXT "Pompa kolektora słonecznego basen K18"
#define ENUM5890_15_TEXT "Pompa kolektora 2 Q16"
#define ENUM5890_16_TEXT "Pompa H3 Q19"
#define ENUM5890_17_TEXT "Przekaźnik spalin K17"
#define ENUM5890_19_TEXT "Pompa kaskady Q25"
#define ENUM5890_1a_TEXT "Pompa przesyłowa zasobnika Q11"
#define ENUM5890_1b_TEXT "Pompa mieszająca CWU Q35"
#define ENUM5890_1c_TEXT "Pompa obiegowa CWU Q33"
#define ENUM5890_1d_TEXT "Zapotrzebowanie na ciepło K27"
#define ENUM5890_21_TEXT "Pompa obiegu grzewczego 1 HK1 Q2"
#define ENUM5890_28_TEXT "Wyjście sygnału K35"
#define ENUM5890_29_TEXT "Informacja o stanie K36"
#define ENUM5890_2_00_TEXT "Brak funkcji"
#define ENUM5890_2_01_TEXT "Pompa obiegu grzewczego 2"
#define ENUM5890_2_02_TEXT "Pompa zasilająca do BW"
#define ENUM5890_2_03_TEXT "Pompa zasilająca przed BW"
#define ENUM5890_2_04_TEXT "Pompa zasilająca na żądanie zewnętrzne"
#define ENUM5890_2_05_TEXT "Pompa cyrkulacyjna CWU"
#define ENUM5890_2_06_TEXT "Grzałka zanurzeniowa CWU"
#define ENUM5890_2_07_TEXT "Pompa solarna"
#define ENUM5890_2_08_TEXT "Pompa H1"
#define ENUM5890_2_09_TEXT "Pompa kotła"
#define ENUM5890_2_0a_TEXT "Pompa obejściowa kotła"
#define ENUM5890_2_0b_TEXT "Wyjście alarmowe"
#define ENUM5895_02_TEXT "Pompa mieszacza CWU Q3"
#define ENUM5895_03_TEXT "Poziom 2 kompresora K2"
#define ENUM5895_04_TEXT "Zawów przełączający Y22"
#define ENUM5895_05_TEXT "Temperatura gorącego gazu K31"
#define ENUM5895_11_TEXT "2 stopień pompy HK1 Q21"
#define ENUM5895_12_TEXT "2 stopień pompy HK2 Q22"
#define ENUM5895_13_TEXT "2 stopień pompy HKP Q23"
#define ENUM5895_1a_TEXT "Zewnętrzny wymiennik pompy solarnej"
#define ENUM5895_20_TEXT "Chłodzenie zaworu przełączającego Y21"
#define ENUM5895_23_TEXT "Wentylacja K19"
#define ENUM5895_24_TEXT "Pompa skraplacza Q9"
#define ENUM5895_25_TEXT "Osuszacz K29"
#define ENUM5895_2b_TEXT "Wymóg chłodzenia K28"
#define ENUM5895_2c_TEXT "Poziom sprężarki 1 K1"
#define ENUM5920_00_TEXT "Domyślnie, bez funkcji"
#define ENUM5920_01_TEXT "Wyjście sygnału"
#define ENUM5920_03_TEXT "Komunikat"
#define ENUM5920_04_TEXT "Zewnętrzy transformator"
#define ENUM5920_05_TEXT "Pompa obiegu grzewczego HK2 (Q2Y2)"
#define ENUM5920_06_TEXT "Pompa obiegowa"
#define ENUM5920_08_TEXT "Przełącznik hydrauliczny pompy"
#define ENUM5920_09_TEXT "Pompa zasilająca Q8"
#define ENUM5920_0a_TEXT "Funkcja podstawowa K2"
#define ENUM5920_0b_TEXT "Przepływ wody"
#define ENUM5920_0d_TEXT "Klapa wydechowa"
#define ENUM5920_0e_TEXT "Pompa kolektora"
#define ENUM5920_0f_TEXT "Wyłączenie dmuchawy"
#define ENUM5920_10_TEXT "Pompa Q1"
#define ENUM5930_02_TEXT "Czujnik kolektora B6"
#define ENUM5930_03_TEXT "Czujnik powrotu B7"
#define ENUM5930_04_TEXT "Czujnik curkulacji CWU B39"
#define ENUM5930_07_TEXT "Czujnik temperatury spalin B8"
#define ENUM5930_08_TEXT "Czujnik przepływu B10"
#define ENUM5930_09_TEXT "Czujnik kotła na paliwo stałe B22"
#define ENUM5930_0a_TEXT "Czujnik ładowania CWU B36"
#define ENUM5930_0b_TEXT "Czujnik zbiornika buforowego B42"
#define ENUM5930_0c_TEXT "Czujnik powrotu B73"
#define ENUM5930_0d_TEXT "Kaskadowy czujnik powrotu B70"
#define ENUM5930_0e_TEXT "Czujnik basenu B13"
#define ENUM5930_0f_TEXT "Czujnik kolektora 2 B61"
#define ENUM5930_10_TEXT "Czujnik przepływu solarnego B63"
#define ENUM5930_11_TEXT "Czujnik powrotu solarnego B64"
#define ENUM5950_07_TEXT "Komunikat o błędzie / alarmie"
#define ENUM5950_08_TEXT "Minimalna wartość zadana przepływu"
#define ENUM5950_09_TEXT "Wyprowadzanie z nadmiernej temperatury"
#define ENUM5950_0b_TEXT "Monitor punktu rosy"
#define ENUM5950_0d_TEXT "Zapotrzebowanie na ciepło 10V"
#define ENUM5950_0e_TEXT "Pomiar ciśnienia 10V"
#define ENUM8000_03_TEXT "Zadziałał czujnik ograniczenia"
#define ENUM8000_04_TEXT "Tryb ręczny aktywny"
#define ENUM8000_16_TEXT "Ochrona przeciwmrozowa instalacji aktywna"
#define ENUM8000_17_TEXT "Ochrona przeciwmrozowa aktywna"
#define ENUM8000_38_TEXT "Ochrona przed przegrzaniem aktywna"
#define ENUM8000_65_TEXT "Ochrona przeciwmrozowa pomieszczenia aktywna"
#define ENUM8000_66_TEXT "Suszenie jastrychu aktywne"
#define ENUM8000_67_TEXT "Ograniczony, ochrona kotła"
#define ENUM8000_68_TEXT "Ograniczony, priorytet CWU"
#define ENUM8000_69_TEXT "Ograniczony, bufor"
#define ENUM8000_6b_TEXT "Wymuszony odbiór bufor"
#define ENUM8000_6c_TEXT "Wymuszony odbiór CWU"
#define ENUM8000_6d_TEXT "Wymuszony odbiór Źródło"
#define ENUM8000_6e_TEXT "Wymuszony odbiór"
#define ENUM8000_6f_TEXT "Optymalizacja zał. + szybkie nagrzewanie"
#define ENUM8000_70_TEXT "Optymalizacja załączania"
#define ENUM8000_71_TEXT "Szybkie nagrzewanie"
#define ENUM8000_72_TEXT "Tryb komfortowy"
#define ENUM8000_73_TEXT "Optymalizacja wyłączania"
#define ENUM8000_74_TEXT "Tryb zredukowany CO"
#define ENUM8000_75_TEXT "Ochrona przeciwmrozowa aktywna"
#define ENUM8000_76_TEXT "Tryb letni"
#define ENUM8000_77_TEXT "Dobowa funkcja Eco aktywna"
#define ENUM8000_78_TEXT "Obniżenie, zdredukowany"
#define ENUM8000_79_TEXT "Obniżenie, ochrona przeciwmrozowa"
#define ENUM8000_7a_TEXT "Ograniczenie temperatury w pomieszeniu"
#define ENUM8003_4b_TEXT "Załadowany"
#define ENUM8003_5e_TEXT "Push aktywny"
#define ENUM8003_62_TEXT "Załadowany, temperatura dezynfekcji"
#define ENUM8003_63_TEXT "Załadowany, temperatura nominalna"
#define ENUM8003_64_TEXT "Załadowany, temperatura zredukowana"
#define ENUM8003_c8_TEXT "Gotowy"
#define ENUM8003_c9_TEXT "Gotowość ładowania"
#define ENUM8010_7c_TEXT "Ładowanie ograniczone"
#define ENUM8313_01_TEXT "Czujnik kotła B22"
#define ENUM8313_02_TEXT "Czujnik temp. powrotu B7"
#define ENUM8313_03_TEXT "Czujnik ładowania CWU B36"
#define ENUM8313_04_TEXT "Czujnik na wyjściu CWU B38"
#define ENUM8313_05_TEXT "Czujnik cyrkulacji CWU B39"
#define ENUM8313_06_TEXT "Czujnik kaskady B10/ B70"
#define ENUM8749_00_TEXT "Brak zapotrzebowania"
#define ENUM_ERROR_1e_TEXT "Czujnik temperatury zasilania 1"
#define ENUM_ERROR_20_TEXT "Czujnik temperatury zasilania 2"
#define ENUM_ERROR_62_TEXT "Moduł dodatkowy 1"
#define ENUM_ERROR_63_TEXT "Moduł dodatkowy 2"
#define ENUM_ERROR_b2_TEXT "Termostat 1 obiegu CO"
#define ENUM_ERROR_b3_TEXT "Termostat 2 obiegu CO"
#define ENUM_ERROR_01_b0_TEXT "Nie podłączono uziemienia X17"
#define ENUM_WEEKDAY_01_TEXT "Poniedziałek"
#define ENUM_WEEKDAY_02_TEXT "Wtorek"
#define ENUM_WEEKDAY_03_TEXT "Środa"
#define ENUM_WEEKDAY_04_TEXT "Czwartek"
#define ENUM_WEEKDAY_05_TEXT "Piątek"
#define ENUM_WEEKDAY_06_TEXT "Sobota"
#define ENUM_WEEKDAY_07_TEXT "Niedziela"
#define WEEKDAY_MON_TEXT "Pon"
#define WEEKDAY_TUE_TEXT "Wto"
#define WEEKDAY_WED_TEXT "Śro"
#define WEEKDAY_THU_TEXT "Czw"
#define WEEKDAY_FRI_TEXT "Pią"
#define WEEKDAY_SAT_TEXT "Sob"
#define WEEKDAY_SUN_TEXT "Nie"
