#define LANGUAGENAME_TEXT "Ελληνικά"
#define ENUM_CAT_00_TEXT "Ημερομηνία/ώρα"
#define ENUM_CAT_01_TEXT "Μονάδα δωματίου"
#define ENUM_CAT_02_TEXT "Ασύρματο"
#define ENUM_CAT_06_TEXT "Ώρα αλλαγής προγράμματος 1"
#define ENUM_CAT_07_TEXT "Ώρα αλλαγής προγράμματος 2"
#define ENUM_CAT_08_TEXT "Ώρα αλλαγής προγράμματος 3"
#define ENUM_CAT_09_TEXT "Ώρα αλλαγής προγράμματος 4/ΖΝΧ"
#define ENUM_CAT_0c_TEXT "Ώρα αλλαγής προγράμματος 5"
#define ENUM_CAT_0e_TEXT "Προγράμματα διακοπών HC1"
#define ENUM_CAT_0f_TEXT "Προγράμματα διακοπών HC2"
#define ENUM_CAT_10_TEXT "Προγράμματα διακοπών HC3"
#define ENUM_CAT_11_TEXT "Κύκλωμα θέρμανσης 1"
#define ENUM_CAT_12_TEXT "Κύκλωμα ψύξης 1"
#define ENUM_CAT_14_TEXT "Κύκλωμα θέρμανσης 2"
#define ENUM_CAT_15_TEXT "Κύκλωμα ψύξης 2"
#define ENUM_CAT_17_TEXT "Κύκλωμα θέρμανσης 3/P"
#define ENUM_CAT_1a_TEXT "ΖΝΧ"
#define ENUM_CAT_1e_TEXT "Αντλία Hx"
#define ENUM_CAT_1f_TEXT "Πισίνα"
#define ENUM_CAT_20_TEXT "Primary controller/system pump"
#define ENUM_CAT_21_TEXT "Primary controller/system pump 2"
#define ENUM_CAT_22_TEXT "Λέβητας"
#define ENUM_CAT_23_TEXT "Sitherm Pro"
#define ENUM_CAT_24_TEXT "Αντλία θερμότητας"
#define ENUM_CAT_25_TEXT "Μετρητής ενεργείας"
#define ENUM_CAT_29_TEXT "Διαδοχή"
#define ENUM_CAT_2a_TEXT "Πρόσθετη πηγή θερμότητας"
#define ENUM_CAT_2b_TEXT "Ηλιακό"
#define ENUM_CAT_2c_TEXT "Λέβητας στερεού καυσίμου"
#define ENUM_CAT_2d_TEXT "Δοχείο αδράνειας"
#define ENUM_CAT_2e_TEXT "Δεξαμενή ΖΝΧ"
#define ENUM_CAT_2f_TEXT "Απευθείας φόρτιση ΖΝΧ"
#define ENUM_CAT_31_TEXT "Διαμόρφωση"
#define ENUM_CAT_32_TEXT "LPB"
#define ENUM_CAT_33_TEXT "Modbus"
#define ENUM_CAT_34_TEXT "Σφάλμα"
#define ENUM_CAT_35_TEXT "Συντήρηση/Ειδική λειτουργία"
#define ENUM_CAT_36_TEXT "Διαμόρφωση πρόσθετων αρθρωμάτων"
#define ENUM_CAT_38_TEXT "Δοκιμές εισόδου/εξόδου"
#define ENUM_CAT_39_TEXT "Κατάσταση"
#define ENUM_CAT_3a_TEXT "Διάγνωση διαδοχής"
#define ENUM_CAT_3c_TEXT "Διάγνωση προμηθευτή"
#define ENUM_CAT_3d_TEXT "Διάγνωση καταναλωτή"
#define ENUM_CAT_3f_TEXT "Έλεγχος καυστήρα"
#define ENUM_CAT_40_TEXT "Ορισμένη από το χρήστη"
#define ENUM_CAT_41_TEXT "Αρτηρία PPS"
#define ENUM_CAT_43_TEXT "Άγνωστη κατηγορία"
