#define LANGUAGENAME_TEXT "Español"
#define ENUM_CAT_00_TEXT "Reloj"
#define ENUM_CAT_03_TEXT "Programa de conmutación 1"
#define ENUM_CAT_04_TEXT "Programa de conmutación 2"
#define ENUM_CAT_05_TEXT "Programa de conmutación 3"
#define ENUM_CAT_06_TEXT "Programa horario ACS"
#define ENUM_CAT_07_TEXT "Programa de conmutación 5"
#define ENUM_CAT_08_TEXT "Programa de vacaciones CC1"
#define ENUM_CAT_09_TEXT "Programa de vacaciones CC2"
#define ENUM_CAT_0b_TEXT "Circuito Calefacción 1"
#define ENUM_CAT_0d_TEXT "Circuito calefacción 2"
#define ENUM_CAT_0f_TEXT "Circuito calefacción 3/P"
#define ENUM_CAT_10_TEXT "ACS"
#define ENUM_CAT_18_TEXT "Caldera"
#define ENUM_CAT_1e_TEXT "Solar"
#define ENUM_CAT_20_TEXT "Tanque acumulación"
#define ENUM_CAT_21_TEXT "Acumulador ACS"
#define ENUM_CAT_22_TEXT "Carga directa ACS"
#define ENUM_CAT_24_TEXT "Configuración"
#define ENUM_CAT_25_TEXT "LPB"
#define ENUM_CAT_26_TEXT "Fallo"
#define ENUM_CAT_27_TEXT "Mantenimiento"
#define ENUM_CAT_2a_TEXT "Estado"
#define ENUM_CAT_2c_TEXT "Diagnóstico productor"
#define ENUM_CAT_2d_TEXT "Diagnóstico consumidor"
#define ENUM_CAT_2e_TEXT "Control de quemador"
#define STR516_TEXT "Valores estándar TSP circuito de calefacción 1"
#define STR536_TEXT "Valores estándar TSP circuito de calefacción 2"
#define STR556_TEXT "Valores estándar TSP circuito de calefacción 3"
#define STR576_TEXT "Valores estándar PCH 4"
#define STR648_TEXT "Nivel de operación en vacaciones del CC1"
#define STR652_TEXT "Periodo 1 Vacaciones CC2: Primer Día"
#define STR653_TEXT "Periodo 1 Vacaciones CC2: Último Día"
#define STR658_TEXT "Nivel de operación en vacaciones del CC2"
#define STR700_TEXT "Modo Operación Circuito Calor 1"
#define STR710_TEXT "Consigna de confort temperatura ambiente CC1"
#define STR712_TEXT "Consigna reducida Temp.Ambiente Cto.Calefac.1"
#define STR714_TEXT "Consigna Antihielo Temp.Ambiente Cto.Calefac.1"
#define STR720_TEXT "Pendiente Curva de Calefacción 1"
#define STR721_TEXT "Desplazamiento Paralelo Curva de Calefacción"
#define STR726_TEXT "Adaptación Curva Calefacción Cto.Calefac. 1"
#define STR730_TEXT "Cambio Verano/Invierno Temp. Circto. Calor 1"
#define STR732_TEXT "Limitación calefacción 24-horas CC1"
#define STR740_TEXT "Limitación Mín. Temp. Impulsión Cto.Calefac. 1"
#define STR741_TEXT "Limitación Máx. Temp. Impulsión Cto.Calefac. 1"
#define STR750_TEXT "Factor ganancia Temp.Ambiente Cto.Calefac. 1"
#define STR760_TEXT "Limitación temperatura ambiente CC1"
#define STR770_TEXT "Consigna Temp.Ambiente Puesta a Régimen CC1"
#define STR780_TEXT "Reduccción Acelerada CC 1"
#define STR790_TEXT "Tiempo Máx.Deslizamto. ControlMarchaOptimiz.CC1"
#define STR791_TEXT "Tiempo Máx.Deslizamto. ControlParadaOptimiz.CC1"
#define STR800_TEXT "Inicio reducción d incremento consig ambient CC1"
#define STR801_TEXT "Fin reducción incremento consg ambt CC1"
#define STR850_TEXT "Función Activación Secado del Suelo"
#define STR851_TEXT "Consigna suelo manual CC1"
#define STR884_TEXT "Velocidad de la bomba para punto diseño planta"
#define STR885_TEXT "Mínima modulación bomba PWM"
#define STR886_TEXT "Temp. Exterior a Máxima Demanda de Calor"
#define STR887_TEXT "Consigna caldera a Temp. Ext de diseño"
#define STR888_TEXT "Límite aceleración temperatura controlador dT"
#define STR894_TEXT "Salto térmico impulsión/retorno a Temp nominal"
#define STR1000_TEXT "Modo Operación Circuito Calor 2"
#define STR1010_TEXT "Consigna Confort temperatura ambiente CC1"
#define STR1012_TEXT "Consigna reducida Temp.Ambiente Cto.Calefac.2"
#define STR1014_TEXT "Consigna Antihielo Temp.Ambiente Cto.Calefac.2"
#define STR1020_TEXT "Pendiente Curva de Calefacción 2"
#define STR1021_TEXT "Desplazamiento Paralelo Curva de Calefacción"
#define STR1026_TEXT "Adaptación Curva Calefacción Cto.Calefac. 2"
#define STR1030_TEXT "Cambio Verano/Invierno Temp. Circto. Calor 2"
#define STR1032_TEXT "Limitación calefacción 24-horas CC2"
#define STR1040_TEXT "Limitación Mín. Temp. Impulsión Cto.Calefac. 2"
#define STR1041_TEXT "Limitación Máx. Temp. Impulsión Cto.Calefac. 2"
#define STR1050_TEXT "Factor ganancia Temp.Ambiente Cto.Calefac. 2"
#define STR1060_TEXT "Limitación temperatura ambiente CC 2"
#define STR1070_TEXT "Consigna Temp.Ambiente Puesta a Régimen CC2"
#define STR1080_TEXT "Reduccción Acelerada CC 2"
#define STR1090_TEXT "Tiempo Máx.Deslizamto. ControlMarchaOptimiz.CC2"
#define STR1091_TEXT "Tiempo Máx.Deslizamto. ControlParadaOptimiz.CC1"
#define STR1100_TEXT "Inicio reducción d incremento consig ambient CC2"
#define STR1101_TEXT "Fin reducción incremento consg ambt CC2"
#define STR1130_TEXT "Temp Aceleración Válvula Mezcla Circto.Calefac"
#define STR1134_TEXT "Tiempo Carrera Actuador Circto. Calefacción"
#define STR1150_TEXT "Función Activación Secado del Suelo"
#define STR1151_TEXT "Consigna de suelo manual CC2"
#define STR1600_TEXT "Modo operación ACS"
#define STR1610_TEXT "Consigna nominal temperatura ACS"
#define STR1612_TEXT "Consigna reducida temperatura  ACS"
#define STR1620_TEXT "Liberación ACS"
#define STR1640_TEXT "Función Legionela"
#define STR1641_TEXT "Periodicidad función legionella"
#define STR1642_TEXT "Día de función legionela"
#define STR1644_TEXT "Tiempo para la función legionella"
#define STR1645_TEXT "ACS: Consigna Función Legionela"
#define STR1646_TEXT "Tiempo duración punto consigna función Legionela"
#define STR1647_TEXT "Funcion. bomba circulación en función legionela"
#define STR1660_TEXT "Liberación bomba circulación ACS"
#define STR1661_TEXT "Ciclo bomba circulación ACS"
#define STR2201_TEXT "Generación calor bloqueada"
#define STR2210_TEXT "Limitación Mínima de la Temperatura de Caldera"
#define STR2212_TEXT "Limitación Máxima de la Temperatura de Caldera"
#define STR2440_TEXT "Grado máximo de modulación en modo calefacción"
#define STR2441_TEXT "Velocidad máx a máxima salida,  modo calefacción"
#define STR2442_TEXT "Salida durante tiempo de retraso del controlador"
#define STR2443_TEXT "Valor arranque Modul. liberar controlador en ACS"
#define STR2451_TEXT "Tiempo mínimo de parada del quemador"
#define STR2452_TEXT "T. paro quemador SD"
#define STR2453_TEXT "Retraso controlador después arrancar quemador"
#define STR2454_TEXT "Diferencial de Conmutación de la Caldera"
#define STR2455_TEXT "Mínimo diferencial apagado de caldera"
#define STR2456_TEXT "Máximo diferencial de apagado de caldera"
#define STR2471_TEXT "Tiempo de retardo a la parada de la bomba"
#define STR2472_TEXT "Temperatura sobrefuncionamiento bomba ACS"
#define STR2521_TEXT "Temp encendido portección antihileo caldera"
#define STR2522_TEXT "Temp apagado protección antihielo caldera"
#define STR3810_TEXT "Diferencial temp. solar para conexión"
#define STR3811_TEXT "Temp diferencial solar para desconexión"
#define STR3812_TEXT "Mínima Temp. de Carga"
#define STR3831_TEXT "Tiempo mínimo funcionamiento bomba colector"
#define STR3840_TEXT "Temp. protección antihielo del colector"
#define STR3850_TEXT "Protección sobretemperatura colector"
#define STR3860_TEXT "Temperatura evaporación en conducto"
#define STR4721_TEXT "Diferencial conmuta bloqueo automátic productor"
#define STR4722_TEXT "Diff temperatura acumulad/BC a liberación produc"
#define STR5019_TEXT "Aceler consigna recarga estratifica. Acumul"
#define STR5020_TEXT "Aceleración de Temperatura de Impulsión del ACS"
#define STR5050_TEXT "Máxima Temp. carga ACS"
#define STR5055_TEXT "Temp mín refrigeración para el tanq almacena ACS"
#define STR5100_TEXT "Velocidad mín bomba para carga completa deposito"
#define STR5020_TEXT "Aceleración de Temperatura de Impulsión del ACS"
#define STR5400_TEXT "Consigna temperatura acelerada"
#define STR5430_TEXT "Diferencial encendido en modo ACS (sensor 1)"
#define STR5431_TEXT "Diferencial apagad mínimo en modo ACS (sensor 1)"
#define STR5432_TEXT "Diferencial apagad máximo en modo ACS (sensor 1)"
#define STR5433_TEXT "Diferencial encencido en modo ACS(sensor 2)"
#define STR5434_TEXT "Mín. diferencial conmutación en modo ACS (sens2)"
#define STR5435_TEXT "Diferencial apagad máximo en modo ACS (sensor 2)"
#define STR5450_TEXT "Umbral de respuesta detección consumo ACS"
#define STR5451_TEXT "Umbral respuesta consumo ACS modo confort"
#define STR5452_TEXT "Umbral respuesta consumo ACS modo calefacción"
#define STR5453_TEXT "Reajuste consigna a 40ºC en modo confor"
#define STR5454_TEXT "Reajsute de consigna a 60ºC en modo confort"
#define STR5455_TEXT "Reajuste consigna a 40ºC temperatura exterior"
#define STR5456_TEXT "Reajuste consigna a 60ºC temperatura exterior"
#define STR5480_TEXT "Tiempo para nivel confort ACS después consumo"
#define STR5481_TEXT "Tiempo nivel confort ACS después consumo(calor)"
#define STR5482_TEXT "Tiempo interruptor flujo ACS está cerrado"
#define STR5483_TEXT "Tiempo interrup flujo confort ACS está cerrado"
#define STR5486_TEXT "Retraso controlad por solicitud ACS instantanea"
#define STR5487_TEXT "Retraso paro bomba con ACS después paro quemador"
#define STR5488_TEXT "Retraso paro bomba con ACS después paro quemador"
#define STR5701_TEXT "Instalación Tipo"
#define STR5710_TEXT "Circuito calefacción 1"
#define STR5715_TEXT "Circuito calefacción 2"
#define STR5732_TEXT "Tiempo parada al cambio modo calefacción a ACS"
#define STR5733_TEXT "Retraso parada al cambio modo calefacción a ACS"
#define STR5761_TEXT "Demanda de calor con asistencia por bomba Q8"
#define STR5920_TEXT "Función salida programable K2 LMU"
#define STR5921_TEXT "Defecto K2 a K1"
#define STR5922_TEXT "Salida función 1 del módulo insertado"
#define STR5923_TEXT "Salida función 2 del módulo insertado"
#define STR5924_TEXT "Salida función 3 del módulo insertado"
#define STR5926_TEXT "Configuración salida 1"
#define STR5927_TEXT "Configuración salidat 2"
#define STR5928_TEXT "Configuración salidat 3"
#define STR5950_TEXT "Selección función entrada H1"
#define STR5957_TEXT "Función del modem"
#define STR5970_TEXT "Configuración termostato ambiente 1"
#define STR5971_TEXT "Configuración termostato ambiente 2"
#define STR5973_TEXT "Función entrada RelCl"
#define STR5975_TEXT "Temp máxima de la demanda de calor externa"
#define STR5976_TEXT "Límite inferior señal salida demanda calor exter"
#define STR6110_TEXT "Constante de tiempo del Edificio"
#define STR6112_TEXT "Gradiente de la habitación modelo"
#define STR6120_TEXT "Protección antihielo de la Instalación"
#define STR6127_TEXT "Hora de función antigripaje bomba/Valvl diversor"
#define STR6220_TEXT "Versión del Programa del Equipo"
#define STR6225_TEXT "Familia del Equipo"
#define STR6226_TEXT "Variante del Equipo"
#define STR6227_TEXT "Versión OV del Equipo"
#define STR6230_TEXT "Etiqueta de ajuste del controlador 0"
#define STR6240_TEXT "Etiqueta de ajuste del controlador 1"
#define STR6250_TEXT "Etiqueta de ajuste del controlador 2"
#define STR6260_TEXT "Etiqueta de ajuste del controlador 3"
#define STR6270_TEXT "Etiqueta de ajuste del controlador 4"
#define STR6300_TEXT "Etiqueta de ajuste del controlador 7"
#define STR6330_TEXT "Configuración controlador 10"
#define STR6604_TEXT "Selección función alimentación bús LPB"
#define STR6605_TEXT "Estado de la alimentación del bús LPB"
#define STR6625_TEXT "ACS: Asignación"
#define STR6640_TEXT "Fuente del Programa de Reloj"
#define STR6705_TEXT "Valor interno del cósigo de diagnóstico"
#define STR6706_TEXT "Valor actual de la fase de bloqueo"
#define STR6741_TEXT "Alarma temperatura impulsión tiemp CC2"
#define STR6823_TEXT "3º valor transferido código diagnóstico albatros"
#define STR6825_TEXT "3º valor transferido código diagnóstico interno"
#define STR6826_TEXT "3º valor transferido de la fase bloqueada"
#define STR6830_TEXT "4º valor transferido del código bloqueo contado"
#define STR6833_TEXT "4º valor transferido código diagnóstico albatros"
#define STR6835_TEXT "4º valor transferido código diagnóstico interno"
#define STR6836_TEXT "4º valor transferido de la fase bloqueada"
#define STR6840_TEXT "5º valor transferido del código bloqueo contado"
#define STR6843_TEXT "5º valor transferido código diagnóstico albatros"
#define STR6845_TEXT "5º valor transferido código diagnóstico interno"
#define STR6846_TEXT "5º valor transferido de la fase bloqueada"
#define STR7001_TEXT "Mensaje de Mantenimiento"
#define STR7007_TEXT "Configuración/ Reset de mensajes de servicio"
#define STR7010_TEXT "Confirmación mensaje servicio"
#define STR7011_TEXT "Tiempo de repetición para mensajes de servicio"
#define STR7040_TEXT "Horas Servicio Quemador hasta su Mantenimiento"
#define STR7041_TEXT "Horas de fucnionamiento desde último servicio"
#define STR7042_TEXT "Límite arranques quemador desde último servicio"
#define STR7043_TEXT "Arranques del quemador desde el último servicio"
#define STR7044_TEXT "Límite de meses desde último servicio"
#define STR7045_TEXT "Meses desde el último servicio"
#define STR7050_TEXT "Umbral velocidad ventilador para mensaje servic"
#define STR7051_TEXT "Mensaje servicio corriente ionización"
#define STR8000_TEXT "Estado cicuito calefacción 1"
#define STR8001_TEXT "Estado cirduito de calefacción 2"
#define STR8003_TEXT "Estado ACS"
#define STR8005_TEXT "Estado caldera"
#define STR8007_TEXT "Estado panel solar"
#define STR8310_TEXT "Valor Actual Temperatura de Caldera"
#define STR8311_TEXT "Consigna Temperatura de Caldera"
#define STR8314_TEXT "Valor Actual Temperatura de Retorno"
#define STR8316_TEXT "Valor Actual Temperatura de Humos"
#define STR8324_TEXT "Velocidad del ventilador actual"
#define STR8325_TEXT "Control de ventilador actual"
#define STR8326_TEXT "Salida relativa"
#define STR8328_TEXT "Indicador operación control de quemador"
#define STR2730_TEXT "Valor medido de corriente de ionización"
#define STR8336_TEXT "Horas de Servicio del Equipo"
#define STR8337_TEXT "Inicio contador quemador"
#define STR8338_TEXT "Horas de servicio del quemador"
#define STR8339_TEXT "Horas servicio calentamiento ACS"
#define STR8340_TEXT "Horas servicio de zona"
#define STR8510_TEXT "Valor actual Temp. 1 Colector (B6)"
#define STR8530_TEXT "Horas operativas de rendimiento solar"
#define STR8700_TEXT "Sonda local de Temperatura Exterior"
#define STR8703_TEXT "Temperatura Exterior Atenuada"
#define STR8704_TEXT "Temperatura Exterior Compuesta"
#define STR8740_TEXT "Valor Actual Temperatura Ambiente 1"
#define STR8741_TEXT "Consigna Resultante de la Temperatura Ambiente"
#define STR8743_TEXT "Valor actual Temp.Impulsión Cto.Calefac. 1"
#define STR8744_TEXT "Consigna temperatura impulsión H1"
#define STR8750_TEXT "Velocidad Bomba"
#define STR8770_TEXT "Valor Actual Temperatura Ambiente 2"
#define STR8771_TEXT "Consigna Actual Temp. Ambiente CC2"
#define STR8773_TEXT "Valor actual Temp.Impulsión Cto.Calefac. 2"
#define STR8774_TEXT "Consigna temperatura impulsión H2"
#define STR8830_TEXT "Temperatura actual superior ACS (B3)"
#define STR8831_TEXT "ACS: Consigna de Temperatura Actual"
#define STR8836_TEXT "Temp. carga ACS"
#define STR8950_TEXT "Señal de proceso Segmento de la Impulsión"
#define STR8952_TEXT "Señal de proceso Segmento del Retorno"
#define STR8980_TEXT "Acumulador: Valor actual Temp. zona alta (B4)"
#define STR9500_TEXT "Tiempo pre-ventilación"
#define STR9502_TEXT "Control ventilad. prepurga"
#define STR9504_TEXT "Velocidad ventilador requerida durante prepurga"
#define STR9510_TEXT "Aire de combustión a carga de encendido"
#define STR9512_TEXT "Velocidad necesaria para carga de encendido"
#define STR9520_TEXT "Aire de combustión a llama baja"
#define STR9522_TEXT "Aire de combustión a llama alta"
#define STR9524_TEXT "Velocidad necesaria a llama baja"
#define STR9527_TEXT "Velocidad necesaria a llama alta"
#define STR9540_TEXT "Tiempo después de ventilación"
#define STR9560_TEXT "Modulación ventil a carga completa tanque estrat"
#define STR9563_TEXT "Velocidad ventil a carga completa tanque estrati"
