#define LANGUAGENAME_TEXT "Magyar nyelv"
#define MENU_TEXT_YES "Igen"
#define MENU_TEXT_NO "Nem"
#define MENU_TEXT_ON "Ki"
#define MENU_TEXT_OFF "Be"
#define MENU_TEXT_OPEN "Nyitva"
#define MENU_TEXT_CLOSE "Zárva"

#define UNIT_METER_TEXT "m"
#define UNIT_MONTHS_TEXT "Hónap"
#define UNIT_DAYS_TEXT "Nap"
#define UNIT_HOUR_TEXT "h"
#define UNIT_MIN_TEXT "min"
#define UNIT_SEC_TEXT "s"
#define UNIT_DEG_TEXT "°C"
#define UNIT_PERC_TEXT "%"
#define UNIT_RPM_TEXT "U/min"
#define UNIT_KW_TEXT "kW"
#define UNIT_KWH_TEXT "kWh"
#define UNIT_KWHM3_TEXT "kWh/m³"
#define UNIT_CURR_TEXT "µA"
#define UNIT_BAR_TEXT "bar"
#define UNIT_VOLT_TEXT "V"
#define UNIT_GRADIENT_TEXT "min/K"
#define UNIT_GRADIENTKS_TEXT "K/s"
#define UNIT_INTEGRAL_TEXT "Kmin"
#define UNIT_TEMP_PER_MIN_TEXT "°C/min"
#define UNIT_CEL_MIN_TEXT "°Cmin"
#define UNIT_LITERPERHOUR_TEXT "l/h"
#define UNIT_LITERPERMIN_TEXT "l/min"
#define UNIT_GR_PER_CUBM_TEXT "g/m³"
#define UNIT_HPA_TEXT "hPa"
#define UNIT_PPM_TEXT "ppm"

#define ENUM_CAT_00_TEXT "Pontos idő és dátum"
#define ENUM_CAT_01_TEXT "Kezelő egység"
#define ENUM_CAT_02_TEXT "Vezeték nélküli eszközök"
#define ENUM_CAT_03_TEXT "Hűtési kör 1 időprogram"
#define ENUM_CAT_04_TEXT "Hűtési kör 2 időprogram"
#define ENUM_CAT_05_TEXT "Hűtési kör 3 időprogram"
#define ENUM_CAT_06_TEXT "Fűtési kör 1 időprogram"
#define ENUM_CAT_07_TEXT "Fűtési kör 2 időprogram"
#define ENUM_CAT_08_TEXT "Fűtési kör 3 időprogram"
#define ENUM_CAT_09_TEXT "Időprogram 4/HMV"
#define ENUM_CAT_0a_TEXT "Szellőztetés kör 1 időprogram"
#define ENUM_CAT_0b_TEXT "Szellőztetés kör 2 időprogram"
#define ENUM_CAT_0c_TEXT "Időprogram 5"
#define ENUM_CAT_0d_TEXT "Szellőztetés kör 3 időprogram"
#define ENUM_CAT_0e_TEXT "Szabadság fűtési kör 1"
#define ENUM_CAT_0f_TEXT "Szabadság fűtési kör 2"
#define ENUM_CAT_10_TEXT "Szabadság fűtési kör 3"
#define ENUM_CAT_11_TEXT "Fűtési kör 1"
#define ENUM_CAT_12_TEXT "Hűtési kör 1"
#define ENUM_CAT_13_TEXT "Szellőztetés kör 1"
#define ENUM_CAT_14_TEXT "Fűtési kör 2"
#define ENUM_CAT_15_TEXT "Hűtési kör 2"
#define ENUM_CAT_16_TEXT "Szellőztetés kör 2"
#define ENUM_CAT_17_TEXT "Fűtési kör 3"
#define ENUM_CAT_18_TEXT "Hűtési kör 3"
#define ENUM_CAT_19_TEXT "Szellőztetés kör 3"
#define ENUM_CAT_1a_TEXT "Használati melegvíz (HMV)"
#define ENUM_CAT_1b_TEXT "Felhasználói kör 1"
#define ENUM_CAT_1c_TEXT "Felhasználói kör 2"
#define ENUM_CAT_1d_TEXT "Uszoda kör"
#define ENUM_CAT_1e_TEXT "Hx-szivattyú"
#define ENUM_CAT_1f_TEXT "Uszoda"
#define ENUM_CAT_20_TEXT "Elsődleges vezérlő/rendszer szivattyú"
#define ENUM_CAT_21_TEXT "Elsődleges vezérlő/rendszer szivattyú"
#define ENUM_CAT_22_TEXT "Kazán"
#define ENUM_CAT_23_TEXT "Sitherm Pro"
#define ENUM_CAT_24_TEXT "Hőszivattyú"
#define ENUM_CAT_25_TEXT "Energia mérés"
#define ENUM_CAT_26_TEXT "Brennerfolge"
#define ENUM_CAT_27_TEXT "Energia mérés 2"
#define ENUM_CAT_28_TEXT "Grid supervision module"
#define ENUM_CAT_29_TEXT "Kaszkád"
#define ENUM_CAT_2a_TEXT "Kiegészítő fűtés"
#define ENUM_CAT_2b_TEXT "Napkollektor"
#define ENUM_CAT_2c_TEXT "Szilárd tüzelésű kazán"
#define ENUM_CAT_2d_TEXT "Puffertároló"
#define ENUM_CAT_2e_TEXT "HMV tároló"
#define ENUM_CAT_2f_TEXT "Áfolyós HMV vételezés"
#define ENUM_CAT_30_TEXT "Általános funkciók"
#define ENUM_CAT_31_TEXT "Konfiguráció"
#define ENUM_CAT_32_TEXT "LPB rendszer"
#define ENUM_CAT_33_TEXT "Modbus rendszer"
#define ENUM_CAT_34_TEXT "Hiba"
#define ENUM_CAT_35_TEXT "Szerviz/ speciális üzem"
#define ENUM_CAT_36_TEXT "Bővítő modulok konfigurációja"
#define ENUM_CAT_37_TEXT "Modbus paraméterek"
#define ENUM_CAT_38_TEXT "Bemenet/ kimenet tesztelés"
#define ENUM_CAT_39_TEXT "Állapot / státusz"
#define ENUM_CAT_3a_TEXT "Kaszkád paraméterek"
#define ENUM_CAT_3b_TEXT "Generátor paraméterek"
#define ENUM_CAT_3c_TEXT "Hőtermelő oldali paraméterek"
#define ENUM_CAT_3d_TEXT "Fogyasztó oldali paraméterek"
#define ENUM_CAT_3e_TEXT "Set day value storage"
#define ENUM_CAT_3f_TEXT "Gázégő vezérlés"
#define ENUM_CAT_40_TEXT "User defined"
#define ENUM_CAT_43_TEXT "PPS bus"
#define ENUM_CAT_44_TEXT "One Wire, DHT & MAX! Sensors"
#define ENUM_CAT_45_TEXT "Ismeretlen kategória"

#define STR0_TEXT "Pontos idő és dátum"
#define STR1_TEXT "Óra / perc"
#define STR2_TEXT "Nap / hónap"
#define STR3_TEXT "Év"
#define STR5_TEXT "Nyári időszámítás kezdete Nap/hónap"
#define STR6_TEXT "Nyári időszámítás vége Nap/hónap"
#define STR70_TEXT "Vezérlőegység verziója"
#define STR516_TEXT "Alapértékek visszaállítása standard értékek 1. fűtési kör"
#define STR536_TEXT "Kapcs.óra program standard értékek 2. fűtési kör"
#define STR556_TEXT "3. kapcsolóóra program standard értékek"
#define STR560_TEXT "Kapcs.óra program HMV"
#define STR576_TEXT "4. kapcsolóóra program"
#define STR648_TEXT "Szünidei üzemi szint FK1"
#define STR652_TEXT "FK2 1. szünidei periódus: első nap"
#define STR653_TEXT "FK2 1. szünidei periódus: utolsó nap"
#define STR658_TEXT "Szünidei üzemi szint FK2"
#define STR700_TEXT "Működési mód"
#define STR701_TEXT "Jelenlét gomb (ideiglenes távollét)"
#define STR707_TEXT "Ideiglenes szobahőmérséklet"
#define STR710_TEXT "Szobahőmérséklet komfort alapjel"
#define STR711_TEXT "Komfort alapjel maximuma"
#define STR712_TEXT "Szobahőmérséklet csökkentett alapjel"
#define STR714_TEXT "Szobahőmérséklet fagyvédelem alapjel"
#define STR720_TEXT "Fűtési jelleggörbe meredekség"
#define STR721_TEXT "Fűtési jelleggörbe párhuzamos eltolás"
#define STR726_TEXT "Fűtési jelleggörbe adaptáció"
#define STR730_TEXT "Nyári/téli fűtési határhőmérséklet"
#define STR732_TEXT "24-órás fűtési korlát"
#define STR733_TEXT "Napi fűtési határérték meghosszabbítása"
#define STR740_TEXT "Előremenő hőmérséklet alapjel minimum"
#define STR741_TEXT "Előremenő hőmérséklet alapjel maximum"
#define STR742_TEXT "Szobatermosztát előremenő hőmérséklet alapjel"
#define STR746_TEXT "Fűtés igény késleltetés"
#define STR750_TEXT "Szobahőmérséklet ráhatási tényező"
#define STR760_TEXT "Elvárt hőmérsékleti tartomány"
#define STR770_TEXT "Szobahőmérséklet alapjel megemelés (gyors felfűtés)"
#define STR780_TEXT "Gyors fűtéscsökkentés"
#define STR790_TEXT "Bekapcsolás optimalizálás max. előrehozatali idő"
#define STR791_TEXT "Kikapcsolás optimalizálás max. előrehozatali idő"
#define STR794_TEXT "Fűtési gradiens"
#define STR800_TEXT "Szobahőmérséklet-csökkentett alapjel megem.kezdet"
#define STR801_TEXT "Szobahőmérséklet-csökkentett alapjel megem.vége"
#define STR809_TEXT "Folyamatos szivattyú üzem"
#define STR810_TEXT "Szivattyú működtetése fagyvédelmi üzemmódban"
#define STR830_TEXT "Az előremenő hőmérséklet túllépése a keverőszelep hőmérsékleti alapértéke felett"
#define STR832_TEXT "Meghajtó típusa"
#define STR833_TEXT "Kapcsolási hiszterézis 2-pont"
#define STR834_TEXT "Meghajtó futásideje"
#define STR850_TEXT "Padló szárítás"
#define STR851_TEXT "Padló szárítás kézi alapjel"
#define STR855_TEXT "Padló szárítás aktuális alapjel"
#define STR856_TEXT "Padló szárítási napok"
#define STR861_TEXT "Felesleg hőmennyiség elvonás"
#define STR864_TEXT "Jelerősítés blokkolása"
#define STR870_TEXT "Puferrel"
#define STR872_TEXT "With prim contr/system pump"
#define STR880_TEXT "A szivattyú fordulatszámának csökkentése"
#define STR881_TEXT "Szivattyú indulási sebessége"
#define STR882_TEXT "Szivattyú minimális fordulatszáma"
#define STR883_TEXT "Szivattyú maximális fordulatszáma"
#define STR884_TEXT "Kazánszivattyú fordulatszám-fokozat névleges munkapont"
#define STR885_TEXT "Modulációs szivattyú imp.szél.mod.minimum"
#define STR886_TEXT "Szivattyú maximális gyári fordulatszáma"
#define STR887_TEXT "Kazánhőmérséklet normál külső hőmérsékletnél"
#define STR888_TEXT "Hőmérséklet megemelési határ dT-szabályozáshoz"
#define STR888_2_TEXT "Görbekorrekció 50% szivattyú sebességnél"
#define STR894_TEXT "Előremenő-/visszatérő különbség normál külső hőmérsékleten"
#define STR898_TEXT "Működési szint átváltás"
#define STR900_TEXT "Működési mód váltás"
#define STR1602_TEXT "HMV Status"
#define STR1603_TEXT "Manuális HMV-Push"
#define STR1610_TEXT "HMV Névleges alapjel"
#define STR1612_TEXT "HMV Csökkentett alapjel"
#define STR1614_TEXT "HMV névleges alapjel maximum"
#define STR1615_TEXT "HMV névleges alapjel minimum"
#define STR1616_TEXT "Fotovoltaikus alapjel"
#define STR1620_TEXT "HMV engedélyezés"
#define STR1630_TEXT "HMV Töltési prioritás"
#define STR1640_TEXT "Legionella elleni védelem"
#define STR1641_TEXT "Periodikus legionella elleni védelem"
#define STR1642_TEXT "Legionella elleni védelem fix nap"
#define STR1644_TEXT "Legionella elleni védelem időpontja"
#define STR1645_TEXT "Lagionella elleni védelem hőmérséklet alapjel"
#define STR1646_TEXT "Legionella elleni védelem időtartama"
#define STR1647_TEXT "Cirkulációs szivattyú üzem legionella elleni védelem során"
#define STR1660_TEXT "Cirkulációs szivattyú engedélyezés"
#define STR1661_TEXT "Periodikus cirkulációs szivattyú járatás"
#define STR1663_TEXT "Cirkulációs alapjel"
#define STR1680_TEXT "Működési mód váltás"
#define STR2201_TEXT "Hőtermelő blokkolása"
#define STR2203_TEXT "Kazán bekapcsolása a beállított külső hőmérséklet alatt"
#define STR2204_TEXT "Bekapcsolása a beállított külső hőmérséklet felett"
#define STR2205_TEXT "Gazdaságos üzemmód"
#define STR2206_TEXT "Működés / Készenlét"
#define STR2208_TEXT "A hőtároló/ puffer teljes feltöltése"
#define STR2210_TEXT "Kazánhőmérséklet alapjel minimum"
#define STR2211_TEXT "Kazánhőmérséklet alapjel gyári minimum"
#define STR2212_TEXT "Kazánhőmérséklet alapjel maximum"
#define STR2213_TEXT "Kazánhőmérséklet alapjel gyári maximum"
#define STR2214_TEXT "Kézi üzem alapjel"
#define STR2215_TEXT "Szabályozási különbség max. a minimális megszakítás törlése nélkül (° K)"
#define STR2217_TEXT "Fagyvédelmi hőmérséklet alapjel"
#define STR2220_TEXT "Aktiválási integrál 2. fokozat"
#define STR2221_TEXT "Integrál visszaállítása 2. fokozatból"
#define STR2222_TEXT "2. fokozat indulásának kikényszerítése"
#define STR2233_TEXT "Fűtési körök arányossági tart. Xp"
#define STR2234_TEXT "Fűtési körök integrálási idő Tn"
#define STR2235_TEXT "Fűtési körök deriválási idő Tv"
#define STR2236_TEXT "HMV arányossági tart. Xp"
#define STR2237_TEXT "HMV integrálási idő Tn"
#define STR2238_TEXT "HMV deriválási idő Tv"
#define STR2241_TEXT "Gázégő minimum futásidő"
#define STR2243_TEXT "Gázégő minimum kikapcsolási idő"
#define STR2245_TEXT "Az alapjel és az aktuális hőmérséklet közötti különbség. Túllépés esetén a bekapcsolás közötti szünetet a rendszer figyelmen kívül hagyja"
#define STR2250_TEXT "Szivattyú utánfutás ideje"
#define STR2253_TEXT "HMV termelés utáni szivattyú utánfutási idő"
#define STR2260_TEXT "Prot boil startup consumers"
#define STR2264_TEXT "Prot boil startup anticipation"
#define STR2270_TEXT "Visszatérő hőmérséklet minimum alapjel"
#define STR2271_TEXT "Visszatérő hőmérséklet minimum gyári alapjel"
#define STR2272_TEXT "Visszatérő hőmérséklet ráhat. hőfogyasztó"
#define STR2301_TEXT "Kazán szivattyú be hőtermelés kizárás"
#define STR2305_TEXT "Hőtermelő kizárás hatása"
#define STR2310_TEXT "Határoló termosztát funkció"
#define STR2316_TEXT "Maximális hőmérséklet különbség"
#define STR2317_TEXT "Névleges hőmérséklet különbség"
#define STR2320_TEXT "Szivattyú moduláció"
#define STR2321_TEXT "Szivattyú indítási fordulatszám"
#define STR2322_TEXT "Szivattyú minimum fordulatszám"
#define STR2323_TEXT "Szivattyú maximum fordulatszám"
#define STR2324_TEXT "Xp fordulatszám"
#define STR2325_TEXT "Tn fordulatszám visszaállítási idő"
#define STR2326_TEXT "Tv fordulatszám visszatartási idő"
#define STR2327_TEXT "Szivattyú gyári fordulatszám minimum"
#define STR2328_TEXT "Szivattyú gyári fordulatszám maximum"
#define STR2329_TEXT "Szivattyú alapjel csökkentés"
#define STR2330_TEXT "Névleges teljesítmény"
#define STR2331_TEXT "Alapfokozat teljesítménye"
#define STR2334_TEXT "Minimum szivattyú fordulatszám kimenet"
#define STR2335_TEXT "Maximum szivattyú fordulatszám kimenet"
#define STR2440_TEXT "Maximális modulációs fok fűtés üzemmódban"
#define STR2441_TEXT "Maximális ventilátor fordulatszám fűtés üzemmódban"
#define STR2442_TEXT "Ventilátor fordulatszám telj.tölt. max."
#define STR2443_TEXT "Ventilátor alapjel ind.ért. átfolyós HMV"
#define STR2444_TEXT "Ventilátor fordulatszám maximum átfolyós HMV"
#define STR2445_TEXT "Ventilátor leállítás fűtési módban"
#define STR2446_TEXT "Ventilátor leállítás késleltetése"
#define STR2450_TEXT "Szabályozó késleltetés"
#define STR2451_TEXT "Égő minimális szünetidő"
#define STR2452_TEXT "Szabályozó késleltetési fordulatszám"
#define STR2453_TEXT "Szabályozó késleltetési idő"
#define STR2454_TEXT "Kapcsolási hiszterézis be FK"
#define STR2455_TEXT "Kapcsolási hiszterézis ki min FK"
#define STR2456_TEXT "Kapcsolási hiszterézis ki max FK"
#define STR2457_TEXT "Fűtési körök beállítási idő"
#define STR2460_TEXT "Kapcsolási hiszterézis be HMV"
#define STR2461_TEXT "Kapcsolási hiszterézis ki min HMV"
#define STR2462_TEXT "Kapcsolási hiszterézis ki max HMV"
#define STR2463_TEXT "HMV beállítási idő"
#define STR2464_TEXT "Dyn SD on setpoint change"
#define STR2465_TEXT "Min setpoint change dyn SD"
#define STR2466_TEXT "Dyn SD with FK/HMV change"
#define STR2467_TEXT "Dyn SD when burner is on"
#define STR2470_TEXT "Fűtés igény késleltetés (speciális működés)"
#define STR2471_TEXT "Szivattyú utánjáratási idő"
#define STR2472_TEXT "HMV szivattyú utánjáratási hőmérséklet"
#define STR2473_TEXT "Füstgáz hőmérséklet riasztás"
#define STR2474_TEXT "Füstgáz hőmérséklet lekapcsolási határ"
#define STR2476_TEXT "Füstgáz hőmérséklet leállás miatti teendő"
#define STR2477_TEXT "Füstgáz hőmérséklet leállás miatti állásidő"
#define STR2478_TEXT "Füstgáz hőmérséklet korlát"
#define STR2479_TEXT "Flue gas superv time con rel mod"
#define STR2480_TEXT "Stat nyomás ellen. kikapcs."
#define STR2490_TEXT "Dyn press superv shutdown activity"
#define STR2491_TEXT "Dyn superv press diff min"
#define STR2492_TEXT "Dyn superv press diff max"
#define STR2494_TEXT "Dyn superv press increase"
#define STR2495_TEXT "Dyn press superv time"
#define STR2496_TEXT "Dyn press superv time const"
#define STR2500_TEXT "Nyomáskapcsoló leállítás"
#define STR2502_TEXT "Áramláskapcsoló leállítás"
#define STR2504_TEXT "Kapcsoló min. bekapcsolási idő"
#define STR2510_TEXT "Gyors leállás hőmérséklet gradiens"
#define STR2511_TEXT "Gyors leállás felügy.idő"
#define STR2512_TEXT "Gyors leállás felügy.HT-tal"
#define STR2521_TEXT "Kazán fagyvédelem bekapcsolási hőmérséklet"
#define STR2522_TEXT "Kazán fagyvédelem kikapcsolási hőmérséklet"
#define STR2531_TEXT "Biztonsági term.kiold. hőmérséklet"
#define STR2550_TEXT "Gáz energia mérés"
#define STR2551_TEXT "Gáz energia mérés újra áll."
#define STR2630_TEXT "Automatikus légtelenítés"
#define STR2655_TEXT "Légtelenítés bekapcsolási idő"
#define STR2656_TEXT "Légtelenítési idő kikapcsolás"
#define STR2657_TEXT "Ismétlések száma"
#define STR2662_TEXT "Fűtési kör légtelenítési idő"
#define STR2663_TEXT "HMV kör légtelenítési idő"
#define STR2670_TEXT "Állandó hőmérséklet felügyelet"
#define STR2672_TEXT "Felfütés hőmérséklet felügyelet"
#define STR2675_TEXT "HMV átfolyás monitorozása"
#define STR2681_TEXT "Sziv.előf.váltósz.poz.HMV"
#define STR2682_TEXT "Sziv.előf.váltósz.poz.FK-ben"
#define STR2700_TEXT "Szűrt ionizációs áram"
#define STR2702_TEXT "Léptető motor állás"
#define STR2703_TEXT "Learning value gas quality"
#define STR2705_TEXT "Szabályozott jel"
#define STR2706_TEXT "Működési szakasz"
#define STR2720_TEXT "Gáztípus választás engedélyezés"
#define STR2721_TEXT "Gáz típusa"
#define STR2730_TEXT "Ionizációs áram"
#define STR2740_TEXT "Drift teszt indítása"
#define STR2741_TEXT "ADA eredmény"
#define STR2742_TEXT "ADA szűrt érték"
#define STR2743_TEXT "ADA korrekció"
#define STR2744_TEXT "ADA eltelt idő"
#define STR2749_TEXT "Drift teszt reset"
#define STR2750_TEXT "várakozó drift tesztek"
#define STR2751_TEXT "ADA intervallum 1"
#define STR2752_TEXT "ADA intervallum 2"
#define STR2753_TEXT "ADA intervallum 3"
#define STR3810_TEXT "Napkollektor bekapcsolási hőmérséklet különbség"
#define STR3811_TEXT "Napkollektor kikapcsolási hőmérséklet különbség"
#define STR3812_TEXT "Minimális töltési hőmérséklet"
#define STR3831_TEXT "Kollektor szivattyú minimális futási idő"
#define STR3840_TEXT "Kollektor fagyvédelmi hőmérséklet"
#define STR3850_TEXT "Kollektor túlmelegedés védelmi hőmérséklet"
#define STR3860_TEXT "Hőhordozó forrásponti hőmérséklet"
#define STR4721_TEXT "Automatikus hőtermelő letiltás hiszterézis"
#define STR4722_TEXT "Puffer/FK dT a hőtermelő engedélyezéséig"
#define STR5019_TEXT "Alapjelmegemelés réteghőmérs.utántöltéshez"
#define STR5020_TEXT "Előremenő hőmérséklet megemelés HMV-hez"
#define STR5050_TEXT "HMV tároló maximális töltési hőmérséklet"
#define STR5055_TEXT "Minimális visszatérő hőmérséklet HMV-tárolóhoz"
#define STR5100_TEXT "Min.sziv.ford.sz. réteghőmérs. áttöltéshez"
#define STR5420_TEXT "Előremenő hőmérséklet felfűtés"
#define STR5429_TEXT "HMV kapcsolási különbség"
#define STR5430_TEXT "Bekap. különbség HMV üzemmódban (1.érzékelő)"
#define STR5431_TEXT "Min.kikapcs.különbs. HMV üzemm.-ban (1.érzékelő)"
#define STR5432_TEXT "Max.kikapcs.különbs. HMV üzemm.-ban (1.érzékelő)"
#define STR5433_TEXT "Bekap. különbség HMV üzemmódban (2.érzékelő)"
#define STR5434_TEXT "Min.kikapcs.különbség HMV-üzemben (2.érzékelő)"
#define STR5435_TEXT "Min.kikapcs.különbs. HMV üzemm.-ban (2.érzékelő)"
#define STR5450_TEXT "Küszöb a HMV-megcsapolás végéhez Dlh-nál"
#define STR5451_TEXT "Küszöb a HMV-megcs. Vég. Dlh-nál komfortban"
#define STR5452_TEXT "Küszöb a HMV-megcs. Vég. Dlh-nál fűtésnél"
#define STR5453_TEXT "Alapjel korrekció komfort szabályozásnál 40°C"
#define STR5454_TEXT "Alapjel korrekció komfort szabályozásnál 60°C"
#define STR5455_TEXT "Alapjel korrekció kifolyás szabályozásnál 40°C"
#define STR5456_TEXT "Alapjel korrekció kifolyás szabályozásnál 60°C"
#define STR5464_TEXT "Hőmérséklet tartásának engedélyezés"
#define STR5470_TEXT "Hőmérséklet tartási idő fűtés nélkül"
#define STR5476_TEXT "Periódikus hőntartás"
#define STR5480_TEXT "Dlh-Komf.idő megcsap.után aktív fűt.höig.nélkül"
#define STR5481_TEXT "Dlh-Komf.idő megcsap.után aktív fűt.höig.mellett"
#define STR5482_TEXT "Áramlás kapcs. időállandó"
#define STR5483_TEXT "HSZ komfort hőm.korl./áraml.kapcs. zárási idő"
#define STR5486_TEXT "Szabályozás késleltetés DLH pulzációs kifutásnál"
#define STR5487_TEXT "Szivattyú utánjár. Dlh-komfort-ban égő KI-nél"
#define STR5488_TEXT "Szivattyú utánjár. Dlh-komfort-ban égő KI-nél"
#define STR5490_TEXT "Learning function keep hot"
#define STR5491_TEXT "Learning time keep hot"
#define STR5700_TEXT "Előbeállítás"
#define STR5701_TEXT "Hidraulikai séma"
#define STR5721_TEXT "Fűtési kör 3"
#define STR5730_TEXT "HMV érzékelő B3"
#define STR5730_2_TEXT "HMV érzékelő "
#define STR5731_TEXT "HMV szabályzó elem"
#define STR5732_TEXT "Sziv.lekapcsolási idő fűtésről HMV-re váltáskor"
#define STR5733_TEXT "Sziv.lekapcs.késleltetés FK-ról HMV-re vált.-kor"
#define STR5734_TEXT "HMV váltószelep alap állapot"
#define STR5736_TEXT "Dedikált HMV termelés"
#define STR5737_TEXT "Működési mód HMV váltószelep"
#define STR5738_TEXT "HMV váltószelep közép állás"
#define STR5761_TEXT "Hőigény a Q8 támogatásával"
#define STR5772_TEXT "Gázégők átfutási ideje"
#define STR5774_TEXT "Kazán szivattyú / HMV szelep szabályozás"
#define STR5775_TEXT "Kazán szivattyú HMV-hez"
#define STR5840_TEXT "Napkollektor szabályozó egység"
#define STR5841_TEXT "Külső szolár hőcserélő"
#define STR5870_TEXT "Kombi tároló tartály"
#define STR5890_TEXT "Relé kimenet QX1"
#define STR5890_2_TEXT "Szivattyúfunkció kimenet K6"
#define STR5891_TEXT "Relé kimenet QX2"
#define STR5891_2_TEXT "Szivattyúfunkció kimenet K7"
#define STR5892_TEXT "Relé kimenet QX3"
#define STR5894_TEXT "Relé kimenet QX4"
#define STR5895_TEXT "Relé kimenet QX5"
#define STR5896_TEXT "Relé kimenet QX6"
#define STR5902_TEXT "Relé kimenet QX21"
#define STR5904_TEXT "Relé kimenet QX23"
#define STR5908_TEXT "Funkció kimenet QX3-Mod"
#define STR5909_TEXT "Funkció kimenet QX4-Mod"
#define STR5920_TEXT "Programozható kimenet K2"
#define STR5921_TEXT "Alapbeállítás K2, K1-re"
#define STR5922_TEXT "Funkció kimenet 1.relé Clip-In"
#define STR5923_TEXT "Funkció kimenet 2.relé Clip-In"
#define STR5924_TEXT "Funkció kimenet 3.relé Clip-In"
#define STR5926_TEXT "1. kimenet konfigurációja"
#define STR5927_TEXT "2. kimenet konfigurációja"
#define STR5928_TEXT "3. kimenet konfigurációja"
#define STR5930_TEXT "Érzékelő bemenet BX1"
#define STR5931_TEXT "Érzékelő bemenet BX2"
#define STR5932_TEXT "Érzékelő bemenet BX3"
#define STR5933_TEXT "Érzékelő bemenet BX4"
#define STR5941_TEXT "Érzékelő bemenet BX21"
#define STR5942_TEXT "Érzékelő bemenet BX22"
#define STR5950_TEXT "Funkció bemenet H1"
#define STR5951_TEXT "Érintkező típus H1"
#define STR5953_TEXT "Feszültség érték 1 H1"
#define STR5954_TEXT "Wärmeanforderung 10V H1"
#define STR5954_2_TEXT "Működési érték 1 H1"
#define STR5955_TEXT "Feszültség érték 2 H1"
#define STR5956_TEXT "Druckwert 3.5V H1"
#define STR5956_2_TEXT "Működési érték 2 H1"
#define STR5957_TEXT "Modemfunkció"
#define STR5960_TEXT "Funkció bemenet H3"
#define STR5961_TEXT "Érintkező típus H3"
#define STR5963_TEXT "Feszültség érték 1 H3"
#define STR5964_TEXT "Wärmeanforderung 10V H3"
#define STR5964_3_TEXT "Működési érték 1 H3"
#define STR5965_TEXT "Feszültség érték 2 H3"
#define STR5966_TEXT "Druckwert 3.5V H2"
#define STR5966_2_TEXT "Működési érték 2 H3"
#define STR5970_TEXT "Szobatermosztát 1 konfigurálása"
#define STR5970_2_TEXT "Funkció bemenet H4"
#define STR5971_TEXT "Szobatermosztát 2 konfigurálása"
#define STR5971_2_TEXT "Érintkező típus H4"
#define STR5973_TEXT "Funkció bemenet RelCl"
#define STR5973_2_TEXT "H4 frekvencia érték 1"
#define STR5974_TEXT "Működési érték 1 H4"
#define STR5975_TEXT "Hőmérséklet határ külső alapjeladóhoz"
#define STR5975_2_TEXT "H4 frekvencia érték 2"
#define STR5976_TEXT "bemenőjel alsó határ külső hőigényhez"
#define STR5976_2_TEXT "Működési érték 2 H4"
#define STR5977_TEXT "Funkció bemenet H5"
#define STR5978_TEXT "Funkció bemenet SolCl"
#define STR5978_2_TEXT "Érintkező típus H5"

#define STR5980_TEXT "Funkció bemenet EX1"
#define STR5981_TEXT "Érintkező típus EX1"
#define STR5982_TEXT "Funkció bemenet EX2"
#define STR5983_TEXT "Érintkező típus EX2"
#define STR5984_TEXT "Funkció bemenet EX3"
#define STR5985_TEXT "Érintkező típus EX3"
#define STR5986_TEXT "Funkció bemenet EX4"
#define STR5987_TEXT "Érintkező típus EX4"
#define STR5988_TEXT "Funkció bemenet EX5"
#define STR5989_TEXT "Érintkező típus EX5"
#define STR5990_TEXT "Funkció bemenet EX6"
#define STR5992_TEXT "Funkció bemenet EX7"
#define STR6008_TEXT "Funkció bemenet H6"
#define STR6009_TEXT "Érintkező típus H6"
#define STR6011_TEXT "Funkció bemenet H7"
#define STR6012_TEXT "Érintkező típus H7"
#define STR6014_TEXT "Funkció keverőcsoport 1"
#define STR6015_TEXT "Funkció keverőcsoport 2"
#define STR6020_TEXT "Funkció bővítő modul 1"
#define STR6021_TEXT "Funkció bővítő modul 2"
#define STR6022_TEXT "Funkció bővítő modul 3"
#define STR6024_TEXT "Funkció bemenet EX21 Modul 1"
#define STR6026_TEXT "Funkció bemenet EX21 Modul 2"
#define STR6028_TEXT "Funkció bemenet EX21 Modul 3"
#define STR6030_TEXT "Relé kimenet QX21 Modul 1"
#define STR6031_TEXT "Relé kimenet QX22 Modul 1"
#define STR6032_TEXT "Relé kimenet QX23 Modul 1"
#define STR6033_TEXT "Relé kimenet QX21 Modul 2"
#define STR6034_TEXT "Relé kimenet QX22 Modul 2"
#define STR6035_TEXT "Relé kimenet QX23 Modul 2"
#define STR6036_TEXT "Relé kimenet QX21 Modul 3"
#define STR6037_TEXT "Relé kimenet QX22 Modul 3"
#define STR6038_TEXT "Relé kimenet QX23 Modul 3"
#define STR6040_TEXT "Érzékelő bemenet BX21 Modul 1"
#define STR6041_TEXT "Érzékelő bemenet BX22 Modul 1"
#define STR6042_TEXT "Érzékelő bemenet BX21 Modul 2"
#define STR6043_TEXT "Érzékelő bemenet BX22 Modul 2"
#define STR6044_TEXT "Érzékelő bemenet BX21 Modul 3"
#define STR6045_TEXT "Érzékelő bemenet BX22 Modul 3"
#define STR6046_TEXT "Funkció bemenet H2 Modul 1"
#define STR6047_TEXT "Érintkező típus H2 Modul 1"
#define STR6048_2_TEXT "Funktionswert Kontakt H2"
#define STR6049_2_TEXT "Feszültség érték 1 H2 modul 1"
#define STR6050_2_TEXT "Működési érték 1 H2 modul 1"
#define STR6052_2_TEXT "Működési érték 2 H2 modul 1"
#define STR6051_TEXT "Feszültség érték 2 H2 modul 1"
#define STR6052_TEXT "Funktionswert 2 H2"
#define STR6054_TEXT "Funkció bemenet H2 modul 2"
#define STR6055_TEXT "Érintkező típus H2 Modul 2"
#define STR6057_TEXT "Feszültség érték 1 H2 modul 2"
#define STR6058_TEXT "Működési érték 1 H2 modul 2"
#define STR6059_TEXT "Feszültség érték 2 H2 modul 2"
#define STR6060_TEXT "Működési érték 2 H2 modul 2"
#define STR6062_TEXT "Funkció bemenet H2 Modul 3"
#define STR6063_TEXT "Érintkező típus H2 Modul 3"
#define STR6065_TEXT "Feszültség érték 1 H2 modul 3"
#define STR6066_TEXT "Működési érték 1 H2 modul 3"
#define STR6067_TEXT "Feszültség érték 2 H2 modul 3"
#define STR6068_TEXT "Működési érték 2 H2 modul 3"
#define STR6070_TEXT "Funkció kimenet UX"
#define STR6071_TEXT "Signallogik Ausgang UX"
#define STR6072_TEXT "Kimenet UX"
#define STR6075_TEXT "Temperaturwert 10V UX"
#define STR6078_TEXT "Funkció kimenet UX2"
#define STR6079_TEXT "Signallogik Ausgang UX2"
#define STR6085_TEXT "PWM-kimenet P1"
#define STR6086_TEXT "Signallogik Ausgang P1"
#define STR6089_TEXT "Mod Pumpe Drehzahlstufen"
#define STR6089_2_TEXT "Funkció kimenet UX3"
#define STR6090_TEXT "Mod Pumpe Förderhöhe Min"
#define STR6091_TEXT "Mod Pumpe Förderhöhe Max"
#define STR6092_TEXT "Mod Pumpe PWM"
#define STR6093_TEXT "Mod Pumpe PWM Max"
#define STR6097_TEXT "Kollektor érzékelő típusa"
#define STR6098_TEXT "Kollektor érzékelő utánállítás"
#define STR6099_TEXT "Kollektor érzékelő utánállítás 2"
#define STR6100_TEXT "Külső érzékelő utánállítás"
#define STR6101_TEXT "Füstgáz hőmérséklet érzékelő típusa"
#define STR6102_TEXT "Füstgáz érzékelő utánállítás"
#define STR6107_TEXT "Messwertkorrektur Trinkwasserfühler 1 (B3)"
#define STR6110_TEXT "Épület időállandó"
#define STR6112_TEXT "Gradient Raummodell"
#define STR6116_TEXT "Alapjel kompenzáció időállandó"
#define STR6117_TEXT "Központi alapjel kompenzáció"
#define STR6118_TEXT "Alapjel csökkentés késleltetés"
#define STR6120_TEXT "Fagyvédelmi üzem"
#define STR6127_TEXT "Szivattyú/szelep járatás időtartam"
#define STR6128_TEXT "Wärmeanforderung unter Außentemperatur"
#define STR6129_TEXT "Wärmeanforderung über Außentemperatur"
#define STR6131_TEXT "Wärmeanforderung bei Ökobetrieb"
#define STR6135_TEXT "Luftentfeuchter"
#define STR6136_TEXT "Luftentfeuchter Freigabe"
#define STR6137_TEXT "Luftentfeuchter relative Luftfeuchtigkeit ein"
#define STR6138_TEXT "Luftentfeuchter relative Luftfeuchtigkeit Schaltdifferenz"
#define STR6140_TEXT "Maximum víznyomás"
#define STR6141_TEXT "Minimum víznyomás"
#define STR6142_TEXT "Víznyomás alsó kritikus szintje"
#define STR6143_TEXT "Wasserdruckschwelle für Kessel und Pumpe aus"
#define STR6144_TEXT "Kapcsolási hiszterézis víznyomás"
#define STR6145_TEXT "Minimale Druckdifferenz nach Pumpe ein"
#define STR6146_TEXT "Maximale Druckdifferenz nach Pumpe ein"
#define STR6146_2_TEXT "Druckwert 3.5V"
#define STR6148_TEXT "Statische Drucküberwachung 1"
#define STR6150_TEXT "Víznyomás 2 maximum"
#define STR6151_TEXT "Víznyomás 2 minimum"
#define STR6152_TEXT "Víznyomás 2 alsó kritikus szintje"
#define STR6153_TEXT "Víznyomás 2 kapcsolási hiszterézis"
#define STR6180_TEXT "Víznyomás 3 maximum"
#define STR6181_TEXT "Víznyomás 3 minimum"
#define STR6182_TEXT "Víznyomás 3 alsó kritikus szintje"
#define STR6183_TEXT "Víznyomás 3 kapcsolási hiszterézis"
#define STR6200_TEXT "Érzékelők tárolása"
#define STR6201_TEXT "Érzékelők törlése"
#define STR6204_TEXT "Paraméterek mentése"
#define STR6205_TEXT "Gyári paraméterek visszaállítása"
#define STR6212_TEXT "Ellenőrző szám hőtermelő 1"
#define STR6213_TEXT "Ellenőrző szám hőtermelő 2"
#define STR6215_TEXT "Ellenőrző szám tároló tart."
#define STR6217_TEXT "Ellenőrző szám fűtési körök"
#define STR6220_TEXT "Szoftver-verzió"
#define STR6221_TEXT "Development Index"
#define STR6222_TEXT "A készülék üzemideje"
#define STR6223_TEXT "Bisher unbekannte Geräteabfrage"
#define STR6224_TEXT "Készülék azonosító"
#define STR6225_TEXT "Készülékcsalád"
#define STR6226_TEXT "Készülékvariáns"
#define STR6227_TEXT "Objektumkönyvtár-verzió"
#define STR6228_TEXT "Bootloader-verzió"
#define STR6229_TEXT "EEPROM-verzió"
#define STR6230_TEXT "KonfigRg0 Bit 0-7"
#define STR6230_2_TEXT "Info 1 OEM"
#define STR6231_TEXT "Info 2 OEM"
#define STR6232_TEXT "Paraméterverzió"
#define STR6233_TEXT "Parametersatznummer"
#define STR6234_TEXT "A kazán típusszáma OEM"
#define STR6235_TEXT "Paraméterkészlet csoport OEM"
#define STR6236_TEXT "Parametersatznummer OEM"
#define STR6240_TEXT "KonfigRg1 Bit 0-7"
#define STR6240_2_TEXT "Funkció kimenet UX21 Modul 1"
#define STR6241_TEXT "Signallogik Ausgang UX21 Modul 1"
#define STR6242_TEXT "Kimeneti jel (szignál) UX21 Modul 1"
#define STR6243_TEXT "Funkció kimenet UX22 Modul 1"
#define STR6244_TEXT "Signallogik Ausgang UX22 Modul 1"
#define STR6245_TEXT "Kimeneti jel (szignál) UX22 Modul 1"
#define STR6246_TEXT "Funkció kimenet UX21 Modul 2"
#define STR6247_TEXT "Signallogik Ausgang UX21 Modul 2"
#define STR6248_TEXT "Kimeneti jel (szignál) UX21 Modul 2"
#define STR6249_TEXT "Funkció kimenet UX22 Modul 2"
#define STR6250_TEXT "KonfigRg2 Bit 0-7"
#define STR6250_2_TEXT "Signallogik Ausgang UX22 Modul 2"
#define STR6251_TEXT "Kimeneti jel (szignál) UX22 Modul 2"
#define STR6252_TEXT "Funkció kimenet UX21 Modul 3"
#define STR6253_TEXT "Signallogik Ausgang UX21 Modul 3"
#define STR6254_TEXT "Kimeneti jel (szignál) UX21 Modul 3"
#define STR6255_TEXT "Funkció kimenet UX22 Modul 3"
#define STR6256_TEXT "Signallogik Ausgang UX22 Modul 3"
#define STR6257_TEXT "Kimeneti jel (szignál) UX22 Modul 3"
#define STR6258_TEXT "Info 3 OEM"
#define STR6259_TEXT "Info 4 OEM"
#define STR6260_TEXT "KonfigRg3 Bit 0-7"
#define STR6270_TEXT "KonfigRg4 Bit 0-7"
#define STR6270_2_TEXT "Túlmelegedés elleni védelem hőmérséklete"
#define STR6271_TEXT "Überhitzschutz Schaltdiff"
#define STR6272_TEXT "Überhitzschutzfühler"
#define STR6273_TEXT "Überhitzschutz Dauer Min."
#define STR6280_TEXT "KonfigRg5 Bit 0-7"
#define STR6290_TEXT "KonfigRg6 Bit 0-7"
#define STR6300_TEXT "KonfigRg7 Bit 0-7"
#define STR6300_2_TEXT "Info 1 OEM"
#define STR6310_TEXT "KonfigRg8 Bit 0-7"
#define STR6330_TEXT "KonfigRg10 Bit 0-7"
#define STR6344_TEXT "Gyártói azonosító (utolsó négy bájt)"
#define STR6345_TEXT "Hozzáférési kód - üzembehelyezés"
#define STR6346_TEXT "Hozzáférési kód - mérnöki"
#define STR6347_TEXT "Hozzáférési kód - OEM"
#define STR6348_TEXT "Hozzáférési kód - OEM2"
#define STR6351_TEXT "Funktion OT Kanal 1"
#define STR6352_TEXT "Funktion OT Kanal 2"
#define STR6355_TEXT "Teremkezelő FK1"
#define STR6356_TEXT "Teremkezelő FK2"
#define STR6357_TEXT "Teremkezelő FK3"
#define STR6359_TEXT "Externe Bedienung TWW"
#define STR6375_TEXT "Relé kimenet QX35"
#define STR6420_TEXT "Funkció bemenet H33"
#define STR6421_TEXT "Érzékelő típusa H33"
#define STR6486_TEXT "Teilschema Heizkreis 1"
#define STR6487_TEXT "Teilschema Kühlkreis 1"
#define STR6488_TEXT "Teilschema Heizkreis 2"
#define STR6489_TEXT "Teilschema Heizkreis 3"
#define STR6490_TEXT "Teilschema Trinkwasserspeicher"
#define STR6491_TEXT "Teilschema Umformer"
#define STR6492_TEXT "Teilschema H1"
#define STR6493_TEXT "Teilschema H2"
#define STR6494_TEXT "Teilschema Feststoffkessel"
#define STR6495_TEXT "Teilschema Oel-/Gasheizkessel"
#define STR6496_TEXT "Teilschema Schwimmbad"
#define STR6497_TEXT "Teilschema Trinkwasser Durchlauferhitzer"
#define STR6498_TEXT "Teilschema Sonnenkollektor"

#define STR6020_TEXT "Funkció bővítő modul 1"
#define STR6021_TEXT "Funkció bővítő modul 2"
#define STR6022_TEXT "Funkció bővítő modul 3"
#define STR6110_TEXT "Épület időállandó"
#define STR6112_TEXT "Helyiség modell meredekség"
#define STR6120_TEXT "Rendszer fagyvédelem"
#define STR6127_TEXT "Időtartam szivattyú / váltószelep megjáratáshoz"
#define STR6220_TEXT "Készülék-SW-verzió"
#define STR6225_TEXT "Készülék-család"
#define STR6226_TEXT "Készülék-változat"
#define STR6227_TEXT "Készülék-OV-verzió"
#define STR6230_TEXT "Szabályozó konfiguráció 0"
#define STR6240_TEXT "Szabályozó konfiguráció 1"
#define STR6250_TEXT "Szabályozó konfiguráció 2"
#define STR6260_TEXT "Szabályozó konfiguráció 3"
#define STR6270_TEXT "Szabályozó konfiguráció 4"
#define STR6300_TEXT "Szabályozó konfiguráció 7"
#define STR6330_TEXT "Szabályozó konfiguráció 10"
#define STR6604_TEXT "LPB-táplálás funkció választás"
#define STR6605_TEXT "LPB-táplálás státusz"
#define STR6625_TEXT "Használati melegvíz hozzárendelés"
#define STR6640_TEXT "Óra-készülékcím"
#define STR6705_TEXT "Belső diagnosztikai  kód"
#define STR6706_TEXT "zavar fázis aktuális értéke"
#define STR6741_TEXT "Előremenő hőmérséklet riasztási idő FK2"
#define STR6823_TEXT "Albatros hibakód 3. korábbi érték"
#define STR6825_TEXT "3-as zavar diagnosztika korábbi értéke"
#define STR6826_TEXT "3-as hibafázis korábbi értéke"
#define STR6830_TEXT "4-es hibakód számláló korábbi értéke"
#define STR6833_TEXT "Albatros hibakód 4. korábbi érték"
#define STR6835_TEXT "4-es zavar diagnosztika korábbi értéke"
#define STR6836_TEXT "4-es hibafázis korábbi értéke"
#define STR6840_TEXT "5-ös hibakód számláló korábbi értéke"
#define STR6843_TEXT "Albatros hibakód 5. korábbi érték"
#define STR6845_TEXT "5-ös zavar diagnosztika korábbi értéke"
#define STR6846_TEXT "5-ös hibafázis korábbi értéke"
#define STR7001_TEXT "Karbantartás jelzés"
#define STR7007_TEXT "karbantartás jelzés konfigurálás / reset"
#define STR7010_TEXT "Karbantartás jelzés nyugtázás"
#define STR7011_TEXT "Ismétlési idő karbantartás jelzéshez"
#define STR7040_TEXT "Gázégő üzemóra intervallum"
#define STR7041_TEXT "Gázégő üzemóra a legutóbbi nullázás óta"
#define STR7042_TEXT "Gázégő indítási időtartam"
#define STR7043_TEXT "Gázégő indítások a legutóbbi nullázás óta"
#define STR7044_TEXT "Karbantartás időtartama"
#define STR7045_TEXT "Legutóbbi karbantartás óta eltelt hónapok száma"
#define STR7050_TEXT "Ventilátor fordulatszám ionizációs áram"
#define STR7051_TEXT "Ionizáció áram jelentés"
#define STR7130_TEXT "Kéményseprő funkció"
#define STR7131_TEXT "Gázégő teljesítmény"
#define STR7140_TEXT "Kézi vezérlés"
#define STR7143_TEXT "Szabályozó stop funkció"
#define STR7145_TEXT "Szabályozó stop alapjel"
#define STR7146_TEXT "Légtelenítési funkció"
#define STR7147_TEXT "Légtelenítés típusa"
#define STR7165_TEXT "HMV kénysz.hőelvonás"
#define STR7166_TEXT "Beüzemelési funkció"
#define STR7170_TEXT "Felhasználói telefonos szolg."
#define STR7230_TEXT "Víz utántöltés törlés"
#define STR7231_TEXT "Újratöltési idő az aktuális héten"


#define STR7700_TEXT "Reléteszt"
#define STR7705_TEXT "Modulationssollwert QX3 Relaistest"
#define STR7705_2_TEXT "Modulationssollwert ZX4 Relaistest"
#define STR7708_TEXT "Modulationssignal QX3"
#define STR7708_2_TEXT "Modulationssignal ZX4"
#define STR7710_TEXT "Kimeneti teszt UX1"
#define STR7711_TEXT "Spannungssignal UX1"
#define STR7711_2_TEXT "Ausgangssignal UX1"
#define STR7712_TEXT "PWM-Signal UX1"
#define STR7713_TEXT "P1 kimeneti teszt"
#define STR7714_TEXT "PWM-jel P1"
#define STR7716_TEXT "Kimeneti teszt UX2"
#define STR7717_TEXT "Kimeneti jel UX2"
#define STR7718_TEXT "Ausgangssignalwert UX2"
#define STR7719_TEXT "PWM-Signal UX2"
#define STR7720_TEXT "Kimeneti teszt Digital"
#define STR7721_TEXT "Digitalausgang D01"
#define STR7722_TEXT "Kühlbetrieb D2"
#define STR7723_TEXT "Wärmepumpe D3"
#define STR7724_TEXT "Kimeneti teszt UX3"
#define STR7725_TEXT "Spannungssignal U4 (Ux3)"
#define STR7725_2_TEXT "Kimeneti jel UX3"
#define STR7726_TEXT "Ausgangssignalwert UX3"
#define STR7730_TEXT "Külső hőmérséklet érzékelő B9"
#define STR7732_TEXT "Vorlauftemperatur B1"
#define STR7734_TEXT "Vorlauftemperatur B12"
#define STR7750_TEXT "HMV hőmérséklet B3/B38"
#define STR7760_TEXT "Kazán hőmérséklet B2"
#define STR7770_TEXT "Vorlauftemperatur WP B21"
#define STR7771_TEXT "Rücklauftemperatur WP B71"
#define STR7772_TEXT "Heissgastemperatur B81"
#define STR7775_TEXT "Quelle Eintrittstemperatur B91"
#define STR7777_TEXT "Fühlertemperatur B92, B84"
#define STR7780_TEXT "Kimeneti teszt UX21 Modul 1"
#define STR7781_TEXT "Ausgangssignal UX21 Modul"
#define STR7782_TEXT "Kimeneti teszt UX22 Modul 1"
#define STR7783_TEXT "Ausgangssignal UX22 Modul 1"
#define STR7784_TEXT "Kimeneti teszt UX21 Modul 2"
#define STR7785_TEXT "Ausgangssignal UX21 Modul 2"
#define STR7785_2_TEXT "Ausgangssignal UX21 Modul 2 PWM %"
#define STR7786_TEXT "Kimeneti teszt UX22 Modul 2"
#define STR7787_TEXT "Ausgangssignal UX22 Modul 2"
#define STR7787_2_TEXT "Ausgangssignal UX22 Modul 2 PWM %"
#define STR7788_TEXT "Kimeneti teszt UX21 Modul 3"
#define STR7789_TEXT "Ausgangssignal UX21 Modul 3"
#define STR7790_TEXT "Kimeneti teszt UX22 Modul 3"
#define STR7791_TEXT "Ausgangssignal UX22 Modul 3"
#define STR7810_TEXT "Hőmérséklet érzékelő BX7"
#define STR7811_TEXT "Hőmérséklet érzékelő BX8"
#define STR7812_TEXT "Hőmérséklet érzékelő BX9"
#define STR7813_TEXT "Hőmérséklet érzékelő BX10"
#define STR7814_TEXT "Hőmérséklet érzékelő BX11"
#define STR7815_TEXT "Hőmérséklet érzékelő BX12"
#define STR7816_TEXT "Hőmérséklet érzékelő BX13"
#define STR7817_TEXT "Hőmérséklet érzékelő BX14"
#define STR7809_TEXT "Hőmérséklet érzékelő BX6"
#define STR7820_TEXT "Hőmérséklet érzékelő BX1"
#define STR7821_TEXT "Hőmérséklet érzékelő BX2"
#define STR7822_TEXT "Hőmérséklet érzékelő BX3"
#define STR7823_TEXT "Hőmérséklet érzékelő BX4"
#define STR7824_TEXT "Hőmérséklet érzékelő BX5"
#define STR7830_TEXT "Hőmérséklet érzékelő BX21 Modul 1"
#define STR7831_TEXT "Hőmérséklet érzékelő BX22 Modul 1"
#define STR7832_TEXT "Hőmérséklet érzékelő BX21 Modul 2"
#define STR7833_TEXT "Hőmérséklet érzékelő BX22 Modul 2"
#define STR7834_TEXT "Hőmérséklet érzékelő BX21 Modul 3"
#define STR7835_TEXT "Hőmérséklet érzékelő BX22 Modul 3"
#define STR7840_TEXT "Feszültség-jel H1"
#define STR7841_TEXT "Érintkező helyzet H1"
#define STR7844_TEXT "Bemenetssignal H1"
#define STR7845_TEXT "Feszültség-jel H2 modul 1"
#define STR7846_TEXT "Érintkező helyzet H2"
#define STR7847_TEXT "Zustand Kontakt H2, Modul 2"
#define STR7848_TEXT "Érintkező helyzet H2 modul 2"
#define STR7849_TEXT "Érintkező helyzet H2 modul 2 - Parameter"
#define STR7852_TEXT "Érintkező helyzet H2 Modul 3"
#define STR7854_TEXT "Feszültség-jel H3"
#define STR7855_TEXT "Érintkező helyzet H3"
#define STR7858_TEXT "Bemenet signal H3"
#define STR7860_TEXT "Érintkező helyzet H4"
#define STR7862_TEXT "H4 Frekvencia"
#define STR7865_TEXT "Érintkező helyzet H5"
#define STR7870_TEXT "Brennerstörung S3"
#define STR7872_TEXT "Érintkező helyzet H6"
#define STR7874_TEXT "Érintkező helyzet H7"
#define STR7881_TEXT "1. Brennerstufe E1"
#define STR7884_TEXT "STB Fehlermeldung L1"
#define STR7889_TEXT "Niederdruckwächter E9"
#define STR7890_TEXT "Hochdruckwächter E10"
#define STR7891_TEXT "Wicklungsschutz Verdicht 1 E11"
#define STR7911_TEXT "Bemenet EX1"
#define STR7912_TEXT "Bemenet EX2"
#define STR7913_TEXT "Bemenet EX3"
#define STR7914_TEXT "Bemenet EX4"
#define STR7915_TEXT "Bemenet EX5"
#define STR7916_TEXT "Bemenet EX6"
#define STR7917_TEXT "Bemenet EX7"
#define STR7919_TEXT "Bemenet EX9"
#define STR7945_TEXT "Bemenet EX10"
#define STR7946_TEXT "Bemenet EX11"
#define STR7950_TEXT "Bemenet EX01 Modul 1"
#define STR7951_TEXT "Bemenet EX01 Modul 2"
#define STR7952_TEXT "Bemenet EX01 Modul 3"
#define STR7973_TEXT "Hőmérséklet érzékelő BX31"
#define STR7974_TEXT "Hőmérséklet érzékelő BX32"
#define STR7975_TEXT "Hőmérséklet érzékelő BX33"
#define STR7976_TEXT "Hőmérséklet érzékelő BX34"
#define STR7977_TEXT "Hőmérséklet érzékelő BX35"
#define STR7978_TEXT "Hőmérséklet érzékelő BX36"
#define STR7996_TEXT "Zustand Kontakt H33"
#define STR7999_TEXT "Bemenetssignal H33"

#define STR8000_TEXT "Fűtési kör 1 állapot"
#define STR8001_TEXT "Fűtési kör 2 állapot"
#define STR8002_TEXT "Fűtési kör 3 állapot"
#define STR8003_TEXT "HMV állapot"
#define STR8005_TEXT "Kazán állapot"
#define STR8007_TEXT "Szolár állapot"
#define STR8008_TEXT "Szilárd tüzelésű kazán állapot"
#define STR8009_TEXT "Gázégők állapota"
#define STR8010_TEXT "Puffer állapot"
#define STR8011_TEXT "Uszoda állapot"
#define STR8023_TEXT "SithermPro állapot"
#define STR8300_TEXT "Égőfokozat 1. - T2"
#define STR8301_TEXT "Égőfokozat 2. - T8"
#define STR8304_TEXT "Kazán szivattyú Q1"
#define STR8308_TEXT "Kazán szivattyú fordulatszám"
#define STR8310_TEXT "Kazánhőmérséklet aktuális érték"
#define STR8311_TEXT "Kazánhőmérséklet alapjel"
#define STR8312_TEXT "Kazán kapcsolási pont"
#define STR8313_TEXT "Kapcsolási pont HMV működés"
#define STR8314_TEXT "Visszatérő hőmérséklet aktuális érték"
#define STR8315_TEXT "Visszatérő hőmérséklet alapjel"
#define STR8316_TEXT "Füstgáz hőmérséklet aktuális érték"
#define STR8318_TEXT "Füstgáz hőmérséklet eddigi maximuma"
#define STR8321_TEXT "Primer hőcserélő hőmérséklet aktuális érték"
#define STR8323_TEXT "Aktuális ventilátor fordulatszám"
#define STR8324_TEXT "Ventilátor fordulatszám alapjel"
#define STR8325_TEXT "Aktuális ventilátor szabályzás"
#define STR8326_TEXT "Égő moduláció"
#define STR8327_TEXT "Víznyomás"
#define STR8328_TEXT "Égővezérlő üzemmód kijelzés"
#define STR8329_TEXT "Ionizációs áram mért érték"
#define STR8330_TEXT "1. fokozat üzemóra"
#define STR8331_TEXT "1. fokozat indulások száma"
#define STR8332_TEXT "2. fokozat üzemóra"
#define STR8333_TEXT "2. fokozat indulások száma"
#define STR8336_TEXT "Készülék üzemóra"
#define STR8337_TEXT "Égő startszámláló"
#define STR8338_TEXT "Fűtési mód üzemóra"
#define STR8339_TEXT "HMV mód üzemóra"
#define STR8340_TEXT "Külső hőigény üzemóraszám"
#define STR8378_TEXT "Teljes eddigi gáz energia felhasználás - Fűtés"
#define STR8379_TEXT "Teljes eddigi gáz energia felhasználás - HMV"
#define STR8380_TEXT "Teljes eddigi gáz energia felhasználás - Összesen"
#define STR8381_TEXT "Gáz energia - fűtés számláló (nullázható)"
#define STR8382_TEXT "Gáz energia - HMV számláló (nullázható)"
#define STR8383_TEXT "Gáz energia - Összesen számláló (nullázható)"
#define STR8390_TEXT "Aktuális szakasz száma"
#define STR8499_TEXT "Zustand Kollektorpumpe (Q5)"
#define STR8499_2_TEXT "Kollektor szivattyú 1"
#define STR8501_TEXT "Napollektor szab.egys. puffer"
#define STR8502_TEXT "Napollektor szab.egys. uszoda"
#define STR8505_TEXT "Kollektor szivattyú 1 fordulatszáma"
#define STR8506_TEXT "Szolár külső hőcserélő szivattyú fordulatszám"
#define STR8507_TEXT "Puffer szolár szivattyú fordulatszám"
#define STR8508_TEXT "Uszoda szolár szivattyú fordulatszám"
#define STR8510_TEXT "Kollektor 1 hőmérséklet aktuális érték (B6)"
#define STR8511_TEXT "Kollektor 1 hőmérsékleti maximum"
#define STR8512_TEXT "Kollektor 1 hőmérsékleti minimum"
#define STR8513_TEXT "dT kollektor 1/ HMV"
#define STR8514_TEXT "dT kollektor 1/ puffer"
#define STR8515_TEXT "dT kollektor 1/ Uszoda"
#define STR8519_TEXT "Kollektor előremenő hőmérséklet"
#define STR8520_TEXT "Kollektor visszatérő hőmérséklet"
#define STR8521_TEXT "Solar flow"
#define STR8526_TEXT "24-órás szolár energia hozam"
#define STR8527_TEXT "Eddigi kinyert szolár energia összesen"
#define STR8530_TEXT "Szolár hőtermelő üzemóraszám"
#define STR8531_TEXT "Kollektor túlhőmérsékleti időtartam"
#define STR8532_TEXT "Kollektor szivattyú üzemidő"
#define STR8543_TEXT "Kollektor szivattyú 2 fordulatszáma"
#define STR8547_TEXT "Kollektor 2 hőmérséklet aktuális érték"
#define STR8548_TEXT "Kollektor 2 hőmérsékleti maximum"
#define STR8549_TEXT "Kollektor 2 hőmérsékleti minimum"
#define STR8550_TEXT "dT kollektor 2/ HMV"
#define STR8551_TEXT "dT kollektor 2/ puffer"
#define STR8552_TEXT "dT kollektor 2/ Uszoda"
#define STR8560_TEXT "Szilárd tüzelésű kazán hőmérséklet"
#define STR8570_TEXT "Szilárd tüzelésű kazán üzemóra"
#define STR8700_TEXT "Külső hőmérséklet"
#define STR8701_TEXT "Külső hőmérsékleti minimum"
#define STR8702_TEXT "Külső hőmérsékleti maximum"
#define STR8703_TEXT "Csillapított külső hőmérséklet"
#define STR8704_TEXT "Korrigált külső hőmérséklet"
#define STR8705_TEXT "Külső hőmérséklet LPB"
#define STR8720_TEXT "A szoba relatív páratartalma"
#define STR8721_TEXT "Szobahőmérséklet"
#define STR8722_TEXT "Harmatponti hőmérséklet"
#define STR8730_TEXT "FK1 szivattyú Q2"
#define STR8731_TEXT "FK1 keverőszelep 1 nyit"
#define STR8732_TEXT "FK1 keverőszelep 2 zár"
#define STR8735_TEXT "FK1 szivattyú fordulatszáma"
#define STR8739_TEXT "Környezeti páratartalom 1"
#define STR8740_TEXT "FK1 Kezelőegységen mért szobahőmérséklet"
#define STR8741_TEXT "FK1 Kezelőegységen beállított ideiglenes hőmérséklet"
#define STR8742_TEXT "FK1 Szobahőmérséklet modell"
#define STR8743_TEXT "FK1 Aktuális előremenő hőmérséklet érték"
#define STR8744_TEXT "FK1 Előremenő alapjel"
#define STR8749_TEXT "Szobatermosztát 1"
#define STR8750_TEXT "FK1 Szivattyú modulációs alapjel"
#define STR8751_TEXT "HK1 szivattyú Q24"
#define STR8752_TEXT "HK1 keverőszelep nyit Y23"
#define STR8753_TEXT "HK1 keverőszelep zár Y24"
#define STR8754_TEXT "HK1 váltószelep Y21"
#define STR8756_TEXT "HK1 aktuális előremenő hőmérséklet"
#define STR8757_TEXT "HK1 előremenő hőmérséklet alapjel"
#define STR8760_TEXT "FK2 szivattyú"
#define STR8761_TEXT "FK2 keverőszelep nyit Y1"
#define STR8762_TEXT "FK2 keverőszelep zár Y2"
#define STR8765_TEXT "FK2 szivattyú fordulatszáma"
#define STR8770_TEXT "FK2 Termosztáton mért szobahőmérséklet"
#define STR8771_TEXT "FK2 Termosztáton beállított ideiglenes hőmérséklet"
#define STR8772_TEXT "FK2 Szobahőmérséklet modell"
#define STR8773_TEXT "FK2 Aktuális előremenő hőmérséklet"
#define STR8774_TEXT "FK2 Előremenő alapjel"
#define STR8779_TEXT "FK2 Szobatermosztát"
#define STR8790_TEXT "FK3 szivattyú"
#define STR8791_TEXT "FK3 keverőszelep nyit Y1"
#define STR8792_TEXT "FK3 keverőszelep zár Y2"
#define STR8795_TEXT "FK3 szivattyú fordulatszáma"
#define STR8800_TEXT "FK3 mért szobahőmérséklet"
#define STR8801_TEXT "FK3 beállított ideiglenes hőmérséklet"
#define STR8802_TEXT "FK3 Szobahőmérséklet modell"
#define STR8803_TEXT "FK3 Aktuális előremenő hőmérséklet"
#define STR8804_TEXT "FK3 Előremenő alapjel"
#define STR8809_TEXT "FK3 Szobatermosztát"
#define STR8820_TEXT "HMV szivattyú Q3"
#define STR8821_TEXT "HMV elektromos fűtőbetét K6"
#define STR8823_TEXT "HMV közbenső kör szivattyú állapota Q33"
#define STR8825_TEXT "HMV szivattyú fordulatszáma"
#define STR8826_TEXT "HMV közbenső kör szivattyú fordulatszáma"
#define STR8827_TEXT "Átfolyós HMV szivattyú fordulatszám"
#define STR8830_TEXT "HMV hőmérséklet alsó"
#define STR8831_TEXT "HMV hőmérséklet alapjel"
#define STR8832_TEXT "HMV hőmérséklet felső"
#define STR8835_TEXT "HMV cirkulációs hőmérséklet"
#define STR8836_TEXT "HMV töltési hőmérséklet"
#define STR8837_TEXT "HMV töltési alapjel"
#define STR8840_TEXT "HMV szivattyú üzemóra"
#define STR8841_TEXT "HMV szivattyú startszámláló"
#define STR8842_TEXT "HMV elektromos fűtőbetét üzemóra"
#define STR8843_TEXT "HMV elektromos fűtőbetét startszámláló"
#define STR8850_TEXT "HMV előzetes szabályozási hőmérséklet"
#define STR8851_TEXT "HMV előzetes szabályozási hőmérséklet alapjel"
#define STR8852_TEXT "HMV vételezési hőmérséklet"
#define STR8853_TEXT "HMV vételezési hőmérséklet alapjel"
#define STR8860_TEXT "HMV áramlás, átfolyás mennyisége"
#define STR8875_TEXT "Előremenő hőmérsékleti alapjel Consumer circuit 1"
#define STR8885_TEXT "Előremenő hőmérsékleti alapjel Consumer circuit 2"
#define STR8895_TEXT "Előremenő hőmérsékleti alapjel uszoda"
#define STR8950_TEXT "Processz szignál aktuális előremenő hőmérséklet"
#define STR8951_TEXT "Processz szignál előremenő hőmérséklet alapjel"
#define STR8952_TEXT "Processz szignál visszatérő hőmérséklet"
#define STR8980_TEXT "Puffertároló hőm. aktuális érték felül (B4)"
#define STR8900_TEXT "Uszoda hőmérséklet"
#define STR8901_TEXT "Uszoda hőmérsékleti alapjel"
#define STR8930_TEXT "Előszabályozás hőmérséklet"
#define STR8931_TEXT "Előszabályozás alapjel"
#define STR8950_TEXT "Közös előremenő aktuális hőmérséklet"
#define STR8951_TEXT "Közös előremenő hőmérséklet alapjel"
#define STR8952_TEXT "Közös visszatérő aktuális hőmérséklet"
#define STR8962_TEXT "Közös teljesítmény alapjel"
#define STR8980_TEXT "Puffer 1 aktuális hőmérséklet"
#define STR8981_TEXT "Puffer hőmérséklet alapjel"
#define STR8982_TEXT "Puffer 2 aktuális hőmérséklet"
#define STR8983_TEXT "Puffer 3 aktuális hőmérséklet"
#define STR9000_TEXT "FK1 hőmérsékletének alapértéke"
#define STR9001_TEXT "FK2 hőmérsékletének alapértéke"
#define STR9004_TEXT "FK3 hőmérsékletének alapértéke"
#define STR9005_TEXT "FK1 víznyomás"
#define STR9006_TEXT "FK2 víznyomás"
#define STR9009_TEXT "FK3 víznyomás"
#define STR9031_TEXT "Relé kimenet QX1"
#define STR9032_TEXT "Relé kimenet QX2"
#define STR9033_TEXT "Relé kimenet QX3"
#define STR9034_TEXT "Relé kimenet QX4"
#define STR9035_TEXT "Relé kimenet QX5"
#define STR9036_TEXT "Relé kimenet QX6"
#define STR9037_TEXT "Relé kimenet QX7"
#define STR9038_TEXT "Relé kimenet QX8"
#define STR9039_TEXT "Relé kimenet QX9"
#define STR9040_TEXT "Relé kimenet QX10"
#define STR9041_TEXT "Relé kimenet QX11"
#define STR9042_TEXT "Relé kimenet QX12"
#define STR9043_TEXT "Relé kimenet QX13"
#define STR9050_TEXT "Relé kimenet QX21 modul 1"
#define STR9051_TEXT "Relé kimenet QX22 modul 1"
#define STR9052_TEXT "Relé kimenet QX23 modul 1"
#define STR9053_TEXT "Relé kimenet QX21 modul 2"
#define STR9054_TEXT "Relé kimenet QX22 modul 2"
#define STR9055_TEXT "Relé kimenet QX23 modul 2"
#define STR9056_TEXT "Relé kimenet QX21 modul 3"
#define STR9057_TEXT "Relé kimenet QX22 modul 3"
#define STR9058_TEXT "Relé kimenet QX23 modul 3"
#define STR9071_TEXT "Relé kimenet QX31"
#define STR9072_TEXT "Relé kimenet QX32"
#define STR9073_TEXT "Relé kimenet QX33"
#define STR9074_TEXT "Relé kimenet QX34"
#define STR9075_TEXT "Relé kimenet QX35"
#define STR9500_TEXT "Előszellóztetési idő"
#define STR9501_TEXT "Előszellóztetési idő minimum"
#define STR9502_TEXT "Levegő moduláció előszellőztetéskor"
#define STR9504_TEXT "Ventilátor előszellőztetési fordulatszám alapjel"
#define STR9505_TEXT "Szükséges fordulatszám minimum előszellőztetéshez"
#define STR9506_TEXT "Fordulatszám eltérés előszellőztetés"
#define STR9510_TEXT "Modulációs levegő gyújtási teljesítménynél"
#define STR9512_TEXT "Szükséges fordulatszám minimum gyújtáshoz"
#define STR9513_TEXT "Szükséges fordulatszám maximum gyújtáshoz"
#define STR9514_TEXT "Fordulatszám eltérés gyújtás"
#define STR9517_TEXT "Előgyújtási idő"
#define STR9518_TEXT "Biztonsági idő"
#define STR9519_TEXT "Biztonsági idő gyújtással"
#define STR9520_TEXT "Modulációs levegő részterhelésnél"
#define STR9522_TEXT "Modulációs levegő teljes terhelésnél"
#define STR9524_TEXT "Szükséges ventilátor fordulatszám részleges terhelésnél"
#define STR9525_TEXT "Szükséges ventilátor fordulatszám részterhelés min"
#define STR9526_TEXT "Ventilátor fordulatszám eltérés részterhelésnél"
#define STR9527_TEXT "Maximum működési cél-fordulatszám"
#define STR9529_TEXT "Szükséges ventilátor fordulatszám teljes terhelésnél"
#define STR9530_TEXT "Szükséges ventilátor fordulatszám teljes terhelésnél max"
#define STR9531_TEXT "Ventilátor fordulatszám eltérés teljes terhelésnél"
#define STR9534_TEXT "Üzemidő égőterheléssel"
#define STR9540_TEXT "Utószellőztetési idő"
#define STR9541_TEXT "Utószellőztetési idő TL max"
#define STR9542_TEXT "Utószellőztetési idő min"
#define STR9545_TEXT "Utószellőztetési lockout pozícióban"
#define STR9551_TEXT "Szükséges fordulatszám stop maximum"
#define STR9560_TEXT "Ventill.mod. biztonsági tároló feltöltéskor"
#define STR9563_TEXT "Ventill.alapjel biztonsági tároló feltöltéskor"
#define STR9610_TEXT "Teljesítmény"
#define STR9611_TEXT "LP konfiguráció"
#define STR9612_TEXT "GP konfiguráció"
#define STR9614_TEXT "Utószellőztetési szint"
#define STR9615_TEXT "Hiba esetén előszellőztetés kikényszerítése"
#define STR9616_TEXT "Maximális fordulatszám"
#define STR9617_TEXT "Hall sensor pulses/rev"
#define STR9618_TEXT "Ion curr level extran light"
#define STR9619_TEXT "Ion curr level flame exting"
#define STR9626_TEXT "Ventilátor kim./fordulatszám görbe"
#define STR9627_TEXT "Ventilátor kim./fordulatszám metsz.p"
#define STR9630_TEXT "Kp fordulatszám"
#define STR9631_TEXT "Tn fordulatszám"
#define STR9632_TEXT "Tv fordulatszám"
#define STR9650_TEXT "Kémény szárítás"
#define STR9651_TEXT "Kémény szárításhoz szükséges fordulatszám"
#define STR9652_TEXT "Kémény szárítás időtartam"

#define ENUM48_00_TEXT "Egyik sem"
#define ENUM48_03_TEXT "Közösen"
#define ENUM130_01_TEXT "Üzemben"
#define ENUM648_00_TEXT "Fagyvédelem"
#define ENUM648_01_TEXT "Csökkentett"
#define ENUM700_00_TEXT "Fagyvédelmi"
#define ENUM700_01_TEXT "Automatikus"
#define ENUM700_03_TEXT "Komfort"
#define ENUM701_00_TEXT "Visszatérés komfort módba"
#define ENUM701_02_TEXT "Komfort mód érvényre juttatása"
#define ENUM780_01_TEXT "Csökkentett hőmérsékleti alapjelre"
#define ENUM780_02_TEXT "Fagyvédelmi hőmérsékleti alapjelre"
#define ENUM832_00_TEXT "2-pont"
#define ENUM832_01_TEXT "3-pont"
#define ENUM861_01_TEXT "Fűtési mód"
#define ENUM861_02_TEXT "Mindig"
#define ENUM880_00_TEXT "Működési szint"
#define ENUM880_01_TEXT "Görbe (curve)"
#define ENUM1600_02_TEXT "Eco"
#define ENUM1602_00_02_TEXT "HMV-Push nem aktív"
#define ENUM1602_02_02_TEXT "HMV-Push aktív"
#define ENUM1602_00_04_TEXT "HMV ki"
#define ENUM1602_04_04_TEXT "HMV be"
#define ENUM1602_00_08_TEXT "HMV töltés nem aktív"
#define ENUM1602_08_08_TEXT "HMV töltés aktív"
#define ENUM1620_00_TEXT "24h/nap"
#define ENUM1620_01_TEXT "Fűtési körök időprogramja"
#define ENUM1620_02_TEXT "Időprogram 4/ HMV"
#define ENUM1630_00_TEXT "Abszolút"
#define ENUM1630_01_TEXT "Csúszó"
#define ENUM1630_02_TEXT "Nem"
#define ENUM1630_03_TEXT "Keverőkhöz csúszó / szivattyúkhoz abszolút"
#define ENUM1660_02_TEXT "HMV engedélyezés"
#define ENUM2320_01_TEXT "Szükséges"

#define ENUM4133_01_TEXT "HMV érzékelő B3"
#define ENUM4133_02_TEXT "HMV érzékelő B31"
#define ENUM4133_04_TEXT "Puffer tartály érzékelő B41"
#define ENUM4133_05_TEXT "Áramlási alapérték"

#define ENUM5730_00_TEXT "Érzékelő"
#define ENUM5730_01_TEXT "Termosztát"
#define ENUM5730_2_03_TEXT "HMV kilépő érzékelő B38"
#define ENUM5731_00_TEXT "Nincs töltési igény"
#define ENUM5731_01_TEXT "Töltőszivattyú"
#define ENUM5731_02_TEXT "Váltószlep"
#define ENUM5734_00_TEXT "Utolsó igény"
#define ENUM5734_01_TEXT "Fűtési kör"
#define ENUM5737_00_TEXT "Bekapcsolva a HMV körön"
#define ENUM5737_FF_TEXT "Bekapcsolva a fűtési körön"
#define ENUM5774_00_TEXT "Összes igény"
#define ENUM5774_ff_TEXT "Igény csak FK1/HMV-től"
#define ENUM8749_00_TEXT "Nem szükséges"

#define ENUM5890_01_TEXT "Cirkulációs szivattyú Q4"
#define ENUM5890_02_TEXT "HMV el. fűtőpatron K6"
#define ENUM5890_03_TEXT "Kollektor szivattyú Q5"
#define ENUM5890_04_TEXT "Hőfogy.köri szivattyú VK1 Q15"
#define ENUM5890_05_TEXT "Kazán szivattyú Q1"
#define ENUM5890_06_TEXT "Bypass szivattyú Q12"
#define ENUM5890_07_TEXT "Riasztás kimenet K10"
#define ENUM5890_08_TEXT "2.szivattyú fordulatszám FK1 Q21"
#define ENUM5890_09_TEXT "2.szivattyú fordulatszám FK2 Q22"
#define ENUM5890_0a_TEXT "2.szivattyú fordulatszám FK3 Q23"
#define ENUM5890_0b_TEXT "3. fűtési kör szivattyú Q20"
#define ENUM5890_0c_TEXT "Hőfogy.köri szivattyú VK1 Q18"
#define ENUM5890_0d_TEXT "Rendszer szivattyú Q14"
#define ENUM5890_0e_TEXT "Hőtermelő kizárószelep Y4"
#define ENUM5890_0f_TEXT "Szilárd tüzelésű kazán szivattyú Q10"
#define ENUM5890_10_TEXT "Időprogram 5 K13"
#define ENUM5890_11_TEXT "Puffer visszatérő szelep Y15"
#define ENUM5890_12_TEXT "Napkollektor szivattyú külső csere K9"
#define ENUM5890_13_TEXT "Napkollektor szabályzó egység puffer K8"
#define ENUM5890_14_TEXT "Napkollektor szabályzó egység medence K18"
#define ENUM5890_15_TEXT "Kollektor szivattyú 2 Q16"
#define ENUM5890_16_TEXT "Medence szivattyú Q19"
#define ENUM5890_17_TEXT "Abgasrelais K17"
#define ENUM5890_18_TEXT "Anfeuerungshilfe Ventilator K30"
#define ENUM5890_19_TEXT "Kaszkád szivattyú Q25"
#define ENUM5890_1a_TEXT "Transzfer szivattyú Q11"
#define ENUM5890_1b_TEXT "HMV keverő szivattyú Q35"
#define ENUM5890_1c_TEXT "HMV belső keringető szivattyú Q33"
#define ENUM5890_1d_TEXT "Hőigény K27"
#define ENUM5890_1e_TEXT "Hűtési igény K28"
#define ENUM5890_21_TEXT "FK1 szivattyú Q2"
#define ENUM5890_22_TEXT "FK2 szivattyú Q6"
#define ENUM5890_23_TEXT "HMV szabályzó elem Q3"
#define ENUM5890_24_TEXT "Átfolyós vízmelegítő szabályzó elem Q34"
#define ENUM5890_26_TEXT "Víz feltöltés K34"
#define ENUM5890_27_TEXT "2. kazán szivattyú fordulatszám Q27"
#define ENUM5890_28_TEXT "Kimenet állapot K35"
#define ENUM5890_29_TEXT "Állapot információ K36"
#define ENUM5890_2a_TEXT "Égéstermék zsalu K37"
#define ENUM5890_2b_TEXT "Ventilátor leállítás K38"
#define ENUM5890_2d_TEXT "dT-szabályzó 1 K21"
#define ENUM5890_2e_TEXT "dT-szabályzó 2 K22"
#define ENUM5896_18_TEXT "3. fűtési kör szivattyú Q20"

#define ENUM5930_02_TEXT "Kollektor érzékelő B6"
#define ENUM5930_03_TEXT "Rücklauffühler B7"
#define ENUM5930_04_TEXT "HMV cirkulációs érzékelő B39"
#define ENUM5930_07_TEXT "Égéstermék hőmérséklet B8"
#define ENUM5930_08_TEXT "Közös előremenő érzékelő B10"
#define ENUM5930_09_TEXT "Szilárd tüz.kazán hőm.érz. B22"
#define ENUM5930_0a_TEXT "HMV töltés érzékelő B36"
#define ENUM5930_0b_TEXT "Puffer érzékelő B42"
#define ENUM5930_0c_TEXT "Közös visszatérő érzékelő B73"
#define ENUM5930_0d_TEXT "Kaszkád visszatérő érzékelő B70"
#define ENUM5930_0e_TEXT "Uszoda érzékelő B13"
#define ENUM5930_0f_TEXT "Kollektor érzékelő 2 B61"
#define ENUM5930_10_TEXT "Napkoll. előremenő érz. B63"
#define ENUM5930_11_TEXT "Napkoll. visszatérő érz. B64"

#define ENUM5950_01_TEXT "Üzemmód váltás FK+HMV"
#define ENUM5950_02_TEXT "Üzemmód váltás minden FK"
#define ENUM5950_03_TEXT "Üzemmód váltás FK1"
#define ENUM5950_04_TEXT "Üzemmód váltás FK2"
#define ENUM5950_05_TEXT "Üzemmód váltás FK3"
#define ENUM5950_07_TEXT "Hiba / riasztás üzenet"
#define ENUM5950_08_TEXT "Minimaler Vorlaufsollwert"
#define ENUM5950_0a_TEXT "Uszoda helyi fűtés enged."
#define ENUM5950_0b_TEXT "Harmatpont monitor"
#define ENUM5950_0c_TEXT "Vorlaufsollwertanhebung Hygro"
#define ENUM5950_0d_TEXT "Teljesítmény igény 10V"
#define ENUM5950_0e_TEXT "Nyomásmérés 10V"
#define ENUM5950_34_TEXT "Verbrauchsanforderung VK1 10V"
#define ENUM5950_2_02_TEXT "Modem funkció inverz"
#define ENUM5950_2_07_TEXT "Rückmeldung Abgasklappe"
#define ENUM5950_2_09_TEXT "Erzeugersperre invers"
#define ENUM5950_3_01_TEXT "BA-Umschaltung HK+TWW"
#define ENUM5950_4_01_TEXT "BA-Umschaltung HK+TWW"
#define ENUM5950_4_02_TEXT "BA-Umschaltung TWW"
#define ENUM5950_4_06_TEXT "BA-Umschaltung HK3"
#define ENUM5950_4_09_TEXT "Verbraucheranforderung VK1"
#define ENUM5950_4_0a_TEXT "Verbraucheranforderung VK2"
#define ENUM5950_4_0b_TEXT "Freigabe Schwimmbad Erzeuger"
#define ENUM5950_4_0d_TEXT "Freigabe Schwimmbad Erzeuger Solar"
#define ENUM5950_4_0e_TEXT "Működési szint HMV"
#define ENUM5950_4_0f_TEXT "Működési szint FK1"
#define ENUM5950_4_10_TEXT "Működési szint FK2"
#define ENUM5950_4_11_TEXT "Működési szint FK3"
#define ENUM5950_4_12_TEXT "Szobatermosztát FK1"
#define ENUM5950_4_13_TEXT "Szobatermosztát FK2"
#define ENUM5950_4_14_TEXT "Szobatermosztát FK3"
#define ENUM5950_4_15_TEXT "HMV áramláskapcsoló"
#define ENUM5950_4_16_TEXT "HMV termosztár"
#define ENUM5950_4_17_TEXT "Zirkulationspumpenthermostat"
#define ENUM5950_4_18_TEXT "Impulzus számlálás"
#define ENUM5950_4_1e_TEXT "Kessel-Rückflussthermostat"
#define ENUM5950_4_1f_TEXT "Kazán áramláskapcsoló"
#define ENUM5950_4_20_TEXT "Kazán nyomáskapcsoló"
#define ENUM5950_4_32_TEXT "Durchflussmessung Hz"
#define ENUM5950_4_33_TEXT "Hőfogyasztás igény VK1 10V"
#define ENUM5950_4_34_TEXT "Hőfogyasztás igény VK2 10V"
#define ENUM5950_4_38_TEXT "Szobahőmérséklet 10V"
#define ENUM5950_5_01_TEXT "BA-Umschaltung HK+TWW"
#define ENUM5950_5_0f_TEXT "Kälteanforderung 10V"
#define ENUM5950_5_11_TEXT "Relative Raumfeuchte 10V"
#define ENUM5950_6_00_TEXT "BA-Umschaltung HK+TWW"
#define ENUM5950_6_01_TEXT "BA-Umschaltung alle HK"
#define ENUM5950_6_02_TEXT "Minimal-Vorlauftemperatur-Sollwert (TVHw)"
#define ENUM5950_6_03_TEXT "Wärmeerzeuger-Sperre"
#define ENUM5950_6_04_TEXT "Wärmeanforderung 0-10V"
#define ENUM5950_7_00_TEXT "Default"

#define ENUM6020_01_TEXT "Multifunkcionális"
#define ENUM6020_04_TEXT "Szolár HMV"

#define ENUM8000_65_TEXT "Fagyvédelmi fűtési mód"
#define ENUM8000_68_TEXT "Szünetel, HMV készítés miatt"
#define ENUM8000_72_TEXT "Komfort fűtési mód"
#define ENUM8000_74_TEXT "Csökkentett fűtési mód"
#define ENUM8000_78_TEXT "Süllyedés csökkentett üzemmódra"
#define ENUM8000_79_TEXT "Süllyedés fagyvédelmi üzemmódra"
#define ENUM8000_04_TEXT "Kézi vezérlés aktív"
#define ENUM8000_11_TEXT "Utánfutás aktív"
#define ENUM8003_c7_TEXT "Vételezés"
#define ENUM8005_a6_TEXT "Üzemben, fűtés"
#define ENUM8005_a7_TEXT "Üzemben, részleges terhelés fűtéshez"
#define ENUM8005_a8_TEXT "Üzemben, átfolyós HMV készítés"
#define ENUM8005_a9_TEXT "Üzemben, részleges terhelés HMV készítéshez"
#define ENUM8005_af_TEXT "Fűtéshez jóváhagyva"
#define ENUM8009_2_D7_TEXT "Indítás közben"
#define ENUM8009_2_DB_TEXT "Utószellőztetés"
#define ENUM9610_00_TEXT "70 kWh alatt"

#define MENU_TEXT_HFK "Fűtési funkciók"
#define MENU_TEXT_SNS "Szenzorok"
#define MENU_TEXT_SN1 "DS18B20 szenzor"
#define MENU_TEXT_SN2 "DHT22 szenzor"
#define MENU_TEXT_CHK "Új paraméterek ellenőrzése"
#define MENU_TEXT_DLG "Naplófájl megjelenítése"
#define MENU_TEXT_SLG "Grafikon"
#define MENU_TEXT_CFG "Beállítások"
#define MENU_TEXT_URL "URL Commands"
#define MENU_TEXT_HWT "HowTo"
#define MENU_TEXT_FAQ "FAQ"
#define ENUM_WEEKDAY_01_TEXT "Hétfő"
#define ENUM_WEEKDAY_02_TEXT "Kedd"
#define ENUM_WEEKDAY_03_TEXT "Szerda"
#define ENUM_WEEKDAY_04_TEXT "Csütörtök"
#define ENUM_WEEKDAY_05_TEXT "Pétek"
#define ENUM_WEEKDAY_06_TEXT "Szombat"
#define ENUM_WEEKDAY_07_TEXT "Vasárnap"