#define LANGUAGENAME_TEXT "Nederlands"
#define ENUM_CAT_00_TEXT "Kloktijd"
#define ENUM_CAT_01_TEXT "bedieningseenheid"
#define ENUM_CAT_02_TEXT "Draadloos"
#define ENUM_CAT_03_TEXT "Klokprogramma 1"
#define ENUM_CAT_04_TEXT "Klokprogramma 2"
#define ENUM_CAT_05_TEXT "Klokprogramma 3"
#define ENUM_CAT_06_TEXT "Klokprogramma 4/tapwater"
#define ENUM_CAT_07_TEXT "Klokprogramma 5"
#define ENUM_CAT_08_TEXT "Vakantieprogramma GR1"
#define ENUM_CAT_09_TEXT "Vakantieprogramma GR2"
#define ENUM_CAT_0a_TEXT "Vakantieprogramma GR3"
#define ENUM_CAT_0b_TEXT "Verwarmingsgroep 1"
#define ENUM_CAT_0c_TEXT "Koelingsgroep 1"
#define ENUM_CAT_0d_TEXT "Verwarmingsgroep 2"
#define ENUM_CAT_0e_TEXT "Koelingsgroep 2"
#define ENUM_CAT_0f_TEXT "Verwarmingsgroep 3/P"
#define ENUM_CAT_10_TEXT "Tapwater"
#define ENUM_CAT_14_TEXT "Hx pomp"
#define ENUM_CAT_15_TEXT "Zwembad"
#define ENUM_CAT_16_TEXT "Voorregelaar/Systeempomp"
#define ENUM_CAT_17_TEXT "Voorregelaar/Systeempomp 2"
#define ENUM_CAT_18_TEXT "Ketel"
#define ENUM_CAT_1a_TEXT "Warmtepomp"
#define ENUM_CAT_1b_TEXT "Energie teller"
#define ENUM_CAT_1c_TEXT "Kaskade"
#define ENUM_CAT_1d_TEXT "Extra warmtebron"
#define ENUM_CAT_1e_TEXT "Zonnepaneel"
#define ENUM_CAT_20_TEXT "Buffervat"
#define ENUM_CAT_21_TEXT "Tapwater-voorraad"
#define ENUM_CAT_22_TEXT "Tapwater direct laden"
#define ENUM_CAT_24_TEXT "Configuratie"
#define ENUM_CAT_25_TEXT "LPB"
#define ENUM_CAT_26_TEXT "Fout"
#define ENUM_CAT_27_TEXT "Onderhoud/Uitzonderingsbedrijf"
#define ENUM_CAT_2a_TEXT "Status"
#define ENUM_CAT_2c_TEXT "Diagnose opwekker"
#define ENUM_CAT_2d_TEXT "Diagnose verbruiker"
#define ENUM_CAT_2e_TEXT "Branderautomaat"
#define ENUM_CAT_30_TEXT "PPS bus"
#define ENUM_CAT_32_TEXT "Onbenkende categorie"

#define MENU_TEXT_HFK "Verwarmingsfuncties"
#define MENU_TEXT_SN1 "DS18B20 Sensor"
#define MENU_TEXT_SN2 "DHT22 Sensor"
#define MENU_TEXT_DLG "Uitvoer logbestand"
#define MENU_TEXT_SLG "Wegschrijven logbestand"
#define MENU_TEXT_CFG "Instellingen"
#define MENU_TEXT_URL "URL commando's"
#define MENU_TEXT_HWT "HowTo"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Ja"
#define MENU_TEXT_NO "Nee"
#define MENU_TEXT_ON "Aan"
#define MENU_TEXT_OFF "Uit"
#define MENU_DESC_HFK "Hiermee kunt u de functies van uw verwarmingssysteem opvragen of regelen. De individuele parameters zijn onderverdeeld in overeenkomstige categorieën, waarop u kunt klikken."
#define MENU_DESC_CFG "Hier ziet u de waarden waarmee BSB-LAN is geconfigureerd. Het wijzigen van deze parameters is mogelijk via de uitgebreide URL-opdrachten."
#define MENU_DESC_URL "Toont een overzicht van de opdrachten die u kunt verzenden via de directe invoer in de adresbalk van de browser. Deze opdrachten zijn ook nodig voor de verbinding met domotica-systemen zoals FHEM."
#define MENU_TEXT_VB1 "Logmodus geactiveerd!"
#define MENU_TEXT_VB2 "Logmodus gedeactiveerd!"
#define MENU_TEXT_VB3 "De logmodus heeft invloed op zowel de seriële console van de Arduino Mega2560 als (optioneel) het loggen van de busgegevens op de microSD-kaart, zodat de kaart wordt snel vol wordt! De HTML-uitvoer blijft ongewijzigd."
#define MENU_TEXT_SR1 "Seriële monitor geactiveerd!"
#define MENU_TEXT_SR2 "Seriële monitor gedeactiveerd!"
#define MENU_TEXT_SR3 "Alleen de seriële uitvoer wordt beïnvloed."
#define MENU_TEXT_ER1 "FOUT: Ongeldige parameter!"
#define MENU_TEXT_ER2 "FOUT: Ongeldige waarde!"
#define MENU_TEXT_ER3 "FOUT: Mislukt om in te stellen!"
#define MENU_TEXT_ER4 "Parameter is alleen lezen."
#define MENU_TEXT_ER5 "FOUT: Verkeerde type!"
#define MENU_TEXT_ER6 "FOUT: Regel niet gevonden!"
#define MENU_TEXT_ER7 "FOUT: Beschermde GPIO-pin!"
#define MENU_TEXT_BST "Branderstatistieken"
#define MENU_TEXT_BRS "Ketel- en Warmwater-looptijd ingesteld op nul"
#define MENU_TEXT_24A "24 uur gemiddelde waarden"
#define MENU_TEXT_24N "Nieuwe gemiddelde parameters"
#define MENU_TEXT_DTR ": bestand verwijderd en geregenereerd."
#define MENU_TEXT_DTD "Gegevens downloaden"
#define MENU_TEXT_DTF "Fout bij het maken van datalog.txt bestand!"
#define MENU_TEXT_DTO "Fout bij openen van datalog.txt bestand!"
#define MENU_TEXT_RAM "Vrij geheugen"
#define MENU_TEXT_BUS "Bus-System"
#define MENU_TEXT_BRW "Lezen/Schrijven"
#define MENU_TEXT_BRO "Alleen lezen"
#define MENU_TEXT_OWP "1-Wire Bus Pins"
#define MENU_TEXT_DHP "DHT22 Bus Pins"
#define MENU_TEXT_EXP "Geblokkeerde GPIO Pins"
#define MENU_TEXT_MAC "MAC-Adresse"
#define MENU_TEXT_LGP "Log alle komende parameters"
#define MENU_TEXT_SEC "Seconden"
#define MENU_TEXT_BZ1 "Branderlooptijd fase 1"
#define MENU_TEXT_BT1 "Brander cycli fase 1"
#define MENU_TEXT_BZ2 "Branderlooptijd fase 2"
#define MENU_TEXT_BT2 "Brander cycli fase 2"
#define MENU_TEXT_TZ1 "Warmwater runtime"
#define MENU_TEXT_TT1 "SWW-cycli"
#define MENU_TEXT_MXI "MAX!-werkelijke temperatuur"
#define MENU_TEXT_MXS "MAX!-doeltemperatuur"
#define MENU_TEXT_MXV "MAX!-klepopening"
#define MENU_TEXT_MXN "Geen MAX!-Gegevens ontvangen."
#define MENU_TEXT_BDT "BOD-gegevenstelegrammen (onafhankelijk van het interval)"
#define MENU_TEXT_BUT "Log alleen onbekende Bus-Telegrammen"
#define MENU_TEXT_MMD "Monitor Modus"
#define MENU_TEXT_VBL "Log level"
#define MENU_TEXT_AVT "Berekening van 24-uursgemiddelden voor de volgende parameters:"
#define MENU_TEXT_LBO "Alleen broadcast Bus-Telegrammen loggen"
#define MENU_TEXT_LGI "Nieuw registratie-interval"
#define MENU_TEXT_LGN "Nieuwe loggingparameters"
#define MENU_TEXT_QSC "Scannen naar apparaten"
#define MENU_TEXT_QFD "Apparaatadres gevonden"
#define MENU_TEXT_QFA "Apparaatquery mislukt"
#define MENU_TEXT_QRT "Test apparaat adres"
#define MENU_TEXT_QST "Start test"
#define MENU_TEXT_QTE "De test is voltooid"

#define STR0_TEXT "Datum/Tijd"
#define STR1_TEXT "Uren/Minuten"
#define STR2_TEXT "Dag/Maand"
#define STR3_TEXT "Jaar"
#define STR5_TEXT "Begin zomertijd dag/Maand"
#define STR6_TEXT "Einde zomertijd dag/Maand"
#define STR20_TEXT "Taal"
#define STR21_TEXT "Geef speciale bediening weer"
#define STR22_TEXT "Info"
#define STR23_TEXT "Foutmelding"
#define STR25_TEXT "Contrast van het display"
#define STR26_TEXT "Werking vergrendelen"
#define STR27_TEXT "Programmering vergrendelen"
#define STR28_TEXT "Besturingseenheid directe aanpassing"
#define STR29_TEXT "Units"
#define STR30_TEXT "Bedieningseenheid Basisinstelling opslaan"
#define STR31_TEXT "Bedieningseenheid activeert basisinstelling"
#define STR40_TEXT "Gebruik als"
#define STR42_TEXT "Toewijzing van ruimte unit 1"
#define STR42_2_TEXT "Werking van RG op de verwarmingscircuits"
#define STR44_TEXT "Bediening HK 2"
#define STR46_TEXT "Bediening HK P"
#define STR48_TEXT "Effect aanwezigheidsknop"
#define STR54_TEXT "Correctieruimte sensor"
#define STR70_TEXT "Apparaatversie bedieningspaneel"
#define STR120_TEXT "Bindend"
#define STR121_TEXT "Testmodus"
#define STR130_TEXT "Ruimte unit 1-status"
#define STR131_TEXT "Ruimte unit 2-status"
#define STR132_TEXT "Ruimte unit P-status"
#define STR133_TEXT "P-status van buitensensor"
#define STR134_TEXT "Repeater P-status"
#define STR135_TEXT "Status van besturingseenheid 1"
#define STR136_TEXT "Status van besturingseenheid 2"
#define STR137_TEXT "Status van besturingseenheid P"
#define STR138_TEXT "Service Apperaat Status"
#define STR140_TEXT "Verwijder alle apparaten"
#define STR500_TEXT "Ma"
#define STR501_TEXT "Di"
#define STR502_TEXT "Wo"
#define STR503_TEXT "Do"
#define STR504_TEXT "Vr"
#define STR505_TEXT "Za"
#define STR506_TEXT "Zo"
#define STR516_TEXT "Standaardwaarden Klokpr Groep 1"
#define STR536_TEXT "Standaardwaarden Klokpr Groep 2"
#define STR556_TEXT "Standaardwaarden Klokpr 3"
#define STR576_TEXT "Standaardwaarden Klokpr 4"
#define STR648_TEXT "Bedrijfswijze vakantie Groep 1"
#define STR652_TEXT "Vakantieperiode 1 Groep 2: Eerste dag"
#define STR653_TEXT "Vakantieperiode 1 Groep 2: Laatste dag"
#define STR658_TEXT "Bedrijfswijze vakantie Groep 2"
#define STR700_TEXT "Bedrijfswijze Groep 1"
#define STR701_TEXT "Bezettingsknop (tijdelijke afwezigheid)"
#define STR710_TEXT "Ruimtemperatuur gewenste waarde Groep 1"
#define STR711_TEXT "Maximum gewenstewaarde"
#define STR712_TEXT "Ruimtetemp. gew.waarde nacht Groep 1"
#define STR714_TEXT "Ruimtetemp. gew.waarde vorst Groep 1"
#define STR720_TEXT "Stooklijn 1 steilheid"
#define STR721_TEXT "Stooklijn-parallelverschuiving"
#define STR726_TEXT "Stooklijn-adaptie Groep 1"
#define STR730_TEXT "Zomer/winter omschakeltemp. Groep 1"
#define STR732_TEXT "Dagstookgrens Groep 1"
#define STR740_TEXT "Aanvoertemp-min-begrenzing Groep 1"
#define STR741_TEXT "Aanvoertemp-max-begrenzing Groep 1"
#define STR750_TEXT "Ruimtetemperatuur invloedfactor Groep 1"
#define STR760_TEXT "Ruimtetemperatuurbegrenzing Groep 1"
#define STR770_TEXT "Ruimtetemp-verhoging Gr 1 (Snelaanw)"
#define STR780_TEXT "Snelafkoeling Groep 1"
#define STR790_TEXT "Optimalisering max. vervroeging Groep 1"
#define STR791_TEXT "Uitsch.optim. max. vervroeging Groep 1"
#define STR800_TEXT "Begin gered.ruimtemp.verhoging Gr 1"
#define STR801_TEXT "Einde gered.ruimtemp.verhoging Gr 1"
#define STR850_TEXT "Vloer-uitdrogingsbescherming"
#define STR851_TEXT "Estrik setpoint hand Groep 1"
#define STR884_TEXT "Toerental ketelpomp bij ontwerpconditie"
#define STR885_TEXT "Mod Pomp PBM min"
#define STR886_TEXT "Buitentemperatuur bij maximale warmtevraag"
#define STR887_TEXT "Gew. keteltemp bij Normbuitentemp"
#define STR888_TEXT "Grens voor temperatuurverhoging dT-regeling"
#define STR894_TEXT "Delta Aanv/Retour bij Norm-buitentemp"
#define STR1000_TEXT "Bedrijfswijze Groep 2"
#define STR1010_TEXT "Ruimtemperatuur Comfortsetpoint Groep 2"
#define STR1012_TEXT "Ruimtetemp. gew.waarde nacht Groep 2"
#define STR1014_TEXT "Ruimtetemp. gew.waarde vorst Groep 2"
#define STR1020_TEXT "Stooklijn 2 steilheid"
#define STR1021_TEXT "Stooklijn-parallelverschuiving"
#define STR1026_TEXT "Stooklijn-adaptie Groep 2"
#define STR1030_TEXT "Zomer/winter omschakeltemp. Groep 2"
#define STR1032_TEXT "Dagstookgrens Groep 2"
#define STR1040_TEXT "Aanvoertemp-min-begrenzing Groep 2"
#define STR1041_TEXT "Aanvoertemp-max-begrenzing Groep 2"
#define STR1050_TEXT "Ruimtetemperatuur invloedfactor Groep 2"
#define STR1060_TEXT "Ruimtetemperatuurbegrenzing Groep 2"
#define STR1070_TEXT "Ruimtetemp-verhoging Gr 2 (Snelaanw)"
#define STR1080_TEXT "Snelafkoeling Groep 2"
#define STR1090_TEXT "Optimalisering max. vervroeging Groep 2"
#define STR1091_TEXT "Uitsch.optim. max. vervroeging Groep 2"
#define STR1100_TEXT "Begin gered.ruimtemp.verhoging Gr 2"
#define STR1101_TEXT "Einde gered.ruimtemp.verhoging Gr 2"
#define STR1130_TEXT "Temperatuur-verhoging Verwarmingsgroep"
#define STR1134_TEXT "Servomotor-looptijd Verwarmingsgroep"
#define STR1150_TEXT "Vloer-uitdrogingsbescherming"
#define STR1151_TEXT "Estrik setpoint Hand Groep 2"
#define STR1600_TEXT "Tapwater-Bedrijfswijze"
#define STR1610_TEXT "Tapwatertemperatuur-Normaal setpoint"
#define STR1612_TEXT "Tapwatertemperatuur-Gereduceerd setpoint"
#define STR1620_TEXT "Tapwatervrijgave"
#define STR1640_TEXT "Legionellafunctie"
#define STR1641_TEXT "Periode Legionellafunctie"
#define STR1642_TEXT "Legionellafunctie dag"
#define STR1644_TEXT "Starttijd Legionellafunctie"
#define STR1645_TEXT "Legionellafunctie gew.waarde"
#define STR1646_TEXT "Duur van Legionella temperatuur"
#define STR1647_TEXT "Tapwaterpompbedrijf tijdens Legionellafunctie"
#define STR1660_TEXT "Tapwater Tapwaterpomp Vrijgave"
#define STR1661_TEXT "Tapwaterpomp taktbedrijf"
#define STR2201_TEXT "Opwekkerblokkering"
#define STR2210_TEXT "Keteltemperatuur-minimaalbegrenzing"
#define STR2212_TEXT "Keteltemperatuur-maximaalbegrenzing"
#define STR2440_TEXT "Max. modulatiegraad in verwarmingsbedrijf"
#define STR2441_TEXT "Max. ventilatortoeren verwarmen"
#define STR2442_TEXT "Vermogen tijdens actieve regelaarvertraging"
#define STR2443_TEXT "Vermogen bij regelaarvrijgave in DLH bedrijf"
#define STR2451_TEXT "Min branderpauzetijd"
#define STR2452_TEXT "Max. Regeldiff. binnen pauzetijd"
#define STR2453_TEXT "Regelaarvertraging na inschakeling"
#define STR2454_TEXT "Ketel-schakeldifferentie"
#define STR2455_TEXT "Min. uitschakeldifferentie ketel"
#define STR2456_TEXT "Max. uitschakeldifferentie ketel"
#define STR2471_TEXT "Pompnadraaitijd"
#define STR2472_TEXT "Pompnadraaitemperatuur Tapwater"
#define STR2521_TEXT "Inschakeltemp ketelvorstbewaking"
#define STR2522_TEXT "Uitschakeltemp ketelvorstbewaking"

#define STR2700_TEXT "Resultaat laatste drifttest"  //drifttest?
#define STR2700_2_TEXT "Ion'strom gefilterd"
#define STR2702_TEXT "Start nieuwe drifttest"
#define STR2702_2_TEXT "Positie stappenmotor"
#define STR2703_TEXT "Reset Drifttest"
#define STR2703_2_TEXT "Leerwaarde gaskwaliteit"
#define STR2704_TEXT "Ondergrens afwijking testfout"
#define STR2705_TEXT "Bovengrens afwijking testfout"
#define STR2705_2_TEXT "R-waarde"
#define STR2706_TEXT "operationele fase"
#define STR2720_TEXT "Activeer het gastype"
#define STR2721_TEXT "Type gas"
#define STR2727_TEXT "Ontstekings- en bewakingsbereik"
#define STR2730_TEXT "Ionisatie"
#define STR2741_TEXT "ADA-punt"
#define STR2742_TEXT "ADA-filterwaarde"
#define STR2743_TEXT "ADA correctie"
#define STR2744_TEXT "ADA geschiedenis"
#define STR2745_TEXT "ADA resultaat"
#define STR2750_TEXT "In afwachting van drifttests"
#define STR2751_TEXT "ADA Tijdsinterval 1"
#define STR2752_TEXT "ADA Tijdsinterval 2"
#define STR2753_TEXT "ADA Tijdsinterval 3"
#define STR2776_TEXT "Pompsnelheid min. voor tapwater"
#define STR2777_TEXT "Pompsnelheid max. voor tapwater"
#define STR2778_TEXT "Pompsnelheid min. bij koelmodus"
#define STR2779_TEXT "Pompsnelheid max. bij koelmodus"
#define STR2785_TEXT "Max. condensatietemperatuur"
#define STR2786_TEXT "Max. condensatietemperatuur SD"  //SD?
#define STR2787_TEXT "Max. condensatietemperatuur reductie"
#define STR2789_TEXT "Condensorpomp bij tapwater"
#define STR2790_TEXT "Modulatie condensatiepomp"
#define STR2799_TEXT "Nominale pompvermindering"
#define STR2800_TEXT "Vorstbescherming condensatiepomp"
#define STR2801_TEXT "Aansturing condensatiepomp"
#define STR2802_TEXT "Doorlooptijd condensatiepomp"
#define STR2803_TEXT "Nalooptijd condensatiepomp"
#define STR2804_TEXT "Max. temperatuurspreidingcondensatie"
#define STR2805_TEXT "Gewenste temperatuurspreidingscondensatie"
#define STR2806_TEXT "Max. afwijking spreiding condensatie"
#define STR2807_TEXT "Min. afwijking spreiding condensatie" //not sure?
#define STR2809_TEXT "Temperatuur Vorst alarm"
#define STR2810_TEXT "Condensor antivries"
#define STR2811_TEXT "Naloopbescherming voor gecondenseerd condensaat"
#define STR2814_TEXT "Maximum brontemperatuur"
#define STR2815_TEXT "Brontemperatuur min. water"
#define STR2816_TEXT "Brontemperatuur min. zout" //not sure Sole
#define STR2817_TEXT "Schakelen tussen differentiële bronbeveiliging"
#define STR2818_TEXT "Verhoog bronbeschermingstemp. min hoogte"
#define STR2819_TEXT "Doorlooptijdbron"
#define STR2820_TEXT "Nalooptijdbron"
#define STR2821_TEXT "Maximale opstarttijd van de bron"
#define STR2822_TEXT "Tijdlimiet bron temp. min. zout"

#define STR2825_TEXT "Min. Verdampingstemperatuur"
#define STR2826_TEXT "Max. Verdampingstemperatuur"

#define STR2870_TEXT "Compressormodulatie Max."
#define STR2871_TEXT "Compressormodulatie Min."


#define STR3810_TEXT "Temperatuurverschil zonnepaneel IN"
#define STR3811_TEXT "Temperatuurverschil zonnepaneel UIT"
#define STR3812_TEXT "Minimale laadtemperatuur"
#define STR3831_TEXT "Min looptijd collectorpomp"
#define STR3840_TEXT "Collectorvorstbev temperatuur"
#define STR3850_TEXT "Collector oververh.bev.temperatuur"
#define STR3860_TEXT "Verdampingstemperatuur warmtedrager"
#define STR4721_TEXT "Automatische opwekkerblokk Schakeldifferentie"
#define STR4722_TEXT "Temp.verschil buffer/gr tot vrijg opwekking"
#define STR5019_TEXT "Setpointverhoging voor nalading voorraadvat"
#define STR5020_TEXT "Aanvoertemperatuurverhoging tapwater"
#define STR5050_TEXT "Maximale tapwater laadtemperatuur"
#define STR5055_TEXT "Min terugkoeltemp voor tapw-vat"
#define STR5100_TEXT "Min. Pomptoeren voor doorlading buffer"
#define STR5020_TEXT "Aanvoertemperatuurverhoging tapwater"
#define STR5400_TEXT "Setpoint voor tapwater gereed temperatuur"
#define STR5430_TEXT "Inschakeldiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5431_TEXT "Min.Uitschdiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5432_TEXT "Max.Uitschdiff. in WTB-Bedrijf (Opnemer 1)"
#define STR5433_TEXT "Inschakeldiff. in WTB-Bedrijf (Opnemer 2)"
#define STR5434_TEXT "Min uitschakeldiff in WTB-bedrijf (Opnemer 2)"
#define STR5435_TEXT "Max.Uitschdiff. in WTB-Bedrijf (Opnemer 2)"
#define STR5450_TEXT "Grens voor beëindigen watertappen bij DLH"
#define STR5451_TEXT "Grens voor watertappen bij DLH in Comfort"
#define STR5452_TEXT "Grens voor watertappen bij DLH in VerwBedrijf"
#define STR5453_TEXT "Setpointcorrectie bij comfortregeling met 40°C"
#define STR5454_TEXT "Setpointcorrectie bij comfortregeling met 60°C"
#define STR5455_TEXT "Setpointcorrectie bij uitloopregeling met 40°C"
#define STR5456_TEXT "Setpointcorrectie bij uitloopregeling met 60°C"
#define STR5480_TEXT "DLH-Comforttijd na tappen zonder warmtevraag"
#define STR5481_TEXT "DLH-Comforttijd na tappen met warmtevraag"
#define STR5482_TEXT "Tijd tot tapw-strom.schak gesloten"
#define STR5483_TEXT "Tijd tot tapw-comfort strom.schak gesloten"
#define STR5486_TEXT "Regelvertraging bij aan/uit uitloopbedrijf"
#define STR5487_TEXT "Pompnadraai in DLH-Comfort bij brander uit"
#define STR5488_TEXT "Pompnadraai in DLH-Comfort bij brander uit"
#define STR5701_TEXT "Installatietype"
#define STR5710_TEXT "Verwarmingsgroep 1"
#define STR5715_TEXT "Verwarmingsgroep 2"
#define STR5732_TEXT "Pompuitschakeltijd bij wissel verw naar WTB"
#define STR5733_TEXT "Vertraging pompuitsch bij wissel verw->WTB"
#define STR5761_TEXT "Warmtevraag met ondersteuning door Q8"
#define STR5920_TEXT "Programmeerbare uitgang K2"
#define STR5921_TEXT "Default K2 op K1"
#define STR5922_TEXT "Funktie uitgang 1 Relais Clip-In"
#define STR5923_TEXT "Funktie uitgang 2 Relais Clip-In"
#define STR5924_TEXT "Funktie uitgang 3 Relais Clip-In"
#define STR5926_TEXT "Configuratie Uitgang 1"
#define STR5927_TEXT "Configuratie Uitgang 2"
#define STR5928_TEXT "Configuratie Uitgang 3"
#define STR5950_TEXT "Ingang H1 functiekeuze"
#define STR5957_TEXT "Modemfunctie"
#define STR5970_TEXT "Config Ruimtethermostaat 1"
#define STR5971_TEXT "Config Ruimtethermostaat 2"
#define STR5973_TEXT "Functie Ingang RelCl"
#define STR5975_TEXT "Temperatuurgrens voor externe warmtevraag"
#define STR5976_TEXT "Ingangssignaal ondergrens ext warmtevraag"
#define STR6110_TEXT "Gebouwtijdconstante"
#define STR6112_TEXT "Ruimtemodel gradient"
#define STR6120_TEXT "Installatievorstbeveiliging"
#define STR6127_TEXT "Tijd voor pomp/klepkick"
#define STR6220_TEXT "Regelaar-SW-Versie"
#define STR6225_TEXT "Regelaar-Familie"
#define STR6226_TEXT "Regelaar-Variant"
#define STR6227_TEXT "Regelaar-OV-Versie"
#define STR6230_TEXT "Regelaarconfiguratie 0"
#define STR6240_TEXT "Regelaarconfiguratie 1"
#define STR6250_TEXT "Regelaarconfiguratie 2"
#define STR6260_TEXT "Regelaarconfiguratie 3"
#define STR6270_TEXT "Regelaarconfiguratie 4"
#define STR6300_TEXT "Regelaarconfiguratie 7"
#define STR6330_TEXT "Regelaarconfiguratie 10"
#define STR6604_TEXT "LPB-voeding Functiekeuze"
#define STR6605_TEXT "LPB-voeding Status"
#define STR6625_TEXT "Tapwatertoewijzing"
#define STR6640_TEXT "Kloktijd-leverancier"
#define STR6705_TEXT "Interne diagnosecode"
#define STR6706_TEXT "Actuele waarde Storingsfase"
#define STR6741_TEXT "Tijd aanvoertemperatuuralarm Groep 2"
#define STR6823_TEXT "3e Oude waarde Albatros Foutcode"
#define STR6825_TEXT "Oude waarde 3 Storingsdiagnose"
#define STR6826_TEXT "Oude waarde 3 Storingsfase"
#define STR6830_TEXT "Oude waarde 4 Storingcode-teller"
#define STR6833_TEXT "4e Oude waarde Albatros Foutcode"
#define STR6835_TEXT "Oude waarde 4 Storingsdiagnose"
#define STR6836_TEXT "Oude waarde 4 Storingsfase"
#define STR6840_TEXT "Oude waarde 5 Storingcode-teller"
#define STR6843_TEXT "5e Oude waarde Albatros Foutcode"
#define STR6845_TEXT "Oude waarde 5 Storingsdiagnose"
#define STR6846_TEXT "Oude waarde 5 Storingsfase"
#define STR7001_TEXT "Onderhoudsmelding"
#define STR7007_TEXT "Configuratie / Reset onderhoudsmeldingen"
#define STR7010_TEXT "Onderhoudsmelding - Bevestiging"
#define STR7011_TEXT "Herhalingstijd voor onderhoudsmeldingen"
#define STR7040_TEXT "Brander onderhoudsinterval"
#define STR7041_TEXT "Bedrijfsuren sinds laatste onderhoud"
#define STR7042_TEXT "Grens voor controle sinds laatste onderhoud"
#define STR7043_TEXT "Controles sinds laatste onderhoud"
#define STR7044_TEXT "Grens voor maanden sinds laatste onderhoud"
#define STR7045_TEXT "Maanden sinds laatste onderhoud"
#define STR7050_TEXT "Ventilatortoerental voor onderhoudsmelding"
#define STR7051_TEXT "Ionisatiestroom- Onderhoudsmelding"

#define STR7750_TEXT "Tapwater Temperatuur"

#define STR8000_TEXT "Status Verw.groep 1"
#define STR8001_TEXT "Status Verw.groep 2"
#define STR8003_TEXT "Status Tapwater"
#define STR8005_TEXT "Status Ketel"
#define STR8006_TEXT "Status Warmptepomp"
#define STR8007_TEXT "Status Zonne-energie"
#define STR8310_TEXT "Keteltemperatuur-meetwaarde"
#define STR8311_TEXT "Keteltemperatuur-gew.waarde"
#define STR8314_TEXT "Retourtemperatuur-meetwaarde"
#define STR8316_TEXT "Rookgastemperatuur-meetwaarde"
#define STR8324_TEXT "Actueel ventilatortoerental"
#define STR8325_TEXT "Actuele ventilatorbesturing"
#define STR8326_TEXT "Relatief vermogen"
#define STR8328_TEXT "Bedrijfsweergave FA"
#define STR2730_TEXT "Ionisatiestroom"
#define STR8336_TEXT "Regelaarbedrijfsuren"
#define STR8337_TEXT "Startteller brander"
#define STR8338_TEXT "Bedrijfsuren verwarmingsbedrijf"
#define STR8339_TEXT "Bedrijfsuren tapwaterbedrijf"
#define STR8340_TEXT "Bedrijfsuren ext. Warmtevraag"

#define STR8400_TEXT "Compressor 1 K1"
#define STR8401_TEXT "Compressor 2 K2"


#define STR8410_TEXT "Retourtemperatuur WP"
#define STR8411_TEXT "Gewenste waarde WP"
#define STR8412_TEXT "Aanvoertemperatuur WP"
#define STR8413_TEXT "Modulatie van de compressor"
#define STR8414_TEXT "Modulatie van elektrische stroming"

#define STR8423_TEXT "Condensortemperatuur"

#define STR8446_TEXT "compressor resultaat"

#define STR8449_TEXT "Bedrijfsuren koelcircuit"
#define STR8450_TEXT "Bedrijfsuren compressor 1"
#define STR8451_TEXT "Teller van opstarten compressor 1"
#define STR8452_TEXT "Bedrijfsuren compressor 2"
#define STR8453_TEXT "Teller van opstarten compressor 2"
#define STR8454_TEXT "Blokduur WP"

#define STR8458_TEXT "Status Smart Grid"
#define STR8460_TEXT "Warmtepomp stroming"


#define STR8510_TEXT "Collectortemperatuur 1 (B6)"
#define STR8530_TEXT "Bedrijfsuren zonopbrengst"
#define STR8700_TEXT "Lokale buitentemperatuur"
#define STR8701_TEXT "Buitentemperatuur Minimum"
#define STR8702_TEXT "Buitentemperatuur Maximum"
#define STR8703_TEXT "Gedempte buitentemperatuur"
#define STR8704_TEXT "Gemengde buitentemperatuur"
#define STR8740_TEXT "Ruimtetemperatuur 1"
#define STR8741_TEXT "Ruimtetemp. 1 gewenste waarde"
#define STR8742_TEXT "Ruimtetemp. 1 Model"
#define STR8743_TEXT "Aanvoertemperatuur meetwaarde Groep 1"
#define STR8744_TEXT "Gewenste waarde aanvoertemperatuur 1"
#define STR8750_TEXT "Pomptoerental"
#define STR8770_TEXT "Ruimtetemperatuur 2 meetwaarde"
#define STR8771_TEXT "Ruimtemp gew.waarde actueel Groep 2"
#define STR8773_TEXT "Aanvoertemperatuur meetwaarde Groep 2"
#define STR8774_TEXT "Aanvoersetpoint H2"
#define STR8830_TEXT "Tapwatertemperatuur 1"
#define STR8831_TEXT "Tapwatertemperatuur-gew.waarde aktueel"
#define STR8836_TEXT "Tapwater Laadtemperatuur"
#define STR8950_TEXT "Proces-Sig Gezamenlijke aanvoertemperatuur"
#define STR8952_TEXT "Proces-Sig Gezamenlijke retourtemperatuur"
#define STR8980_TEXT "Buffertemperatuur Boven (B4)"
#define STR9500_TEXT "Voorspoeltijd"
#define STR9502_TEXT "Modulatie lucht in voorventilatie"
#define STR9504_TEXT "Setpoint vent.toerental in voorventilatie"
#define STR9510_TEXT "Modulatie lucht in aansteeklast"
#define STR9512_TEXT "Ventilatortoerental in aansteeklast"
#define STR9520_TEXT "Modulatie lucht in deellast"
#define STR9522_TEXT "Modulatie lucht in vollast"
#define STR9524_TEXT "Ventilatortoerental in deellast"
#define STR9527_TEXT "Ventilatortoerental in vollast"
#define STR9540_TEXT "Naspoeltijd"
#define STR9560_TEXT "Ventilatormodulatie bij bufferlading"
#define STR9563_TEXT "Setpoint ventilator bij bufferlading"

#define ENUM20_01_TEXT "English"
#define ENUM20_02_TEXT "Deutsch"
#define ENUM20_03_TEXT "Francais"
#define ENUM20_04_TEXT "Nederlands"
#define ENUM20_05_TEXT "Italiano"
#define ENUM20_06_TEXT "Espanol"
#define ENUM20_07_TEXT "Polski"
#define ENUM20_08_TEXT "Ceski"
#define ENUM22_01_TEXT "Tijdelijk"
#define ENUM22_02_TEXT "Permanent"
#define ENUM23_00_TEXT "Code"
#define ENUM23_01_TEXT "Code en tekst"
#define ENUM28_01_TEXT "Sla automatisch op"
#define ENUM28_02_TEXT "Bewaar met bevestiging"
#define ENUM29_01_TEXT "°C,bar"
#define ENUM29_02_TEXT "°F,PSI"
#define ENUM40_00_TEXT "Ruimte 1"
#define ENUM40_01_TEXT "Ruimte 2"
#define ENUM40_02_TEXT "Ruimte P"
#define ENUM40_03_TEXT "bedienningsapparaat 1"
#define ENUM40_04_TEXT "bedienningsapparaat 2"
#define ENUM40_05_TEXT "Service apparaat"
#define ENUM42_01_TEXT "Verwarmingskring 1 en 2"
#define ENUM42_02_TEXT "Verwarmingskring 1 en P"
#define ENUM42_03_TEXT "Alle Verwarmingskringen"
#define ENUM44_01_TEXT "Samen met HK1"
#define ENUM44_02_TEXT "onafhankelijk"
#define ENUM47_02_TEXT "Voor alle toegewezen verwarmingscircuits"
#define ENUM48_00_TEXT "Geen"
#define ENUM48_03_TEXT "Samen"
#define ENUM130_00_TEXT "Ontbreekt"
#define ENUM130_01_TEXT "In bedrijf"
#define ENUM130_02_TEXT "Geen ontvangst"
#define ENUM130_03_TEXT "Vervang de batterij"
#define ENUM648_00_TEXT "Vorstbeveiliging"
#define ENUM648_01_TEXT "Gereduceerd"
#define ENUM700_00_TEXT "Beschermingsmodus"
#define ENUM700_01_TEXT "Automatisch"
#define ENUM700_03_TEXT "Comfort"
#define ENUM702_00_TEXT "Zomerstand"
#define ENUM702_01_TEXT "Verwarmingsprogramma 1"
#define ENUM702_02_TEXT "Eco-programma"
#define ENUM702_03_TEXT "Normale programma"
#define ENUM702_04_TEXT "Onbekent"
#define ENUM702_05_TEXT "Verwarmingsprogramma 2"
#define ENUM702_06_TEXT "Verwarmingsprogramma 3"
#define ENUM703_00_TEXT "Aanwezig"
#define ENUM703_01_TEXT "Afwezig"
#define ENUM780_01_TEXT "Naar verlaagde waarde"
#define ENUM780_02_TEXT "Naar vorstbeveiliging waarde"
#define ENUM832_00_TEXT "2-punts"
#define ENUM832_01_TEXT "3-punts"
#define ENUM850_01_TEXT "Verwarmingseisen"  //not sure

#define ENUM850_05_TEXT "Handmatig"
#define ENUM861_01_TEXT "Verwarming"
#define ENUM861_02_TEXT "Altijd"
#define ENUM880_00_TEXT "Operationeel niveau"
#define ENUM880_01_TEXT "karakteristiek" //not sure
#define ENUM880_02_TEXT "Temperatuurslag nominaal"
#define ENUM1600_02_TEXT "Eco"
#define ENUM1602_00_02_TEXT "SWW pomp niet actief"
#define ENUM1602_02_02_TEXT "SWW pomp actief"
#define ENUM1602_00_04_TEXT "SWW uit"
#define ENUM1602_04_04_TEXT "SWW aan"
#define ENUM1602_00_08_TEXT "SWW laden niet actief"
#define ENUM1602_08_08_TEXT "SWW laden actief"
#define ENUM1620_00_TEXT "24 uur/dag"
#define ENUM1620_01_TEXT "Tijd programma verwarmingscircuits"
#define ENUM1620_02_TEXT "Tijd programma 4/SWW"
#define ENUM1630_00_TEXT "Absoluut"
#define ENUM1630_01_TEXT "Glijdend"
#define ENUM1630_02_TEXT "Geen"
#define ENUM1630_03_TEXT "MK glijdend PK absoluut"
#define ENUM1640_01_TEXT "Periodiek"
#define ENUM1640_02_TEXT "Vaste weekdag"
#define ENUM1660_02_TEXT "Tapwater vrijgave"

#define ENUM2200_00_TEXT "Continubedrijf"
#define ENUM2200_02_TEXT "Auto, verlengde termijn"
#define ENUM2205_01_TEXT "Tapwater 1"
#define ENUM2206_00_TEXT "In Bedrijf"
#define ENUM2206_01_TEXT "Standby"
#define ENUM2291_00_TEXT "Parallelle branderbediening"
#define ENUM2291_01_TEXT "Retourtemperatuur"
#define ENUM2305_00_TEXT "Alleen verwarming"
#define ENUM2305_01_TEXT "Verwarming en drinkwater"
#define ENUM2320_01_TEXT "Behoefte"

#define ENUM2706_04_TEXT "Initialisatie"
#define ENUM2706_05_TEXT "Branden"

#define ENUM5730_01_TEXT "Thermostaat"

#define ENUM5731_00_TEXT "Geen"

#define ENUM6621_00_TEXT "Lokaal"
#define ENUM6621_01_TEXT "Centraal"

#define ENUM7147_04_TEXT "Tapwater timer"

#define ENUM7425_00_TEXT "0..10V"

#define ENUM7700_01_TEXT "Alles uit"

#define ENUM7999_02_TEXT "Puls"

#define ENUM7999_03_TEXT "Frequentie Hz"
#define ENUM7999_04_TEXT "Spanning V"

#define ENUM8000_04_TEXT "Handmatige modus actief"
#define ENUM8000_11_TEXT "Naloop actief"
#define ENUM8000_16_TEXT "Vorstbeveiliging systeem actief"
#define ENUM8000_17_TEXT "Vorstbescherming actief"
#define ENUM8000_38_TEXT "Oververhitting actief"
#define ENUM8000_65_TEXT "Vorstbescherming kamer actief"
#define ENUM8000_66_TEXT "Vloerfunctie actief"  //not sure
#define ENUM8000_67_TEXT "Beperkte ketelbescherming"
#define ENUM8000_68_TEXT "Beperkte prioriteit Tapwater"
#define ENUM8000_69_TEXT "Beperkte buffer"
#define ENUM8000_6a_TEXT "Verwarming beperkt"
#define ENUM8000_6b_TEXT "Gedwongen ontladen buffer"
#define ENUM8000_6c_TEXT "Gedwongen ontladen Tapwater"
#define ENUM8000_6d_TEXT "Gedwongen ontladen produceren" //not sure
#define ENUM8000_6e_TEXT "Gedwongen ontladen"
#define ENUM8000_6f_TEXT "Inschakelen + snelle verwarming"
#define ENUM8000_70_TEXT "Opstart optimalisatie"
#define ENUM8000_71_TEXT "Snelvoorverwarming"
#define ENUM8000_72_TEXT "Comfort in de verwarmingsmodus"
#define ENUM8000_73_TEXT "Stopregeling"
#define ENUM8000_74_TEXT "Verwarmingsmodus verlaagd"
#define ENUM8000_75_TEXT "Bevriezingsbeveiliging actief"
#define ENUM8000_76_TEXT "Zomerstand"
#define ENUM8000_77_TEXT "Dag Eco actief"

#define ENUM8000_79_TEXT "Vorstbescherming verlagen"
#define ENUM8003_35_TEXT "Na koelen actief"
#define ENUM8003_42_TEXT "Elektrische wisselplaat opladen"
#define ENUM8003_43_TEXT "Geforceerd laden actief"
#define ENUM8003_45_TEXT "Laden actief"
#define ENUM8003_46_TEXT "Geladen, Maximale Opslagtemp"
#define ENUM8003_47_TEXT "Geladen, Maximale Laadtemp"
#define ENUM8003_4b_TEXT "Geladen"

#define ENUM8006_2d_TEXT "Compresoor 1 en 2 aan"
#define ENUM8006_2e_TEXT "Compressor 1 aan"
#define ENUM8006_2f_TEXT "Compressor 2 aan"
#define ENUM8006_30_TEXT "Vorstbeschermingswarmtepomp"
#define ENUM8006_31_TEXT "Verloop actief"

#define ENUM8006_33_TEXT "Geen warmtevraag"

#define ENUM8749_00_TEXT "Geen behoefte"
