#define LANGUAGENAME_TEXT "Dansk"
#define ENUM_CAT_00_TEXT "Klokkeslæt og dato"
#define ENUM_CAT_06_TEXT "Tidsprogram varmekreds 1"
#define ENUM_CAT_07_TEXT "Tidsprogram varmekreds 2"
#define ENUM_CAT_08_TEXT "Tidsprogram 3 / VKP"
#define ENUM_CAT_09_TEXT "Time switch program DHW"
#define ENUM_CAT_0c_TEXT "Tidsprogram varmekreds 5"
#define ENUM_CAT_0e_TEXT "Ferie varmekreds 1"
#define ENUM_CAT_0f_TEXT "Ferie varmekreds 2"
#define ENUM_CAT_11_TEXT "Varmekreds 1"
#define ENUM_CAT_14_TEXT "Varmekreds 2"
#define ENUM_CAT_17_TEXT "Varmekreds 3/P"
#define ENUM_CAT_1a_TEXT "Brugsvand"
#define ENUM_CAT_22_TEXT "Kedel"
#define ENUM_CAT_2b_TEXT "Solvärme"
#define ENUM_CAT_2d_TEXT "Buffertank"
#define ENUM_CAT_2e_TEXT "Brugsvandsbeholder"
#define ENUM_CAT_2f_TEXT "Brugsvand direkte opladning"
#define ENUM_CAT_31_TEXT "Konfiguration"
#define ENUM_CAT_32_TEXT "LPB-system"
#define ENUM_CAT_33_TEXT "Modbus-system"
#define ENUM_CAT_34_TEXT "Fejl"
#define ENUM_CAT_35_TEXT "Vedligehold/specialdrift"
#define ENUM_CAT_39_TEXT "Status"
#define ENUM_CAT_3c_TEXT "Diagnose varmegiver"
#define ENUM_CAT_3d_TEXT "Forbrugerdiagnose"
#define ENUM_CAT_3f_TEXT "Fyringsautomat"
#define STR516_TEXT "Standard values TSP heating circuit 1"
#define STR536_TEXT "Standard values TSP heating circuit 2 "
#define STR556_TEXT "Standard values TSP3"
#define STR576_TEXT "Standard values TSP 4"
#define STR648_TEXT "Feriedriftniveau VK1"
#define STR652_TEXT "Ferieperiode 1 VK2: Første dag"
#define STR653_TEXT "Ferieperiode 1 VK2: Sidste dag"
#define STR658_TEXT "Feriedriftniveau VK2"
#define STR700_TEXT "Driftsform varmekreds 1"
#define STR710_TEXT "Rumtemperatur komfortsetpunkt VK 1"
#define STR712_TEXT "Reduceret rumtemp.setpunkt varmekreds 1"
#define STR714_TEXT "Frostbeskyttelsessetpunkt rumtemp. varmekreds 1"
#define STR720_TEXT "Varmekurvestejlhed 1"
#define STR721_TEXT "Karakteristik forskydning"
#define STR726_TEXT "Heating curve adaptation heat circuit 1"
#define STR730_TEXT "Sommer/vinteromkobl.temp. varmekreds 1"
#define STR732_TEXT "24-hour heating limit HC1"
#define STR740_TEXT "Flow temp min limitation heat circuit 1"
#define STR741_TEXT "Flow temp max limitation heat circuit 1"
#define STR750_TEXT "Room temp gain factor heat circuit 1"
#define STR760_TEXT "Room temperature limitation heating circuit 1"
#define STR770_TEXT "Room temp setpoint boost HC1 (boost heating)"
#define STR780_TEXT "Quick setback heat circuit 1"
#define STR790_TEXT "Optimeret start maks.fremrykning VK1"
#define STR791_TEXT "Optimum stop control max forward shift HC1"
#define STR800_TEXT "Start reduced room temp setpoint increase HC1"
#define STR801_TEXT "End reduced room temp setpoint increase HC1"
#define STR850_TEXT "Gulvfunktion"
#define STR851_TEXT "Floor setpoint manually HC1"
#define STR884_TEXT "Hastighedstrin dimens.punkt"
#define STR885_TEXT "Mod pumpe PBM min."
#define STR886_TEXT "Norm udetemperatur"
#define STR887_TEXT "Fremløbssetp. norm udetemp."
#define STR888_TEXT "dT forhøjelsesfaktor"
#define STR894_TEXT "dT spredning norm udetemp."
#define STR1000_TEXT "Driftsform varmekreds 2"
#define STR1010_TEXT "Rumtemperatur komfortsetpunkt VK 2"
#define STR1012_TEXT "Reduceret rumtemp.setpunkt varmekreds 2"
#define STR1014_TEXT "Frostbeskyttelsessetpunkt rumtemp. varmekreds 2"
#define STR1020_TEXT "Varmekurvestejlhed 2"
#define STR1021_TEXT "Karakteristik forskydning"
#define STR1026_TEXT "Heating curve adaptation heat circuit 2"
#define STR1030_TEXT "Sommer/vinteromkobl.temp. varmekreds 2"
#define STR1032_TEXT "24-hour heating limit HC2"
#define STR1040_TEXT "Flow temp min limitation heat circuit 2"
#define STR1041_TEXT "Flow temp max limitation heat circuit 2"
#define STR1050_TEXT "Room temp gain factor heat circuit 2"
#define STR1060_TEXT "Room temperature limitation heating circuit 2"
#define STR1070_TEXT "Room temp setpoint boost HC2 (boost heating)"
#define STR1080_TEXT "Quick setback heat circuit 2"
#define STR1090_TEXT "Optimeret start maks.fremrykning VK2"
#define STR1091_TEXT "Optimum stop control max forward shift HC2"
#define STR1100_TEXT "Start reduced room temp setpoint increase HC2"
#define STR1101_TEXT "End reduced room temp setpoint increase HC2"
#define STR1130_TEXT "Forhøjelse via blandeventil"
#define STR1134_TEXT "Motorgangtid"
#define STR1150_TEXT "Gulvfunktion"
#define STR1151_TEXT "Floor setpoint manually HC2"
#define STR1600_TEXT "BV-driftsform"
#define STR1610_TEXT "Nominelt setpunkt"
#define STR1612_TEXT "Reduceret setpunkt"
#define STR1620_TEXT "Frigivelse"
#define STR1640_TEXT "Legionellafunktion"
#define STR1641_TEXT "Legionellafunkt. periodisk"
#define STR1642_TEXT "Legionellafunkt. ugedag"
#define STR1644_TEXT "Legionellafunkt. tidspunkt"
#define STR1645_TEXT "Legionellafunkt. setpunkt"
#define STR1646_TEXT "Legionellafunkt. varighed"
#define STR1647_TEXT "Legionellafunkt. cirk.pumpe"
#define STR1660_TEXT "Cirkulationspumpe frigivelse"
#define STR1661_TEXT "Cirk.pumpe periodisk"
#define STR2201_TEXT "Varmegiverspærring"
#define STR2210_TEXT "Setpunkt min."
#define STR2212_TEXT "Setpunkt max."
#define STR2440_TEXT "Blæser-PBM opvarm. max."
#define STR2441_TEXT "Blæserhast. opvarm. max."
#define STR2442_TEXT "Blæser-PBM regul. forsink."
#define STR2443_TEXT "Blæser-PBM startværdi DLH"
#define STR2451_TEXT "Brænderpausetid minimum"
#define STR2452_TEXT "KD brænderpause"
#define STR2453_TEXT "Regul.forsinkelse varighed"
#define STR2454_TEXT "Koblingsdifferens kedel"
#define STR2455_TEXT "Kobl.diff. kedel off min."
#define STR2456_TEXT "Kobl.diff. kedel off max."
#define STR2471_TEXT "Pumpeefterløbstid"
#define STR2472_TEXT "Pumpeefterløbstemp. BV"
#define STR2521_TEXT "Frostbeskytt. indkobl.temp."
#define STR2522_TEXT "Frostbeskyt. udkobl.temp."
#define STR3810_TEXT "Temp.diff. ON"
#define STR3811_TEXT "Temp.diff. OFF"
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Kollektorfrostbeskyttelse"
#define STR3850_TEXT "Kollektorovertemp.sikring"
#define STR3860_TEXT "Fordampning varmebærer"
#define STR4721_TEXT "Auto generatorspærring KD"
#define STR4722_TEXT "Temp.diff. buffer/varmekr."
#define STR5019_TEXT "Efterladn.forhøj. lagd.beh."
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Flowswitch-tid tapning"
#define STR5483_TEXT "Flowswitch-tid komfort"
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Hydr. diagram"
#define STR5710_TEXT "Varmekreds 1"
#define STR5715_TEXT "Varmekreds 2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Fødepumpe Q8"
#define STR5920_TEXT "Relæudgang K2 LMU-basis"
#define STR5921_TEXT "Default K2 til K1"
#define STR5922_TEXT "Relæudgang 1 RelCl"
#define STR5923_TEXT "Relæudgang 2 RelCl"
#define STR5924_TEXT "Relæudgang 3 RelCl"
#define STR5926_TEXT "Relæudgang 1 SolCl"
#define STR5927_TEXT "Relæudgang 2 SolCl"
#define STR5928_TEXT "Relæudgang 3 SolCl"
#define STR5950_TEXT "Funktion indgang H1"
#define STR5957_TEXT "Modemfunktion"
#define STR5970_TEXT "Konfig rumtermostat 1"
#define STR5971_TEXT "Konfig rumtermostat 2"
#define STR5973_TEXT "Funktion indgang RelCl"
#define STR5975_TEXT "Ekst. fremløbssetp. max."
#define STR5976_TEXT "Ekst. effektindst. tærskel"
#define STR6110_TEXT "Tidskonstant bygning"
#define STR6112_TEXT "Gradient rummodel"
#define STR6120_TEXT "Anlægsfrostbeskyttelse"
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6220_TEXT "Softwareversion"
#define STR6225_TEXT "Apparatfamilie"
#define STR6226_TEXT "Apparatvariant"
#define STR6227_TEXT "Objektbibliotekversion"
#define STR6230_TEXT "KonfigRg 0"
#define STR6240_TEXT "KonfigRg 1"
#define STR6250_TEXT "KonfigRg 2"
#define STR6260_TEXT "KonfigRg 3"
#define STR6270_TEXT "KonfigRg 4"
#define STR6300_TEXT "KonfigRg 7"
#define STR6330_TEXT "KonfigRg 10"
#define STR6604_TEXT "Busforsyning funktion"
#define STR6605_TEXT "Busforsyning tilstand"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Urdrift"
#define STR6705_TEXT "SW diagnosekode"
#define STR6706_TEXT "FA fase fejlstilling"
#define STR6741_TEXT "Fremløbstemperatur 2 alarm"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "SW diagnosekode 3"
#define STR6826_TEXT "FA fase 3"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "SW diagnosekode 4"
#define STR6836_TEXT "FA fase 4"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "SW diagnosekode 5"
#define STR6846_TEXT "FA fase 5"
#define STR7001_TEXT "Melding"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Kvittering melding"
#define STR7011_TEXT "Gentagelsestid melding"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Blæserhastighed ion-strøm"
#define STR7051_TEXT "Melding ion-strøm"
#define STR8000_TEXT "Status varmekreds 1"
#define STR8001_TEXT "Status varmekreds 2"
#define STR8003_TEXT "Status brugsvand"
#define STR8005_TEXT "Status kedel"
#define STR8007_TEXT "Status solvarme"
#define STR8310_TEXT "Kedeltemperatur"
#define STR8311_TEXT "Kedelsetpunkt"
#define STR8314_TEXT "Kedeltreturtemperatur"
#define STR8316_TEXT "Røggastemperatur"
#define STR8324_TEXT "Ventilatorhastighed"
#define STR8325_TEXT "Aktuel blæserstyring"
#define STR8326_TEXT "Relativ effekt"
#define STR8328_TEXT "Driftsvisning FA"
#define STR2730_TEXT "Ioniseringsstrøm"
#define STR8336_TEXT "Driftstimer apparat"
#define STR8337_TEXT "Starttæller brænder"
#define STR8338_TEXT "Driftstimer varmedrift"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Driftstimer zoner"
#define STR8510_TEXT "Kollektortemp. 1"
#define STR8530_TEXT "Driftstm. solvarmeudbytte"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Udetemperatur dæmpet"
#define STR8704_TEXT "Udetemperatur blandet"
#define STR8739_TEXT "Omgivende luftfugtighed 1"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Fremløbstemperatur 1"
#define STR8744_TEXT "Fremløbssetpunkt H1"
#define STR8750_TEXT "Mod pumpe setpunkt"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Rumsetpunkt 2"
#define STR8773_TEXT "Fremløbstemperatur 2"
#define STR8774_TEXT "Fremløbssetpunkt H2"
#define STR8830_TEXT "Brugsvandstemperatur 1"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "BV-ladetemperatur"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Buffertanktemperatur 1"
#define STR9500_TEXT "Forluftningstid"
#define STR9502_TEXT "Blæserstyr. forventilation"
#define STR9504_TEXT "Indstill.hastigh. forventilat."
#define STR9510_TEXT "Blæserstyring tænding"
#define STR9512_TEXT "Indstil.hastighed tænding"
#define STR9520_TEXT "Blæserstyring drift min."
#define STR9522_TEXT "Blæserstyring drift max."
#define STR9524_TEXT "Indstil.hastighed drift min."
#define STR9527_TEXT "Indstil.hastighed drift max."
#define STR9540_TEXT "Efterventilationstid"
#define STR9560_TEXT "Blæserstyring fuld opladn."
#define STR9563_TEXT "Indstil.hastigh. fuld opladn."
