#define LANGUAGENAME_TEXT "English"
#define ENUM_CAT_00_TEXT "Date/Time"
#define ENUM_CAT_01_TEXT "Room Unit"
#define ENUM_CAT_02_TEXT "Wireless"
#define ENUM_CAT_03_TEXT "Time program cooling 1"
#define ENUM_CAT_04_TEXT "Time program cooling 2"
#define ENUM_CAT_05_TEXT "Time program cooling 3"
#define ENUM_CAT_06_TEXT "Time program heating circuit 1"
#define ENUM_CAT_07_TEXT "Time program heating circuit 2"
#define ENUM_CAT_08_TEXT "Time program 3"
#define ENUM_CAT_09_TEXT "Time program 4/DHW"
#define ENUM_CAT_0a_TEXT "Time program ventilation 1"
#define ENUM_CAT_0b_TEXT "Time program ventilation 2"
#define ENUM_CAT_0c_TEXT "Time program 5"
#define ENUM_CAT_0d_TEXT "Time program ventilation 3"
#define ENUM_CAT_0e_TEXT "Holidays zone 1"
#define ENUM_CAT_0f_TEXT "Holidays zone 2"
#define ENUM_CAT_10_TEXT "Holidays zone 3"
#define ENUM_CAT_11_TEXT "Heating circuit 1"
#define ENUM_CAT_12_TEXT "Cooling circuit 1"
#define ENUM_CAT_13_TEXT "Ventilation 1"
#define ENUM_CAT_14_TEXT "Heating circuit 2"
#define ENUM_CAT_15_TEXT "Cooling circuit 2"
#define ENUM_CAT_16_TEXT "Ventilation 2"
#define ENUM_CAT_17_TEXT "Heating circuit 3/P"
#define ENUM_CAT_18_TEXT "Cooling circuit 3"
#define ENUM_CAT_19_TEXT "Ventilation 3"
#define ENUM_CAT_1s_TEXT "Domestic Hot Water (DHW)"
#define ENUM_CAT_1b_TEXT "Consumer circuit 1"
#define ENUM_CAT_1c_TEXT "Consumer circuit 2"
#define ENUM_CAT_1d_TEXT "Swimming pool circuit"
#define ENUM_CAT_1e_TEXT "Hx pump"
#define ENUM_CAT_1f_TEXT "Swimming pool"
#define ENUM_CAT_20_TEXT "Primary controller/system pump"
#define ENUM_CAT_21_TEXT "Primary controller/system pump"
#define ENUM_CAT_22_TEXT "Boiler"
#define ENUM_CAT_23_TEXT "Sitherm Pro"
#define ENUM_CAT_24_TEXT "Heat pump"
#define ENUM_CAT_25_TEXT "Energy counter"
#define ENUM_CAT_26_TEXT "Brennerfolge"
#define ENUM_CAT_27_TEXT "Energy counter 2"
#define ENUM_CAT_28_TEXT "Grid supervision module"
#define ENUM_CAT_29_TEXT "Cascade"
#define ENUM_CAT_2a_TEXT "Extra heat source"
#define ENUM_CAT_2b_TEXT "Solar"
#define ENUM_CAT_2c_TEXT "Solid fuel boiler"
#define ENUM_CAT_2d_TEXT "Buffer tank"
#define ENUM_CAT_2e_TEXT "DHW storage tank"
#define ENUM_CAT_2f_TEXT "DHW direct charging"
#define ENUM_CAT_30_TEXT "General Features"
#define ENUM_CAT_31_TEXT "Configuration"
#define ENUM_CAT_32_TEXT "LPB"
#define ENUM_CAT_33_TEXT "Modbus"
#define ENUM_CAT_34_TEXT "Error"
#define ENUM_CAT_35_TEXT "Service/special operation"
#define ENUM_CAT_36_TEXT "Configuration extension modules"
#define ENUM_CAT_37_TEXT "Modbus diagnostics"
#define ENUM_CAT_38_TEXT "Input/output tests"
#define ENUM_CAT_39_TEXT "Status"
#define ENUM_CAT_3a_TEXT "Diagnostics cascade"
#define ENUM_CAT_3b_TEXT "Diagnostics generator"
#define ENUM_CAT_3c_TEXT "Diagnostics producer"
#define ENUM_CAT_3d_TEXT "Diagnostics consumer"
#define ENUM_CAT_3e_TEXT "Set day value storage"
#define ENUM_CAT_3f_TEXT "Burner control"
#define ENUM_CAT_40_TEXT "User defined"
#define ENUM_CAT_43_TEXT "PPS bus"
#define ENUM_CAT_44_TEXT "One Wire, DHT & MAX! Sensors"
#define ENUM_CAT_45_TEXT "Unknown category"

#define MENU_TEXT_HFK "Heater functions"
#define MENU_TEXT_SNS "Sensors"
#define MENU_TEXT_SN1 "DS18B20 sensors"
#define MENU_TEXT_SN2 "DHT22 sensors"
#define MENU_TEXT_CHK "Device-specific parameter list"
#define MENU_TEXT_DLG "Display log file"
#define MENU_TEXT_SLG "Plot log file"
#define MENU_TEXT_CFG "Settings"
#define MENU_TEXT_URL "URL commands"
#define MENU_TEXT_HWT "HowTo"
#define MENU_TEXT_FAQ "FAQ"
#define MENU_TEXT_YES "Yes"
#define MENU_TEXT_NO "No"
#define MENU_TEXT_ON "On"
#define MENU_TEXT_OFF "Off"
#define MENU_TEXT_NOQ "The device-specific parameter list is only supported on BSB- and LPB-based systems.<BR>For PPS devices, you can use the corresponding category directly.\r\n"
#define MENU_TEXT_QNC "BSB-LAN cannot connect to the heating system. Please make sure that the adapter is connected to the heater and that the heater is turned on. Then restart BSB-LAN to connect to the heater."
#define MENU_TEXT_QIN "In order to create a device-specific parameter list, please click on 'Download' below.<BR>If several controllers are connected via LPB, you <B>must</B> connect BSB-LAN via LPB, too, in order to get all parameters of all connected devices!<BR>The creation of this file can take several minutes and may seem to stall especially at the beginning, <B>please be patient!</B> \r\n<BR>Afterwards, let us know in which language you want to use BSB-LAN and send the saved file to bsb(ät)code-it.de.\r\nWe try our best to create a device-specific parameter list and return it to you as soon as possible, but after all this is a hobby project, so please bear with us.<BR><B>This process generally needs to be done just once (and not with every BSB-LAN update)!</B><BR><BR>Alternatively, you can find the BSB_LAN_custom_defs.h which was used in previous versions of BSB-LAN in release version 2.2. However, since this parameter list is missing hundreds of parameters from newer devices and contains a lot of ambiguities and sometimes also errors, its use is <B>not recommended</B> and should only be done after carefully examining the parameters you want to use.<BR>"
#define MENU_TEXT_QSC "Scanning for devices..."
#define MENU_TEXT_QFD "Device address found"
#define MENU_TEXT_QFA "Device query failed"
#define MENU_TEXT_QRA "Running test with destination device address"
#define MENU_TEXT_QST "Start test"
#define MENU_TEXT_QTE "Test finished"
#define MENU_TEXT_QFE "Done"
#define MENU_TEXT_QFF "Disconnected from MQTT broker, please try again later."
#define MENU_TEXT_TOC "Manual"
#define MENU_TEXT_MAS "Creating devices via MQTT auto discovery..."
#define MENU_TEXT_MAR "Removing devices via MQTT auto discovery..."
#define MENU_TEXT_MOD "Installed modules"
#define MENU_TEXT_NVS "Checking for newer version"
#define MENU_TEXT_NVA "Newer version found"
#define MENU_TEXT_NVN "Current version is up to date"
#define MENU_TEXT_NVW "Attention! New version can contain breaking changes that require changes in configuration. Please read the ChangeLog in CHANGELOG.md carefully!"
#define MENU_TEXT_SDF "Attention! This BSB-LAN installation only contains a rudimentary set of parameters.  To use the full set of parameters supported by your heating system, please generate a device-specific parameter list via the menu function above and flash BSB-LAN again with this file."
#define MENU_LINK_TOC "https://docs.bsb-lan.de/"
#define MENU_LINK_FAQ "https://docs.bsb-lan.de/faq.html"
#define MENU_LINK_URL "https://docs.bsb-lan.de/using.html"
#define MENU_DESC_HFK "Allows you to query or set parameters of your heating system, sorted in different clickable categories."
#define MENU_DESC_CFG "Displays a list of configuration options. You can change most of these by using the extended URL commands."
#define MENU_DESC_URL "Displays a list of extended commands which you can access by directly entering them in the browser's address line. These commands are also necessary to link up BSB-LAN to any home automation system such as FHEM."
#define MENU_TEXT_VB1 "Verbose mode activated!"
#define MENU_TEXT_VB2 "Verbose mode deactivated!"
#define MENU_TEXT_VB3 "Verbose output affects both the serial console of the mega2560 as well as (optional) logging bus data to SD card, so this can fill up your card pretty fast! The html output is kept unchanged."
#define MENU_TEXT_CLH "Click here"
#define MENU_TEXT_MQ1 "to start the MQTT Auto Discovery process (this may take a while)."
#define MENU_TEXT_MQ0 "to remove the MQTT Auto Discovery entries (this may take a while)."

#define MENU_TEXT_ER1 "ERROR: invalid parameter line!"
#define MENU_TEXT_ER2 "ERROR: invalid parameter value!"
#define MENU_TEXT_ER3 "ERROR: set failed!"
#define MENU_TEXT_ER4 "parameter is readonly."
#define MENU_TEXT_ER5 "ERROR: wrong type!"
#define MENU_TEXT_ER8 "Global write-protection is active in BSB-LAN settings."
#define MENU_TEXT_ER6 "ERROR: line not found!"
#define MENU_TEXT_ER7 "ERROR: protected GPIO pin!"
#define MENU_TEXT_BST "Heater statistics"
#define MENU_TEXT_BRS "Furnace and hot water duration is set to zero"
#define MENU_TEXT_24A "24h averages"
#define MENU_TEXT_24N "New average parameters"
#define MENU_TEXT_DTR ": file was removed and recreated."
#define MENU_TEXT_DLD "(loading data...)"
#define MENU_TEXT_DDO "Download displayed data"
#define MENU_TEXT_DTD "Download all data"
#define MENU_TEXT_DTF "Failed to create datalog.txt!"
#define MENU_TEXT_DTO "Error opening datalog.txt!"
#define MENU_TEXT_RAM "Free memory"
#define MENU_TEXT_BUS "Bus system"
#define MENU_TEXT_BRW "Read/Write"
#define MENU_TEXT_BRO "Read-Only"
#define MENU_TEXT_OWP "1-Wire bus pins"
#define MENU_TEXT_DHP "DHT22 bus pins"
#define MENU_TEXT_EXP "Protected GPIO pins"
#define MENU_TEXT_MAC "MAC address"
#define MENU_TEXT_LIR "Log parameter will be logged now and log interval counter will be reset."
#define MENU_TEXT_LGP "Logging the following parameters every"
#define MENU_TEXT_SEC "seconds"
#define MENU_TEXT_BZ1 "Burner runtime level 1"
#define MENU_TEXT_BT1 "Burner cycles level 1"
#define MENU_TEXT_BZ2 "Burner runtime level 2"
#define MENU_TEXT_BT2 "Burner cycles level 2"
#define MENU_TEXT_TZ1 "DHW runtime"
#define MENU_TEXT_TT1 "DHW cycles"
#define MENU_TEXT_MXI "MAX! current temperature"
#define MENU_TEXT_MXS "MAX! temperature setpoint"
#define MENU_TEXT_MXV "MAX! valve opening"
#define MENU_TEXT_MXN "No MAX! data received yet."
#define MENU_TEXT_BDT "BSB-Data telegrams (irrespective of interval)"
#define MENU_TEXT_BUT "Logging unknown bus telegrams only"
#define MENU_TEXT_UBT "Logging unknown broadcast bus telegrams only"
#define MENU_TEXT_MMD "Raw data mode"
#define MENU_TEXT_VBL "Verbosity mode"
#define MENU_TEXT_AVT "Calculating 24h averages for the following parameters"
#define MENU_TEXT_LBO "Log broadcast bus-telegrams only"
#define MENU_TEXT_LGI "New logging interval"
#define MENU_TEXT_LGN "New logging parameters"
#define MENU_TEXT_LOT "Log of telegrams"
#define MENU_TEXT_FSP "Free space in file system"
#define MENU_TEXT_CNV "Category not valid for destination device."

#define STR_24A_TEXT "24h average"
#define S_ERROR "Current error code"
#define S_MAINT "Current maintenance code"


//WEBCONFIG
#define CF_CONFIG_LEVEL_TEXT "Display extended configuration"
#define CF_USEEEPROM_TEXT "Read config from EEPROM"
#define CF_RX_PIN_TEXT "RX pin number"
#define CF_TX_PIN_TEXT "TX pin number"
#define CF_BUSTYPE_TEXT "Type"
#define CF_OWN_ADDR_TEXT "Own address"
#define CF_DEST_ADDR_TEXT "Destination address"
#define CF_PPS_WRITE_TEXT "PPS: mode"
#define CF_QAA_TYPE_TEXT "PPS: QAA model"
#define CF_LOGTELEGRAM_TEXT "Bus telegrams"
#define CF_LOGCURRVALUES_TEXT "Logging enabled"
#define CF_LOGCURRINTERVAL_TEXT "Interval (seconds)"
#define CF_CALCULATION_TEXT "Calculation"
#define CF_PROGLIST_TEXT "Parameters"
#define CF_DEVICES_TEXT "Devices"
#define CF_DHCP_TEXT "DHCP usage"
#define CF_IPADDRESS_TEXT "IP address (fixed)"
#define CF_MAC_TEXT "MAC address"
#define CF_TRUSTEDIPADDRESS_TEXT "Trusted IP address"
#define CF_MASK_TEXT "Subnet"
#define CF_WIFI_PASSWORD_TEXT "WLAN password"
#define CF_WEBSERVER_TEXT "Webserver file system"
#define CF_BASICAUTH_TEXT "HTTP authentification"
#define CF_ONEWIREBUS_DEVICES_TEXT "Devices"
#define CF_PINS_TEXT "Pins"
#define CF_USE_TEXT "Usage"
#define CF_MAX_IPADDRESS_TEXT "IP address cube"
#define CF_WRITEMODE_TEXT "Write access (level)"
#define CF_MQTT_SERVER_TEXT "Broker server"
#define CF_MQTT_PASSWORD_TEXT "Password"
#define CF_MQTT_DEVICE_TEXT "Device ID"
#define CF_MQTT_TOPIC_TEXT "Topic prefix"
#define CF_MQTT_UNITS_TEXT "Units"
#define CF_LOGMODE_TEXT "Logging mode"
#define CF_CHECKUPDATE_TEXT "Check for updates"
#define CF_SHOW_UNKNOWN_TEXT "Display unknown parameters"
#define CF_ENERGY_SAVE_TEXT "Energy saving"
#define CF_LOG_DEST_TEXT "Storage device"

#define ENUM_LOG_DEST_00_TEXT "SD card"
#define ENUM_LOG_DEST_01_TEXT "Internal flash storage"
#define ENUM_VERBOSE_00_TEXT MENU_TEXT_OFF
#define ENUM_VERBOSE_01_TEXT MENU_TEXT_ON
#define ENUM_VERBOSE_02_TEXT "Developer"

#define CAT_GENERAL_TEXT "General"
#define CAT_IPV4_TEXT "Network"
#define CAT_24HAVG_TEXT "24h averages"
#define CAT_RGT_EMUL_TEXT "RU emulation"

#define STR500_TEXT "Mo"
#define STR501_TEXT "Tu"
#define STR502_TEXT "We"
#define STR503_TEXT "Th"
#define STR504_TEXT "Fr"
#define STR505_TEXT "Sa"
#define STR506_TEXT "Su"
#define STR516_TEXT "Standard values time switch program"
#define STR632_TEXT "Holiday period 1: first day"
#define STR633_TEXT "Holiday period 1: last day"
#define STR634_TEXT "Holiday period 2: first day"
#define STR635_TEXT "Holiday period 2: last day"
#define STR636_TEXT "Holiday period 3: first day"
#define STR637_TEXT "Holiday period 3: last day"
#define STR638_TEXT "Holiday period 4: first day"
#define STR639_TEXT "Holiday period 4: last day"
#define STR640_TEXT "Holiday period 5: first day"
#define STR641_TEXT "Holiday period 5: last day"
#define STR642_TEXT "Holiday period 6: first day"
#define STR643_TEXT "Holiday period 6: last day"
#define STR644_TEXT "Holiday period 7: first day"
#define STR645_TEXT "Holiday period 7: last day"
#define STR646_TEXT "Holiday period 8: first day"
#define STR647_TEXT "Holiday period 8: last day"
#define STR648_TEXT "Holiday operating level"

#define STR700_TEXT "Operating mode"
#define STR710_TEXT "Room temperature Comfort setpoint"
#define STR712_TEXT "Room temp reduced setpoint"
#define STR714_TEXT "Room temp frost protection setpoint"
#define STR720_TEXT "Heating curve slope"
#define STR721_TEXT "Heating curve parallel displacement"
#define STR726_TEXT "Heating curve adaptation"
#define STR730_TEXT "Summer/winter changeover temp"
#define STR732_TEXT "24-hour heating limit"
#define STR740_TEXT "Flow temp min limitation"
#define STR741_TEXT "Flow temp max limitation"
#define STR750_TEXT "Room temp gain factor"
#define STR760_TEXT "Room temperature limitation"
#define STR770_TEXT "Room temp setpoint boost (boost heating)"
#define STR780_TEXT "Quick setback"
#define STR790_TEXT "Optimum start control max forward shift"
#define STR791_TEXT "Optimum stop control max forward shift"
#define STR800_TEXT "Start reduced room temp setpoint increase"
#define STR801_TEXT "End reduced room temp setpoint increase"
#define STR830_TEXT "Temp boost mixing valve heat circuit"
#define STR834_TEXT "Actuator running time heat circuit"
#define STR850_TEXT "Flooring plaster dry up function"
#define STR851_TEXT "Floor setpoint manually"
#define STR884_TEXT "Pump speed at the heating plant´s design point"
#define STR885_TEXT "Modulating pump PWM min"
#define STR886_TEXT "Outside temperature at max heat demand"
#define STR887_TEXT "Boiler setpoint at design outside temperature"
#define STR888_TEXT "Limit of temperature boost of dT controller"
#define STR894_TEXT "Delta flow / return temperature at TiAussenNorm"

#define STR947_TEXT "Flow temp setp incr hygro"

#define STR1600_TEXT "DHW operating mode"
#define STR1610_TEXT "DHW temperature nominal setpoint"
#define STR1612_TEXT "DHW temperature reduced setpoint"
#define STR1620_TEXT "DHW release"
#define STR1640_TEXT "Legionella function"
#define STR1641_TEXT "Legionella function periodicity"
#define STR1642_TEXT "Legionella function day"
#define STR1644_TEXT "Time for legionella function"
#define STR1645_TEXT "Legionella function setpoint"
#define STR1646_TEXT "Dwelling time at legionella function setpoint"
#define STR1647_TEXT "Circul. pump operation during legionella func"
#define STR1660_TEXT "DHW circulating pump release"
#define STR1661_TEXT "DHW circulating pump cycling "
#define STR2201_TEXT "Heat generation lock"
#define STR2210_TEXT "Boiler temp min limitation"
#define STR2212_TEXT "Boiler temp max limitation"
#define STR2440_TEXT "Maximum degree of modulation in heating mode"
#define STR2441_TEXT "Max. speed at maximum output in heating mode"
#define STR2442_TEXT "Output during controller delay time"
#define STR2443_TEXT "Modul. start value at controller release in DHW"
#define STR2451_TEXT "Burner off time min"
#define STR2452_TEXT "Max. control diff without abortion of pause time"
#define STR2453_TEXT "Controller delay after burner is started up"
#define STR2454_TEXT "Boiler switching differential"
#define STR2455_TEXT "Minimum switch-off differential of burner"
#define STR2456_TEXT "Maximum switch-off differential of burner"
#define STR2471_TEXT "Pump overrun time"
#define STR2472_TEXT "Pump overrun temperature DHW"
#define STR2521_TEXT "Boiler frost protection switch-on temperature"
#define STR2522_TEXT "Boiler frost protection switch-off temperature"
#define STR2730_TEXT "Measured value of ionization current"
#define STR3810_TEXT "Temp differential on solar"
#define STR3811_TEXT "Temp differential off solar"
#define STR3812_TEXT "Charging temp min"
#define STR3831_TEXT "Min running time of collector pump"
#define STR3840_TEXT "Collector frost protection temp"
#define STR3850_TEXT "Collector overtemperature protection"
#define STR3860_TEXT "Evaporation temperature of heat carrier"
#define STR4721_TEXT "Automatic producer lock switching differential"
#define STR4722_TEXT "Diff. Buffer/HC temp to producer release"
#define STR5019_TEXT "Setpoint boost for recharging of stratific. Tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5050_TEXT "Max dhw charging temp"
#define STR5055_TEXT "Min recooling temperature for DHW storage tank"
#define STR5100_TEXT "Min. pump speed for full charging of strat. tank"
#define STR5020_TEXT "Flow temp boost dhw"
#define STR5400_TEXT "Setpoint for readiness temperature"
#define STR5430_TEXT "Switch-on differential in DHW mode (sensor 1)"
#define STR5431_TEXT "Min. switch-off differ. in DHW mode (sensor 1)"
#define STR5432_TEXT "Max. switch-off differ. In DHW mode (sensor 1)"
#define STR5433_TEXT "Switch-on differential in DHW mode (sensor 2)"
#define STR5434_TEXT "Min. switch-off differential in DHW mode (sens2)"
#define STR5435_TEXT "Max. switch-off difer. in DHW mode (sensor 2)"
#define STR5450_TEXT "Response treshold for detection of DHW consumpt."
#define STR5451_TEXT "Resp. treshold for DHW consumpt. in comfort mode"
#define STR5452_TEXT "Resp. treshold for DHW consumpt. in heating mode"
#define STR5453_TEXT "Setpoint readjustment at 40°C in comfort mode"
#define STR5454_TEXT "Setpoint readjustment at 60°C in comfort mode"
#define STR5455_TEXT "Setpoint readjustment at 40°C outlet temperature"
#define STR5456_TEXT "Setpoint readjustment at 60°C outlet temperature"
#define STR5480_TEXT "Time for inst. DHW comfort after consumption"
#define STR5481_TEXT "Time for inst. DHW comf. after consumpt. (heat)"
#define STR5482_TEXT "Time DHW flow switch is closed"
#define STR5483_TEXT "Time DHW Comfort flow switch is closed"
#define STR5486_TEXT "Controller delay at instant. DHW chopping mode"
#define STR5487_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5488_TEXT "pump overrrun in DHW comfort after burner off"
#define STR5701_TEXT "Plant type"
#define STR5710_TEXT "Heating circuit 1"
#define STR5715_TEXT "Heating circuit 2"
#define STR5732_TEXT "Pump-off time at change from heating to DHW mode"
#define STR5733_TEXT "Pump-off delay at change from heating to DHW"
#define STR5761_TEXT "Heat demand with assistance by pump Q8"
#define STR5920_TEXT "Function programmable output K2 LMU"
#define STR5921_TEXT "Default K2 on K1"
#define STR5922_TEXT "Function output 1 clip-in function module"
#define STR5923_TEXT "Function output 2 clip-in function module"
#define STR5924_TEXT "Function output 3 clip-in function module"
#define STR5926_TEXT "Configuration output 1"
#define STR5927_TEXT "Configuration output 2"
#define STR5928_TEXT "Configuration output 3"
#define STR5950_TEXT "Input H1 function selection"
#define STR5957_TEXT "Modem function"
#define STR5970_TEXT "Config room thermostat 1"
#define STR5971_TEXT "Config room thermostat 2"
#define STR5973_TEXT "Function Input RelCl"
#define STR5975_TEXT "Maximum temperature of external heat demand"
#define STR5976_TEXT "Lower Limit of input signal for ext. heat demand"
#define STR6110_TEXT "Building time constant"
#define STR6112_TEXT "Gradient room model"
#define STR6120_TEXT "Frost protection for the plant"
#define STR6127_TEXT "Time for kick function of pump / diverting valve"
#define STR6204_TEXT "Save parameter"
#define STR6220_TEXT "Device SW version"
#define STR6225_TEXT "Device family"
#define STR6226_TEXT "Device variant"
#define STR6227_TEXT "Device OV version"
#define STR6230_TEXT "Controller setting flags 0"
#define STR6240_TEXT "Controller setting flags 1"
#define STR6250_TEXT "Controller setting flags 2"
#define STR6260_TEXT "Controller setting flags 3"
#define STR6270_TEXT "Controller setting flags 4"
#define STR6300_TEXT "Controller setting flags 7"
#define STR6330_TEXT "Controller configuration 10"
#define STR6604_TEXT "LPB power supply function selection"
#define STR6605_TEXT "LPB power supply status"
#define STR6625_TEXT "Dhw allocation"
#define STR6640_TEXT "Clock time source"
#define STR6705_TEXT "Internal value of diagnostic code"
#define STR6706_TEXT "Current value of lockout phase"
#define STR6741_TEXT "Time flow temperature alarm heating circuit 2"
#define STR6823_TEXT "3rd past value of albatros diagnostic code"
#define STR6825_TEXT "3rd past value of internal diagnostic code"
#define STR6826_TEXT "3rd past value of lockout phase"
#define STR6830_TEXT "4th past value of lockout code counter"
#define STR6833_TEXT "4th past value of albatros diagnostic code"
#define STR6835_TEXT "4th past value of internal diagnostic code"
#define STR6836_TEXT "4th past value of lockout phase"
#define STR6840_TEXT "5th past value of lockout code counter"
#define STR6843_TEXT "5th past value of albatros diagnostic code"
#define STR6845_TEXT "5th past value of internal diagnostic code"
#define STR6846_TEXT "5th past value of lockout phase"
#define STR7001_TEXT "Maintenance message"
#define STR7007_TEXT "Configuration / Reset of service messages"
#define STR7010_TEXT "Confirmation of service message"
#define STR7011_TEXT "Repetition time for service messages"
#define STR7040_TEXT "Burner maintenance interval"
#define STR7041_TEXT "Hours run since last service"
#define STR7042_TEXT "Limit of burner starts since last service"
#define STR7043_TEXT "Burner starts since last service"
#define STR7044_TEXT "Limit of months since last service"
#define STR7045_TEXT "Months since last service"
#define STR7050_TEXT "Fan speed treshold for service message"
#define STR7051_TEXT "Ionisation current service message"
#define STR8000_TEXT "Status heating circuit 1"
#define STR8001_TEXT "Status heating circuit 2"
#define STR8003_TEXT "Status DHW"
#define STR8004_TEXT "Status cooling circuit 1"
#define STR8005_TEXT "Status boiler"
#define STR8007_TEXT "Status solar"
#define STR8300_TEXT "1. Appliance burner stage T2"
#define STR8301_TEXT "2. Appliance burner stage T8"
#define STR8302_TEXT "Condition burner flap open"
#define STR8303_TEXT "Condition burner flap closed"
#define STR8304_TEXT "Boiler pump Q1"
#define STR8308_TEXT "Boiler pump speed"
#define STR8310_TEXT "Boiler temp actual value"
#define STR8311_TEXT "Boiler temp setpoint"
#define STR8312_TEXT "Boiler switching point"
#define STR8313_TEXT "Regulation sensor"
#define STR8314_TEXT "Return temp actual value"
#define STR8315_TEXT "Boiler return flow temperature setpoint"
#define STR8316_TEXT "Flue gas temp actual value"
#define STR8318_TEXT "Exhaust temperature max"
#define STR8319_TEXT "Control temperature"
#define STR8320_TEXT "Control setpoint"
#define STR8321_TEXT "Actual control deviation"
#define STR8323_TEXT "Fan speed"
#define STR8324_TEXT "Current fan speed"
#define STR8325_TEXT "Current fan control"
#define STR8326_TEXT "Relative output"
#define STR8327_TEXT "Water pressure"
#define STR8328_TEXT "Operation indication burner control"
#define STR8330_TEXT "Operating hours 1. Level"
#define STR8331_TEXT "Startcount 1. Level"
#define STR8332_TEXT "Operating hours 2. Level"
#define STR8333_TEXT "Startcount 2. Level"
#define STR8336_TEXT "Device operating hours"
#define STR8337_TEXT "Start counter burner"
#define STR8338_TEXT "Hours run burner"
#define STR8339_TEXT "Hours run DHW heating"
#define STR8340_TEXT "Hours run zone"
#define STR8378_TEXT "Total gas energy heating mode"
#define STR8379_TEXT "Total gas energy DHW"
#define STR8380_TEXT "Total gas energy"
#define STR8381_TEXT "Gas energy heating"
#define STR8382_TEXT "Gas energy DHW"
#define STR8383_TEXT "Gas energy"
#define STR8390_TEXT "Actual phase number"
#define STR8395_TEXT "Heat emission"
#define STR8396_TEXT "Heat absorption source"
#define STR8397_TEXT "Power consumption"
#define STR8398_TEXT "Performance coefficient"
#define STR8510_TEXT "Collector temp 1 actual value (B6)"
#define STR8530_TEXT "solar yield operating hours"
#define STR8700_TEXT "Outside temp sensor local"
#define STR8703_TEXT "Outside temp attenuated"
#define STR8704_TEXT "Outside temp composite"
#define STR8739_TEXT "Room humid 1 actual value"
#define STR8740_TEXT "Room temp 1 actual value"
#define STR8741_TEXT "Room temp setpoint current"
#define STR8743_TEXT "Flow temp actual value heat circuit 1"
#define STR8744_TEXT "Flow temperature setpoint H1"
#define STR8750_TEXT "Pump speed"
#define STR8770_TEXT "Room temp 2 actual value"
#define STR8771_TEXT "Room temp setpoint actual HC2"
#define STR8773_TEXT "Flow temp actual value heat circuit 2"
#define STR8774_TEXT "Flow temperature setpoint H2"
#define STR8830_TEXT "DHW temperature actual value top (B3)"
#define STR8831_TEXT "Dhw temp setpoint current"
#define STR8836_TEXT "DHW charging temperature"
#define STR8950_TEXT "Process signal segment flow"
#define STR8952_TEXT "Process signal segment return"
#define STR8980_TEXT "Buffer temp actual value top (B4)"
#define STR9500_TEXT "Pre-ventilation time"
#define STR9502_TEXT "Modulation Luft in Vorlüftung"
#define STR9504_TEXT "Required fan speed during prepurging"
#define STR9510_TEXT "Modulation air at ignition load"
#define STR9512_TEXT "Speed required at ignition load"
#define STR9520_TEXT "Modulation air at low-fire"
#define STR9522_TEXT "Modulation air at high-fire"
#define STR9524_TEXT "Speed required at low-fire"
#define STR9527_TEXT "Speed required at high-fire"
#define STR9540_TEXT "After-ventilation time"
#define STR9560_TEXT "Fan modulation for full charging of strat. tank"
#define STR9563_TEXT "Fan speed for full charging of stratific. tank"
#define STR10100_TEXT "System status"

#define STR15000_TEXT "Operating Mode"
#define STR15001_TEXT "Occupancy Button"
#define STR15002_TEXT "Position Setting Knob"
#define STR15003_TEXT "Remaining Holidays"
#define STR15004_TEXT "Comfort Setpoint"
#define STR15005_TEXT "Reduced Setpoint"
#define STR15006_TEXT "Frost Protection Setpoint"
#define STR15007_TEXT "Setpoint Maximum"
#define STR15008_TEXT "Room Temperature"
#define STR15020_TEXT "DHW Charging"
#define STR15021_TEXT "DHW Temperature 1"
#define STR15022_TEXT "DHW Reduced Setpoint"
#define STR15023_TEXT "DHW Nominal Setpoint"
#define STR15030_TEXT "Outside Temperature"
#define STR15031_TEXT "Outside Temperature Composite"
#define STR15032_TEXT "Flow Temperature 1"
#define STR15033_TEXT "Flow Temperature Setpoint 1"
#define STR15034_TEXT "Flow Temperature Mixing Module"
#define STR15035_TEXT "Setpoint Temperature"
#define STR15036_TEXT "Burner Modulation"
#define STR15040_TEXT "Time"
#define STR15041_TEXT "Day"
#define STR15042_TEXT "Next Time Switch Program"
#define STR15043_TEXT "Manual Heating"
#define STR15044_TEXT "Status Burner"
#define STR15045_TEXT "Connection Interrupted"
#define STR15046_TEXT "QAA Model"
#define STR15050_TEXT "Time Switch Program Montag"
#define STR15056_TEXT "Time Switch Program Dienstag"
#define STR15062_TEXT "Time Switch Program Mittwoch"
#define STR15068_TEXT "Time Switch Program Donnerstag"
#define STR15074_TEXT "Time Switch Program Freitag"
#define STR15080_TEXT "Time Switch Program Samstag"
#define STR15086_TEXT "Time Switch Program Sonntag"
#define STR20100_TEXT "DHT22 Sensor ID"
#define STR20101_TEXT "DHT22 Sensor Temperature"
#define STR20102_TEXT "DHT22 Sensor Humidity"
#define STR20103_TEXT "DHT22 Sensor Abs. Humidity"
#define STR20200_TEXT "BME280 Sensor ID"
#define STR20201_TEXT "BME280 Sensor Temperature"
#define STR20202_TEXT "BME280 Sensor Humidity"
#define STR20203_TEXT "BME280 Sensor Pressure"
#define STR20204_TEXT "BME280 Sensor Altitude"
#define STR20205_TEXT "BME280 Sensor Abs. Humidity"
#define STR20300_TEXT "DS18B20 Sensor ID"
#define STR20301_TEXT "DS18B20 Sensor Temperature"
#define STR20500_TEXT "MAX! Sensor ID"
#define STR20501_TEXT "MAX! Sensor Current Temperature"
#define STR20502_TEXT "MAX! Sensor Setpoint Temperature"
#define STR20503_TEXT "MAX! Sensor Valve Opening"
#define STR20504_TEXT "MAX"

#define ENUM15000_00_TEXT "Automatic"
#define ENUM15000_01_TEXT "Manual"
//#define ENUM15000_02_TEXT MENU_TEXT_OFF. This definition is moved to BSB_LAN/BSB_LAN_defs.h file
#define ENUM15044_00_02_TEXT "Auto-Mode: off"
#define ENUM15044_02_02_TEXT "Auto-Mode: on"
#define ENUM15044_00_08_TEXT "Pump on"
#define ENUM15044_08_08_TEXT "Pump off"
#define ENUM15044_00_10_TEXT "Contact H1: open"
#define ENUM15044_10_10_TEXT "Contact H1: closed"

#define ENUM_WEEKDAY_01_TEXT "Monday"
#define ENUM_WEEKDAY_02_TEXT "Tuesday"
#define ENUM_WEEKDAY_03_TEXT "Wednesday"
#define ENUM_WEEKDAY_04_TEXT "Thursday"
#define ENUM_WEEKDAY_05_TEXT "Friday"
#define ENUM_WEEKDAY_06_TEXT "Saturday"
#define ENUM_WEEKDAY_07_TEXT "Sunday"

#define ENUM_PPS_MODE_PASSIVE_TEXT "passive"
#define ENUM_PPS_MODE_QAA_TEXT "as room unit"
#define ENUM_MQTT_UNITS_LOCALIZED_TEXT "Localized"
#define ENUM_MQTT_UNITS_HOMEASSISTANT_TEXT "Home Assistant"
#define ENUM_MQTT_UNITS_NONE_TEXT "None"
#define ENUM_WRITE_ENG_TEXT "On (Standard)"
#define ENUM_WRITE_OEM_TEXT "On (Complete)"

#define ENUM_LOGMODE_01_TEXT "Write to SD card"
#define ENUM_LOGMODE_02_TEXT "Calculate 24h averages"
#define ENUM_LOGMODE_04_TEXT "Send to MQTT broker"
#define ENUM_LOGMODE_08_TEXT "Only send log parameters to MQTT"
#define ENUM_LOGMODE_10_TEXT "Send to UDP"

#define ENUM8000_04_TEXT "Manual control active"
#define ENUM8000_11_TEXT "Overrun active"
#define ENUM8000_16_TEXT "Frost prot plant active"
#define ENUM8000_17_TEXT "Frost protection active"
#define ENUM8000_75_TEXT "Frost protection flow active"
#define ENUM8004_02_TEXT "Fault"
#define ENUM8004_11d_TEXT "Cooling mode Reduced"
#define ENUM8004_85_TEXT "Dewpoint monitor active"
#define ENUM8004_86_TEXT "Cooling limit OT active"
#define ENUM8004_87_TEXT "Locking time after heating"
#define ENUM8004_8a_TEXT "Cooling mode off"
#define ENUM8004_90_TEXT "Cooling mode restricted"
#define ENUM8004_92_TEXT "Cooling mode locked"
#define ENUM8004_96_TEXT "Cooling mode Comfort"
#define ENUM8004_b1_TEXT "Limit flow min dewpoint"
#define ENUM8004_b2_TEXT "Limit flow min outside temp"
#define ENUM8004_b3_TEXT "Flow limit reached"
#define ENUM8004_cc_TEXT "Locked, heating mode"
#define ENUM8004_cd_TEXT "Locked, source"
#define ENUM8004_ce_TEXT "Locked, buffer"

#define ENUM10100_02_TEXT "Maintenance"
#define ENUM10100_04_TEXT "Burner 1 active"
#define ENUM10100_08_TEXT "Direct display"
#define ENUM10100_10_TEXT "Burner 2 active"
#define ENUM10100_20_TEXT "Radio: Clock not adjustable"
#define ENUM10100_40_TEXT "Radio: Invalid time"
#define ENUM10100_80_TEXT "Radio: Clock adjusted"

// These strings do not take space in Arduino memory. They are for external interfaces.
#define EXTIF_HOME_TEXT "Home"
#define EXTIF_MANAGEMENT_TEXT "Management"
#define EXTIF_MONITOR_TEXT "Monitor"
#define EXTIF_ABOUT_TEXT "About"
#define EXTIF_SAVELOAD_TEXT "Save/Load"
#define EXTIF_SETCLOCK_TEXT "Set clock"
#define EXTIF_RESET_TEXT "Reset"
#define EXTIF_BACK_TEXT "Back"
#define EXTIF_UPDATE_TEXT "Update"
#define EXTIF_CANCEL_TEXT "Cancel"
#define EXTIF_SAVE_TEXT "Save"
#define EXTIF_CANTREADFILE_TEXT "File can't be read! Error code"
#define EXTIF_CATNOTEXIST_TEXT "Error: Category not exist!"
#define EXTIF_NOTEXIST_TEXT "not exist!"
#define EXTIF_CATNO_TEXT "Category #"
#define EXTIF_FUNCNO_TEXT "Parameter #"
#define EXTIF_CHANGEPARAM1_TEXT "Parameter"
#define EXTIF_CHANGEPARAM2_TEXT "was changed to"
#define EXTIF_CHANGEPARAM3_TEXT ""
#define EXTIF_OK_TEXT "ok"
#define EXTIF_FAILED_TEXT "failed"
#define EXTIF_ERROR_TEXT "Error"
#define EXTIF_SETTIME_TEXT "Time set to"
#define EXTIF_JSONERROR_TEXT "Error: JSON parsing failed."
#define EXTIF_ERROR404_TEXT "Error 404: file not found!"
#define EXTIF_ERRORREQUEST_TEXT "Error: AJAX request failed."
#define EXTIF_WARNEXIT_TEXT "Warn about exit without save. Are you sure?"
#define EXTIF_DOWNLOADCONF_TEXT "Download config"
#define EXTIF_UPLOADCONF_TEXT "Upload config to system"
#define EXTIF_DOWNLOADEXCL_TEXT "Create and download exclusions list"
#define EXTIF_ALLCAT_TEXT "All categories"
